### ISSUE TITLE
[BUG] Uploaded songs get skipped

### ISSUE THREAD

**Issue by SubZeroNexii** [ciderapp/Cider#100]
**Describe the bug**
Skipping to a uploaded song trough iTunes will skip said song without user input.

**To Reproduce**
1. Go to the Songs section
2. Click on any Apple Music song
3. Skip until you get to an uploaded song
4. The songs get skipped

**Screenshots**
![ezgif com-gif-maker](https://user-images.githubusercontent.com/11245286/148700966-0eeac75c-fc7b-4a93-8f09-8bb6159d2c8f.gif)

**More information**
Same thing happens with seamless audio turned on or off

**Environment Information**
 - OS *Windows 11 Insider Beta 22000.376*: 
 - Application Version *Cider commit d99b9d1eac7e8188dd8741ea2294f9040c9968db*:

**Comment by Aria-NL** [comment]
I've narrowed this issue down a little bit. This behavior only occurs when you skip from a streamed song (i.e. Non-Library) to an iCloud Music Library uploaded song. Skipping from another Library uploaded song works fine, as well as playing an uploaded song directly. Finally, letting the streamed song finish and go into the uploaded song works fine.

For example, I have a playlist with a streamed song, and then 10 uploaded songs. I start the streamed song, and skip to the first uploaded song. Cider then skips through every single uploaded song until the next streamed song.

**Comment by vapormusic** [comment]
should be mitigated https://github.com/ciderapp/Cider/commit/317a56e4397fa5af9f1a41886ed00fd4bb0a98f8

**Comment by vapormusic** [comment]
> Confirming it's mostly mitigated now, however keeping on seamless transitions and letting a streamed song end and try to go onto a library song, that library song is still skipped.

only when shuffle is on , right?
