### ISSUE TITLE
[Bug]: Slow UI due to Failed GPU Acceleration

### ISSUE THREAD

**Issue by bcrescimanno** [ciderapp/Cider#1005]
### Describe the Bug

After a recent update, Cider has become nearly unusable due to how slow the UI responds. A bit of digging shows that hardware acceleration is disabled due to looking for a higher version of GLES than is reported. However, I'm on the latest nvidia drivers on a current generation nvidia card; so, unless this is a case of nvidia screwing something up (admittedly possible in the Linux world) I don't know why it would be a problem.

I also don't really understand why it would be looking for OpenGL ES on a desktop system.

As a workaround, I can disable hardware acceleration to use the basic mode; but, this shouldn't be an issue on current generation hardware.

### Steps to Reproduce

Happens at app start and throughout the lifecycle

### Environment Information

- OS: Arch Linux
- App Version and/or Commit ID: 1.4.6.3468.d4efa688-1
- GPU: Nvidia RTX 3080ti
- Driver: Nvidia 510.68.02

### Anything else?

Full errors from startup: https://pastebin.com/raw/T3sHj2dT

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Hardware Acceleration is handled by Chromium's implementation which mean's in a short way *its terrible on Linux.* Unfortunately there's no good way to get around Chromium trying to use GLES as means of graphical acceleration and most of the time it fails.

I'd definitely make an issue on https://bugs.chromium.org and see if something could get added to fix it for you.

**Comment by bcrescimanno** [comment]
Lovely! On a whim, I decided to reboot and now it's working; so....no idea.
