### ISSUE TITLE
[BUG] Volume wheel doesn't touch the end of the bar in fullscreen mode

### ISSUE THREAD

**Issue by Nosh118** [ciderapp/Cider#101]
**Describe the bug**
Volume bar doesn't reach the end of the bar at max volume in fullscreen mode

**To Reproduce**
1. Double click on album art of song playing
2. Try drag the volume wheel to the end
3. See error

**Expected behavior**
At max/100% volume of the app, the wheel should be at the end

**Screenshots**
![image](https://user-images.githubusercontent.com/67752804/148737004-d5b3f6e9-f500-46ff-8e6c-393e2f86b82d.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows
 - Application Version *(e.g. 2.5.0)*: latest commit

**Comment by gms10ur** [comment]
fixed in upcoming @vapormusic @cryptofyre
