### ISSUE TITLE
[Bug]: Previous keybind bug in first songs of albums/playlist

### ISSUE THREAD

**Issue by yazninja** [ciderapp/Cider#1011]
### Describe the Bug

When playing the first song in a playlist/album and using the keybinds to go back a song, Cider will instead play the next song whilst not updating the progress bar

### Steps to Reproduce

1. play a song, make sure its the first song it an album/playlist
2. do a `ctrl + left arrow`
3. plays the next song but does not update the current playing song display

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID:  26e84c61480bd45901ed1538dd127bae638d73fc

### Anything else?

[Uploading 2022-05-09 23-16-41.mp4…](https://user-images.githubusercontent.com/71800112/167445033-d68addbe-8abf-4f14-917e-99a009cc849d.mp4)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
Can confirm I encounter the same bug.
