### ISSUE TITLE
[Bug]: essential albums won’t play 

### ISSUE THREAD

**Issue by docace911** [ciderapp/Cider#1024]
### Describe the Bug

Search for Duran Duran rio essential album (a new feature). You cannot play it

### Steps to Reproduce

Search for “essential album Duran Duran rio”. These are new series with a commentator putting tracks into context and some brief interviews

Shows up in cider 

however had large “not” sign (circle with line). Cannot play

### Environment Information

- OS: windows 10 and 11
- App Version and/or Commit ID: 1.46 beta windows EXE

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amaru8** [comment]
Hi! This is a restriction by made Apple. If you try playing these stations on the [Apple Music Web](https://beta.music.apple.com) player, it will just show the name and the cover image of the station, but it won't play anything.

![AMWeb_EssentialAlbum](https://user-images.githubusercontent.com/52407090/167851960-2da79a6b-2443-4dc3-a1d6-dea42d72f3c0.png)
