### ISSUE TITLE
[Bug]: Cider Folder

### ISSUE THREAD

**Issue by SynCode05** [ciderapp/Cider#1026]
### Describe the Bug

When trying to open the Cider Folder I get prompted with an error saying the folder doesn't exist. I'm not sure but I think it affects the upgrading of themes. 

### Steps to Reproduce

Click on settings, 
Advanced
Open Cider Folder (Button Open)

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: Microsoft Store Version 1.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amaru8** [comment]
**Hi @SynCode05, I have some great news!** This bug is now fixed in the latest development version of **Cider** and will be resolved with the next Microsoft Store update.

**Comment by SynCode05** [comment]
That's great!
