### ISSUE TITLE
[Bug]: Building playlist cache indefinitely / Playlists not working

### ISSUE THREAD

**Issue by NGPixel** [ciderapp/Cider#1031]
### Describe the Bug

Since yesterday's update, opening the app gets stuck on "Building playlist cache... (0/0)", preventing any playlist from displaying.

After a while, the "Building playlist cache... (0/0" message disappear but playlists still do not work.

Resetting / Reinstalling the app doesn't fix the issue.

<img width="1158" alt="image" src="https://user-images.githubusercontent.com/15522395/168154090-e6a13bc6-f0e0-4b92-83bf-f7d522660de1.png">

Note that browsing / searching still works and it's possible to play songs from there.

### Steps to Reproduce

1. Open the app

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.4.6 from Microsoft Store

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
There is an ongoing Apple outage and this has nothing to do with us at this time.
