### ISSUE TITLE
[Translation]: Problem with the Chinese language 

### ISSUE THREAD

**Issue by maikirakiwi** [ciderapp/Cider#1034]
### Relevant Language

zh_CN; zh_HK; zh_TW

### Change or Addition or Both

Change a Language

### Change Requested / Any Additional Information

There is a major issue with the way how these languages are translated in some parts of the app.
Notably the following items:

`Open Cider on Startup` under Settings - General
`Resume behavior` under Settings - General
`Volume Controls` under Settings - Audio 
`Every option` under Settings - Audio - Browse (Cider Audio Labs)

The translations are either inaccurate, or choppy to the point where it interferes with the overall cohesion of the app. 
The localization files mentioned should be thoroughly reviewed and edited by the community, if you speak Chinese and are decent at translating strings, please help!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Sheey11** [comment]
(Chinese Simplified)
1. `Open Cider on Startup` -> `登陆时启动 Cider`
2. `Resume behavior` -> `启动时打开的页面`
	- Also, for `Dynamic` option -> `记住上次`
3. `Volumn Control` -> `音量控制`
	- `Volumn` -> `音量` (Currently is fine)
	- `Volumn step` -> `调整增减量`
	- `Max Volumn` -> `最大音量` (Currently is fine)
4. I didn't found that option

**Comment by maikirakiwi** [comment]
> (Chinese Simplified)
> 
> 1. `Open Cider on Startup` -> `开机启动 Cider`
> 
> 2. `Resume behavior` -> `启动时打开的页面`
> 
> 	- Also, for `Dynamic` option -> `记住上次`
> 
> 3. `Volumn Control` -> `音量控制`
> 
> 	- `Volumn` -> `音量` (Currently is fine)
> 
> 	- `Volumn step` -> `调整增减量`
> 
> 	- `Max Volumn` -> `最大音量` (Currently is fine)
> 
> 4. I didn't found that option

2其实是自动把最后播放的歌曲加入队列这样你一打开app就能播放上次放的歌曲

两个选项的差别主要是加入上次在Cider客户端放的歌曲或是加入从Apple获取其他设备最后播放放的歌曲

4目前被译为Cider音讯实验室而这个菜单里面的很多选项都翻译的有点怪怪的，不知道能不能麻烦你看一下。

**Comment by Sheey11** [comment]
既然是国人，想知道为啥你不自己看呢
2选项名字翻译成`记住上次播放的歌曲`，选项翻译成 `Disabled` -> `不记住`、`Locally` -> `仅本地`、`History` -> `同步 Apple Music`
4翻译成 `Cider 音效实验室` 就行，至于里面，专业词汇有点多我先看看

**Comment by Sheey11** [comment]
另外我感觉在国内直连 Apple Music 服务器可能会偶尔断联，不清楚原因（服务器应该是在国内，Apple Music 也会这样，不过症状轻一点），不走代理的话 Cider 经常炸掉，图片加载不出来、点了播放没反应、启动的时候就 `Cider is not responding, reload?`、突然有一天打开要重新登录之类的问题。
还是希望先把加载效果、网络错误的提示做出来先，再来审校翻译的问题

**Comment by Sheey11** [comment]
随便查了点资料，这几个选项打开我都不知道具体的效果到底让我感受到了啥。
![image](https://user-images.githubusercontent.com/13375959/168471454-b587e61c-ad38-4741-9752-fc4b4afa96b1.png)
```
Cider 音频质量增强
根据人类听觉的心理声学模型和 AAC 音频编码特性，实时提升 256Kbps AAC 音频的感知质量。
数字和声
模拟旗舰级播放器的数字和声。
Cider 临场声效
由业界顶尖的算法实现临场感。
Cider 空间音频
内置的空间音频效果。需要先启用空间音频。
```

---

至于 `Designed by Cider Acoustic Technologies in California` 这句，我的建议是不翻译，我把 mac 翻过来看了，`Designed by Apple in California` 他也没有翻译。

**Comment by maikirakiwi** [comment]
> 既然是国人，想知道为啥你不自己看呢

我自己现在比较忙，都没有时间去看这个问题。而且我算ABC，语文不是很好hhh。

> 还是希望先把加载效果、网络错误的提示做出来先，再来审校翻译的问题

我们算分工比较明确的那种，我做我的音频实验室然后其他的一概不碰。所以抱歉你得等其他人去解决这个问题。

我只是觉得每次少有的时候我去换成把App换成中文的时候有些翻出来的意思和英文差挺多的。所以会立这个issue。

**Comment by kshuiroy** [comment]
I've created a pull request for updating the Traditional Chinese (Hong Kong) translation (#1060).
Since I don't know the function of some translations, I just leave those in English. I hope there is someone can help for completing the translation.
