### ISSUE TITLE
[Bug]: Observed error when having Cider check for updates

### ISSUE THREAD

**Issue by nikhilnmore99** [ciderapp/Cider#1040]
### Describe the Bug

I purchased Cider from the MS store last week. Today I navigated to Settings > Advanced > Update Cider > Check 
Received error "Error Updating Cider"
![image](https://user-images.githubusercontent.com/19182112/168411768-d64ae3b3-e09a-41ba-924b-8b799ebde895.png)

### Steps to Reproduce

1. Cider verson 1.4.5 downloaded from MS Store
2. Navigate to Settings > Advanced > Update Cider > Check 
3. Received error "Error Updating Cider"
![image](https://user-images.githubusercontent.com/19182112/168411768-d64ae3b3-e09a-41ba-924b-8b799ebde895.png)
[Cider_1.4.5.error.log](https://github.com/ciderapp/Cider/files/8692264/Cider_1.4.5.error.log)

### Environment Information

- OS: Windows
- App Version and/or Commit ID: 1.4.5
- Installed from MS Store

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
This feature has been scrapped and no longer functions. Seeing as you have the Microsoft Store version check for updates in the MS Store instead of Cider itself.

**Comment by nikhilnmore99** [comment]
Yeah, that's working fine. Thanks.
