### ISSUE TITLE
[Bug]: (Linux Mint 20.3) Ctrl+R to reload creates duplicate tray icons that cannot be removed

### ISSUE THREAD

**Issue by Thunderz2016** [ciderapp/Cider#1047]
### Describe the Bug

On Linux, using Ctrl + R to reload Cider will create duplicate tray icons that cannot be removed until reboot or log out. This issue can be reproduced as many times as one desires, creating a seemingly infinite amount of duplicate tray icons. If the user attempts to restart the Cinnamon desktop environment using the panel menu, the tray icons will turn invisible and stay on the system tray; right clicking on them will present a tall, empty context menu.

### Steps to Reproduce

1. Ctrl + R anywhere in Cider, and click OK to reload Cider.
2. A new tray icon appears on the system tray, next to the existing one.
3. Exit Cider and restart Cinnamon on Linux Mint.
4. All tray icons still exist, but are now invisible.

### Environment Information

- OS: Linux Mint 20.3 (5.4.0-110-generic) with Cinnamon desktop environment
- App Version and/or Commit ID: 1.4.7-alpha Build 2550 (commit 51df544, .deb obtained from Releases page)

### Anything else?

Screenshot of system tray after 3 reloads with Ctrl + R:
![image](https://user-images.githubusercontent.com/24950670/168706105-c4a852e4-73f2-425a-89f4-f01145019119.png)

After exiting Cider and restarting Cinnamon: 
![image](https://user-images.githubusercontent.com/24950670/168706314-38fdbc33-b98e-473f-8147-0690b4b9f0b4.png)

Right clicking on the "ghost" tray icon:
![image](https://user-images.githubusercontent.com/24950670/168706676-9fc988cc-d3f8-4c38-8b77-39f4b91f5871.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
Yes, this also happens on Windows.

**Comment by coredev-uk** [comment]
Previously discussed in #858. Not sure why it was closed or sure if any changes were made to resolve the issue.
