### ISSUE TITLE
Touchscreen (again)

### ISSUE THREAD

**Issue by devKaili** [ciderapp/Cider#1048]
### Describe the Bug

When I want to scroll an album on my Surface device, instead of scrolling, I grab songs and move them around.

### Steps to Reproduce

1. Go to an "Album"
2. Try scrolling songs on a touchscreen. 

### Environment Information

- OS: Windows 11 | Version: 10.0.22000 Build 22000
- App Version: 1.4.3-alpha.1862

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
Did you try the latest version of Cider?

**Comment by devKaili** [comment]
Oh I'm sorry, I didn't realise that there is a Beta available.

**Comment by devKaili** [comment]
Ok I just updated and it works amazingly. Thanks for your work on this great app
