### ISSUE TITLE
[Bug]: FileError: 'https://fonts.googleapis

### ISSUE THREAD

**Issue by pozm** [ciderapp/Cider#1056]
### Describe the Bug

when loading the app i encounter the following error:
```
FileError: 'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&display=swap' wasn't found (0)
in [style.less](http://localhost:9000/style.less) on line 2, column 1:

1@import url("assets/fonts/Inter/inter.css");
2@import url('https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100;300;400;500;700;900&display=swap');
3@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@100;300;400;500;700;900&display=swap");
```

I am and was connected to the internet when this occured, restarting, going to old builds etc does not fix.

### Steps to Reproduce

1. literally just opened cider.

### Environment Information

- OS: Windows 11.
- App Version and/or Commit ID:
1.4.7.2558

### Anything else?

![image](https://user-images.githubusercontent.com/44528100/169304967-20c1b97c-1071-49ca-853c-222e377e561d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GamingLiamStudios** [comment]
This error occurs because Cider cannot connect to Google servers. This can be caused by;
- A bad internet connection
- A poorly setup DNS(NextDNS sometimes blocks it)
- Your country is blocking the connection(Mainland China)

**Comment by pozm** [comment]
When trying to access the resource within my browser it loads perfectly fine.

**Comment by pozm** [comment]
For some reason uninstalling and reinstalling the app has bizarrely fixed it. I don't know if you guys want to look into it more, or just close this issue since it's technically fixed.
