### ISSUE TITLE
[Bug]: Missing fonts in tray icon (snap)

### ISSUE THREAD

**Issue by fredrikhl** [ciderapp/Cider#1057]
### Describe the Bug

The systray menu entries consists only of empty squares / notdef glyphs:

![image](https://user-images.githubusercontent.com/1093531/169411018-73307d17-8552-4a0a-9a77-53a77f40ded3.png)

### Steps to Reproduce

1. Install Cider from the snap store (latest/edge, v1.4.6, 2022-05-11)
2. Start Cider
3. Right click the Cider systray icon

### Environment Information

- OS: Fedora 35
- snapd: 2.55.3
- snap-id: 2PJi9WNcrpxB9Bh79Ov3E2V7Hc7PIMV8
- App Version: 1.4.6

### Anything else?

I've found multiple issues on the snapcraft forums regarding missing fonts on Arch and Fedora — so this seems to be a bit of an upstream issue maybe?  However, it also looks like there are fewer issues when building on the core20 base.  Maybe repackaging using a newer base would fix this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mefsaal** [comment]
this is a snap fontconfig bug.

Please try this :

`rm -rf ~/.cache/fontconfig `
`sudo fc-cache -r -v`

**Comment by fredrikhl** [comment]
> Please try this :

That did not help in my case.

**Comment by yazninja** [comment]
> That did not help in my case.

did you try installing the snap files from [releases repo](https://github.com/ciderapp/cider-releases/releases/download/v1.4.7-beta.212/cider_1.4.7-beta.212_amd64.snap)?
