### ISSUE TITLE
[Bug]: Unable to close fullscreen view when not playing a song

### ISSUE THREAD

**Issue by bierbaumtim** [ciderapp/Cider#1062]
### Describe the Bug

If you open the fullscreen view, where only the album cover, the music controls and the lyrics are visible and wait until the song is completed and try to close the fullscreen view, a error message _`Error occured: Uncaught TypeError: Cannot read properties of undefined (reading 'type')`_ is shown multiple times(3 times).

### Steps to Reproduce

1. Play a song
2. open fullscreen view
3. wait until song is completed
4. try to close fullscreen view by pressing _`esc`_

### Environment Information

- OS: WIndows 11 21H2 Build: 22000.675
- App Version and/or Commit ID: 1.4.7-alpha

### Anything else?

Screenshot of the error message: 
![image](https://user-images.githubusercontent.com/40519580/169662816-6e3d6794-00cb-4af7-b093-5dacaf0a6c08.png)

You can workaround that error, when you open the queue and play the song again and while the song is played you close the fullscreen view.

I think the issue is caused by a missing null check when loading the album cover for the hero animation.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amaru8** [comment]
**Hi @bierbaumtim, I have some great news!** A fix has been implemented by @cryptofyre in the latest development version of **Cider** and will be included with the next Microsoft Store update.

**Comment by bierbaumtim** [comment]
Great, thanks :)
