### ISSUE TITLE
[Bug]: Space bar scrolls page down or selects recently clicked button

### ISSUE THREAD

**Issue by CapnCocoa** [ciderapp/Cider#1064]
### Describe the Bug

If I want to press the space bar to pause/resume playback, it also scrolls the page down for some reason as if it were a webpage. Additionally, if I recently clicked a button in the app and then press the space bar, the button is selected with a red outline. 

https://user-images.githubusercontent.com/105993474/169668650-e9093408-99a0-4237-bb63-2414c9bb3a7a.mov

### Steps to Reproduce

To scroll down:
1. Press space without having clicked any buttons

To highlight a button:
1. Click on a button, then press space to pause/resume playback
<img width="259" alt="Screenshot 2022-05-21 at 3 55 31 PM" src="https://user-images.githubusercontent.com/105993474/169668661-c8822402-5169-4309-a5b2-3631ddb0fe8f.png">

### Environment Information

- OS: macOS 12.3.1
- App Version and/or Commit ID: ver 1.4.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DashCruft** [comment]
Similar issue happens on Linux - difference being is that the highlight shows up when clicking on a button and then pressing the super key.
