### ISSUE TITLE
[Bug]: 900x900px Album Art Quality loads with signifacnt delay

### ISSUE THREAD

**Issue by DashCruft** [ciderapp/Cider#1070]
### Describe the Bug

When opening to an artist's profile for instance, the album/single covers take significant amounts of time to load. It's not my Internet's fault because I have a pretty strong connection to the internet.

### Steps to Reproduce

1. Open Cider
2. Enable 900x900 album cover loader by using iTheme advanced settings
3. Go to an artists profile
4. witness the load time. sometimes it might take even 5 seconds for a cover to load.

### Environment Information

- OS: Arch Linux
- App Version and/or Commit ID: 1.4.7-beta.undefined

### Anything else?

I understand loading cover arts in that quality comes with expenses, however, the default resolution is very low.

Loading banners with 900x900 resolution as well shouldn't take a very huge amount of time to get loaded one by one. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
hi @DashCruft,
iVanced is not related to Cider, please post your issue there to avoid confusion

**Comment by DashCruft** [comment]
Alright sorry for the confusion.
