### ISSUE TITLE
[Bug]: Playlist "large" layout awkwardly reflows "Search" bar under row of buttons (for playlist that is in your library)

### ISSUE THREAD

**Issue by macintacos** [ciderapp/Cider#1074]
### Describe the Bug

When viewing a playlist that is "large" (i.e. you have not begin scrolling so the artwork has not compacted) the buttons are reflowed oddly on macOS:

![CleanShot 2022-05-23 at 22 10 46@2x](https://user-images.githubusercontent.com/8128941/169934568-0a887ba6-a247-4db1-8961-dc532863b28f.png)

When I scroll so that the playlist artwork gets smaller, the issue goes away:

<img width="969" alt="CleanShot 2022-05-23 at 22 13 25@2x" src="https://user-images.githubusercontent.com/8128941/169934621-98bec77d-e5ed-4466-b666-05b21c24dce3.png">

### Steps to Reproduce

1. Open any playlist that you have added to your library and resize the window so that the "Play"/"Shuffle"/"Remove from Library" buttons brush right up against the "Search" bar.
2. Observe as the buttons awkwardly jump up above the "Search" bar.

### Environment Information

- OS: macOS 12.4 (+ screenshot of About, if that helps)

<img width="698" alt="CleanShot 2022-05-23 at 22 15 17@2x" src="https://user-images.githubusercontent.com/8128941/169934861-3a54534e-0350-4e8b-be83-60b77fd92fab.png">

- App Version and/or Commit ID: 1.4.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
can confirm, this exists in all other platforms

**Comment by DashCruft** [comment]
Yeah it's really annoying. I'd at least think this feature should have a toggle in settings or should be just disabled by default.
