### ISSUE TITLE
[Bug]: Remote Keybind crashes app.

### ISSUE THREAD

**Issue by lilyjeffs** [ciderapp/Cider#1080]
### Describe the Bug

When I press Command + W on my Mac, it just quits the app rather than opening the remote like it's supposed to.

### Steps to Reproduce

1. I clicked on Command + W on my Mac

### Environment Information

- OS: Monterey 12.3.1
- App Version and/or Commit ID: 1.4.7

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
Privately being handled.

User is not behind any firewall or enterprise network.

Remote URL works when typed in manually into browser omnibox, however keybind crashes Cider

**Comment by quacksire** [comment]
macOS window controls override given Web Remote combo.


TL;DR Change default Web Remote combo

**Comment by mefsaal** [comment]
Reset Keybinds.
