### ISSUE TITLE
[Bug]: Any Library tab causes Cider to freeze

### ISSUE THREAD

**Issue by folp02** [ciderapp/Cider#1086]
### Describe the Bug

Clicking on Recently Added, Songs, Albums, Artists, Videos or Podcasts causes app to freeze.

### Steps to Reproduce

1. Clicked on... Recently Added, Songs, Albums, Artists, Videos or Podcasts causes app to freeze.

### Environment Information

- OS: macos 12.4
- App Version and/or Commit ID: 1.4.7

### Anything else?

If I start playing something from a playlist and then click on one of the above the music will continue to play but the app is essentially frozen.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Cannot reproduce need more information.
