### ISSUE TITLE
[Bug]: Can't sign in and use the app after buying it

### ISSUE THREAD

**Issue by JohKC** [ciderapp/Cider#1087]
### Describe the Bug

I downloaded the app via Microsoft Store as a free trial. It worked wonderfully. Some days later, I got a Microsoft Store message that the free trial is over. I bought the app and I can´t sign in. I get a popup message saying "Error occurred: Script error". I uninstalled the app and it still doesn't work.

### Steps to Reproduce

1. Download the app as free trial
2. Wait some days for the free trial to expire
3. Buy the app and open it
4. Sign in (successfully)
5. Get a popup message that says "Error occurred: Script error"

![image](https://user-images.githubusercontent.com/34071606/170803179-5cbd6337-ff2c-4b86-b368-6afe65e3d190.png)

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Hello we have a server outage right now relating to Railway. What you are experiencing is normal behavior during this time. I kindly ask you to wait for those people investigating this issue.

**Comment by maikirakiwi** [comment]
Should be resolved

**Comment by JohKC** [comment]
Thank you! :)
