### ISSUE TITLE
[Bug]: Video controls are moved beyond lower window border in Mojave Window Style

### ISSUE THREAD

**Issue by jantede** [ciderapp/Cider#1090]
### Describe the Bug

When using the Mojave style, controls of the video player are moved beyond the lower window border so that you cannot control playback. I would expect the controls to be fully visible and usable as in Maverick style.

### Steps to Reproduce

1. Under Settings > Visual select "Mojave" as Window Style
2. Start Playback of a music video

### Environment Information

- OS: Windows 11 Pro 21H2 (22000.675)
- App Version and/or Commit ID: 1.5.0-beta.271

### Anything else?

Video Controls in Maverick window style (as it should be)
![grafik](https://user-images.githubusercontent.com/4920603/171050641-7ef26c44-85e6-437c-89ea-7420759790c1.png)

Video controls moved beyond lower window border when using Mojave window style
![grafik](https://user-images.githubusercontent.com/4920603/171050575-3829de5e-a803-48d4-aa68-ba8c4b186522.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Fixed, as of https://github.com/ciderapp/Cider/commit/e78ac427a42472c8a96c9adf6c30efe9bffed6e7.
