### ISSUE TITLE
[Bug]: San Francisco Font Fails to Appear in the Lyrics Section

### ISSUE THREAD

**Issue by HashaRock** [ciderapp/Cider#1091]
### Describe the Bug

I've been using Cider for the past week or so and decided to test the lyrics feature in my music.  However, the original font displayed in some of the docs regarding the font of the lyrics is off on my Cider application. 
![image](https://user-images.githubusercontent.com/63619145/171057893-95146370-5e8d-4c69-b105-18872b63d91c.png)

There is an example of the lyrics being different than normal. 

### Steps to Reproduce

1. Click on lyrics icon while listening song
2. Observe the different font

### Environment Information

- OS: Windows 10 21H2
- App Version and/or Commit ID: Cider Version 1.5.0-beta.297

### Anything else?

![image](https://user-images.githubusercontent.com/63619145/171058116-5a1253be-f5da-4137-b4d7-ffb995d3011f.png)

Lyrics font shown properly in demo pic.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HashaRock** [comment]
Also note to mention, this is a local install only to the user.

**Comment by cryptofyre** [comment]
Fixed, also we don't use San Francisco just a heads up. We use a font called [Pretendard].(https://fonts.adobe.com/fonts/pretendard)
