### ISSUE TITLE
[Bug]: Follow On Cider and Subscribe On iTunes buttons is not working

### ISSUE THREAD

**Issue by ductoanvo** [ciderapp/Cider#1095]
### Describe the Bug

When I click both buttons to add a podcast to my library, I get no response from the App and the button's status doesn't change to Unsubscribe.

### Steps to Reproduce

1. Go to the Podcasts tab
2. In the search bar, type the name of the podcast you want to find
3. Click to view your channel from the results
4. Click "Subscribe on iTunes"

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: version 1.4.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by megaturbo** [comment]
Same issue on 

Manjaro `21.3.6`
Cider `1.5.3-beta.1`
