### ISSUE TITLE
[Bug]: Can't install with winget

### ISSUE THREAD

**Issue by issac4892** [ciderapp/Cider#1104]
### Describe the Bug

A bug happened!

winget throws on 404 when i try to download via winget

### Steps to Reproduce

run winget install --id=CiderCollective.Cider.Nightly  -e

### Environment Information

- OS: windows 11 
- App Version and/or Commit ID: X

### Anything else?

C:\Users\issac>winget install --id=CiderCollective.Cider.Nightly  -e
Found Cider Nightly [CiderCollective.Cider.Nightly] Version 1.4.7-alpha
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/ciderapp/cider-releases/releases/download/v1.4.7.2511/Cider-Setup-winget-1.4.7-alpha.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
hey, while we are resolving the issue with Cider Nightly you can use Cider package `winget install --id=CiderCollective.Cider -e`

**Comment by elvergal** [comment]
> hey, while we are resolving the issue with Cider Nightly you can use Cider package `winget install --id=CiderCollective.Cider -e`

Collective version is also broken on winget, you changed the app verions nomenclature

**Comment by oXyiGYJ** [comment]
I tried to install using `winget install --id=CiderCollective.Cider  -e` today and it errored out with a 404. It is trying to download https://github.com/ciderapp/cider-releases/releases/download/v1.5.2-beta.9/Cider-Setup-winget-1.5.2-beta.9.exe but when going to the releases repo, that file is not in the releases, just a .dmg and a .pkg (for files relevant to this).

**Comment by coredev-uk** [comment]
The winget version is extremely outdated. Feel free to install from the latest release found [here](https://github.com/ciderapp/cider-releases/releases/latest).
