### ISSUE TITLE
[Bug]: Cant loggin on Windows

### ISSUE THREAD

**Issue by luigira** [ciderapp/Cider#1106]
### Describe the Bug

Cant login on windows app, even with an specific app password, new password, nothing. 

### Steps to Reproduce

1. Just oppening Cider.
2. Try to loggin.

### Environment Information

- OS:
- App Version and/or Commit ID:

Windows 11 21H2
Cider Version 1.5.0-beta.332 (main)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Can't reproduce, nor is there enough information for us to create a fix.
