### ISSUE TITLE
Use Apple social sign on

### ISSUE THREAD

**Issue by DrewNeilson** [ciderapp/Cider#111]
**Is your feature request related to a problem? Please describe.**
To sign in, I'm required to enter my Apple ID and password. I'm not comfortable entering that password into this app. I only enter that password into official Apple sites and software.

**Describe the solution you'd like**
A "sign in with Apple" button. I've seen it on other sites. It functions like Facebook's 'sign in with Facebook' button, but it goes through Apple instead.

**Describe alternatives you've considered**
I doubt that I'll use Cider until there is a way for me to sign into my Apple account in it without giving it my password and without giving Cider's developers access to my Apple account (other than required access to my Apple Music data, such as my library and my playlists).

**Additional context**

**Comment by DrewNeilson** [comment]
This should be a high priority feature, perhaps the highest priority feature, because all of the other features are meaningless for anyone whom chooses not to sign in in the first place.

**Comment by vapormusic** [comment]
What do you mean? This app uses the official Apple log-in API and there is no other way about that. This app opens an iframe for you to log in (which is actually Apple opens the iframe themselves from their own library MusicKitJS) and has no way to access your credentials. We can't even change the iframe to load as a Chrome tab as the process is 100% done by Apple and it will invalidate any tampering attempts.

If you have any doubts, you can further ask us at our discord: https://discord.gg/applemusic. Furthermore, if you are worried of anything, the project is fully open-sourced and you can verify and compile the app yourselves.

**Comment by vapormusic** [comment]
> And it couldn't be made as a pop up instead of an iframe?
> 
> Because that would provide a lot more verifiability for the non-tech users to see that it's actually the apple page rather than an iframe just designed to look like it.

Apple handles all of the sign-in themselves, we can't touch this, sorry. Also, that iframe is Apple's own log-in website, We don't and can't tamper with that.
