### ISSUE TITLE
[Bug]: Library not opening until I kill all Cider processes (Flatpak Fedora Linux)

### ISSUE THREAD

**Issue by Dworv** [ciderapp/Cider#1112]
### Describe the Bug

Usually, when I open Cider on Fedora, everything works well. However, recently nothing has been loading. I need to close all Cider processes (there are usually like 10-20 which is annoying) to make the library load again.

### Steps to Reproduce

1. I opened Cider.

### Environment Information

- OS: Fedora 36 Linux
- App Version and/or Commit ID: 1.5.0-beta.334

### Anything else?

![image](https://user-images.githubusercontent.com/88643996/171552736-56497887-2e00-4544-a5a9-1993c07f8c3d.png)
![image](https://user-images.githubusercontent.com/88643996/171552756-7c29b55c-8916-4f7d-b1b5-6c3369977358.png)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by pietropecchi** [comment]
Same issue over here, Fedora36 + FlatHub

**Comment by Dworv** [comment]
I can't figure out how to remove that, can somebody else do it?

**Comment by Dworv** [comment]
Not stale

**Comment by yazninja** [comment]
update Cider and delete `~\.config\Cider`

**Comment by Dworv** [comment]
> update Cider and delete `~\.config\Cider`

Didn't work for me

**Comment by cryptofyre** [comment]
Seems like an edge case and I can't seem to reproduce this issue.

Closing.
