### ISSUE TITLE
[Bug]: Start Radio on Song not working

### ISSUE THREAD

**Issue by steffenw94** [ciderapp/Cider#1116]
### Describe the Bug

A bug happened!

When i want to start a Radio directly from a Song in Library, it dont work. Nothing happen.

When i start radio from a artist, it is working.

### Steps to Reproduce

1. Clicked on Songs
2. Right click on a song
3. Clicked on Start Radio
4. Nothing happen

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.5.0 beta 353

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnbreakCode** [comment]
it's working fine for me in latest build

**Comment by steffenw94** [comment]
i updated now to latest main build, but its not working on my side.

i right click any song in a playlist and click start radio -> nothing happen

**Comment by steffenw94** [comment]
Just to clearify what i mean

![image](https://user-images.githubusercontent.com/68820195/172136785-bf964a99-694e-4979-8315-61f1b817a939.png)

Song in playlist not working
Radio on artist is working

But i saw, in Apple Music its also not working on a title, maybe you can just remove the start radio button on titles, so its not confusing anymore?

**Comment by Naxterra** [comment]
I have version 1.5.1 Beta 65 and have the same issue. Start Radio does nothing and app is not generating any logs. It happens in all the songs in the library.

If I start songs under Listen Now, it works, but not from my library.

**Comment by kyrie25** [comment]
Seems like this issue still persists on 1.5.1 beta 435 for me.
If anyone needs it, apparently it's a MusicKit problem when it tries to fetch a (could be) outdated URL?
![image](https://user-images.githubusercontent.com/77577746/179435511-0655d3c4-fd62-48dd-a678-9ea993359b97.png)
