### ISSUE TITLE
[Bug]: Pressing "View all" leads to crash

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider#1118]
### Describe the Bug

Pressing on "View all" button leads to crash.
Cider isn't responding anymore.

### Steps to Reproduce

1. Clicked on "View all"

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID: 1.5.369

### Anything else?

![image](https://user-images.githubusercontent.com/34512773/171909953-58597af5-f693-496d-86f7-21c94bea5ca3.png)
p.s. there are no logs

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Thunderz2016** [comment]
Can confirm this happens on both Windows and Linux, and it seems to be affecting version 1.4.7 as well.

**Comment by coredev-uk** [comment]
Issue not resolved, fix seemed to only work when launching uncompiled.
