### ISSUE TITLE
[BUG] Behaviour of the Rewind/Previous button is inconsistent when paused

### ISSUE THREAD

**Issue by JKingweb** [ciderapp/Cider#112]
**Describe the bug**
When paused, rewinding retains the paused state, but changing to the previous track switches to the play state

**To Reproduce**
1. Seek into the second track in a playlist
2. Pause playback
3. Press the Rewind/Previous button to jump to the beginning of the track; observe playback is still paused
4. Press the button again to move to the beginning of the previous track; observe playback begins automatically

**Expected behavior**
Behaviour should be consistent one way or the other. I would prefer that audio remains paused until explicitly unpaused, but this is not the behaviour of the "Next" button, so the resuming of playback is presumably intentional.

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Linux
 - Application Version *(e.g. 2.5.0)*: Commit c1becbd

**Comment by vapormusic** [comment]
I think this is due to Apple's "go to previous track" method will automatically play that track (as you expected) while the rewind function (which we added) wont do this.
