### ISSUE TITLE
[Bug]: OOBE setup text mixing/placeholder

### ISSUE THREAD

**Issue by Ilovemyhous** [ciderapp/Cider#1131]
### Describe the Bug

Hello!
After installing cider (version 1.5.397) trough the AUR , and went trough the setup process, I've noticed that there's one slide where the text doesn't load/placeholder.
![image](https://user-images.githubusercontent.com/50217071/172052132-01ee3fdd-93b9-48b6-9478-02f6f8433b3d.png)

The rest of the app works fine... more or less, I've tried a spatial audio song, which should be Dolby Atmos, but to my surprise, it only reports as being two channels. In context, I've opened an actual DolbyAtmos demo file, and it reported way more channels.
![image](https://user-images.githubusercontent.com/50217071/172052369-11a04b29-6f4a-42a2-862c-7f22ffcb2ff4.png)

One last thing, but I need to check if it works, is that my keyboard has media control buttons, and I'm not sure if they work.

### Steps to Reproduce

Missing text: First start of the program.
Only two channels: Used PulseEffects

### Environment Information

- OS: Arch Linux on kernel 5.18.1-zen1-1-zen
- App Version and/or Commit ID: 1.5.397

### Anything else?

So far, great app, thanks for it!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
OOBE ( setup ) is a WIP. Cider doesn't support Dolby Atmos.

**Comment by Ilovemyhous** [comment]
As for the bandwidth, I saw it's limited for 265kbps, so no Lossless I guess?

**Comment by GamingLiamStudios** [comment]
https://github.com/ciderapp/Cider/discussions/889#discussioncomment-2581757
> Lossless playback is currently not supported in Cider. Apple's MusicKit Framework does have lossless support, however, decryption of this audio is not supported.

**Comment by GamingLiamStudios** [comment]
We got CAP tho

**Comment by Ilovemyhous** [comment]
Okay, thank you for all the responses!
And again, thanks for the app!
