### ISSUE TITLE
[Bug]: An icon appears next to the song

### ISSUE THREAD

**Issue by MuhammetEminCakir** [ciderapp/Cider#1134]
### Describe the Bug

An icon appears next to the song. It happens in both Mojave and Maveric window style.

### Steps to Reproduce

1. Open the app
2. Open any song

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: 1.5.403 (main)

### Anything else?

<img width="846" alt="Ekran görüntüsü 2022-06-06 115858" src="https://user-images.githubusercontent.com/64583157/172130926-ea434c4b-beea-49a8-94f0-1c636f9c3c56.png">
<img width="846" alt="Ekran görüntüsü 2022-06-06 120156" src="https://user-images.githubusercontent.com/64583157/172130948-73ff369c-7fe4-4ea0-a7bc-da87e0673632.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
That's the icon for CAP (Cider Adrenaline Processor). You can find more on this in the settings.
