### ISSUE TITLE
[Bug]: Cider icon doesn't work properly when Library is hidden

### ISSUE THREAD

**Issue by MuhammetEminCakir** [ciderapp/Cider#1135]
### Describe the Bug

When I click on the Cider icon it brings up some options. But while the Library is hidden, it opens the Library first. Then the options will open.

### Steps to Reproduce

1. Open the app
2. Click to "Hide Library"
3. Click the Cider icon

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: 1.5.403 (main)

### Anything else?

https://user-images.githubusercontent.com/64583157/172132406-395377a7-3f84-4e51-821a-70dd29d5e884.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
Its a feature from how you used to close and open the library, so it is a bug, however if you right click on the Cider icon, it will open the menu even when the library is closed, and will not open the library again.

**Comment by coredev-uk** [comment]
I believe the collapsable sidebar has been removed from the maverick layout. Just update your Cider and the issue will be resolved.
