### ISSUE TITLE
[Bug]: There is an empty line in the system tray menu

### ISSUE THREAD

**Issue by MuhammetEminCakir** [ciderapp/Cider#1136]
### Describe the Bug

There is an empty line in the system tray menu (only visible when app is not minimized).

### Steps to Reproduce

1. Open the app
2. Open system tray
3. Right click the Cider icon

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: 1.5.404 (main)

### Anything else?

When app not minimized
<img width="1012" alt="Ekran görüntüsü 2022-06-06 122025" src="https://user-images.githubusercontent.com/64583157/172134535-b03d0598-a788-40df-a8cc-9e2d418872ce.png">

When app minimized
<img width="965" alt="Ekran görüntüsü 2022-06-06 122546" src="https://user-images.githubusercontent.com/64583157/172134544-cc76e0b7-cad2-41fb-93e3-030fbe3c23f1.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Probably a missing locale item.

**Comment by MuhammetEminCakir** [comment]
It happens English too
<img width="362" alt="Ekran görüntüsü 2022-06-06 174922" src="https://user-images.githubusercontent.com/64583157/172185579-af97ad48-dee9-4869-9a11-4316681ad44d.png">

**Comment by MuhammetEminCakir** [comment]
<img width="238" alt="Ekran görüntüsü 2022-06-17 020112" src="https://user-images.githubusercontent.com/64583157/174192061-b7d37d3e-baf2-4939-9793-b710ef810fdb.png">
It is still an issue in 1.5.1 (stable) and 1.5.1-beta.70 (main).
