### ISSUE TITLE
[Bug]: Songs added via iTunes are not respected if a different version is found in Apple Music

### ISSUE THREAD

**Issue by katawful** [ciderapp/Cider#1137]
### Describe the Bug

I have an album of game soundtracks that I added via iTunes. However, some of the tracks are on Apple Music already on a different album (like a compilation of series tracks). When playing these songs, Cider will always choose the song from Apple Music which completely messes up the metadata for the song itself

### Steps to Reproduce

Add a song via iTunes from an album not found on Apple Music, but has a version elsewhere like in a compilation. "Escape from the city" by Jen Senoue for Sonic Adventure 2's soundtrack album is an example. Other songs in the album added via iTunes contain all the metadata I added myself, but playing this song Cider will choose to include the metadata from the compilation "Non-Stop Music Selection Vol 2"

### Environment Information

- OS: Arch Linux
- App Version and/or Commit ID: 1.5.0.3896.d0c2d6d3-1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by booploops** [comment]
Does the same happen with the Apple Music web player?
https://music.apple.com/
