### ISSUE TITLE
[BUG] Double clicking a song in any playlist or album adds nothing to queue

### ISSUE THREAD

**Issue by lance-374** [ciderapp/Cider#114]
**To Reproduce**
1. Go to any playlist or album
2. Double click a song
3. Open queue
4. Queue is empty, attempting to skip to next track stops playback

**Expected behavior**
Songs should be queued the same way they are when clicking the play button on the album art

**Environment Information**
 - Windows 10 21H2
 - Application Build 534

**Comment by Swiftzerr** [comment]
Fixed problem in newest pull request

**Comment by vapormusic** [comment]
![image](https://user-images.githubusercontent.com/27716185/149270321-9236a8dd-37b3-4f81-901f-7ff345c401f1.png)
I think it is intended, click the artwork will queue the whole thing
