### ISSUE TITLE
[Bug]:  OOBE showing on every startup

### ISSUE THREAD

**Issue by Shane-Park** [ciderapp/Cider#1140]
### Describe the Bug

whenever i restart the cider app, it shows this screen again and requires login
![image](https://user-images.githubusercontent.com/74809918/172547594-ded9caa4-aec3-4db5-b417-32eeac8d3e98.png)

### Steps to Reproduce

1. restart the app

### Environment Information

- OS: Ubuntu 20.04
- App Version and/or Commit ID: 1.5.419

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by booploops** [comment]
OOBE has been disabled in today's commit

**Comment by Shane-Park** [comment]
Actually it was because i use port 9000 in another application :(
if any of you have login issue, please check it !
