### ISSUE TITLE
[Bug]: Enabling mica background causes frontend to become unresponsive

### ISSUE THREAD

**Issue by pozm** [ciderapp/Cider#1141]
### Describe the Bug

When enabling Mica (Window background style in visual settings) the frontend will just freeze up, the app will continue to play music but you're unable to interact with it.

### Steps to Reproduce

1. go to seconds -> visual
2. enable mica in window background style

### Environment Information

- OS: Windows 11: 22H2 22621.1
- App Version and/or Commit ID: 1.5.414

### Anything else?

This has been happening for quite alot of builds for me. but i have only just reinstalled windows today and im still experiencing this issue so i don't think it's unique to me although im unable to find any issues about it in this repo.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozm** [comment]
oh you need to have transparent frame enabled

**Comment by KillerParticles** [comment]
> oh you need to have transparent frame enabled

No you don't, Mica will work without it enabled.

Question, do you use wallpaper engine? If you do, this is known to cause this bug (i had the same bug as you and other did too)

**Comment by KillerParticles** [comment]
I see, well transparent frame causes a lot of Cider's stuff to break like rounded corners and animations and needs theme support, just fyi.
