### ISSUE TITLE
[Bug]: Casting instantly says connected, no audio output.

### ISSUE THREAD

**Issue by snjyr123** [ciderapp/Cider#1150]
### Describe the Bug

Trying to connect to my Google Home stereo pair, says connected instantly, nothing plays. Happens to all the other Google Homes in my house as well. 

### Steps to Reproduce

1. Clicked on... Cast, waited for scanning, clicked on the desired output device.

### Environment Information

- OS: Microsoft
- App Version and/or Commit ID: 1.5.434

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by snjyr123** [comment]
any updates :)

**Comment by snjyr123** [comment]
Open Control Panel
Click Network and Internet
Click Network and Sharing centre
Click Change Advanced Sharing Settings on the left-hand side
Expand the Guest or Public list and turn on both options.
Restart your PC
I followed all of this but it still doesn't work, currently on version 1.5.1

**Comment by OscarDL** [comment]
Having the same issue here on Windows 11 on the latest Cider version currently (1.5.6)

**Comment by coredev-uk** [comment]
Try the latest pre-release beta found [here](https://github.com/ciderapp/cider-releases/releases/tag/v1.5.7-beta.204)

**Comment by TimothyRowley** [comment]
Having the same issue with Casting. I select any device, I hear the connect chime but no sound comes out when it's playing. Tried on 1.5.9 and 1.6.0.

**Comment by maikirakiwi** [comment]
wont fix as Cider 1 is reaching EOL
