### ISSUE TITLE
[Bug]: disabling Audio Advanced Functionality increases the volume

### ISSUE THREAD

**Issue by xeron** [ciderapp/Cider#1151]
### Describe the Bug

Repeatedly enabling / disabling Audio Advanced Functionality keeps increasing the volume.

### Steps to Reproduce

1. Start playing some track
2. Go to Settings - Audio
3. Enable Advanced Functionality
4. Disable Advanced Functionality
5. Volume will increase
6. Repeat
7. Volume will increase again
8. Etc...

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID: 1.5.434

### Anything else?

Cider restart fixes the audio volume.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Are you from Microsoft Store or GitHub beta?

**Comment by xeron** [comment]
From winget.

**Comment by maikirakiwi** [comment]
> From winget. I think it uses github.

winget is maintained by a third party and isn’t up to date as of now. Try current builds on GitHub instead.

**Comment by xeron** [comment]
1.5.434 is also affected.

**Comment by maikirakiwi** [comment]
Fixed by [ba30e1f6](https://github.com/ciderapp/Cider/commit/ba30e1f636042d670e20cf3155cf03cb09f065a1)
