### ISSUE TITLE
[Bug]: Microsoft App Store Version of Cider Beta Wont Open

### ISSUE THREAD

**Issue by nigelonius** [ciderapp/Cider#1152]
### Describe the Bug

I was on the trial version of the Cider Alpha which I acquired from the MS Store and this morning it told me the trial was over. So I had to purchase the app (for twice the amount than the Alpha was costing) but now it simply wont open. I am beyond livid...why would you charge for a product that is incomplete? Please provide a fix or alternatively, instructions on how to initiate a refund. Granted it's not a lot of money, but its the principle.
![image](https://user-images.githubusercontent.com/87260000/173013819-c3e0b3fb-9bbf-4b6d-8efb-b284f9832035.png)

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
> ### Describe the Bug
> I was on the trial version of the Cider Alpha which I acquired from the MS Store and this morning it told me the trial was over. So I had to purchase the app (for twice the amount than the Alpha was costing) but now it simply wont open. I am beyond livid...why would you charge for a product that is incomplete? Please provide a fix or alternatively, instructions on how to initiate a refund. Granted it's not a lot of money, but its the principle. ![image](https://user-images.githubusercontent.com/87260000/173013819-c3e0b3fb-9bbf-4b6d-8efb-b284f9832035.png)
> 
> ### Steps to Reproduce
> 1. Clicked on...
> 
> ### Environment Information
> * OS: Windows 11
> * App Version and/or Commit ID:
> 
> ### Anything else?
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

The app works fine for me, try to use a VPN, our token server may have trouble connecting to your internet.

**Comment by RyzenDew** [comment]
his cancel instead of ok and it works
