### ISSUE TITLE
[Bug]: Cider won't play songs with no album art

### ISSUE THREAD

**Issue by Thrilla1** [ciderapp/Cider#1154]
### Describe the Bug

On Cider, whenever I try and play a song in my playlist with no album art it just refuses to play. When searching for the song, it displays with album art and plays, but after adding to playlist it has no album art and won't play. It shows with no album art on the Apple Music app but still plays.

Try with Fevgo-Hoizo by Pashalis Terzis on the album Ine Kapies Agapes

### Steps to Reproduce

1. Clicked on song in my playlist
2. Song refuses to play

### Environment Information

- OS: Windows 11 64-bit
- App Version and/or Commit ID: 1.5.0-beta.347

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
This is an Apple Music bug and not a Cider bug.

Nonetheless, this is how you fix the bug and play the song.

> How to fix songs blanked out: (need to use iTunes/MacOS Music app for this)
> 
> 1. Remove the song from your Library and Playlists
> 2. Update iCloud Music Library
> 3. Close iTunes/Music app and reopen, checking to make sure the song is fully gone
> 4. Re-add the song to your Library and Playlist, then edit the metadata for one of the songs you added (add a comment or 
>    something)
> 5. Update iCloud Music Library
> 
> - Song should now be fully synced and working again.
