### ISSUE TITLE
[Bug]: Cider constantly freezes on Ubuntu Linux 22.04 while playing

### ISSUE THREAD

**Issue by glaubermd-leaf** [ciderapp/Cider#1156]
### Describe the Bug

First of all, what a nice piece of work here... I think this is the best music player I used in years for listening to streaming music.

Unfortunately, it keeps freezing constantly :(

### Steps to Reproduce

1. When playing music, it freezes for some time (maybe bad wi-fi signal sometimes?) and I need to close the application and reopen in order to listen again.

### Environment Information

- OS: Ubuntu 22.04
- App Version and/or Commit ID: 1.4.6

### Anything else?

I'm using a relative new laptop, a Samsung Intel Core i5 with 8GB RAM and NVMe.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Any updates or recent crashing as of later releases?

**Comment by glaubermd-leaf** [comment]
1.5.1-beta.99 snap package is way more stable than the previous version I've been using on Ubuntu 22.04.

The issue was solved in this new version.
