### ISSUE TITLE
[BUG] I can't play iCloud Music Library's music.

### ISSUE THREAD

**Issue by YTJVDCM** [ciderapp/Cider#116]
I'm a non-English speaker (using Google Translate), so there may be grammatical mistakes. 

**Describe the bug**
It's not showing the iCloud music library music (that's not available on Apple Music) on some tabs.
We can find the album on "Home" tab, but it can't open album page.
On "Songs" page, it can find the music that uploaded that, but it can't play that music (and that play incorrect music).

**To Reproduce**
1. Upload music to iCloud music library (with iTunes or Music app on macOS)
2. Open Cider
3. We can't see the added musics on "Recently Added", "Listen Now", "Albums", and so on.

**Expected behavior**
We can see and play music on iCloud music library.

**Screenshots**
Left : "Recently Added" tab on Apple Music for web
Right : "Recently Added" tab on Cider

![ciderbug](https://user-images.githubusercontent.com/50657624/148990427-69868218-fd25-4e12-a271-d2c52024c876.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Arch Linux x86_64 (Kernel Version : 5.15.12-arch1-1)
 - Application Version *(e.g. 2.5.0)*: 1.0.0.692.a663f30-1
 
**Additional context**

I'm not trying on iTunes match, but I think that has the same problem.
Maybe #99 and #100 are the same issue.

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Comment by vapormusic** [comment]
fixed by [#222a19](https://github.com/ciderapp/Cider/commit/222aa19d4c42137e19f2f04c5d88ae25aaf0f778)
