### ISSUE TITLE
Stuck in building playlist cache

### ISSUE THREAD

**Issue by AetherKong** [ciderapp/Cider#1164]
### Describe the Bug

After installation and signing in, the program was just stuck in "building playlist cache"
![Uploading 屏幕截图 2022-06-12 235728_115749.png…](https://img1.imgtp.com/2022/06/13/cX4vBEr6.png)

### Steps to Reproduce

1. signed in apple account
2. clicked "continue" button in the sign in page
3. bug happened

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID:v1.51 stable installed by manual installation from the github release pages
- Location: Chinese Mainland

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Please try a [clean install](https://docs.cider.sh/support/troubleshooting#1-clean-installation)

**Comment by AetherKong** [comment]
> Please try a [clean install](https://docs.cider.sh/support/troubleshooting#1-clean-installation)

It works! Thank you.
