### ISSUE TITLE
[Bug]: Integration with Modern Flyouts

### ISSUE THREAD

**Issue by Soren6999** [ciderapp/Cider#1166]
### Describe the Bug

I am currently using the application called modern flyouts which enhances various Windows features 
When using cider it is not allowing me to change the time stamp of the song through modern flyouts. I have contacted them for help which they replied back that you guys have to support the timeline feature of the GSMTC API.

### Steps to Reproduce

I have the modern flyout application.
When changing the volume the time stamp is grayed out and the time and end time are both at 0:00 

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.50

### Anything else?

![image](https://user-images.githubusercontent.com/107338518/173255598-a546e87e-87f8-4798-bae3-2cd3f3cd075b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
As this is more of a feature request, please in the future place these in discussions.

**Comment by cryptofyre** [comment]
Chromium currently does not support the timestamp feature of GSMTC. We use Electron in our project and unfortunately this falls under that category.
