### ISSUE TITLE
[Bug]: Can't play all of the top songs

### ISSUE THREAD

**Issue by wbs306** [ciderapp/Cider#1168]
### Describe the Bug

I can't play all of an artist's top songs, it just play single song in the top songs list.

### Steps to Reproduce

1. Click to any artist detail.
2. In top songs, click See All.
3. Click any songs.

### Environment Information

- OS: Archlinux
- App Version: 1.5.1

### Anything else?

I think there should be a button to play all of top songs, just like apple music do :)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JaxonTekk** [comment]
You can play the artist's top songs on Cider by pressing the play button next to the artists name. 
![image](https://user-images.githubusercontent.com/45437968/174685833-2ac948e5-8c42-4080-8fd3-3e0a6484773f.png)

**Comment by wbs306** [comment]
Have't found this button before until I touch artist's avater...Thanks😂
Before
![image](https://user-images.githubusercontent.com/10919115/174792791-5f6fbaac-6c21-4dac-b279-a50a4902da7b.png) 
After
![image](https://user-images.githubusercontent.com/10919115/174793245-ca9d9d61-802c-4391-9ce3-274e646c5c32.png)

**Comment by TBE4034** [comment]
I've been testing this and it seems like the play button only plays the artist's most popular songs while shuffling the top songs list will play all of their songs.
