### ISSUE TITLE
[Bug]: Cider Remote page is unreadable

### ISSUE THREAD

**Issue by Schmensch** [ciderapp/Cider#1173]
### Describe the Bug

When one enables dark mode and then accesses the "Cider Remote" page (cider icon in the top-left corner -> Web Remote), the page background is still in blinding white.

This means that the rest of the page is pretty unreadable.

### Steps to Reproduce

1. Click the cider icon in the top left corner
2. Click "Web Remote"
3. The Page is white, with some text being black and other being white.

### Environment Information

- OS: Arch Linux, Cider installed via Flatpak.
- App Version and/or Commit ID: 1.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
As the remote is running a web server and the flatpak is sandboxed I'm unsure if this can be worked on. Please forward the issue to the Flatpak repository found [here](https://github.com/flathub/sh.cider.Cider).
