### ISSUE TITLE
[Bug]: New stopped artwork conflict with iVanced plugin

### ISSUE THREAD

**Issue by MuhammetEminCakir** [ciderapp/Cider#1176]
### Describe the Bug

This issue is caused by Cider not iVanced plugin. Because it was working fine before commit mentioned below

iVanced plugin's Use Apple Icons option doesn't work properly after this commit: https://github.com/ciderapp/Cider/commit/493492c579ad7c71b49072905768e1a6b659b4d0

### Steps to Reproduce

1. Open the app
2. Install iVanced plugin
3. Open Super Secret Theme Settings (iVanced settings)
4. Enable "Use Apple Icons" option

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: 1.5.1-beta.70 (main)

### Anything else?

Older versions of Cider
<img width="845" alt="Ekran görüntüsü 2022-06-06 122025" src="https://user-images.githubusercontent.com/64583157/174196089-eae9af39-e253-4d66-9367-c9ce0ceef739.png">

Newer versions of Cider
<img width="834" alt="Ekran görüntüsü 2022-06-17 024556" src="https://user-images.githubusercontent.com/64583157/174195990-9d4c8103-8b8f-4a62-8b41-4c41beead4f8.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
This is not a Cider issue, this is due to a bad theme or plugin combination. 

*Note: not all current plugins and themes are compatible with Cider 1.5.0 and those that don't work properly will need an update.*

**Comment by yazninja** [comment]
iVanced is deprecated, pls use iTheme++ theme pack as i am planning to remove ivanced from the plugins channel... still keeping it there for the hq album artwork
