### ISSUE TITLE
[Bug]: Two systray icon

### ISSUE THREAD

**Issue by MuhammetEminCakir** [ciderapp/Cider#1177]
### Describe the Bug

Two Cider icons appear after an update is installed. ıt will fix after a while

### Steps to Reproduce

1. Install an update
2. Open Windows Systray 

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: 1.5.1-beta.70 (main)

### Anything else?

<img width="283" alt="Ekran görüntüsü 2022-06-17 035519" src="https://user-images.githubusercontent.com/64583157/174201291-d97cabbd-a69c-4399-8e37-7625e925da6f.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
This is a windows visual bug. Doesn't relate to Cider's task tray implementation.
