### ISSUE TITLE
[Bug]: Cider don't play musics with explicit lyrics.

### ISSUE THREAD

**Issue by tomaz-f** [ciderapp/Cider#1178]
### A bug with cider app just don't play explicit songs.
My parental controls are disabled in my apple account. Apple music web  played the music normally.

### Steps to Reproduce

1. Started the app.
2. Search for a explicit music in my playlist (see image below)
3. Click in the music.
4. Cider does nothing.
5. Select another music without explicit tag.
6. Cider starts to play the music without explicit tag.

### Environment Information

- OS: Ubuntu 22.04
- App Version and/or Commit ID: 1.5.1

### Anything else?

![image](https://user-images.githubusercontent.com/35739732/174220117-1cae04c6-c33c-4a1c-9c29-0cf60c62d8d9.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 91XX** [comment]
acing the same issue here...

**Comment by FramedOne** [comment]
I had the content restriction set to OFF. This resulted Cider not be able to play songs with explicit tag. When I turned content restrictions to ON and music to EXPLICIT, Cider works as intended.
![image](https://user-images.githubusercontent.com/107858465/174599390-7bc73201-04ab-4440-8314-ddd44a59bd91.png)
