### ISSUE TITLE
[Bug]: when fullscreen ,cider will lock 30fps (with Gsync)

### ISSUE THREAD

**Issue by xos84292-hub** [ciderapp/Cider#1179]
### Describe the Bug

When I use full screen I feel the screen flicker and feel slow
Then I found out that the cider would be locked at 30fps,But all my other programs work fine at 120hz
 I couldn't find any option to modify the cider's fps.

### Steps to Reproduce

1. fullscreen

### Environment Information

- OS:windows 11 
- App Version and/or Commit ID:1.5.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
We can't do anything about this, G-Sync is controllable by the user. I suggest disabling it for the application.

**Comment by xos84292-hub** [comment]
i m disabling GSYNC for the application in nvidia control panel, problem solved.thank for reply,
