### ISSUE TITLE
[Bug]: Songs with big titles move the tabular view sideways.

### ISSUE THREAD

**Issue by maxrozhik** [ciderapp/Cider#1185]
### Describe the Bug

When adding a song with a big title (Flume - ╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌) shifts the song date and its genre in Songs tab. 

![image](https://user-images.githubusercontent.com/58780544/174489356-c95957c8-fbe1-43eb-8ec7-dda7a96ae11e.png)
![image](https://user-images.githubusercontent.com/58780544/174489364-93c14707-c6f2-4007-9fee-2d4a8ae917cc.png)

### Steps to Reproduce

1. Find **Flume - Hi This Is Flume** mixtape 
2. Find 5th song called ╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌╫§╜φ°⌂▌
3. Add to library
4. Go to **Songs** tab
5. Observe result

### Environment Information

- OS: Windowns 11
- App Version and/or Commit ID: 1.5.1 beta 59 

### Anything else?

ER: The title should be truncated when it reaches the Explicit content boundary

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by JaxonTekk** [comment]
It seems like because the song name contains special character, the title isn't being truncated properly. For other songs without special characters, the title seems to truncate properly.

**Comment by mefsaal** [comment]
it's not a Cider bug : 

Wikipedia :
![Screenshot_20220620_2150-1](https://user-images.githubusercontent.com/56521591/174694182-b582d012-604f-4fbd-913c-ec3e205ca3fd.png)

Apple Music Website:
![Screenshot_20220620_2149](https://user-images.githubusercontent.com/56521591/174694189-af003018-57b1-49a2-a688-8b31bb1b9232.png)

Spotify:
![Screenshot_20220620_2149-1](https://user-images.githubusercontent.com/56521591/174694196-cbbcaafd-62a5-4c20-84ae-d5680dc12489.png)

Apple Music Android App:
![Screenshot_20220620-214834](https://user-images.githubusercontent.com/56521591/174694421-57984339-4694-42c6-9545-da418c763e9d.png)

**Comment by UnbreakCode** [comment]
there is also another issue with it: 
![image](https://user-images.githubusercontent.com/34512773/174808573-e9019d2e-0040-4330-9990-8fb15f4d4b79.png)

**Comment by cryptofyre** [comment]
Fixable, we'll put this on our radar.
