### ISSUE TITLE
[Bug]:  Flicker

### ISSUE THREAD

**Issue by adynt8** [ciderapp/Cider#1187]
### Describe the Bug

When minimize the app to the taskbar and then reopening it about 30 minutes later it proceeds flicker at different speeds.

### Steps to Reproduce

1. Minimize app
2. Wait ~30 minutes
3. Click icon in taskbar
4. Flicker

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.5.0

### Anything else?

https://user-images.githubusercontent.com/34221122/174698977-4a1982ff-9ced-466b-855f-726273c3cae0.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Can't seem to reproduce, buggy driver or windows version?

**Comment by adynt8** [comment]
Not sure, didn't used to happen and I have not updated anything.
