### ISSUE TITLE
[Bug]: Removing a song from queue will always just remove the first song instead

### ISSUE THREAD

**Issue by spjoes** [ciderapp/Cider#1194]
### Describe the Bug

A bug happened!
Imagine you have a queue of 8 songs.
You right click song 5 and click remove. 
Whats this? It removed song 1.

### Steps to Reproduce

1. Start a queue. Doesnt matter the amount of songs
2. open the "Queue Drawer"
3. Right click a song you want to remove
4. Click to remove the song
5. Notice how the first song in the queue gets removed

### Environment Information

- OS: Windows 10 21H1 (19043.1706)
- App Version and/or Commit ID: 1.5.1-beta.99

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nate-thegrate** [comment]
I've also experienced this issue, and I'd like to add that reordering a queue doesn't work either. You can click and drag a song, but once you let go of the mouse it just ends up back where it was.

**Comment by nate-thegrate** [comment]
Out of all the issues currently open, this is the one that affects my experience the most. I like being able to change the song queue, and that just isn't possible right now. (Making a comment so the "stale" label is removed)

Thanks so much to the devs for all the hard work! Even with this issue I much prefer using Cider to iTunes—it's not even close.

**Comment by cryptofyre** [comment]
We'll try and fix this to the best our ability soon.

**Comment by nate-thegrate** [comment]
Making a comment to remove the "stale" label

**Comment by coredev-uk** [comment]
I have not been able to replicate this. Is this issue still occurring?

**Comment by nate-thegrate** [comment]
Oh wow, looks like it's been fixed! Awesome!
