### ISSUE TITLE
[Bug]: Disable backrounds buttons while playing a music video

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider#1203]
### Describe the Bug

If you play a music video you can press the play/pause/etc. buttons in the background while you are watching the video.

You should not be able to press any button in the background while playing a video except the buttons for the video player.

![image](https://user-images.githubusercontent.com/34512773/175843061-2a0d8b31-673b-42c1-850b-5f9feb152f92.png)

### Steps to Reproduce

1. play a music video
2. hover over the background buttons

### Environment Information

cider: 1.5.1 - 130

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
Same here, seems to be left over from the old Music Video UI.

**Comment by KillerParticles** [comment]
Issue is not fixed on latest version.

**Comment by UnbreakCode** [comment]
.

**Comment by KillerParticles** [comment]
Bump as issue has not been fixed on latest version.

**Comment by bobi1024** [comment]
I don't know if it is related, but the close button is always visible when playing the video and never disappears, no matter fullscreen or not.

**Comment by Monochromish** [comment]
Since `z-index` won't fix the issue, maybe disabling the buttons playback buttons (or any underlying clickable buttons) when video playback is going on would be an easy cheat solution.
