### ISSUE TITLE
[Bug] Many songs don't work in playlists. Shuffle will only play a few, and clicking on them will play a different song instead.

### ISSUE THREAD

**Issue by afland** [ciderapp/Cider#1206]
### Describe the Bug

A lot of songs just don't work. If I'm in a playlist, shuffle will only play e.g. 3 songs and then stop. Clicking on any other song in the playlist will just play 1 of those 3 that work. The same problem occurs when I search for an artist. When I directly search for the song, though, it does work. 

It seems in any context where songs are organized/grouped together (playlist, artist search), something is messed up. 

### Steps to Reproduce

1. Go to a playlist (e.g. Post Malone Essentials)
2. Click shuffle/play/select random songs
3. Only a few will actually work

and 

1. Search for an artist (e.g. Post Malone)
2. Click on a song in the results (e.g. I Fall Apart)
3. Other song from artist plays instead
4. Directly search for song (e.g. I Fall Apart)
5. Plays as expected

### Environment Information

- OS: Fedora 36 (I had this on kubuntu as well, so it doesn't seem distro specific)
- App Version and/or Commit ID: 1.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SStarlight9614** [comment]
I've been having the same issue. I went to the web apple music player page and it shows all the songs that I can't play with cider, all grayed out and the ones that I can play are normal. I think it's something apple is doing on their side than with the application!

**Comment by afland** [comment]
> 

That's weird, especially since I can play the songs when I search for them directly. Will have to check that out later

**Comment by afland** [comment]
Well it seems like something changed, IDK whether in Cider's or Apple's side. Problem is gone for now, but I've only tested a few playlists.
