### ISSUE TITLE
[Bug]: Stopped view progress bar

### ISSUE THREAD

**Issue by MuhammetEminCakir** [ciderapp/Cider#1212]
### Describe the Bug

Progress bar not visible when music is stopped

### Steps to Reproduce

1. Open the app for the first time
2. Do not play any song

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: 1.5.1-beta.99 (main)

### Anything else?

![resim](https://user-images.githubusercontent.com/64583157/176397258-575f23d7-727c-46ab-8861-f11bf5a15396.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnbreakCode** [comment]
this is not a bug

**Comment by coredev-uk** [comment]
^
