### ISSUE TITLE
[Bug]: Application (at least the flatpak) takes a couple of attempts to open 

### ISSUE THREAD

**Issue by linusrg1** [ciderapp/Cider#1214]
### Describe the Bug

Whenever you try and launch Cider it doesn't seem to ever open the application the first time. It just hangs at the splash screen. After you close it and then open it again. It THEN decides to open correctly.

### Steps to Reproduce

Open application
Let it hang 
Close
Open again, application works

Application should load on first attempt.

### Environment Information

- OS: Fedora 36 kde 5.25.2
- App Version and/or Commit ID: 1.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
From my knowledge, this is not an issue with the main cider builds. Please try the troubleshooting steps outlined [here](https://docs.cider.sh/support/troubleshooting). If this does not resolve the issue, please forward the issue to the [flatpak repository](https://github.com/flathub/sh.cider.Cider) as the Flatpak release is not maintained by the Cider Development Team.
