### ISSUE TITLE
[Bug]: Winget command - 404

### ISSUE THREAD

**Issue by kpcenti** [ciderapp/Cider#1216]
### Describe the Bug

A bug happened!

I ran the `winget install --id=CiderCollective.Cider.Nightly  -e` command and I got this error
`Found Cider Nightly [CiderCollective.Cider.Nightly] Version 1.4.7-alpha
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/ciderapp/cider-releases/releases/download/v1.4.7.2511/Cider-Setup-winget-1.4.7-alpha.exe
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).`

### Steps to Reproduce

1. Clicked on GET IT VIA WINGET button on the releases page
2. Copied the command from winstall page
3. Open and paste command in Terminal
4. 

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ctaetcsh** [comment]
The release Winget attempted to download was seemingly removed, so GitHub returned a 404.

**Comment by thammawat-s** [comment]
I ran on PowerShell successfully.

``
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

Warning: PowerShell detected that you might be using a screen reader and has disabled PSReadLine for compatibility purposes. If you want to re-enable it, run 'Import-Module PSReadLine'.

PS C:\Users\thammawat> winget install --id=CiderCollective.Cider  -e
The `msstore` source requires that you view the following agreements before using.
Terms of Transaction: https://aka.ms/microsoft-store-terms-of-transaction
The source requires current machine's geographic region to be sent to function properly.

Do you agree to all the source agreements terms?
[Y] Yes  [N] No: y
Found Cider [CiderCollective.Cider] Version 1.5.1-beta.470
This application is licensed to you by its owner.
Microsoft is not responsible for, nor does it grant any licenses to, third-party packages.
Downloading https://github.com/ciderapp/cider-releases/releases/download/v1.5.1-beta.470/Cider-Setup-winget-1.5.1-beta.470.exe
  ██████████████████████████████  93.3 MB / 93.3 MB
Successfully verified installer hash
Starting package install...
Successfully installed
``

**Comment by ctaetcsh** [comment]
Yeah, Winget pulls the latest release it has available. This was a one-off fluke for OP.
