### ISSUE TITLE
[Bug]: Anti Virus trigger

### ISSUE THREAD

**Issue by akavkl** [ciderapp/Cider#1221]
### Describe the Bug

Drop.Win32.MLDCpy.1710520 as detected by avira for beta 1.5.1 build 99

### Steps to Reproduce

winget install --id=CiderCollective.Cider  -e
anti-virus gets triggered

### Environment Information

- OS: Windows 11 Pro for Workstations 22000.778

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by ctaetcsh** [comment]
As a test, I ran the 1.5.1-beta.197 Windows standalone installer through VirusTotal, with no vendors, including Avira, flagging it. Whatever false positive is being tripped here is specific to whatever Winget is retrieving.
Result: https://www.virustotal.com/gui/file/34a7228336737d38f4746eba7f163be421d2b04be697ccc728b90f7b9df8e46d/detection
![image](https://user-images.githubusercontent.com/48845980/176854554-78dd4b20-2ba5-4adb-a7ed-b4a3dc781aeb.png)
