### ISSUE TITLE
[Bug]: When cider is in use prevent compluter from locking.

### ISSUE THREAD

**Issue by linusrg1** [ciderapp/Cider#1227]
### Describe the Bug

When using cider your pc will still lock, while this is ok, it would be great to have the option to prevent your computer from locking via some option in cider. Weather that just be when cider is being used in full screen, even better in both normal and full screen mode. 

### Steps to Reproduce

Let music play.
Despite music playing computer still locks, and then eventually sleeps.

### Environment Information

- OS: Fedora 36
- App Version and/or Commit ID: latest build as of midday yesterday. (Jul 1st)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
I have made a few changes to how Window closing is handled. Please try the latest release.
