### ISSUE TITLE
[Bug]: Blurred visual until the mouse hovers on them.

### ISSUE THREAD

**Issue by artemiskiss** [ciderapp/Cider#1247]
### Describe the Bug

The visuals throughout the app look extremely blurred on the app. This blur goes away once you hover the mouse over that particular element.  However, you have to hover over each individual element for it to go away. It looks like you're viewing stuff without glasses on. 

### Steps to Reproduce

 There is no pattern to when it happens. It happens often and unpredictably. First I thought it happened every time the app was opened and then once an element was hovered over, it would permanently go away. However, the blur randomly keeps appearing every now and then. 

### Environment Information

- OS:  Windows 11 Pro 21H2, build 22000.739
- App Version: 1.5.0 download from the Microsoft store

### Anything else?

https://user-images.githubusercontent.com/98501067/177459658-f870aac5-311a-4f1f-97ac-5de4574d2723.mp4

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by artemiskiss** [comment]
https://user-images.githubusercontent.com/98501067/177459530-96cff493-7013-4352-af2a-2cf3575e6b01.mp4

Here's a video of the bug in action.

**Comment by artemiskiss** [comment]
![Screenshot 2022-07-06 124358](https://user-
images.githubusercontent.com/98501067/177459699-7ed6b250-ca77-4156-b055-db16a6df85a2.png)
![Screenshot 2022-07-06 123411](https://user-images.githubusercontent.com/98501067/177459703-87cb5f11-01c3-4501-a75c-44db75416d58.png)
Here's some pictures for more context.

**Comment by middle-states** [comment]
Experiencing this as well in Windows 10 and it is the rule- the app is almost never "in focus" and is almost always blurry if it's not selected and being actively clicked around in. Occurs 100% of time during usage when app is not selected and is in background relative to one or two other windows, or more. Blurry spots appear to be uneven throughout the app- some spots seem blurrier than others and seemingly random spots snap in and out of focus when interacting with the app. Eventually after using Cider exclusively for a moment (10 seconds or so?), the full app comes into focus and everything looks normal. Cider then returns to being very blurry when I click away to focus on other windows. 

I do not have any scaling enabled, though I did try tinkering with "Change High DPI Settings" menu in the Cider.exe properties. No luck in there.

My system info-
_OS: Microsoft Windows 10 Pro
Version: 10.0.19044 Build 19044
System type: 64-bit operating system, x64-based processor
Installed Physical Memory (RAM): 32.0 GB
GPU: NVIDIA GeForce RTX 3080
Driver Version: 30.0.15.1215
Adapter Type: NVIDIA GeForce RTX 3080, NVIDIA compatible
Resolution: 3840 x 1600 x 143 hertz
Bits/Pixel: 32_




![blurry](https://user-images.githubusercontent.com/109345945/179198708-76bbe83f-6fd4-4b40-a962-6f52713d9e18.jpg)
