### ISSUE TITLE
Small grammer tweaks in cider.sh

### ISSUE THREAD

**Issue by nate-thegrate** [ciderapp/Cider#1251]
### Relevant Language

English

### Change or Addition or Both

Change a Language

### Change Requested / Any Additional Information

I'd like to propose some very minor grammar tweaks to the [cider.sh](https://cider.sh/) site.

An open source and **community oriented** Apple Music client…  
→ An open source and **community-oriented** Apple Music client…

Quickly share and show others what **your listening to;** right out of the box.  
→ Quickly share and show others what **you're listening to,** right out of the box.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Resolved in commit 628ecd4c55beeb66befb461afd3cfea8917d7b4e

**Comment by nate-thegrate** [comment]
You even fixed stuff that I didn't catch! Awesome!!
