### ISSUE TITLE
[Bug]: lastfm does not work

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider#1255]
### Describe the Bug

lastfm is not working after the recode for me.
I also can't save those bools
![image](https://user-images.githubusercontent.com/34512773/177837102-02e9eb3c-f808-4a64-8db5-af436c8c7e1b.png)

### Steps to Reproduce

connect lastfm with cider, play the song

### Environment Information

- OS: win11
- App Version and/or Commit ID: build 331

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Should be fixed?

**Comment by UnbreakCode** [comment]
> Should be fixed?

not fixed in latest build, settings still can't be saved and it only scrobbles the song directly after login. After a restart it doesn't scrobble anymore

**Comment by yazninja** [comment]
do update your cider to the latest version and then re-login LastFM

**Comment by UnbreakCode** [comment]
> 

yes, as I already said: tried it with build 331 and now with 371

**Comment by GGrandma** [comment]
@UnbreakCode have you tried deleting `cider-config.json`, the file can be found at `%APPDATA%/Cider`.

This issue seems to be because of the new lastfm scrobble filter option that was recently added.

**Comment by UnbreakCode** [comment]
> @UnbreakCode have you tried deleting `cider-config.json`, the file can be found at `%APPDATA%/Cider`.
> 
> This issue seems to be because of the new lastfm scrobble filter option that was recently added.

ye already tried this before, does not fix the issue for me

**Comment by coredev-uk** [comment]
What current configuration are you using in Cider for LastFM?
What songs are you playing?
Is it failing to display both now playing and scrobble on LastFM or is one appearing?

**Comment by UnbreakCode** [comment]
> What current configuration are you using in Cider for LastFM? What songs are you playing? Is it failing to display both now playing and scrobble on LastFM or is one appearing?

I'm using this configuration:
![image](https://user-images.githubusercontent.com/34512773/180417802-3791d1c7-4feb-4382-9545-de4dcbe645d4.png)
(can't set any bool)
I've noticed that scrobble does work with local songs lmao
If the song is directly from AM it does not work(scrobble and now playing)

**Comment by coredev-uk** [comment]
Is this resolved?

**Comment by UnbreakCode** [comment]
well after completely uninstalling and reinstalling cider it works somehow now. But the bool fields still aren't working for me^^

**Comment by coredev-uk** [comment]
So filter types and filter loop no work?

**Comment by UnbreakCode** [comment]
only the filter types aren't working

**Comment by UnbreakCode** [comment]
after some days it seems like scrobbling won't work for me again

**Comment by coredev-uk** [comment]
Well filter types should be fixed now, as for the scrobbling I've got no clue.

**Comment by UnbreakCode** [comment]
will debug if I can reproduce it again

**Comment by cryptofyre** [comment]
Gonna close for now, as it seems to be fine for now.

**Comment by UnbreakCode** [comment]
> Gonna close for now, as it seems to be fine for now.

well no it's still not fine for me. just takes some time
