### ISSUE TITLE
[Bug]: Queue wonky with the latest commit.

### ISSUE THREAD

**Issue by linusrg1** [ciderapp/Cider#1263]
### Describe the Bug

When removing items from a queue the wrong item is removed. (Like the item one or two above the one you wanted to remove are removed instead) Also when moving songs around in the queue, they either do not rearrange, and/or they become clones of another song that is already in the queue.

### Steps to Reproduce

1. Create a queue
2. try removing songs, the wrong song will be removed
3. try rearranging songs they will not rearrange or they will become clones of other songs

### Environment Information

- OS: fedora 36
- App Version and/or Commit ID: 1.5.1 commit bc63d79

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lkreimann** [comment]
Additional to that: My queue always gets mixed (like I would randomly play a playlist) on Ubuntu 20.04

Not sure if that should be a separate issue
