### ISSUE TITLE
[Bug]: Lyrics are not shwoing up for specific song

### ISSUE THREAD

**Issue by UnbreakCode** [ciderapp/Cider#1264]
### Describe the Bug

The lyrics for example this song won't be displayed: https://music.apple.com/de/album/%C3%BCberfall/1477898277?i=1477898302

There are Lyrics on Musixmatch:

https://www.musixmatch.com/de/songtext/Kollegah/%C3%9Cberfall

### Steps to Reproduce

play song "Kollegah - Überfall"

### Environment Information

- App Version and/or Commit ID: Beta 371

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by UnbreakCode** [comment]
still a thing

**Comment by svalencia014** [comment]
I'm having the same issue with this song https://music.apple.com/us/album/all-my-favorite-songs-feat-ajr/1566553526?i=1566553534

**Comment by pkpnr** [comment]
I faced the same issue but for literally any song that have lyrics existing.

**Comment by maikirakiwi** [comment]
Cider now uses official lyrics

**Comment by UnbreakCode** [comment]
that's actually a very sad solution just because mxm does not work anymore lmao

**Comment by KillerParticles** [comment]
> that's actually a very sad solution just because mxm does not work anymore lmao

i miss translations :(( was my favoruite feature of Cider
