### ISSUE TITLE
[Bug]: database io error?

### ISSUE THREAD

**Issue by ChocolateBread799** [ciderapp/Cider#1266]
### Describe the Bug

A bug happened!

can't open cider

$ cider
[4635:0710/090156.041128:ERROR:service_worker_storage.cc(1899)] Failed to delete the database: Database IO error

### Steps to Reproduce

1. run cider

### Environment Information

- OS: archlinux
- App Version and/or Commit ID: bc63d79

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Cider is already open somewhere else.
