### ISSUE TITLE
[BUG] Newly added playlists do not show up in sidebar

### ISSUE THREAD

**Issue by lucamarcelpeters** [ciderapp/Cider#127]
**Problem**
Newly added playlists do not show up on left sidebar. This is also a bug on music.apple.com, but maybe there is a good way to fix this in Cider (maybe a refresh of the sidebar after certain actions?).

This can be reproduced by adding and removing a playlist to your library.

**Environment Information**
 - Windows 11 Pro (22533.1001)
 - Cider v0.0.1-alpha

**Current workaround**
Restart app ^^

**Comment by damian-kociszewski** [comment]
Restarting the app does not help
