### ISSUE TITLE
[Bug]: Listen Now not navigating to albums.

### ISSUE THREAD

**Issue by cryptofyre** [ciderapp/Cider#1273]
### Describe the Bug

@vapormusic fuck up with social profiles.
![image](https://user-images.githubusercontent.com/33162551/178355578-75487ea7-b884-4bb2-9411-bbaf2f8a9ac7.png)

### Steps to Reproduce

self explanatory

### Environment Information

irrelevant.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
Waah
