### ISSUE TITLE
[Enhancement] Enhance look of UI on smaller devices/in small windows

### ISSUE THREAD

**Issue by lucamarcelpeters** [ciderapp/Cider#128]
**Is your feature request related to a problem? Please describe.**
Currently resizing Cider brings up bad looking buttons and missing buttons.
![image](https://user-images.githubusercontent.com/9435787/149420752-acd08ef1-9361-43ae-8bc3-84f2f10d5748.png)

**Environment Information**
- Windows 11 Pro (22533.1001)
- Cider v0.0.1-alpha

**Comment by booploops** [comment]
Try out the latest commit

**Comment by lucamarcelpeters** [comment]
Yeah, would like to. Can't get it work. Will wait then ^^

![image](https://user-images.githubusercontent.com/9435787/149620566-cdea1fed-7265-4fff-9963-c8287f8a5478.png)
