### ISSUE TITLE
[Bug]: Cider force closes and takes up a lot of ram and cpu.

### ISSUE THREAD

**Issue by Bananz0** [ciderapp/Cider#1280]
### Describe the Bug

After adding a substantial local library to Cider, it starts scanning for some time and later closes. Ram and CPU usage spikes to high numbers.
![Screenshot (2)](https://user-images.githubusercontent.com/31777541/178840482-3aec2bc7-b378-41a9-9caf-11fe8dea77cc.png)

### Steps to Reproduce

1. Add a large local library.
2. Wait.

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: 1.5.1-beta.391

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by r33ce15** [comment]
I have seen this same bug in the Mac OS version

**Comment by direrFlood** [comment]
yes happened to me on w11 22h2

**Comment by cryptofyre** [comment]
You need to update Cider. We're all the way on 1.5.8.
