### ISSUE TITLE
[Bug]: Now Playing Album/Artist links do not respond to tip of cursor

### ISSUE THREAD

**Issue by ctaetcsh** [ciderapp/Cider#1286]
### Describe the Bug

The text in the now playing box that links to the currently playing album and artist do not react to the tip of the cursor like most applications, only reacting to the middle of the cursor.
It's not super consistent with when it happens but it keeps tripping me up. I checked the CSS to see if it was just an offset link but it didn't look like it. 
![Cider_lfd9HfGv60](https://user-images.githubusercontent.com/48845980/179338405-5f85a56c-6c93-4c7d-8743-ee84e70db876.gif)
 

### Steps to Reproduce

1. Play a song
2. Hover over the now playing album/artist text with just the tip of your cursor
3. Be annoyed

### Environment Information

- OS: Windows 10 21H2 19044.1826
- App Version and/or Commit ID: 1.5.1-beta.415

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
#787 duplicate

**Comment by ctaetcsh** [comment]
#787 isn't the same as what I'm describing in this issue

**Comment by ctaetcsh** [comment]
@coredev-uk This issue is not a duplicate of #787. Please reopen.
