### ISSUE TITLE
MusicKit V3 API Transition

### ISSUE THREAD

**Issue by booploops** [ciderapp/Cider#129]
Transitioning most the mk.api.* to mk.api.v3.*.  With full MK V3 the end points will still be the same

**Comment by cryptofyre** [comment]
please musickit.js v3 me harder dad
![NewPFP22-1-transparent](https://user-images.githubusercontent.com/33162551/149454428-a5b8fa5b-5598-409c-af77-7b03d7245e31.png)

**Comment by saboooor** [comment]
what the fuck

**Comment by booploops** [comment]
> please musickit.js v3 me harder dad ![NewPFP22-1-transparent](https://user-images.githubusercontent.com/33162551/149454428-a5b8fa5b-5598-409c-af77-7b03d7245e31.png)
![f9PYyZG](https://user-images.githubusercontent.com/49113086/149467039-a6c93933-c190-49b8-8f45-ebba15981ab4.gif)

**Comment by saboooor** [comment]
that's hot

**Comment by GamingLiamStudios** [comment]
the fuck happened here + should we upgrade to `https://js-cdn.music.apple.com/musickit/v3/amp/musickit.js` or we just chilling with v2

**Comment by cryptofyre** [comment]
> the fuck happened here + should we upgrade to `https://js-cdn.music.apple.com/musickit/v3/amp/musickit.js` or we just chilling with v2

We are using v3 API's in v2. Apple still has V3 in a buggy state and its currently not possible to migrate to that version yet.

**Comment by GamingLiamStudios** [comment]
nice
