### ISSUE TITLE
Cider menu button doesn't look like a menu button

### ISSUE THREAD

**Issue by narFnarF** [ciderapp/Cider#1295]
### Describe the Bug

The Cider Menu button looks like a Play button and is located near the playback controls (previous, next, pause, etc), making it difficult for new user to know that it's actually a menu button.

### Steps to Reproduce

1. Launch Cider

![screenshot of the issue, with an arrow pointing at the menu button](https://i.imgur.com/uHFOr2h.png)

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID: 1.5.1

### Anything else?

Proposed solutions:
- Change the look of the button to look more like a menu button. For example, you could replace the triangle with a ["hamburger" icon](https://duckduckgo.com/?q=hamburger+menu+icon&t=ffab&iar=images&iax=images&ia=images&iai=https%3A%2F%2Fmpng.subpng.com%2F20180628%2Fzaz%2Fkisspng-computer-icons-hamburger-button-menu-new-menu-5b34724be5a1f0.5796308115301637879406.jpg).
- Change the location of the button to the right side, which, in my opinion, would be more consistent with the usual position of menu buttons on desktop (for example, in Firefox, Google Chrome, Thunderbird, etc)

Note: I realize that a "hamburger menu" icon would look a lot like the current "Queue" button. I would therefore move the Queue button to the left, with the playback controls, since they are thematically related.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ilyshirai** [comment]
I think it's more cosmetic thing, imo it's hard to mistake the both of them, because playback buttons have the same colour in contrast of Cider logo, which is red and different size. Also, between playback status and Cider logo there are navigation buttons to navigate between pages on Cider. Just my opinion, don't take too seriously. (btw. if you can't accustom to this, then you can still change it by making theme like [this)](https://github.com/SoNothingMC/Cider_OldLogoTheme)) Have a nice day!

**Comment by coredev-uk** [comment]
Window's does it, Apple does it, everyone does it...

**Comment by narFnarF** [comment]
I understand your points but it did took me multiple weeks to realize that this was a Menu button.

I don't understand why you say that Apple and Windows do it. iTunes on Windows uses a Menu bar. iTunes on MacOS uses the stardard menu bar at the top.
![](https://i.imgur.com/LxFi79B.png)
![](https://i.imgur.com/JUNmQxA.png)
I'm not saying that a Menu bar is better. I'm just saying that a menu button should look like a menu button to help user discover its functionality.

You've closed the 2 usability issues that I submitted, disregarding my feedback, which is a little disappointing. Can you tell me about your preferred way of receiving usability concerns? Cider is a great software, even better than iTunes on a lot of points! But there are some little issues that makes it harder to use for new users. I am sensible to these kind of details, since it's part of my day job. How can I put my expertise to good use on the Cider project?
