### ISSUE TITLE
[Bug]: Select all text (macOS)

### ISSUE THREAD

**Issue by rubenhaz** [ciderapp/Cider#1301]
### Describe the Bug

When selecting all (cmd + A) in the search bar on a Mac, it jumps to the albums section. 

### Steps to Reproduce

1. Type in the search bar
2. Press cmd + A to select all text

### Environment Information

- OS: macOS Ventura
- App Version and/or Commit ID: Cider 1.5.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Whoever chose all the shortcuts for the app needs to be slapped

**Comment by coredev-uk** [comment]
For now, just change the bind for albums in settings, I will make a fix for the defaults.
