### ISSUE TITLE
[Bug]:Can't sync the latest song list

### ISSUE THREAD

**Issue by BTimer6** [ciderapp/Cider#1303]
### Describe the Bug

A bug happened!
I don't know what's happening, but I can't sync the latest song list in the song section.
In the recently added column is to find the latest songs.

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/71555757/180629204-240c8a53-797f-448f-a968-483f3abd890b.png)
![image](https://user-images.githubusercontent.com/71555757/180629209-7eb2315b-770e-4b1d-8d8e-53d4f3ec26cf.png)

### Environment Information

- OS:win11
- App Version and/or Commit ID:latest version 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Cider 无法实时同步你在其他设备上做的清单更改，需手动用歌曲菜单下位于右上角的刷新按钮来主动更新。
（或我记得每次开客户端的时候也会更新一次）

**Comment by BTimer6** [comment]
我点了刷新的，试了好多次，就是刷新不出来歌曲。而且我在cider里面添加到资料库的歌曲自己也不显示 从 Windows 版邮件发送 发件人: Maikiwi发送时间: 2022年7月24日 10:37收件人: ciderapp/Cider抄送: BTimer6; Author主题: Re: [ciderapp/Cider] [Bug]:Can't sync the latest song list (Issue #1303) Cider 无法实时同步你在其他设备上做的清单更改，需手动用歌曲菜单下位于右上角的刷新按钮来主动更新。（或我记得每次开客户端的时候也会更新一次）—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by BTimer6** [comment]
> 

我点了刷新的，试了好多次，就是刷新不出来歌曲。而且我在cider里面添加到资料库的歌曲自己也不显示 从 Windows 版邮件发送

**Comment by maikirakiwi** [comment]
你在网页版看看，再不行的话我会investigate的。
话说新开了个Q群531185058
