### ISSUE TITLE
[Bug]: Songs won't play if "Enable Advanced Functionality" is off

### ISSUE THREAD

**Issue by martinsstuff** [ciderapp/Cider#1309]
### Describe the Bug

Songs won't play if "Enable Advanced Functionality" is off

### Steps to Reproduce

1. Disable "Enable Advanced Functionality" in the Audio settings.
2. Sometimes the first song that is open will work, but trying to play another one always fails.

### Environment Information

- OS: Windows 11 21H2
- App Version and/or Commit ID: 1.5.1-beta.443

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Update 1:
When the application is in this bugged state, the playback section sometimes (not always) turns into this: 
![image](https://user-images.githubusercontent.com/29005772/180712635-6824cac4-0d19-402f-95cc-400ed76ec1b9.png)
Note the lack of timeline/progress bar and song name.

Here is how it looks normally:
![image](https://user-images.githubusercontent.com/29005772/180712872-d9d0e940-9ba5-46dc-be11-81c0e105c564.png)

**Comment by trevorraney** [comment]
I'm also experiencing problems with this, specifically with the latest version from the Microsoft Store, running on Windows 10.

The Advanced Functionality/Cider Audio Lab settings are all enabled by default after install. Whether enabled or disabled, Cider refuses to play after one song.

When using media keys, the Windows media playback overlay started to appear as well. Never happened on any of the other versions of Cider I've used. It didn't even show any song information, just said "Cider" and only allowed for play/pause.

These issues all happened after attempting to install from both Microsoft Store and the GitHub releases page (various versions), clean installs each time. Reverted back to the [1.5.0 stable release](https://github.com/ciderapp/cider-releases/releases/tag/v1.5.0).
