### ISSUE TITLE
[Bug]: Language choice other than English (UK) (and maybe some others?) doesn't apply to parts of the program.

### ISSUE THREAD

**Issue by martinsstuff** [ciderapp/Cider#1310]
### Describe the Bug

Apple Music defaults to German for me, but I want it in English (US, ideally). Thankfully English (UK) works, but having tried a few languages, it appears the be (one of) the only one(s) that works, the other ones show the affected parts of Apple Music in German. **Edit:** I made sure to reload Cider when changing the language.

### Steps to Reproduce

1. Be somewhere where Apple Music defaults to a certain language
2. Try to set it to use a different language

Note: This bug may depend on geo- and account location

### Environment Information

- OS: Windows 11 21H2
- App Version and/or Commit ID: 1.5.1-beta.443

### Anything else?

Interestingly, when deleting everything but `Local Storage` from the AppData folder, it starts in English (US) once, but returns to German (or en_GB) afterwards.

**Edit:** Here are my Windows locale settings: 
![image](https://user-images.githubusercontent.com/29005772/180714740-7e7a1a3b-75bc-42da-9b4f-57a2d5622d82.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
The language you set in the settings menu will apply to all parts of the interface that are coded directly in. Certain areas such as album/playlist names will be set based off your storefront (Apple Account Region). Unfortunately we cannot do much to resolve this.
