### ISSUE TITLE
[Bug]: Explore GitHub themes goes to the Visual section in Settings instead of the theme explorer

### ISSUE THREAD

**Issue by cmdrneon** [ciderapp/Cider#1312]
### Describe the Bug

The "Explore GitHub Themes" brings the user to the next settings menu down instead of the theme explorer

### Steps to Reproduce

1. Went to "Styles" tab in Settings
2. Clicked on "Explore GitHub themes"
3. Brought to the "Visual" menu instead 

### Environment Information

- OS: Debian 11 bullseye
- App Version and/or Commit ID: 1.5.1-beta.466

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by trevorraney** [comment]
Just updated from Microsoft Store on Win10 and this is happening to me.

**Comment by cryptofyre** [comment]
We're looking into it.

**Comment by cmdrneon** [comment]
Just updated to the latest build on Linux... (1.5.4-beta.9) seems to be fixed? Not sure when it would have...

**Comment by coredev-uk** [comment]
Various issues are fixed every day, the Microsoft Store build is just outdated as this is only updated on major versions.
