### ISSUE TITLE
[Bug]: New search UI only shows up on Tracks tab

### ISSUE THREAD

**Issue by jordanspringer** [ciderapp/Cider#1330]
### Describe the Bug

When viewing an album that shows additional tabs such as "Tracks, You Might Also Like, Music Videos, More by...", the search button appears to do nothing when you are viewing a tab other than 'Tracks', because the search UI only appears on the 'Tracks' tab.

### Steps to Reproduce

1. View any album.
2. Select a different tab that isn't 'Tracks'.
3. Click the Search button. Nothing appears to happen.
4. Go to the Tracks tab, you'll see the Search box.

### Environment Information

- OS: Windows 10 Pro
- App Version and/or Commit ID: Windows Store Version 1.5.2 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
The search bar will appear on the tracks tab, this is done as intended as the other tabs usually don't have much content on them so searching is not necessary.
