### ISSUE TITLE
[Bug]: core pushed faulty notification code to main

### ISSUE THREAD

**Issue by ctaetcsh** [ciderapp/Cider#1336]
### Describe the Bug

core pushed #1333 to main with refactored notification code that doesnt work as intended (no album cover shown cause you cant have buttons and an image) and also has a notification sound for every song change 
figure a. (top is new, bottom is old)
![image](https://user-images.githubusercontent.com/48845980/182076539-3bba957a-8690-4560-abd1-a44d903a31b0.png)
figure b. defective refactored code
![image](https://user-images.githubusercontent.com/48845980/182076675-30f19bfb-4a4c-4f25-897c-790a2eeb0393.png)
figure c. existing functioning code with silent property that isnt annoying
![image](https://user-images.githubusercontent.com/48845980/182076746-e5f57431-5ef9-4f89-a457-351bbeb1f43b.png)

### Steps to Reproduce

1. wait for a song change
2. be annoyed

### Environment Information

- OS: windows 10 latest 
- App Version and/or Commit ID: 1.5.4-beta.2

### Anything else?

@coredev-uk this is your fault 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Monochromish** [comment]
This isn't core's fault, it's mine. Ill push a fix for it in some time.

**Comment by ctaetcsh** [comment]
Core was the one who committed the refactored code and merged the PR, if it wasn't them then I'm confused.

**Comment by Monochromish** [comment]
> Core was the one who committed the refactored code and merged the PR, if it wasn't them then I'm confused.

Core in-fact was the one who pushed the code but i contributed some part of it that includes the notification silent part.

**Comment by coredev-uk** [comment]
Just to make this clear, the code worked as intended with the one fault of the silent option. Artwork was removed for windows as a trial to see the communities feedback on it as buttons and artwork could not both be done. 

If you have an issue with changes to the code, feel free to use the latest stable build.
