### ISSUE TITLE
[Bug]: Login after every launch

### ISSUE THREAD

**Issue by codevski** [ciderapp/Cider#1337]
### Describe the Bug

Seems like I need to re-login every time I launch cider. Tested fresh OS install and fresh cider install.

Weird thing is I restarted once, and it didn't request to log in, but I have not managed to reproduce the behaviour. Maybe a permission bug?

### Steps to Reproduce

1. Open cider
2. login
3. close cider
4. reopen and it will ask to login again

### Environment Information

- OS: Fresh arch install
- App Version and/or Commit ID: currently 1.5.4-beta.536

### Anything else?

Happy to supply any logs that you need.
Noticed after logging in the account details seems to be blank not sure if that's a bug or unfinished:
![image](https://user-images.githubusercontent.com/1435321/182093360-da6d05d6-a48c-4fe4-9945-adf4c6955131.png)

![image](https://user-images.githubusercontent.com/1435321/182092290-236b7424-5163-4dde-9e38-cf36da92ebc4.png)
![image](https://user-images.githubusercontent.com/1435321/182092374-7044662e-d001-40c3-b893-eab3b80c132a.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Normally this is an issue with Apple.
Most likely is that you don’t have an Apple Music subscription.
Free trials are wonky and we can’t provide support on that.

**Comment by maikirakiwi** [comment]
It asks to relog because the Cider app is not authorized by Apple (yet) to access Apple Music.

**Comment by codevski** [comment]
> Normally this is an issue with Apple. Most likely is that you don’t have an Apple Music subscription. Free trials are wonky and we can’t provide support on that.

def have a subscription: 
Individual
$11.99/Month
Next billing date: 31 Aug 2022

> It asks to relog because the Cider app is not authorized by Apple (yet) to access Apple Music.

After logging in it works fine, it just doesn't hold on the next time I launch cider...

**Comment by codevski** [comment]
Found the problem. When ssh tunnelling (work related) port 9000 is being used and cider needs port 9000 available?

**Comment by cryptofyre** [comment]
Yup.

**Comment by codevski** [comment]
sweet thats def the issue closing :)

**Comment by giovanniPepi** [comment]
Altough Cider keeps the login info after closing and opening it again, if I reboot Arch Linux it asks again for login info and appeareance settings, language settings. I'm guessing this is a different problem than the one in this issue?

**Comment by coredev-uk** [comment]
> Altough Cider keeps the login info after closing and opening it again, if I reboot Arch Linux it asks again for login info and appeareance settings, language settings. I'm guessing this is a different problem than the one in this issue?

Yeah this is a different issue. This can be down to how the config file is being stored on your system, usually its stored in `$HOME/.config/Cider` so make sure the directory is persisted.

**Comment by giovanniPepi** [comment]
> > Altough Cider keeps the login info after closing and opening it again, if I reboot Arch Linux it asks again for login info and appeareance settings, language settings. I'm guessing this is a different problem than the one in this issue?
> 
> Yeah this is a different issue. This can be down to how the config file is being stored on your system, usually its stored in `$HOME/.config/Cider` so make sure the directory is persisted.

I thought Cider was keeping up between relaunches, turns out I was wrong. It does lose the login after closing/opening again or rebooting, and goes back to the initial config screen: 

![image](https://user-images.githubusercontent.com/5255535/191520109-64cb4886-4b6a-45e7-adf1-55f9c71f3dea.png)

other settings in the advanced menu persist though: 

![image](https://user-images.githubusercontent.com/5255535/191520558-e63b3e25-ebd9-486e-9938-a18fa0a0ec42.png)

I've tried chmoding 777 $HOME/.config/Cider; nothing else changed. Some directories persist; others are modified as soon as I reopen the program as can be seem here:

![image](https://user-images.githubusercontent.com/5255535/191520904-68f4006a-10db-408b-83d9-95711d7cad57.png)

allowing port 9000 on UFW didn't change this behavior, although I'm not using SSH

**Comment by italoandre** [comment]
@giovanniPepi did you find a solution for what you reported? I'm facing the exact same thing (every launch of the app is just like the first launch).
