### ISSUE TITLE
[Bug]: 50% Volume isn't centered in Full Screen View

### ISSUE THREAD

**Issue by SralFX** [ciderapp/Cider#1341]
### Describe the Bug

When you're in the Full Screen Lyric View, the Volume slider point isn't centered when at 50%. It's not alligned with the Play/Pause button which should be centered. 
![image](https://user-images.githubusercontent.com/110462127/182350495-f916c235-469d-4a20-898d-08d34e52e99f.png)

### Steps to Reproduce

1. Put Volume to 50%
2. Go to Full Screen View

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.5.1-beta.443

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by yazninja** [comment]
that is aligned... accounting the volume icon in the side

**Comment by yazninja** [comment]
![image](https://user-images.githubusercontent.com/71800112/182359748-82448570-f5b1-4419-95b9-477d952a1d3e.png)
if we remove the volume icon in the left, here is low it looks

**Comment by KillerParticles** [comment]
Honestly, it looks better, its the same as how iPadOS and iOS does it.
