### ISSUE TITLE
[Bug]: MiniPlayer shuffle and repeat buttons are not working, and artwork doesn't fit the screen

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Cider#1349]
### Describe the Bug

A bug happenedIn MiniPlayer view clicking on Shuffle and Repeat buttons have no effect
Album Artwork doesn't fit / stretch to MiniPlayer. I have to manually adjust window size each time I open a new song.

### Steps to Reproduce

Start song
Switch to MiniPlayer
Click on Repeat and Shuffle buttons
They only say Enable Shuffle and Enable Repeat without any effects.

As for album art, issue is visible in the video. Start a song and see album artwork doesn't fit the MiniPlayer.

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.5.4 Beta 34

### Anything else?

![07-08-2022_02-15-20](https://user-images.githubusercontent.com/41871948/183269826-b1b5bfd6-7753-4074-9d4a-a35c7047e28c.gif)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by Naxterra** [comment]
[]

https://user-images.githubusercontent.com/41871948/183269903-bf6426a3-7f46-4626-9bf3-3f35ef26711d.mp4

(url)

**Comment by cryptofyre** [comment]
This issue appears to be present with the native title bar enabled, could you try turning it off?

**Comment by Naxterra** [comment]
It is still weird but at least top bar is not white anymore.

![grafik](https://user-images.githubusercontent.com/41871948/185434568-66500d04-94b6-4736-88d3-0410e95b49f8.png)

![grafik](https://user-images.githubusercontent.com/41871948/185434593-f4af265d-1aeb-4978-9a56-242fb260963b.png)

![grafik](https://user-images.githubusercontent.com/41871948/185434623-8658a014-311e-4950-b76e-d680e640ac23.png)

![grafik](https://user-images.githubusercontent.com/41871948/185434704-d1dbfb72-36fb-4977-92c5-7370e67fdcd3.png)

**Comment by Naxterra** [comment]
Also, buttons are still not working.  I updated to 1.5.4 Beta 77 and issue still exists.

**Comment by cryptofyre** [comment]
Are you using any themes or modifications?

**Comment by cryptofyre** [comment]
What's your screen resolution?

**Comment by Naxterra** [comment]
> What's your screen resolution?

3440x1440 21:9

I took these pictures in windowed mode.

**Comment by coredev-uk** [comment]
Apolgies for the delay on this one. It should be now resolved as of b29bb3c96310d9f2b98fb4c9389024b16547af41.
