### ISSUE TITLE
[Bug]: The time for albums/singles is off by 1 day

### ISSUE THREAD

**Issue by GiddyGoatGaming** [ciderapp/Cider#1351]
### Describe the Bug

I’ve encountered an issue with cider that has persisted for a while now. I’ve noticed that cider dates back a song by a day which can make albums that appear as coming out January 1st, appear as December 31st from the previous year.

![D800716F-9796-49A3-A377-B5E0687A1613](https://user-images.githubusercontent.com/109806759/183328048-9b28da11-220b-4da9-aa23-623a95abf065.jpeg)
![51E53869-9852-4781-8E55-AD482EC61BD7](https://user-images.githubusercontent.com/109806759/183328152-bcffe3a9-0a88-453f-9e66-eff25265c06d.jpeg)

### Steps to Reproduce

1. Click on album. 2. See album/single date. 3.compare with Apple Music

### Environment Information

- OS:Windows 11
- App Version and/or Commit ID: 1.5.4-beta.34

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by GiddyGoatGaming** [comment]
![Uploading EE0899D2-C8BB-411C-8323-95A551F2903D.jpeg…]()

**Comment by coredev-uk** [comment]
I assume this is an old bug, after testing on multiple albums, including the one you've provided as an example here, this doesn't appear to be a current issue.

**Comment by GiddyGoatGaming** [comment]
I’m still experiencing this issue unfortunately. I’am now on cider 1.5.6 beta 4 and it’s still persisting. I’ve cleared the app data folder and relogged and still the same issue occurs to me

**Comment by coredev-uk** [comment]
What albums are you experiencing the issue on?
What language is the application set to?

**Comment by GiddyGoatGaming** [comment]
Every album is set back by a day. This also occurs with singles for me too. For example, the album god did by dj khaled that just came out appears as august 24th as the release date on cider but came out on august 25th according to Apple Music. My language is set to English (US) (English (US))

**Comment by GiddyGoatGaming** [comment]
Still an issue for me on 1.5.7 beta 215

**Comment by coredev-uk** [comment]
I cannot replicate this issue. The example that you provided in my testing displays the correct date of 25th August.
