### ISSUE TITLE
[Bug]: Media Keys are not working

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Cider#1352]
### Describe the Bug

Windows Media Keys are not working. I am using Razer Synapse to control my media, like next track and previous track but they are not working with Cider anymore. Spotify has no issues. It was working in previous builds but I couldn't remember which one was the latest.

### Steps to Reproduce

Open Cider
Start a song
Click next and previous track keys on mouse or keyboard
Nothing happens
Only Play/Pause works

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.5.4 Beta 43

### Anything else?

![grafik](https://user-images.githubusercontent.com/41871948/183424173-be76cf5c-ac8a-49a6-9f7d-ed77560ec57b.png)

![grafik](https://user-images.githubusercontent.com/41871948/183424193-76763911-4779-4896-b2a6-0dc93a08dc6f.png)

![grafik](https://user-images.githubusercontent.com/41871948/183424233-bb9a65c3-5185-4030-a781-e41ed1c7e699.png)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Could you provide a picture of the devtools console

**Comment by Naxterra** [comment]
![grafik](https://user-images.githubusercontent.com/41871948/183652849-a0af2190-c1da-41e0-8fce-744297e96caa.png)

![grafik](https://user-images.githubusercontent.com/41871948/183653029-e6f98fd8-e1fd-43f1-9c5a-92ef8c007d86.png)

**Comment by shawnanastasio** [comment]
I'm also encountering this after upgrading from Cider 1.5.1-beta.417 to Cider 1.5.3, implying that media keys on Windows broke somewhere in between those two builds.

**Comment by coredev-uk** [comment]
No changes have been made to any code related to this functionality. More time will be needed to look into this more.

**Comment by Naxterra** [comment]
Issue still exists in Beta 77

**Comment by coredev-uk** [comment]
There may be another application using your media keys. Try starting the app standalone with no chromium applications running (Discord, Brave, Chrome, Teams etc.), or any applications that play media.

**Comment by vrga** [comment]
interesting that chromium running at the same time as cider triggered this on debian 11. Literally never had this issue with any other apps (including running discord and chromium and playing audio via chromium for example...)

**Comment by grouchal** [comment]
Seeing this issue on Windows 10 - very annoying.  Any news on how to solve?

**Comment by cuevasclemente** [comment]
Also seeing this issue on Windows 11 at the moment.

**Comment by grouchal** [comment]
My issue turned out to caused by Microsoft Teams and not Cider.

**Comment by coredev-uk** [comment]
For anyone who is still receiving this issue:

Make sure you do not have any other application running that may capture your media keys. This can be anything that can play media (Chrome, Discord, Steam, etc.). Any applications that can play videos or audio may be capturing the media key instance, preventing them from controlling Cider.
