### ISSUE TITLE
[Bug]: Playback controls disappear on Maveric theme

### ISSUE THREAD

**Issue by plastikman** [ciderapp/Cider#1356]
### Describe the Bug

When the Cider window is below a certain size, the playback controls are gone.

### Steps to Reproduce

Make the window smaller than what is expected, you can see the playback controls are missing.

![image](https://user-images.githubusercontent.com/1246023/183948474-70795868-6105-4dee-96bb-4cfc658400b6.png)

Make the window larger and you can see the playback controls come back.  

![image](https://user-images.githubusercontent.com/1246023/183948668-86ab926f-c429-4bb4-897a-b9a163659a28.png)

This only happens with the Maverik theme.

### Environment Information

- OS: Windows 11 21H2
- App Version and/or Commit ID: Installed from the Microsoft Store 1.5.3 

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
When the Window is shrunk to where the playback controls no longer fit they move down to the bottom left hand side to which is visible by the screenshot.

**Comment by plastikman** [comment]
They also disappear from the bottom left corner.  Let me take another screenshot.

**Comment by plastikman** [comment]
![image](https://user-images.githubusercontent.com/1246023/184245182-32bba3b5-9938-417f-b652-ebc04cc2862a.png)
YOU can see the playback controls are missing.

**Comment by plastikman** [comment]
I have a debug log if you like, i am not sure if there is an PII or confidential data in this, so i havent posted here.
