### ISSUE TITLE
[Bug]: "Apple Music Edition" Albums have the "Apple Music" removed from their title in cider.

### ISSUE THREAD

**Issue by plb-42** [ciderapp/Cider#1357]
### Describe the Bug

When viewing Albums called "Apple Music Edition" or some variation thereof in the cider app, the "Apple Music" is removed from their title.

### Steps to Reproduce

1. Search for "Apple Music Edition" in Cider
2. Search for "Apple Music Edition" in a first-party Apple Music App
3. Compare the results

### Environment Information

- OS: openSUSE Tumbleweed x86_64 20220809
- App Version and/or Commit ID: 1.5.4-beta.544

### Anything else?

![image](https://user-images.githubusercontent.com/111060117/184130572-5645addd-91eb-44f9-8578-9d720ec80b56.png)
![image](https://user-images.githubusercontent.com/111060117/184130683-a90bfa77-a1a4-4c72-b702-b854d6080113.png)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
Good ol' Apple Music API.

**Comment by coredev-uk** [comment]
Complain to Apple

**Comment by vapormusic** [comment]
Update Cider, should fix
