### ISSUE TITLE
[Bug]: App always opens on the same song

### ISSUE THREAD

**Issue by glassd** [ciderapp/Cider#1360]
### Describe the Bug

Whenever I start the app, it always starts on the same song. It doesn't matter what was playing or how I exit the app. It always goes back to the same song.

### Steps to Reproduce

1. Open the app.
2. See the song the app always opens with
3. Play something else, or even stations or hours of other content
4. Close the app, reboot, shut down, anything.
5. reopen the app
6. The same original song is at the same position as always

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: Newest up to date version from the microsoft store.

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by KillerParticles** [comment]
You probably have the setting on called "resume playback" or something. It's under the General tab in settings.

**Comment by glassd** [comment]
Sorry. I must not have been clear enough. It's not the song that was last playing. It always goes back to the same song at the same position. Specifically Planet of the Grapes by Berried Alive at 51 seconds. It doesn't matter what I play. It always opens to that song at that position.

**Comment by KillerParticles** [comment]
Yeah as i said, i suspect you have that option enabled, can you check? It might be bugged out and always open to that song at the same time.
![image](https://user-images.githubusercontent.com/93286201/184502953-ea14d7a4-89a6-40fd-82a0-1595deaa1bb6.png)

**Comment by glassd** [comment]
Yes I do have it on. I can try with it off for a while. I do want that feature though. If it's bugged, that's why this is in a bug report.

**Comment by coredev-uk** [comment]
If you re-enable the local setting it should be resolved as of 746e96e33a7ca05acf98a966853d74a1ad7d6ba8.
