### ISSUE TITLE
[Bug]: Invalid CORS request

### ISSUE THREAD

**Issue by BrackRat** [ciderapp/Cider#1361]
### Describe the Bug

When login to Apple Music, report Invalid CORS request.

### Steps to Reproduce

1. Installed `Cider-Setup-1.5.4-beta.49`
2. Open app and try to log in.
3. Import account and password. Then type confirming code.
4. Keep loading and report `Invalid CORS request`

### Environment Information

- OS:Windows 11 21H2 22000.856
12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
16.0 GB
- App Version and/or Commit ID:Cider-Setup-1.5.4-beta.49

### Anything else?

This bug also happened on `Cider-Setup-winget-1.5.4-beta.47`

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by BrackRat** [comment]
![Snipaste_2022-08-14_11-46-44.png](https://cdn.liil.cc/2022/08/14/62f872c321324.png)

**Comment by pshakhmin** [comment]
Same issue on: 
Arch Linux x86_64 
cider-git 1.5.4.beta.49-1

**Comment by yazninja** [comment]
> Same issue on: 
> 
> - Arch Linux x86_64 
> - cider-git 1.5.4.beta.49-1

Just a query but, are you using /have Chinese ISP?

**Comment by pshakhmin** [comment]
> > Same issue on:
> > 
> > * Arch Linux x86_64
> > * cider-git 1.5.4.beta.49-1
> 
> Just a query, do you use /have a Chinese ISP?

No, I don't.

**Comment by coredev-uk** [comment]
What storefront (Region) are you in?
Have you tried deleting the application data (.config/Cider on Linux)?

**Comment by pshakhmin** [comment]
> What storefront (Region) are you in? Have you tried deleting the application data (.config/Cider on Linux)?

Russia.
Deleting .config/Cider actually helped, thank you

**Comment by coredev-uk** [comment]
@BrackRat https://docs.cider.sh/support/faqs#how-to-find-the-application-data-directory

**Comment by BrackRat** [comment]
> @BrackRat https://docs.cider.sh/support/faqs#how-to-find-the-application-data-directory

I tried removing the config file but it was still the same result.

**Comment by BrackRat** [comment]
> What storefront (Region) are you in? Have you tried deleting the application data (.config/Cider on Linux)?

China mainland.
Problem still here.

**Comment by coredev-uk** [comment]
I'm not on about the config file on its own, the whole directory.

**Comment by BrackRat** [comment]
> I'm not on about the config file on its own, the whole directory.

Well, but deleting folder `C:\Users\{myname}\AppData\Roaming\Cider` didn't work. Still can't sign in.

**Comment by coredev-uk** [comment]
Afaik this is resolved. Feel free to reopen if it continues.

**Comment by BrackRat** [comment]
2022.8.19 Problem still here.

**Comment by yazninja** [comment]
> 2022.8.19 Problem still here.

Should be fixed, can you still not log in?

**Comment by yazninja** [comment]
Does signing in on https://music.apple.com work?

**Comment by cryptofyre** [comment]
And if so what region and operating system do you reside on?

**Comment by BrackRat** [comment]
> And if so what region and operating system do you reside on?

China mainland 
OS:Windows 11 21H2 22000.856

> Does signing in on https://music.apple.com work?

Yes.I can log in normally and listen to music.

---

Fortunately, after sign in on https://music.apple.com/ . Now I can sign in ciderapp.
Problem solved, thx.
