### ISSUE TITLE
[Bug]: Cider is not remembering window position

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Cider#1362]
### Describe the Bug

When I restart Cider, it always opens in full screen mode. I am changing window position every time I restart the app but still it is not remembering last used window position.

I tried enabling and disabling Native Title Bar and setting hardware renderer to WebGPU and default but nothing changed.

### Steps to Reproduce

1- Start Cider
2- Adjust window position
3- Close and start Cider again
4- It open in full screen mode.
5- When I double click on top bar, it switches to windowed mode but not to my configured window size.

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: 1.5.4 Beta 49

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by yazninja** [comment]
Your window config might be bugged. In any case try deleting Cider's appdata 

`rm /S /Q %appdata%\Cider` just type this into cmd and restart the app.

*Note: this would make you sign in to apple music again

**Comment by Naxterra** [comment]
I deleted C:\Users\xxx\AppData\Roaming\Cider folder completely and then started Cider again. I entered my Apple credentials, adjusted window, started a playlist, and closed Cider. After that I reopened Cider again but window position got reset. At least it is not opening in full screen mode anymore.

**Comment by DeN-AlB** [comment]
Same here. Window position is not remembered. Just changed the properties of the desktop shortcut and enabled "maximized" so Cider starts in fullscreen now. Would be great if Cider is remembering the window position.

**Comment by ozumado** [comment]
Same here. It does not remember position/size of the window, would be great if it did...

**Comment by cryptofyre** [comment]
I'm investigating the issue.

**Comment by cryptofyre** [comment]
Technically this should work but it appears that it's not saving the attributes on close. This may be because the user is alt+f4'ing the application causing the exit event not to trigger therefore not saving the final size/position.

I'll keep an eye on this for now.

**Comment by DeN-AlB** [comment]
> This may be because the user is alt+f4'ing the application
I'm just closing the app with the help of the close button, not pressing ALT+F4.

**Comment by GGrandma** [comment]
I was having the same issue, deleting `window-state.json` fixed the issue for me. The file can be found at `%APPDATA%/Cider/window-state.json`. Although it is odd entirely deleting the Cider folder did not fix this issue for most.
