### ISSUE TITLE
[Bug]: Lengthy playlist names break playlist icon (SOLUTION ATTACHED)

### ISSUE THREAD

**Issue by CrunchyCat** [ciderapp/Cider#1366]
### Describe the Bug

Minor bug in sidebar playlists list

The default behavior of flexbox is to shrink some elements for more important elements (such as icons and labels). To specify an element which should not be shrunk, add the CSS property "flex-shrink: 0".

BEFORE:
![before-fix](https://user-images.githubusercontent.com/15345696/185002442-2c18b1e3-5fc2-4567-aba1-47b4ce01a953.png)

AFTER:
![after-fix](https://user-images.githubusercontent.com/15345696/185002440-678c78f0-dde9-4267-9f13-3407d1fc6d7d.png)

SOLUTION:
![solution](https://user-images.githubusercontent.com/15345696/185002443-06caa88f-3dde-4830-b094-18ddb17c2217.png)
Add "flex-shrink: 0" to the _svg-icon class

### Steps to Reproduce

Have a playlist name that is long enough to shrink the playlist icon.

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: Version 1.5.4-beta.67

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
I suggest [forking the project](https://github.com/ciderapp/Cider/fork) and creating a [Pull Request](https://github.com/ciderapp/Cider/compare)
