### ISSUE TITLE
Cider doesn't play songs marked with Explicit

### ISSUE THREAD

**Issue by VikITP-Lars** [ciderapp/Cider#1382]
### Describe the Bug

Whenever a song marked Explicit comes on Cider stops playing. Skipping to a song that is not marked as Explicit resumes play.

### Steps to Reproduce

Try to play song marked with Explicit content

### Environment Information

Win10
Cider Version 1.5.3

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Follow this [faq](https://docs.cider.sh/support/faqs#cider-is-skipping-or-not-playing-explicit-songs). It should resolve your issue.
