### ISSUE TITLE
[Bug]: Cider freezes when shuffling a playlist via the shuffle button

### ISSUE THREAD

**Issue by N1lzh** [ciderapp/Cider#1383]
### Describe the Bug

Since one week cider freezes as soon as I press the shuffle button next to the play button in a playlist. When I shuffle a playlist that is already playing via the bottom controlpanel it works just fine, only when I hit the shuffle button next to the play button cider freezes.

### Steps to Reproduce

1. Choose a playlist.
2. Press the shuffle button next to the play button.

### Environment Information

- OS: Windows 11 Pro, 21H2
- App Version and/or Commit ID: 1.5.3

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by aadityadhruv** [comment]
I am also facing the same issue. Clicking Shuffle freezes the app, but the audio continues playing. I am running Cider on Fedora 36 (kernel 5.19) using Flatpak.

**Comment by leoinpython** [comment]
same issue on win10pro Version	10.0.19044 Build 19044
cider version 1.5.8 from windows store

**Comment by maikirakiwi** [comment]
lmao thread the shuffling logic or make it async
