### ISSUE TITLE
[Bug]: Mac app won't start

### ISSUE THREAD

**Issue by dnestico** [ciderapp/Cider#1386]
### Describe the Bug

I'm on latest version and I have been waiting like 10 minutes for the app to open but it just won't open

It shows the dot to show it's open and it's even in the top bar but there is no window.

<img width="142" alt="Screen Shot 2022-08-25 at 8 00 31 PM" src="https://user-images.githubusercontent.com/3034555/186789315-e57006d1-dd35-4c49-9f77-1d18c625bf4c.png">

### Steps to Reproduce

1. Downloaded plugin to change icon
2. Restarted cider
3. Now won't oepn

### Environment Information

- OS: MacOS 12.4
- App Version and/or Commit ID:  1.3.0 (1.3.0)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
1.3.0???

**Comment by dnestico** [comment]
I just looked and thats what it said, haven't used cider in a long time so maybe i am outdated but it was working fine before that plugin.

**Comment by coredev-uk** [comment]
I suggest updating using the new package on homebrew. 
`brew install --cask cider`

**Comment by dnestico** [comment]
Reinstalled via homebrew, and it's doing the same thing, I don't understand...

<img width="1440" alt="Screen Shot 2022-08-26 at 10 08 03 PM" src="https://user-images.githubusercontent.com/3034555/187010103-1f1d3282-3b2e-483e-9404-bbb6fd71450b.png">
<img width="119" alt="Screen Shot 2022-08-26 at 10 08 15 PM" src="https://user-images.githubusercontent.com/3034555/187010104-7c453c80-8e54-406f-89c0-4478d4bca645.png">

<img width="649" alt="Screen Shot 2022-08-26 at 10 01 58 PM" src="https://user-images.githubusercontent.com/3034555/187009917-375da6c7-c16a-4bbf-880b-c9355cc2fbeb.png">

**Comment by yazninja** [comment]
> Reinstalled via homebrew, and it's doing the same thing, I don't understand...
Close Cider
remove delete the application data folder: `rm -rf $HOME/Library/Application Support/Cider`
Rep-open Cider

*note: app will ask you to sign in to Apple Music again, also themes/plugins installed will be removed
