### ISSUE TITLE
[Bug]: "Mica (Beta)" Window Background Style causes Cider to crash

### ISSUE THREAD

**Issue by TheNewSkai** [ciderapp/Cider#1391]
### Describe the Bug

I tried to change the option "Window Background Style" to the "Mica (Beta)" option. Cider froze and then after a few seconds of being unresponsive it crashed. If I tried to launch cider again it would crash instantly, so I had to reinstall it. This happens with both the microsoft store and main branch versions of Cider.

Happens with and without all my styles (like iTheme) enabled.

### Steps to Reproduce

1. Open the settings
2. Go to visual tab
3. Under "Window Background Style" select "Mica (Beta)"

### Environment Information

- OS: Windows 10 Home
- App Version and/or Commit ID: 1.5.3 (microsoft store) and 1.5.5-beta122 (main branch)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Update to the latest version of Cider.

**Comment by TheNewSkai** [comment]
> Update to the latest version of Cider.

I tried with 1.5.6 on the Microsoft store version and 1.5.7 on the main branch and they both still crash.

**Comment by coredev-uk** [comment]
What background are you using?

**Comment by TheNewSkai** [comment]
> What background are you using?

Sorry, I forgot to specify. It crashes after selecting the Mica (Beta) background and doesn't crash otherwise. Once I select the Mica background, the app will crash every time I launch it, forcing me to reinstall it.

**Comment by coredev-uk** [comment]
I was on about desktop background...

**Comment by vapormusic** [comment]
and specifically the image file you used as background, some hi-res images could have caused an overflow/crash.

**Comment by TheNewSkai** [comment]
> and specifically the image file you used as background, some hi-res images could have caused an overflow/crash.

I changed my desktop background and that fixed it. Thanks for the help.
