### ISSUE TITLE
[Bug]: Search Page does not properly refresh it's state

### ISSUE THREAD

**Issue by rlaphoenix** [ciderapp/Cider#1392]
### Describe the Bug

If you search for one song and start playing the 2nd song result, and do another search you will see the 2nd result has it being played and any action/state of the previous result would be glued to this one. So it wouldn't be possible to add the new search result to your library if the first search was added.

See the screenshot below for an example

### Steps to Reproduce

1. Search for 'KSI - Not Over Yet' and start playing the 2nd result (2nd is just an example). Also add it to your library.
2. Go back to your Songs library.
3. Search for 'Thunder - Gabry Ponte' and you will see the 2nd result is being played (with the visualiser animation). You will also not be able to add the 2nd result to your library because it thinks it's KSI - Not Over Yet and is already added to your library.

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: Version 1.5.4-beta.43

### Anything else?

![image](https://user-images.githubusercontent.com/17136956/187093316-852727e8-cff0-4bac-ad2c-c846732918de.png)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Few days back I made a few changes to the search page so this should no longer happen.
