### ISSUE TITLE
[Bug]:  music breaks

### ISSUE THREAD

**Issue by siwu23** [ciderapp/Cider#1395]
### Describe the Bug

When playing music, it is always suddenly interrupted and paused, and there is no response when pressing the play button, and it will get stuck after a while when it is re-opened.

### Steps to Reproduce

1.no action

### Environment Information

- OS:win11
- App Version and/or Commit ID:1.5.6-beta.6

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Similar to #814, as far as I know this is an Apple issue. See issue #814 for potential ways to prevent this.
