### ISSUE TITLE
[Bug]: malformed query parameters when "&" present (not escaped)

### ISSUE THREAD

**Issue by arthur-apanovics** [ciderapp/Cider#1413]
### Describe the Bug

Receiving a `400` response when trying to "Go to Artist"/"Go to Album" with an ampersand in title.

### Steps to Reproduce

1. Clicked on artist name with "&" in title
2. Nothing happens in UI

### Environment Information

- OS: MacOS
- App Version and/or Commit ID: Version 1.5.7-beta.8

### Anything else?

Example request/response

Request
```
https://amp-api.music.apple.com/v1/catalog/nz/search?term=Lisa Batiashvili & Giorgi Gigashvili&limit=1&types=artists
```

Response
```
{
    "errors": [
        {
            "id": "432734R2I7OJUWJZGXDHSF2YYY",
            "title": "Invalid Parameter",
            "detail": "Parameter ' Giorgi Gigashvili' is not allowed",
            "status": "400",
            "code": "40004",
            "source": {
                "parameter": " Giorgi Gigashvili"
            }
        }
    ]
}
```

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Update to the latest beta, this issue should be resolved.
