### ISSUE TITLE
[Bug]: Sorting by date added does not work correctly

### ISSUE THREAD

**Issue by theyanniss23002** [ciderapp/Cider#1415]
### Describe the Bug

When sorting "Date added", the last added track is not displayed in the list, but is somewhere in the playlist

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS: MacOs, M1 pro
- App Version and/or Commit ID: 1.5.7-beta.8

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Resolved in [5099d41](https://github.com/ciderapp/Cider/commit/5099d41260515c2496d33a817b6e36a9f4a45069)
