### ISSUE TITLE
[Bug]: Music Added to Cloud Music Library doesn't show Album Art under Discord RPC

### ISSUE THREAD

**Issue by themacintoshnerd** [ciderapp/Cider#1416]
### Describe the Bug

Music Added to Cloud Music Library doesn't show Album Art under Discord RPC. It some times will also play for a few seconds and then skip to the next track when in playlists with music from Apple Music. 

![image](https://user-images.githubusercontent.com/32601031/188723223-5c764bf9-be22-4fbd-9e5a-0435b52bf0f8.png)

### Steps to Reproduce

1. Upload songs to Apple Music using iTunes or the macOS Music App 
   https://support.apple.com/guide/itunes/icloud-music-library-itnsa3dd5209/windows
   https://support.apple.com/guide/itunes/icloud-music-library-itnsa3dd5209/mac
   https://support.apple.com/guide/music/access-your-music-library-musa3dd5209/1.2/mac/12.0
2. Play a song synced using this method 
3. look at discord

### Environment Information

- OS: Manjaro Linux x86_64 
- Kernel: 5.15.60-1-MANJARO 
- App Version and/or Commit ID: 1.5.6

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by themacintoshnerd** [comment]
The Screenshot shows the advanced-rpc plugin but this occurs on both that and the built in RPC

**Comment by down-bad** [comment]
That's Apple's fault I'm pretty sure

**Comment by cryptofyre** [comment]
Our API used to handle this but since we started load balancing this has not been the case, we'll look into this on a later date as we finish migrating all of our services.
