### ISSUE TITLE
[Bug]: No music plays

### ISSUE THREAD

**Issue by ajs256** [ciderapp/Cider#1417]
### Describe the Bug

No audio plays, whether it's from a station or playlist. I can tell something is happening because the song name and album art show up. The play button has no effect.

### Steps to Reproduce

1. Start a track or station from the home page
2. Observe that nothing plays, despite the art showing up

### Environment Information

- OS: macOS 12.5.1
- App Version and/or Commit ID: Cider 1.5.7-beta.44

### Anything else?

Here is a log when attempting to start a station:
<details>
<pre>
Loaded Preload
VM7:201 [cider:preload] IPC Listeners Created!
less.js:10 Less has finished and no sheets were loaded.
resonance-audio.min.js:166 [Omnitone] Version 1.0.6 (running Chrome 104.0.5112.102 on Mac OS X) (@156.00ms)
index.js?v=1:208 WebGPU disabled / WebGPU initialization failed
index.js?v=1:111 MusicKit loaded
amp-api.music.apple.com/v1/storefronts/undefined:1          Failed to load resource: the server responded with a status of 404 ()
vueapp.js:4817 locale err NOT_FOUND: 404
    at MKError.responseError (https://api.cider.sh/musickit.js:15:3647)
    at https://api.cider.sh/musickit.js:44:255293
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
vueapp.js:4801 Array(5)
vueapp.js:4814 en-us
vueapp.js:1466 using cached playlists
vueapp.js:1474 using cached track mapping
vueapp.js:1486 scanning p.playlistsroot
vueapp.js:285 hashchange home
node:electron/js2c/sandbox_bundle:29 Uncaught (in promise) Error: Error invoking remote method 'scanLibrary': No handler registered for 'scanLibrary'
    at o.invoke (node:electron/js2c/sandbox_bundle:29:551)
(index):2692 Object
(index):2692 Object
vueapp.js:1491 Array(17)
vueapp.js:254 Config changed: {"main":{"PLATFORM":"darwin","UPDATABLE":true},"general":{"close_button_hide":false,"language":"en_US","playbackNotifications":true,"resumeOnStartupBehavior":"local","privateEnabled":false,"themeUpdateNotification":true,"sidebarItems":{"recentlyAdded":true,"songs":true,"albums":true,"artists":true,"videos":true,"podcasts":true},"sidebarCollapsed":{"cider":false,"applemusic":false,"library":false,"amplaylists":false,"playlists":false,"localLibrary":false},"onStartup":{"enabled":false,"hidden":false},"resumeTabs":{"tab":"home","dynamicData":""},"keybindings":{"search":["CommandOrControl","F"],"listnow":["CommandOrControl","L"],"browse":["CommandOrControl","B"],"recentAdd":["CommandOrControl","G"],"songs":["CommandOrControl","J"],"albums":["CommandOrControl","Option","A"],"artists":["CommandOrControl","D"],"togglePrivateSession":["CommandOrControl","P"],"webRemote":["CommandOrControl","Option","W"],"audioSettings":["CommandOrControl","Option","A"],"pluginMenu":["CommandOrControl","Option","P"],"castToDevices":["CommandOrControl","Option","C"],"settings":["CommandOrControl",","],"zoomn":["Control","numadd"],"zoomt":["Control","numsub"],"zoomrst":["Control","num0"],"openDeveloperTools":["CommandOrControl","Shift","I"]},"showLovedTracksInline":true},"connectivity":{"discord_rpc":{"enabled":false,"client":"Cider","clear_on_pause":true,"hide_buttons":false,"hide_timestamp":false,"state_format":"by {artist}","details_format":"{title}"},"lastfm":{"enabled":false,"scrobble_after":50,"filter_loop":false,"filter_types":{},"remove_featured":true,"secrets":{"username":"","key":""}}},"home":{"followedArtists":[],"favoriteItems":[]},"libraryPrefs":{"songs":{"scroll":"paged","sort":"name","sortOrder":"asc","size":"normal"},"albums":{"scroll":"paged","sort":"name","sortOrder":"asc","viewAs":"covers"},"playlists":{"scroll":"infinite"},"localPaths":[],"pageSize":250},"audio":{"volume":0,"volumeStep":0.05,"maxVolume":1,"lastVolume":1,"muted":false,"playbackRate":1,"quality":"HIGH","seamless_audio":true,"normalization":true,"dBSPL":false,"dBSPLcalibration":90,"maikiwiAudio":{"ciderPPE":true,"ciderPPE_value":"MAIKIWI","staticOptimizer":{"state":false,"lock":false},"opportunisticCorrection_state":"OFF","atmosphereRealizer1":false,"atmosphereRealizer1_value":"NATURAL_STANDARD","atmosphereRealizer2":false,"atmosphereRealizer2_value":"NATURAL_STANDARD","spatial":false,"spatialProfile":"BPLK","vibrantBass":{"frequencies":[17.182,42.169,53.763,112.69,119.65,264.59,336.57,400.65,505.48,612.7,838.7,1155.3,1175.6,3406.8,5158.6,5968.1,6999.9,7468.6,8862.9,9666,10109],"Q":[2.5,0.388,5,5,2.5,7.071,14.14,10,7.071,14.14,8.409,0.372,7.071,10,16.82,7.071,28.28,20,8.409,40,40],"gain":[-0.34,2.49,0.23,-0.49,0.23,-0.12,0.32,-0.29,0.33,0.19,-0.18,-1.27,-0.11,0.25,-0.18,-0.53,0.34,1.32,1.78,0.41,-0.28]},"lastNode":"n1","firstNode":"n1"},"spatial":false,"spatial_properties":{"presets":[],"gain":0.8,"listener_position":[0,0,0],"audio_position":[0,0,0],"room_dimensions":{"width":32,"height":12,"depth":32},"room_materials":{"left":"metal","right":"metal","front":"brick-bare","back":"brick-bare","down":"acoustic-ceiling-tiles","up":"acoustic-ceiling-tiles"}},"equalizer":{"preset":"default","frequencies":[32,63,125,250,500,1000,2000,4000,8000,16000],"gain":[0,0,0,0,0,0,0,0,0,0],"Q":[1,1,1,1,1,1,1,1,1,1],"mix":1,"vibrantBass":0,"presets":[],"userGenerated":false}},"visual":{"theme":"","styles":[],"scrollbars":0,"refresh_rate":0,"window_background_style":"none","animated_artwork":"limited","animated_artwork_qualityLevel":1,"bg_artwork_rotation":false,"hw_acceleration":"default","showuserinfo":true,"transparent":false,"miniplayer_top_toggle":true,"directives":{"windowLayout":"twopanel"},"windowControlPosition":0,"nativeTitleBar":false,"windowColor":"#000000","customAccentColor":false,"accentColor":"#fc3c44","purplePodcastPlaybackBar":false,"maxElementScale":-1},"lyrics":{"enable_mxm":true,"mxm_karaoke":false,"mxm_language":"disabled","enable_qq":false,"enable_yt":false},"advanced":{"AudioContext":true,"experiments":[],"playlistTrackMapping":true,"ffmpegLocation":"","disableLogging":false},"connectUser":{"auth":null,"sync":{"themes":false,"plugins":false,"settings":false}},"__internal__":{"migrations":{"version":"1.5.7-beta.44"}},"cc_authURL":"https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000"}
cideraudio.js:91 [Cider][MaikiwiSoundCheck] normalizer func err: TypeError: Cannot read properties of undefined (reading 'songId')
cideraudio.js:1039 [Cider][Audio] Finished hierarchical unloading
cideraudio.js:764 [Cider][Audio] CAP Adaptive - 256kbps
cideraudio.js:885 [Cider][Audio] llpw_n1 -> destination
cideraudio.js:1135 [Cider][Audio] gainNode -> llpw
cideraudio.js:1143 [Cider][Audio]
spatial,false,n6,false,n5,false,n4,false,n3,false,n2,false,n1,true
 lastNode: n1
cideraudio.js:307 [Cider][Audio] IntelliGainComp: -0.90 dB (0.9016)
cideraudio.js:1146 [Cider][Audio] Finished hierarchical loading
VM7:38 [cider:preload] nowPlayingItemDidChange
vueapp.js:1077 [Cider][MaikiwiSoundCheck] previewURL in app.mk.nowPlayingItem.previewURL: https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/9f/16/4a/9f164a77-1d5a-1738-1507-f879da8e379e/mzaf_17616078379057106226.plus.aac.ep.m4a
vueapp.js:928 [Cider][MaikiwiSoundCheck] Peak Gain: '-0.01' dB | Adjusting '-1.69' dB
cideraudio.js:1039 [Cider][Audio] Finished hierarchical unloading
cideraudio.js:764 [Cider][Audio] CAP Adaptive - 256kbps
cideraudio.js:885 [Cider][Audio] llpw_n1 -> destination
cideraudio.js:1135 [Cider][Audio] gainNode -> llpw
cideraudio.js:1143 [Cider][Audio]
spatial,false,n6,false,n5,false,n4,false,n3,false,n2,false,n1,true
 lastNode: n1
cideraudio.js:307 [Cider][Audio] IntelliGainComp: -0.90 dB (0.9016)
cideraudio.js:1146 [Cider][Audio] Finished hierarchical loading
vueapp.js:3020 Object
vueapp.js:3206 Object
vueapp.js:3234 musixmatch worki
VM7:67 [cider:preload] mediaPlaybackError] UNKNOWN_ERROR: MEDIA_LICENSE
(anonymous) @ VM7:67
(index):9693 Object undefined -1 'radioStation' 'ra.359553651' false false false
vueapp.js:254 Config changed: {"main":{"PLATFORM":"darwin","UPDATABLE":true},"general":{"close_button_hide":false,"language":"en_US","playbackNotifications":true,"resumeOnStartupBehavior":"local","privateEnabled":false,"themeUpdateNotification":true,"sidebarItems":{"recentlyAdded":true,"songs":true,"albums":true,"artists":true,"videos":true,"podcasts":true},"sidebarCollapsed":{"cider":false,"applemusic":false,"library":false,"amplaylists":false,"playlists":false,"localLibrary":false},"onStartup":{"enabled":false,"hidden":false},"resumeTabs":{"tab":"home","dynamicData":""},"keybindings":{"search":["CommandOrControl","F"],"listnow":["CommandOrControl","L"],"browse":["CommandOrControl","B"],"recentAdd":["CommandOrControl","G"],"songs":["CommandOrControl","J"],"albums":["CommandOrControl","Option","A"],"artists":["CommandOrControl","D"],"togglePrivateSession":["CommandOrControl","P"],"webRemote":["CommandOrControl","Option","W"],"audioSettings":["CommandOrControl","Option","A"],"pluginMenu":["CommandOrControl","Option","P"],"castToDevices":["CommandOrControl","Option","C"],"settings":["CommandOrControl",","],"zoomn":["Control","numadd"],"zoomt":["Control","numsub"],"zoomrst":["Control","num0"],"openDeveloperTools":["CommandOrControl","Shift","I"]},"showLovedTracksInline":true},"connectivity":{"discord_rpc":{"enabled":false,"client":"Cider","clear_on_pause":true,"hide_buttons":false,"hide_timestamp":false,"state_format":"by {artist}","details_format":"{title}"},"lastfm":{"enabled":false,"scrobble_after":50,"filter_loop":false,"filter_types":{},"remove_featured":true,"secrets":{"username":"","key":""}}},"home":{"followedArtists":[],"favoriteItems":[]},"libraryPrefs":{"songs":{"scroll":"paged","sort":"name","sortOrder":"asc","size":"normal"},"albums":{"scroll":"paged","sort":"name","sortOrder":"asc","viewAs":"covers"},"playlists":{"scroll":"infinite"},"localPaths":[],"pageSize":250},"audio":{"volume":1,"volumeStep":0.05,"maxVolume":1,"lastVolume":1,"muted":false,"playbackRate":1,"quality":"HIGH","seamless_audio":true,"normalization":true,"dBSPL":false,"dBSPLcalibration":90,"maikiwiAudio":{"ciderPPE":true,"ciderPPE_value":"MAIKIWI","staticOptimizer":{"state":false,"lock":false},"opportunisticCorrection_state":"OFF","atmosphereRealizer1":false,"atmosphereRealizer1_value":"NATURAL_STANDARD","atmosphereRealizer2":false,"atmosphereRealizer2_value":"NATURAL_STANDARD","spatial":false,"spatialProfile":"BPLK","vibrantBass":{"frequencies":[17.182,42.169,53.763,112.69,119.65,264.59,336.57,400.65,505.48,612.7,838.7,1155.3,1175.6,3406.8,5158.6,5968.1,6999.9,7468.6,8862.9,9666,10109],"Q":[2.5,0.388,5,5,2.5,7.071,14.14,10,7.071,14.14,8.409,0.372,7.071,10,16.82,7.071,28.28,20,8.409,40,40],"gain":[-0.34,2.49,0.23,-0.49,0.23,-0.12,0.32,-0.29,0.33,0.19,-0.18,-1.27,-0.11,0.25,-0.18,-0.53,0.34,1.32,1.78,0.41,-0.28]},"lastNode":"n1","firstNode":"n1"},"spatial":false,"spatial_properties":{"presets":[],"gain":0.8,"listener_position":[0,0,0],"audio_position":[0,0,0],"room_dimensions":{"width":32,"height":12,"depth":32},"room_materials":{"left":"metal","right":"metal","front":"brick-bare","back":"brick-bare","down":"acoustic-ceiling-tiles","up":"acoustic-ceiling-tiles"}},"equalizer":{"preset":"default","frequencies":[32,63,125,250,500,1000,2000,4000,8000,16000],"gain":[0,0,0,0,0,0,0,0,0,0],"Q":[1,1,1,1,1,1,1,1,1,1],"mix":1,"vibrantBass":0,"presets":[],"userGenerated":false}},"visual":{"theme":"","styles":[],"scrollbars":0,"refresh_rate":0,"window_background_style":"none","animated_artwork":"limited","animated_artwork_qualityLevel":1,"bg_artwork_rotation":false,"hw_acceleration":"default","showuserinfo":true,"transparent":false,"miniplayer_top_toggle":true,"directives":{"windowLayout":"twopanel"},"windowControlPosition":0,"nativeTitleBar":false,"windowColor":"#000000","customAccentColor":false,"accentColor":"#fc3c44","purplePodcastPlaybackBar":false,"maxElementScale":-1},"lyrics":{"enable_mxm":true,"mxm_karaoke":false,"mxm_language":"disabled","enable_qq":false,"enable_yt":false},"advanced":{"AudioContext":true,"experiments":[],"playlistTrackMapping":true,"ffmpegLocation":"","disableLogging":false},"connectUser":{"auth":null,"sync":{"themes":false,"plugins":false,"settings":false}},"__internal__":{"migrations":{"version":"1.5.7-beta.44"}},"cc_authURL":"https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000"}
:9000/#home:1 Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause(). https://goo.gl/LdLk22
VM7:38 [cider:preload] nowPlayingItemDidChange
vueapp.js:3602 ra.359553651 radioStations false
2VM7:38 [cider:preload] nowPlayingItemDidChange
3VM7:88 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at Object.fetchPrimaryArtist (<anonymous>:88:42)
    at <anonymous>:40:91
    at wrappedCallback (musickit.js:44:288320)
    at musickit.js:29:20834
    at Array.forEach (<anonymous>)
    at PubSub.publish (musickit.js:29:20822)
    at set nowPlayingItem [as nowPlayingItem] (musickit.js:44:53103)
    at AudioPlayer.<anonymous> (musickit.js:44:56704)
    at Generator.next (<anonymous>)
    at fulfilled (musickit.js:29:977)
musickit.js:44 Uncaught (in promise) Error: A method was called without a previous descriptor
    at get previousDescriptor [as previousDescriptor] (musickit.js:44:43417)
    at PlayActivity.<anonymous> (musickit.js:44:41271)
    at Generator.next (<anonymous>)
    at musickit.js:29:1210
    at new Promise (<anonymous>)
    at __awaiter (musickit.js:29:909)
    at PlayActivity.scrub (musickit.js:44:41135)
    at PAFTrackerAPI.scrub (musickit.js:44:400202)
    at PAFTrackerAPI.<anonymous> (musickit.js:44:400311)
    at Generator.next (<anonymous>)
VM7:38 [cider:preload] nowPlayingItemDidChange
VM7:88 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'attributes')
    at Object.fetchPrimaryArtist (<anonymous>:88:42)
    at <anonymous>:40:91
    at wrappedCallback (musickit.js:44:288320)
    at musickit.js:29:20834
    at Array.forEach (<anonymous>)
    at PubSub.publish (musickit.js:29:20822)
    at set nowPlayingItem [as nowPlayingItem] (musickit.js:44:53103)
    at AudioPlayer.<anonymous> (musickit.js:44:56704)
    at Generator.next (<anonymous>)
    at fulfilled (musickit.js:29:977)
VM7:38 [cider:preload] nowPlayingItemDidChange
vueapp.js:1077 [Cider][MaikiwiSoundCheck] previewURL in app.mk.nowPlayingItem.previewURL: https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/v4/ef/76/78/ef7678c2-8b6b-32c2-b1bc-afa8fa5de233/mzaf_3075931532821100900.plus.aac.ep.m4a
vueapp.js:3206 Object
vueapp.js:3234 musixmatch worki
VM7:67 [cider:preload] mediaPlaybackError] UNKNOWN_ERROR: MEDIA_LICENSE
(anonymous) @ VM7:67
vueapp.js:928 [Cider][MaikiwiSoundCheck] Peak Gain: '-1.64' dB | Adjusting '-0.06' dB
cideraudio.js:1039 [Cider][Audio] Finished hierarchical unloading
cideraudio.js:764 [Cider][Audio] CAP Adaptive - 256kbps
cideraudio.js:885 [Cider][Audio] llpw_n1 -> destination
cideraudio.js:1135 [Cider][Audio] gainNode -> llpw
cideraudio.js:1143 [Cider][Audio]
spatial,false,n6,false,n5,false,n4,false,n3,false,n2,false,n1,true
 lastNode: n1
cideraudio.js:307 [Cider][Audio] IntelliGainComp: -0.90 dB (0.9016)
cideraudio.js:1146 [Cider][Audio] Finished hierarchical loading
manifest.json:1          Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/less.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/CiderHls.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/stackblur.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/bootstrap-vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/vuedraggable.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/bootstrap-vue.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
musickit.js:44          GET https://amp-api.music.apple.com/v1/me/library/playlists/p.oOzA3m7ClO5k16G/tracks 404
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:29
__awaiter @ musickit.js:29
(anonymous) @ musickit.js:44
(anonymous) @ musickit.js:44
constructUrlMiddleware @ musickit.js:44
(anonymous) @ musickit.js:44
processMiddleware @ musickit.js:44
request @ musickit.js:44
(anonymous) @ vueapp.js:1501
asyncForEach @ index.js?v=1:188
cidercache.js:15 Caching library-playlists-tracks
cidercache.js:15 Caching library-playlists
</pre></details>

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by pretzel66** [comment]
Same happens on Win11 build 10.0.22000 Build 22000

App Version Cider 1.5.6 (microsoft store and experimental from Winget)

**Comment by thecute** [comment]
Experiencing the same issue on Windows 10 Pro Version 21H2 Build 19044.1889

Cider Version 1.5.6 (Microsoft Store)

**Comment by guitarzen2006** [comment]
+1 Having the identical issue too on MacOS 12.5.1 Monterey using Apple M1 chip.  Was on Cider Version 1.5.7-beta.8, then tried upgrading to beta.44 and issue still persisted. Cider was working with out issue on beta.8 for the past couple of days and just stopped in the middle of a song. When I click the play button nothing happens. Tried rebooting application and computer to no avail.

**Comment by coredev-uk** [comment]
We are aware of this issue, its due to Apple making a mistake with MusicKit. More information can be found on this [Twitter post](https://twitter.com/usecider/status/1567269946605944835).

**Comment by guitarzen2006** [comment]
> We are aware of this issue, its due to Apple making a mistake with MusicKit. More information can be found on this [Twitter post](https://twitter.com/usecider/status/1567269946605944835).

Issue appears to be resolved now. I retested Cider and working as expected now. Thanks for the heads up. 　😀👍
