### ISSUE TITLE
[Bug]: Invalid CORS Request When Signing In

### ISSUE THREAD

**Issue by jlut93** [ciderapp/Cider#1418]
### Describe the Bug

When signing in for the first time, after inputting the 6 digit two factor authorisation code I get the error ' Invalid CORS Request'

### Steps to Reproduce

Signed in to Apple Music for the first time

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID: 1.5.6

### Anything else?

Account is through Apple Family Sharing, not sure if this may be the issue?

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by themacintoshnerd** [comment]
I think this might be platform specific as I use a family sharing account on Linux and macOS and Cider plays nicely with it.

**Comment by jlut93** [comment]
I think I've found a fix -  I can sign into Cider if I sign into music.apple.com first on the same PC.

**Comment by vapormusic** [comment]
> I think I've found a fix - I can sign into Cider if I sign into music.apple.com first on the same PC.

Yeah i guess i does work with some people that way.

**Comment by khurd21** [comment]
> I think I've found a fix - I can sign into Cider if I sign into music.apple.com first on the same PC.

I came across this same issue. MacOS 12.3.1 with App v1.5.6

**Comment by arowla** [comment]
>  I tried logging into music.apple.com on the device and still ran into the same message.

Same. MacOS 12.6.5, Cider v1.6.0. Also on a Family account.
