### ISSUE TITLE
[Bug]: Cider does not report a song playtime to ModernFlyouts application. 

### ISSUE THREAD

**Issue by JakeR04** [ciderapp/Cider#1423]
### Describe the Bug

If using the ModernFlyouts application, Cider no longer reports the current timestamp of the song or song length to the application anymore, instead displaying a 00:00/00:00. It used to send the timestamps to it after updating to 1.5.6, it no longer does. 

### Steps to Reproduce

1. Open ModernFlyouts. 
2. Start Playing a song. 
3. Pause the song using keyboard shortcuts and you will not see timestamps on the media player flyout.  

### Environment Information

- OS: Windows 10 21H2
- App Version and/or Commit ID: 1.5.6

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
This is due to the lack of GSMTC which unfortunately we can't add ourselves without going through WinRT hell and even then it wouldn't support scrubbing.

I'd suggest adding comments some pre-existing issues/feature-requests on https://bugs.chromium.org related to GSMTC to get it added.
