### ISSUE TITLE
[Bug]: Clicking on artist name, redirects to another artist with same name

### ISSUE THREAD

**Issue by qai9ar** [ciderapp/Cider#1432]
### Describe the Bug

When I click on artist name to view his/her/their profile, it redirects me on another artist with same name

Attachment: When clicking on "NATURE" K-pop girls group, redirects me to "Nature" another artist

### Steps to Reproduce

1. Add "SOME (You'll Be Mine) - NATURE" a K-pop song to a playlist
2. Click on "NATURE" the artist name
3. It will redirects you "Nature" an American rapper

### Environment Information

- OS: Windows 10
- Desktop Environment: Windows
- App Version: 1.5.6
- Commit ID:

### How did you download the software?

GitHub

### Anything else?

![Screenshot_1](https://user-images.githubusercontent.com/29235530/190278117-2ec7fc53-c6b5-4a78-bec5-767599adc5a1.png)
![Screenshot_2](https://user-images.githubusercontent.com/29235530/190278114-28cc0741-fc2a-49dd-b0dd-947197592812.png)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Fixed in bf6c439927fd0f3df5c07e199386e2a66e302cd5
