### ISSUE TITLE
[Bug]: Cider fails to start: 404 from amp-api.music.apple.com

### ISSUE THREAD

**Issue by pplachta** [ciderapp/Cider#1439]
### Describe the Bug

After startup, filling in my Apple ID info, leads to this

VM7:3 Loaded Preload
less.js:10 Less has finished and no sheets were loaded.
resonance-audio.min.js:166 [Omnitone] Version 1.0.6 (running Chrome 104.0.5112.114 on Linux) (@363.30ms)
index.js?v=1:208 WebGPU disabled / WebGPU initialization failed
vueapp.js:4938 locale err TypeError: Cannot read properties of undefined (reading 'api')
    at Cn.MKJSLang (vueapp.js:4916:48)
    at Cn.setLz (vueapp.js:373:32)
    at Cn.oobeInit (vueapp.js:297:12)
    at waitForApp (index.js?v=1:236:13)
amp-api.music.apple.com/v1/storefronts/undefined:1          Failed to load resource: the server responded with a status of 404 ()
vueapp.js:4938 locale err NOT_FOUND: 404
    at MKError.responseError (https://api.cider.sh/musickit.js:15:3647)
    at https://api.cider.sh/musickit.js:44:255293
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
vueapp.js:4922 Array(5)
vueapp.js:4935 en-us
amp-api.music.apple.com/v1/me/social-profile:1          Failed to load resource: the server responded with a status of 403 ()
vueapp.js:868 SyntaxError: "undefined" is not valid JSON
    at JSON.parse (<anonymous>)
    at Cn.init (vueapp.js:831:31)
vueapp.js:1171 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'remove')
    at Cn.init (vueapp.js:1171:40)
amp-api.music.apple.com/v1/me/recent/played?l=en-us&include=tracks&include%5Balbums%5D=catalog%2Ctracks%2Cartists&include%5Bsongs%5D=catalog%2Cartists:1          Failed to load resource: the server responded with a status of 403 ()
vue.js:6 ACCESS_DENIED: 403
    at MKError.responseError (https://api.cider.sh/musickit.js:15:3647)
    at https://api.cider.sh/musickit.js:44:255293
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
Ve @ vue.js:6
amp-api.music.apple.com/v1/me/recommendations?timezone=-07%3A00&name=listen-now&with=friendsMix,library,social&art[social-profiles:url]=c&art[url]=c,f&omit[resource]=autos&relate[editorial-items]=contents&extend=editorialCard,editorialVideo&extend[albums]=artistUrl&extend[library-albums]=artistUrl,editorialVideo&extend[playlists]=artistNames,editorialArtwork,editorialVideo&extend[library-playlists]=artistNames,editorialArtwork,editorialVideo&extend[social-profiles]=topGenreNames&include[albums]=artists&include[songs]=artists&include[music-videos]=artists&fields[albums]=artistName,artistUrl,artwork,contentRating,editorialArtwork,editorialVideo,name,playParams,releaseDate,url&fields[artists]=name,url&extend[stations]=airDate,supportsAirTimeUpdates&meta[stations]=inflectionPoints&types=artists,albums,editorial-items,library-albums,library-playlists,music-movies,music-videos,playlists,stations,uploaded-audios,uploaded-videos,activities,apple-curators,curators,tv-shows,social-upsells&platform=web&l=en-us:1          Failed to load resource: the server responded with a status of 403 ()
amp-api.music.apple.com/v1/me/library/playlist-folders/p.playlistsroot/children/:1          Failed to load resource: the server responded with a status of 403 ()
amp-api.music.apple.com/v1/me/social/profile/:1          Failed to load resource: the server responded with a status of 403 ()
musickit.js:15 Uncaught (in promise) ACCESS_DENIED: 403
    at MKError.responseError (https://api.cider.sh/musickit.js:15:3647)
    at https://api.cider.sh/musickit.js:44:255293
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
musickittools.js:16 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'data')
    at sendReq (musickittools.js:16:52)
    at async Object.v3Continuous (musickittools.js:30:5)
    at async deepScan (vueapp.js:1513:30)
    at async Cn.refreshPlaylists (vueapp.js:1554:7)
musickit.js:15 Uncaught (in promise) ACCESS_DENIED: 403
    at MKError.responseError (https://api.cider.sh/musickit.js:15:3647)
    at https://api.cider.sh/musickit.js:44:255293
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
amp-api.music.apple.com/v1/me/recent/played?l=en-us&include=tracks&include%5Balbums%5D=catalog%2Ctracks%2Cartists&include%5Bsongs%5D=catalog%2Cartists:1          Failed to load resource: the server responded with a status of 403 ()
vue.js:6 ACCESS_DENIED: 403
    at MKError.responseError (https://api.cider.sh/musickit.js:15:3647)
    at https://api.cider.sh/musickit.js:44:255293
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
Ve @ vue.js:6
amp-api.music.apple.com/v1/me/social/profile/:1          Failed to load resource: the server responded with a status of 403 ()
amp-api.music.apple.com/v1/me/recommendations?timezone=-07%3A00&name=listen-now&with=friendsMix,library,social&art[social-profiles:url]=c&art[url]=c,f&omit[resource]=autos&relate[editorial-items]=contents&extend=editorialCard,editorialVideo&extend[albums]=artistUrl&extend[library-albums]=artistUrl,editorialVideo&extend[playlists]=artistNames,editorialArtwork,editorialVideo&extend[library-playlists]=artistNames,editorialArtwork,editorialVideo&extend[social-profiles]=topGenreNames&include[albums]=artists&include[songs]=artists&include[music-videos]=artists&fields[albums]=artistName,artistUrl,artwork,contentRating,editorialArtwork,editorialVideo,name,playParams,releaseDate,url&fields[artists]=name,url&extend[stations]=airDate,supportsAirTimeUpdates&meta[stations]=inflectionPoints&types=artists,albums,editorial-items,library-albums,library-playlists,music-movies,music-videos,playlists,stations,uploaded-audios,uploaded-videos,activities,apple-curators,curators,tv-shows,social-upsells&platform=web&l=en-us:1          Failed to load resource: the server responded with a status of 403 ()
2musickit.js:15 Uncaught (in promise) ACCESS_DENIED: 403
    at MKError.responseError (https://api.cider.sh/musickit.js:15:3647)
    at https://api.cider.sh/musickit.js:44:255293
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
amp-api.music.apple.com/v1/social/badging-map:1          Failed to load resource: the server responded with a status of 403 ()
musickit.js:15 Uncaught (in promise) ACCESS_DENIED: 403
    at MKError.responseError (https://api.cider.sh/musickit.js:15:3647)
    at https://api.cider.sh/musickit.js:44:255293
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:29:977)
musickit.js:44 Uncaught (in promise) AUTHORIZATION_ERROR: Unauthorized
    at Store.<anonymous> (https://api.cider.sh/musickit.js:44:217169)
    at Generator.next (<anonymous>)
    at fulfilled (https://api.cider.sh/musickit.js:15:647)
manifest.json:1          Failed to load resource: the server responded with a status of 404 (Not Found)
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/less.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/CiderHls.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/bootstrap.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/stackblur.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/bootstrap-vue.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/lib/vuedraggable.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://localhost:9000/bootstrap-vue.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### Steps to Reproduce

Install version I built. Run cider. Log in with Apple credentials.

### Environment Information

- OS: Ubuntu 22.04
- Desktop Environment: 
- App Version:
- Commit ID: c30e0a2e252e9e3ed957dd791f98a38933735077

### How did you download the software?

GitHub

### Anything else?

main error log does not contain any errors. It ends in

[2022-09-15 14:15:24.879] [info]  From here can you check for real changes, the initial scan has been completed.
[2022-09-15 14:15:24.879] [info]  Cider client port: 9000
[2022-09-15 14:15:24.883] [info]  Cider remote port: 6942
[2022-09-15 14:15:24.885] [info]  remote broadcasted

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Are you running the app in a compiled state?

**Comment by pplachta** [comment]
> Are you running the app in a compiled state? I.e. using the start command.

No: I installed it using "dpkg -i <name>" where I got <name> from the "dist/" directory.
I then ran 'cider' from the command line as well as from the app menu.

Let me know if I can provide more info.
