### ISSUE TITLE
[Bug]: Songs within playlists with over 250 or more songs are not showing up

### ISSUE THREAD

**Issue by sandrinok** [ciderapp/Cider#1440]
### Describe the Bug

Every playlist in Cider with a greater than 250 songs in them, are not showing

### Steps to Reproduce

Have a playlist with 250+ songs.

Like this one: https://music.apple.com/nl/playlist/the-list-10/pl.u-XmEESDMz6yK

### Environment Information

- OS: Windows 11
- Desktop Environment: i9
- App Version: 1.5.6
- Commit ID: None

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by SMASH-DIAMOND** [comment]
![image](https://user-images.githubusercontent.com/45404735/190656913-73f88bcf-700e-4299-a2b5-4282d1407bcc.png)

**Comment by quacksire** [comment]
@SMASH-DIAMOND Showed exactly how to fix this issue.
