### ISSUE TITLE
[Bug]: Cannot delete song from library

### ISSUE THREAD

**Issue by keinsell** [ciderapp/Cider#1442]
### Describe the Bug

I cannot delete song from library

### Steps to Reproduce

1. Right-clicked on song
2. Delete from library
3. Nothing happens.

### Environment Information

- OS: MacOS 12.5.1
- Desktop Environment: 
- App Version: 1.5.7-beta.137
- Commit ID:

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Providing you were trying to remove the currently playing song from your library, this issue should be resolved.
