### ISSUE TITLE
[Bug]: Windows freezes randomly after the application has open once

### ISSUE THREAD

**Issue by Ramz1994** [ciderapp/Cider#1453]
### Describe the Bug

I do not know how to describe the issue, but when I open Cider once, my computer freezes randomly. The GPU spike up to 100% utilization. I first noticed the issue while playing a game, I was alt-tabing between the game and Cider. While trying to isolate the issue, I found that the game was not the issue at all and I was able to have random freeze doing basic tasks in Windows. If I reboot my computer and do not open Cider, the issue never happens. It seems to be an issue with the GPU, but I am not sure. Do you think I could disable something to prevent this from happening ? It is kinda strange, because when I close the app, the issue does not resolve itself. If I can provide something else, you can ask me. :-)

### Steps to Reproduce

1. Open Cider
2. Windows 11 randomly freeze

### Environment Information

- OS: Windows 11 21H2
- App Version: 1.5.6.0
- CPU : Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   3.70 GHz
- Memory : 16 GB
- GPU : GeForce GTX 1060 6GB

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
Yeah this does not seem like a Cider issue, there is something definitely wrong with your operating system or GPU.
