### ISSUE TITLE
[Bug]: Pressing Next pauses the song & stops playback

### ISSUE THREAD

**Issue by Zexyen** [ciderapp/Cider#1457]
### Describe the Bug

Whenever attempting to skip a song by either pressing next via media key or the software key, playback stops and the queue ends. Pressing Next again via the media key continues playback again.

Attempted fixes:

- Cleared all data of the application & reinstalled
- Downloaded latest beta (1.5.7-beta-99)
- Unplugged any USB keyboards
- Disabled DiscordRPC

### Steps to Reproduce

1. Start playing any music
2. Hit 'Next Track' Either by Media Keys or by Software Key
3. Playback stops & the queue clears out
4. Hitting 'Next Track' Again restarts the Queue again.

### Environment Information

- OS: W11 22H2
- App Version: Verified the issue with 1.5.6 & 1.5.7 Beta 99
- Commit ID:

### How did you download the software?

GitHub

### Anything else?

![7kfyus](https://user-images.githubusercontent.com/13377953/191639959-f985c014-ff61-4879-9f97-f7ae936bdcb4.gif)

Looking through the Console I see some errors when playing next, Issue happens whether I enable/disable musickit.
![](https://images.zexyen.com/Images/2022/09-21/uw4bD9.png)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
50a8524 should fix this.

**Comment by ogpaulgould** [comment]
> [50a8524](https://github.com/ciderapp/Cider/commit/50a8524f55619a6884cefccb3fe21d59b5a8f1bc) should fix this.

Thanks for the quick fix works awesome now!

**Comment by Zexyen** [comment]
> [50a8524](https://github.com/ciderapp/Cider/commit/50a8524f55619a6884cefccb3fe21d59b5a8f1bc) should fix this.

can confirm this fixes it for me as well now.
