### ISSUE TITLE
[Enhancement] i18n/Localization

### ISSUE THREAD

**Issue by maikirakiwi** [ciderapp/Cider#146]
**Is your feature request related to a problem? Please describe.**
UX/UI Inconsistencies for people who do not have their Apple ID in an English-speaking country.

**Describe the solution you'd like**
A repository/website that allows for peer contribution and considers the following criteria: 
- Standardizing key formatting. i.e. ```class``` _ ```page``` _ ```string``` (sidebar-library-item_library-recentlyadded_RecentlyAdded)
- Solution must contain string checks. (Avoiding punctuation inconsistencies with the original en_US string)
- For code cleanliness, Conform to the ISO/Apple standards outlined [here](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/LanguageandLocaleIDs/LanguageandLocaleIDs.html)
- Automatically pull locale data from the said repository/website at a reasonably set interval OR push an event to the client that warrants a client update/rebuild.
- Default client language/region should be pulled from the MusicKit/URL (Ex: /v1/catalog/```jp```/playlists/...) and client locale should be overrideable in Settings.

**Describe alternatives you've considered**
Writing a plugin that allows for hot-swapping .ejs files that contain the translated strings.
The drawbacks are that it is extremely unorganized and would be a pain to have everyone scour for different plugins for different languages. Instead, a uniform solution built by the official development team would solve this issue.

**Additional context**
Areas with inconsistencies boxed with a red rectangle.
![chrome_l1ExME3EQNNPsyLA](https://user-images.githubusercontent.com/74925636/149848789-7958f858-0fce-40d5-83ea-06784befd20c.png)

**Comment by gms10ur** [comment]
+1 to this. I can do the Turkish translations

**Comment by quacksire** [comment]
#179 #180 

Total Locales: 6

**Comment by quacksire** [comment]
Total Locales: 8

Feel free to PR if you want to add more!

**Comment by maikirakiwi** [comment]
Countless locales including galactic alphabet
Unpin
