### ISSUE TITLE
[Bug]: App stuck when trying to play explicit songs

### ISSUE THREAD

**Issue by AppleJeb** [ciderapp/Cider#1461]
### Describe the Bug

Because of new Apple's parental control playback just stucks after you click on explicit songs.
You can't play more songs until restart. Apple Music Web displays message "Explicit content restricted".
For me problem is resolved and i just wanna report this bug. 

### Steps to Reproduce

1. Go to web version of Apple Music and disable explicit content (for me it was disabled by default, changing settings on my phone doesnt help)
2. Search for any song with explicit tag
3. Click Play
4. Player stuck until restart

### Environment Information

- OS: Windows 11 Pro 21H2
- App Version: 1.5.6 (winget)
- Commit ID: No idea

### How did you download the software?

Winget

### Anything else?

I think adding same popup in cider would do the job

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Please read the FAQs before opening issues.
https://docs.cider.sh/support/faqs#cider-is-skipping-or-not-playing-explicit-songs
