### ISSUE TITLE
[Enhancement] Send title of song and artist to application title

### ISSUE THREAD

**Issue by 8times9** [ciderapp/Cider#147]
**Is your feature request related to a problem? Please describe.**
Many other applications show useful context information in the titlebar of their app. For instance, Files (WinUI File Explorer replacement) shows the current directory in the window title. I often wish that the Cider window title displayed information on the current song that is playing instead of requiring me to tab over to the Cider window.

**Describe the solution you'd like**
I do not wish that the top left corner Cider text and logo display this information. Instead, it would only appear externally such as in the taskbar when hovering over/combine labels is turned off or in the Task View.

The display could be something like:
"Songtitle by Artist - Cider"

**Describe alternatives you've considered**
There is no miniplayer currently or else this might be a good alternative to see the current song.

**Additional context**
![image](https://user-images.githubusercontent.com/35514663/149857293-95eede70-3861-4730-8384-1e077f46fdaa.png)
![image](https://user-images.githubusercontent.com/35514663/149857353-3a853694-dcd4-453e-83e1-3e446fb998bc.png)

In these images I show which region I am speaking about.

**Comment by 8times9** [comment]
Wow that was fast! Great work, this project has some incredible potential

**Comment by coredev-uk** [comment]
Sorry for the lateness of this, just note: As the extras don't get executed, copy the sendSongTotielBar.ts file from Extras to %appdata%/Cider/plugins or .config/Cider/plugins. (Create the folder if it's not there) @8times9

**Comment by 8times9** [comment]
@coredev-uk If I am using the Microsoft store version where can I find this Extras folder? I poked around in AppData/Local/Packages and couldn't find much.
