### ISSUE TITLE
[Bug]: Cider does not remember page position when going back

### ISSUE THREAD

**Issue by MarcSteak** [ciderapp/Cider#1474]
### Describe the Bug

this bug can also be counted as a feature request

### Steps to Reproduce

1. open a larger playlist (for example official charts)
2. scroll down to the end
3. click on artist to go to the artist page
4. go back
5. you are at the top of the playlist instead at the position where you left

### Environment Information

- OS: Windows 10 and Windows 11
- App: latest Microsoft Store build

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by KillerParticles** [comment]
wish this was added aswell

**Comment by cryptofyre** [comment]
Fixed. c5d86a9a0f3c4e007086721997d2566cf7795730
