### ISSUE TITLE
[Bug]: Cider-git 1.5.8.beta.001-1 will not launch (Arch Linux)

### ISSUE THREAD

**Issue by undeadbydawn** [ciderapp/Cider#1479]
### Describe the Bug

App will not launch. It tries for a few seconds then just stops.

### Steps to Reproduce

1. Clicked on... the app icon
2. nothing happens

### Environment Information

- OS: Arch Linux [kernel tkg-bore 5.19.12.270]
- Desktop Environment: KDE  Plasma
- App Version: cider-git 1.5.8.beta.001-1
- Commit ID:

### How did you download the software?

AUR

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Delete .config/cider

**Comment by undeadbydawn** [comment]
> Delete .config/cider

Didn't work, Cider-git still won't launch.
The main branch is fine

**Comment by coredev-uk** [comment]
Unfortunately I can’t make a patch until Monday, in the meantime try cider or cider-bin packages.

**Comment by undeadbydawn** [comment]
No probs, I'll switch to -bin for the weekend.


> Unfortunately I can’t make a patch until Monday, in the meantime try cider or cider-bin packages.

No probs, I'll switch to -bin for the weekend.
Cheers

**Comment by undeadbydawn** [comment]
Update 14-1 works perfectly, so I'm closing this issue
