### ISSUE TITLE
[BUG] wrong song being displayed

### ISSUE THREAD

**Issue by nanopone** [ciderapp/Cider#148]
**Describe the bug**
cider sometimes shows the wrong song being played in both the app and the discord presense. it appears to happen to songs that do not exist on apple music but only exist in the user's icloud music library.

**Screenshots**
actual song in my library:
![image](https://user-images.githubusercontent.com/49787675/149998474-832b72bd-eb48-4e3f-bb24-abab3a44a718.png)
what is being displayed:
![image](https://user-images.githubusercontent.com/49787675/149998481-983ded3b-2c7c-4db6-a5c3-876139c3aa24.png)
![image](https://user-images.githubusercontent.com/49787675/149998494-a49ed85b-c5c6-4c27-9a94-54504a317c3e.png)

**Environment Information**
 - OS windows 10
 - Application Version 1.0.4.0
 
**Additional context**
the song (and entire album) in the screenshots doesn't exist on apple music. i uploaded it to my cloud music library.

**Comment by motz0815** [comment]
can confirm, although in my case the song (which also is just in icloud, not apple music) appears to be right in the app, although not so in the discord RP.
