### ISSUE TITLE
[Bug]: Cider-git Build fail

### ISSUE THREAD

**Issue by undeadbydawn** [ciderapp/Cider#1480]
### Describe the Bug

```
./resources/version.sh: line 40: $GITHUB_ENV: ambiguous redirect
./resources/version.sh: line 41: $GITHUB_ENV: ambiguous redirect
==> ERROR: pkgver is not allowed to contain colons, forward slashes, hyphens or whitespace.
==> ERROR: pkgver() generated an invalid version: 1.5.8.beta.30
1.5.8.beta.030
error: failed to build 'cider-git-1.5.8-5': 
error: packages failed to build: cider-git-1.5.8-5
```

### Steps to Reproduce

running paru -Syu in Arch

### Environment Information

- OS: Arch, kernel 6.0
- Desktop Environment: KDE
- App Version: Cider-git 1.5.8-5
- Commit ID:

### How did you download the software?

AUR

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
@coredev-uk lol

**Comment by coredev-uk** [comment]
Follow the support disclaimer in future. It states clearly on the aur that this issue has been since resolved.

**Comment by undeadbydawn** [comment]
> Follow the support disclaimer in future. It states clearly on the aur that this issue has been since resolved.

Noted.
this morning's build works just fine
