### ISSUE TITLE
Playing Music Videos breaks the whole app

### ISSUE THREAD

**Issue by KillerParticles** [ciderapp/Cider#1482]
### Describe the Bug

If you play a music video in Cider, you will no longer be able to play any song/music video or radio station at all anymore after you close the video or it ends, the only way to fix it is to restart the app.

What should of happened is after the song ends, i can play another song or video.

### Steps to Reproduce

1. Open Cider
2. Play any music video
3. Wait for it to finish or close the video manually
4. Try to play another music video or song

### Environment Information

- OS: Windows 11 22H2
- Desktop Environment: 
- App Version: v1.5.8.beta0.32
- Commit ID:

### How did you download the software?

GitHub

### Anything else?

https://user-images.githubusercontent.com/93286201/193888948-c92501bb-53b8-4738-acbc-551e8243ac36.mp4

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by vapormusic** [comment]
Hmm doesnt happen to me
