### ISSUE TITLE
[Bug]: lots of plugins does not work with store version of cider.

### ISSUE THREAD

**Issue by direrFlood** [ciderapp/Cider#1492]
### Describe the Bug

for example this plugin: https://github.com/lx200916/desktop_lyrics_plugin 
works just fine on cider desktop version
when trying it on cider store version it does not work. this is pretty annoying as i paid for the store version thinking i will get better product and stability. turns out the free one is more stable!

### Steps to Reproduce

1. install desktop lyrics plugin on store and desktop versions of cider
2. compare between both. on desktop the plugin works o store version the plugin does not work

### Environment Information

- OS: w11 22h2 
- Desktop Environment: w11 22h2 
- App Version:
- Commit ID:

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by vapormusic** [comment]
Please contact the plugin maker, we can't do anything with it.
Longer answer: the lyrics plugin you downloaded works by injecting a second Application to cider, which could have been blocked by Microsoft Store Sandbox policy
