### ISSUE TITLE
[Bug]: Every time I restart app i see onboarding screen and need to login again as well

### ISSUE THREAD

**Issue by iamruletik** [ciderapp/Cider#1494]
### Describe the Bug

Every time I restart app i see onboarding screen and need to login again as well

### Steps to Reproduce

1. Just restart the app

### Environment Information

- OS: Windows 10
- Desktop Environment: Asus Notebook
- App Version: 1.57
- Commit ID:

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Did you try a [clean install](https://docs.cider.sh/support/troubleshooting)?

**Comment by 00-XPRT-00** [comment]
got this happening to me aswell

**Comment by SentixDev** [comment]
same here

**Comment by iamruletik** [comment]
> Did you try a [clean install](https://docs.cider.sh/support/troubleshooting)?

I tried. Did't work. But i tried install latest alpha and it's no longer an issue. But stable release still didn't work out for me.

**Comment by icerain9247** [comment]
same for me

**Comment by coredev-uk** [comment]
Just use the latest release for now then. Not sure what would be causing this.

**Comment by Mikolaj-Walkowiak** [comment]
I have the same problem, tried reinstalling to a different drive, clean install, both master and stable branches - nothing. If it helps anything my log in window doesn't close / continue button is doing nothing.
![obraz](https://user-images.githubusercontent.com/33766092/196668827-ac463896-6320-4df6-ab40-a61f4c337a22.png)

**Comment by veilin** [comment]
Same issue here. This is really irritating.

**Comment by fherenius** [comment]
Having the same on Linux. Which branch are the alpha builds? The docs still refer to the `develop` branch but it no longer seems to exist.

**Comment by coredev-uk** [comment]
The main branch is alpha.

**Comment by fherenius** [comment]
Thanks! Then I'm already on the Alpha branch and the issue still exists, unfortunately. 

For reference, it seems Apple at least recognizes it as the same browser since I don't have to enter the verification code every time (only on a clean install). If I remember I'll try to see where it goes wrong :)

**Comment by mbures** [comment]
I also see this. I am using snaps on Ubuntu using the most recent alpha release. I have tried the instructions to do a clean remove and have also removed/reinstalled with the snap --purge option but it has no effect. This has been affecting me for a while. I believe the stable(OLD) version in the snap store works correctly but none of the betas/alphas I have tried since do.

Is there anything that I can check on my system? Files that should stay/be created, etc?

**Comment by mbures** [comment]
Yeah - I tried the --purge option because I don't have an entry in ~/.config for Cider.

**Comment by d0lb33** [comment]
Clean uninstall and 1.5.9 fixed it for me!

Continue button still doesn't close the login prompt though!

**Comment by Mikolaj-Walkowiak** [comment]
For me it's still happening, the initial setup remembers my language/visual/audio settings but I need to click through and login each time I close and open the app.

**Comment by kode54** [comment]
Still happening with 1.5.9-1 from AUR package `cider-bin`, and `cider` package 1.5.9-4. Installing version 1.6.0.beta.67-1 from the `cider-git` package results in an app that won't even open. I have tried deleting `~/.config/Cider` each launch.

**Comment by NeutronicMC** [comment]
The same thing happens to me every time I launch on 1.5.9 with arch linux

**Comment by NeutronicMC** [comment]
Okay, I found the source of the issue. I have a database for development that uses port 9000, and whenever Cider isn't able to bind to that port, it shows the onboarding/login screen. If I do nothing, close Cider, stop the database, and then re-open the Cider, it no longer shows the onboarding screen and behaves like normal. I've tested this multiple times and it behaves this way consistently.

**Comment by Mikolaj-Walkowiak** [comment]
I can confirm it does the same thing for me as well - I have a docker container on port 9000 - when it's active, I see the onboarding screen, and when disabled, it opens up without a login prompt.

Is there a plan to fix this or no chance?

**Comment by fherenius** [comment]
@Mikolaj-Walkowiak @NeutronicMC Nice catch! I looked at the code and I think the issue originates from this line:
https://github.com/ciderapp/Cider/blob/cb3a3053baf51c78538eb1d0a21f34086a563c16/src/main/base/browserwindow.ts#L399

I just tested it by setting the `CIDER_PORT` variable in the terminal from where I was launching Cider to some available port and Cider now works as expected. So there's already a workaround in place!

@coredev-uk Would be nice to add this to the documentation! Ideally of course a check if port 9000 is already taken or not and generating a warning in this case or taking another port. If I have time this weekend I might be able to write a PR for this.

**Comment by coredev-uk** [comment]
Hi, sorry for the lack of responses on this. The team has been fully focused on Cider 2, with a lot of c1 issues being disregarded.
There is already a check in place for the client port to check if it is available, however the range of ports that we check is not that large, thus if 9000 is taken and no environment var is passed it will randomise. I will make a commit making the port a option within the 9000-9999 range.

Other than this, there are a few other areas in Cider where the port is incorrectly set (like in chromecast) which default to 9000. This will be resolved soon.

**Comment by coredev-uk** [comment]
Moving the application to port 0 may work. The original suggestion that I was proposing requires a conversion to node ESM modules, which requires a refactor of the entire repository.
