### ISSUE TITLE
[Bug]: stable branch version.sh warning causes AUR build failure

### ISSUE THREAD

**Issue by ingrinder** [ciderapp/Cider#1495]
### Describe the Bug

When running version.sh (as in the AUR package PKGBUILD, i.e. `GITHUB_REF_NAME=stable ./resources/version.sh`), bash emits the following warnings to stderr:

```
./resources/version.sh: line 39: $GITHUB_ENV: ambiguous redirect
./resources/version.sh: line 40: $GITHUB_ENV: ambiguous redirect
```

This causes a build failure as the warnings are included as part of the package version, making it invalid.

### Steps to Reproduce

1. Run `GITHUB_REF_NAME=stable ./resources/version.sh`
2. Observe the output

### Environment Information

- OS: Arch Linux
- Desktop Environment: KDE
- App Version: n/a
- Commit ID: regression appears to be caused by ec70754a64e37c151d59c0f4967dca80fb35781f

### How did you download the software?

AUR

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
A fix for this issue was made on the main branch, I'll port the commit over to stable in a bit.
