### ISSUE TITLE
[Enhancement] cider on the taskbar on windows 10 has an extremely ugly square icon.

### ISSUE THREAD

**Issue by peepee** [ciderapp/Cider#150]
**Is your feature request related to a problem? Please describe.**
cider as an app is extremely pretty, but i hate looking at this icon. it looks fine everywhere else, it just looks bad on the taskbar.
![image](https://user-images.githubusercontent.com/49787675/150042703-6e548af0-780b-4c17-8439-f246115d4145.png)

**Describe the solution you'd like**
here is a concept which i think looks a lot nicer.
![image](https://user-images.githubusercontent.com/49787675/150042622-18caa637-6d3a-46f2-9302-5964efa6ba87.png)

**Comment by coredev-uk** [comment]
Resolved in develop branch. Await next windows store release.
