### ISSUE TITLE
[Bug]: "Play next" button doesn't work

### ISSUE THREAD

**Issue by artemiskiss** [ciderapp/Cider#1502]
### Describe the Bug

Whenever I am playing a station, the play next function does not work. On iTunes, if you are playing a station, and then right-click on a song>play next, that song is added to the queue. On cider, it doesn't work, and the queue remains unchanged. 

### Steps to Reproduce

1. Played a station.
2. Right-click on song
3. click on play next
4. check current queue

### Environment Information

- OS: Windows 11
- App Version: 1.5.7

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by maikirakiwi** [comment]
I am unable to reproduce this on the latest nightly build. Please check to see if this is still an issue.

**Comment by squarebowl** [comment]
I also have the same issue in the latest stable version.
