### ISSUE TITLE
[Bug]: sometime the cider didn't play songs without v2ray or others

### ISSUE THREAD

**Issue by Tommyfu0603** [ciderapp/Cider#1505]
### Describe the Bug

I'll try to explain it as clearly as possible，when i play valorant, a few mintues later, cider  is stop playing songs, i press so many times play buttons and it doesn't work

### Steps to Reproduce

1. play songs 
2. wait for the song to finish playing
3. the next song can't play with no reason

### Environment Information

- OS: windows11 21H2
- Desktop Environment:  omen16 
- App Version: 1.5.7.7040
- Commit ID: 

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by maikirakiwi** [comment]
登录Cider的时候不要挂梯子不然这样你放歌的时候就需要一直挂着。

Avoid using proxies while authenticating with MusicKit as that affects the location of the asset server you’re being routed to.
