### ISSUE TITLE
[Bug]: Loading System for Song Previews is Too Agressive

### ISSUE THREAD

**Issue by TriVoxel** [ciderapp/Cider#1507]
### Describe the Bug

This issue was hard to name. What I mean is that it is very apparent Cider has been designed to be very lightweight. As such, it seems to only load the content in albums and playlists that is displayed on-screen, and then loads and unloads this content as you scroll. This makes a lot of sense. However, it seems that Cider ONLY keeps content loaded that is in the viewport. This means that as you scroll, the program has to load the album art and song titles on the fly which leads to a noticeable gap between user input and display output. This is especially noticeable in long playlists with lots of album art and artists. The proposed fix is for the program to load further than the view area by about 1-3 pages in both directions. This may slightly raise memory usage, but the payoff is a more seamless experience for the user as songs appear to all be loaded, even though they in fact are not. This will help massively for people with large playlists who want to quickly scroll through them without outpacing the program's capacity to load content.

### Steps to Reproduce

1. Create a large playlist (or use mine https://music.apple.com/us/playlist/gems-rocks/pl.u-gxblk8DFbL9yPDo)
2. Scroll up and down quickly, paying attention to the song titles lower on the list. They will likely appear to be blank until the program has time to load them in.

### Environment Information

- OS: macOS Monterey
- Desktop Environment: macOS
- App Version: 1.5.7
- Commit ID: N/A

### How did you download the software?

GitHub

### Anything else?

https://user-images.githubusercontent.com/25536957/194996700-d8dfe323-ff80-4d6f-ad58-d495645f9cf3.mov

https://user-images.githubusercontent.com/25536957/194991255-0f900246-d9f1-481b-9957-fffa989c334d.mov

The official Apple Music does something like this. You will see it loads ahead of my scrolling, but I can beat the loading system by scrolling fast enough. What I especially like about how Apple Music loads its list, however, is how it loads the artist name, album title, and track time before the album art so that you can always get a sense of where you are in the list. It seems Cider waits to display that information until the album art is loaded. I think if Cider could pre-load a lot of the track information (excluding album art), and then load some album art ahead of the view area, it would make the program feel a lot more responsive and high quality.

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by maikirakiwi** [comment]
This is really a balance between performance and RAM usage. For the general public, it is clear that more people are on older hardware that serves the purpose of both gaming and music listening. We at Cider Collective wants to make the app as inclusive as possible and so we went with the optimized route. However, power options will be available for Cider 2.x that will include more aggressive caching and etc. So get excited for 2.x I guess!

**Comment by maikirakiwi** [comment]
Also keep in mind our codebase for 1.x is Vue + Electron
Chromium can only run so fast against a native app lmfao.
