### ISSUE TITLE
[Bug]: Background Blur Not Working Properly (macOS only)

### ISSUE THREAD

**Issue by TriVoxel** [ciderapp/Cider#1508]
### Describe the Bug

In macOS, the settings window does not seem to handle blur correctly. It blurs the background, but also appears to have a transparency that allows the main window behind the settings window to appear subtly without any blur. This allows you to read the text clearly behind the settings window which distracts from the function of said window.

### Steps to Reproduce

1. Open the app's settings by clicking "Cider" in the menu bar, and clicking "settings"

### Environment Information

- OS: macOS Monterey (v12.6)
- Desktop Environment: macOS
- App Version: 1.5.9-beta.20 & 1.5.7 stable
- Commit ID: N/A

### How did you download the software?

GitHub

### Anything else?

<img width="1440" alt="Screen Shot 2022-10-10 at 10 07 06 PM" src="https://user-images.githubusercontent.com/25536957/194994916-e15fa60b-8ce2-4fd5-9bfa-5d99e8820238.png">

Keep in mind, I have no plugins and am running with default settings. This bug does not appear to affect the Linux version available through Flathub.

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by TriVoxel** [comment]
Any progress? (stale)

**Comment by cryptofyre** [comment]
This is kinda just how Electron works on macOS.

**Comment by TriVoxel** [comment]
@cryptofyre Fair enough. macOS tends to suck at graphics anyways. Thanks for looking into the issue!
