### ISSUE TITLE
MusixMatch Lyrics and translations are broken since Apple Lyrics has been reenabled

### ISSUE THREAD

**Issue by KillerParticles** [ciderapp/Cider#1511]
### Describe the Bug

Confusing title but bascially since you guys re-enabled lyrics from Apple as default, MusixMatch lyrics and translations do not work. I am not sure if these are related however version 1.5.9.021, which has Apple Lyrics by default, MusixMatch lyrics do not translate at all, whereas version 1.5.9.02, a build before Apple lyrics was enabled again, Lyric translations work as intended. Which leads me to the conclusion that since Apple Lyrics was reenabled, it might of broken MusixMatch lyrics and translations.

### Steps to Reproduce

1. Use latest build from Github
2. Enable MusixMatch lyrics and set translation language
3. Play a song that has translated lyrics
4. View lyrics and see no translated lyrics

### Environment Information

- OS: Windows 11 22H2
- Desktop Environment: 
- App Version: 1.5.9.021
- Commit ID:

### How did you download the software?

GitHub

### Anything else?

As I said, if you try a version of Cider before Apple Lyrics was enabled again, lyric translations work fine and as intended, so the problem has to be because of that.

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
I used translations yesterday just fine, unsure why your hitting this issue.

**Comment by vapormusic** [comment]
> I used translations yesterday just fine, unsure why your hitting this issue.

Must be that Apple Music has 0 lyrics for that song

**Comment by vapormusic** [comment]
fixed in 9622814ebf3e31f5d812871d06fdf8a29196fbbb

**Comment by KillerParticles** [comment]
Thank you Vapour it works fine now. This issue is now closed.

**Comment by KillerParticles** [comment]
Hello, please reopen this as it looks like Deja vu has happened and this is now broken again.

**Comment by vapormusic** [comment]
> Hello, please reopen this as it looks like Deja vu has happened and this is now broken again.

blame new api server.

**Comment by KillerParticles** [comment]
New MusixMatch API? Can this be worked around?
