### ISSUE TITLE
[Bug]: Volume Mixer keeps resetting every time I use Cider

### ISSUE THREAD

**Issue by Trend-Net** [ciderapp/Cider#1512]
### Describe the Bug

Whenever I open or use Cider the volume mixer automatically resets to 100%. I keep setting it at 20% but after a while or if I reopen the app it gets reset back to 100% and then I have to lower it again manually.

![ApplicationFrameHost_RjvW4gmGg8](https://user-images.githubusercontent.com/115723916/195650836-e7bc0550-c229-4873-af60-14c22c33a850.png)

### Steps to Reproduce

1. Lower Cider's volume in the volume mixer (typically to 20%).
2. Close Cider.
3. Reopen Cider.

### Environment Information

- OS: Windows 11 Pro, Version 22H2, Build 22621.608
- App Version: 1.5.8

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by Trend-Net** [comment]
The issue has been solved.

**Comment by nazsol** [comment]
> The issue has been solved.

How did you solve it?

**Comment by Trend-Net** [comment]
> > The issue has been solved.
> 
> How did you solve it?

Just updated to one of the beta builds and it was fixed. I think it was Version 1.5.9-beta.39, but I wouldn't use that version now, there's much newer versions. Like this one: [https://github.com/ciderapp/cider-releases/releases/tag/v1.5.9](url).
