### ISSUE TITLE
[Translation]: Inappropriate font / glyph of Simplified Chinese characters

### ISSUE THREAD

**Issue by amorphobia** [ciderapp/Cider#1523]
### Relevant Language

zh_CN

### Change or Addition or Both

Change a Language

### Change Requested / Any Additional Information

I set the language to `zh_CN`, but the font family is for Japanese. For most characters it's OK, but some are different. For example, the character [`门`](https://en.wiktionary.org/wiki/%E9%97%A8) (U+95E8), the glyph in `zh_CN` is:
![图片](https://user-images.githubusercontent.com/523025/196314712-57f2d683-0485-4ccc-8f79-635538c561e6.png)

But in the app, Japanese glyph is used (the glyph of [`今`](https://en.wiktionary.org/wiki/%E4%BB%8A) (U+4ECA) is neither for `zh_CN`):
![图片](https://user-images.githubusercontent.com/523025/196314796-eebb984d-68c2-42dd-b120-38f07e98ef0b.png)

I think it's because the same font is used for all CJK languages. Maybe it's better to use dedicated font for each language.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amorphobia** [comment]
anyone have a look?

**Comment by antcar0929** [comment]
It's still a problem
