### ISSUE TITLE
[Bug]: Failed to Load "api.music.apple..." preventing playing from Library and loading of Listen Now

### ISSUE THREAD

**Issue by Supplex44** [ciderapp/Cider#1526]
### Describe the Bug

As title says, I checked the console and it says 98 errors, but specifically a LOT of errors communicating with "https://amp-api.music.apple.com/v1/storefronts/undefined" and a lot others from music.apple. 

The effect of it is that I can not play anything from the library even though it loads the artwork and displays all my playlists correctly. HOWEVER, I can play music from the "Radio" and "Browse" tabs. But the "Home" and "Listen Now" tabs are both useless, Listen Now doesnt even have a loading animation so its just empty, which is only a little worse than the loading bars in Home that just spin.

This happens every single time I open the program. Whats really weird is that re-installing fixes it for THAT session, but the next bootup and its back to being useless. THIS PROGRAM WORKS SO WELL WHEN IT DOES, its so frustrating. 

I am using the Windows installer version from Github, the latest stable release I believe.
Is the Windows Store version better in some obvious way?
Does Apple just not like remembering my password? 

I feel like there is a simple solution since nearly all of the errors in the console are that ONE address.

Thoughts?

### Steps to Reproduce

1. Litterally just open the program.
2. profit, of lack thereof.

Seriously, i just open it, it loads breifly and I then I can see my library but when click an albums play button nothing happens and if I enter the album and click play it still wont work despite loading just fine.

I saw the console fill up with errors after loading.

UPDATE: Sometimes it loads correctly and I dont know why. But in these instances it just opens like day 1, as if it wasnt just refusing to load for a week straight.

### Environment Information

- OS: Windows 11 22H2 x64
- App Version:  1.5.7

- Bogos: Binted

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by cryptofyre** [comment]
Sometimes MusicKit complains about "&" signs in URL's and such for obvious reasons. We're looking into a temporary fix for this.

**Comment by maikirakiwi** [comment]
Please include the region of your Apple ID

**Comment by Supplex44** [comment]
My region is Canada!

Recently i purchased the Windows store edition. In trying it I have found new and quirky versions of this issue. It just doesn't open, it is stuck in the logo pre-screen. I just force quit and re-open to make it work flawlessly.

**Comment by Supplex44** [comment]
*Bump*

this does still happen on nearly every occasion I launch Cider. It Takes about 3-10 tries to get it to actually open. 

It is very frustrating since it’s impossible to close while in this failed launch state so I have to kill every task individually through Task Manager. 

I understand this takes time to fix and isn’t a priority. I’m just keeping this open so the issue isn’t assumed fixed 🤷
