### ISSUE TITLE
[Bug]: Cider doesn't load without access to google domains

### ISSUE THREAD

**Issue by moenodedev** [ciderapp/Cider#1530]
### Describe the Bug

The Cider app doesn't load on MacOS without access to googleapis.com, google.com, gvt1.com, and other google domains.

### Steps to Reproduce

1. Launch the Cider app when the Little Snitch firewall is installed
2. Don't allow any requests to google domains because music content and data is hosted on Apple servers
3. The main window doesn't show

### Environment Information

- OS: MacOS
- Desktop Environment: MacOS
- App Version: 1.5.7

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by moenodedev** [comment]
The purpose of the MacOS build of Cider seems to be for people that also have non-MacOS devices and want the same Apple Music UI across multiple OSes. If all of your desktop devices are MacOS (not Windows or Linux) then it's probably better to use the built-in Music app for MacOS. Otherwise you're going to be compromising your privacy because Cider sends data to Google.

**Comment by vapormusic** [comment]
Huh? There is no telemetry, just google fonts. You are just overreacting i think.

**Comment by quacksire** [comment]
You can look all over the source code, it’s just fonts, nothing more.

**Comment by cryptofyre** [comment]
Pretty odd that you would complain about us "giving data to google" despite not even bothering to check the source.
