### ISSUE TITLE
[Bug]: No lyrics / lyrics button not working

### ISSUE THREAD

**Issue by pkpnr** [ciderapp/Cider#1531]
### Describe the Bug

Hi! Apparently after using Cider a while from v1.5.6, the lyrics feature does not seem to load after restarting the program or a system restart. I cannot click the lyrics button as it is greyed out, even though when lyrics are present on a specific song via the Apple Music mobile app or iTunes. 

### Steps to Reproduce

1. Selecting a song with existent lyrics
2. Clicked the lyrics button, but it is greyed out

### Environment Information

- OS: Windows 11 Home Single Language
- App Version: 1.5.7

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by KillerParticles** [comment]
For Cider v1.5.6, something technical on the backend changed and made lyrics not function, so you need to update your Cider to the latest version for Lyrics to work again.

Basically, just update your Cider to the latest version and lyrics will work again.

**Comment by pkpnr** [comment]
Hi, @KillerParticles! The bug occurred on Cider v1.5.7, which is also the latest stable build I am on, so updating it to the latest version would not solve the issue as I am on the latest version right now. Should I switch to the beta build instead?

**Comment by KillerParticles** [comment]
v1.5.7 is not the latest Cider version, [v1.5.9 is](https://github.com/ciderapp/cider-releases/releases/tag/v1.5.9-beta.056)

**Comment by maikirakiwi** [comment]
Cider now uses official source for lyrics.
