### ISSUE TITLE
[Bug]: No local library in the sider bar.

### ISSUE THREAD

**Issue by RinChanNOWWW** [ciderapp/Cider#1533]
### Describe the Bug

No local library in the sider bar and settings,

I couldn't find the local library page. And I coudn't find any option about it in settings, either.

I did find some settings in `cider-config.json`, but I can't see them on the UI.
![image](https://user-images.githubusercontent.com/33975039/197371741-c816f8ab-9940-4b60-8602-42594eb456e0.png)
![image](https://user-images.githubusercontent.com/33975039/197371748-d3919d68-5c68-4d51-8ac1-597d6ebd4aa5.png)

The log shows the played songs are from the internet even if I have already writtten the settings manually
I want to play songs on my disk which are downloaded from iTunes.

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS: Windows 11 (22H2)
- App Version: 1.5.7 (Stable) / 767d8d7 

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
This was a old feature which was since removed. Your finding must just be old, or the config code wasn’t removed.

**Comment by RinChanNOWWW** [comment]
> This was a old feature which was since removed. Your config must just be old, or the config code wasn’t removed.

So there is no way to play local media?

**Comment by coredev-uk** [comment]
Currently in Cider, no.
