### ISSUE TITLE
[Bug]: Search dropdown transparent over UI

### ISSUE THREAD

**Issue by rzblue** [ciderapp/Cider#1544]
### Describe the Bug

Search results dropdown is transparent over user interface, making text hard to read.

<img width="237" alt="image" src="https://user-images.githubusercontent.com/13878527/198858441-3ff96e11-963c-4c35-ab9f-89d10c89347f.png">

### Steps to Reproduce

1. Click on search bar
2. Start typing a search term

### Environment Information

- OS: Windows 11 (10.0.22621 Build 22621)
- Desktop Environment: n/a
- App Version: tested on 1.5.7 and 1.6.0
- Commit ID:

### How did you download the software?

Winget (Nightly)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Not really sure about this one, seems the backdrop blur filter is not being correctly applied. This will need to be looked into more for something to be done.

**Comment by coredev-uk** [comment]
Sure, go ahead. We're no longer actively developing Cider 1, so pull requested are welcomed

**Comment by iprasandeep** [comment]
> 

Hi! @coredev-uk please provide setup documentation, I am not able to run setup on my machine.

**Comment by coredev-uk** [comment]
We no longer use Slack, feel free to join the [Discord server](https://discord.gg/AppleMusic) and ask if have any issue. As for setting up the app, all the information you should need can be found [here](https://cider.gitbook.io/welcome-to-gitbook/).

**Comment by iprasandeep** [comment]
@coredev-uk Alright!, I want to work on Cider 2, but for Linux(Ubuntu) where could I get Cider 2 Image for testing? Or please give me access link to opened issue for Cider 2.

**Comment by coredev-uk** [comment]
@iprasandeep of you could join the Discord and open a ticket. As Cider 2 is currently closed source, we would need to invite you onto the team if you are interested on working on Cider 2. The application process is currently handled through tickets on the Discord where we will discuss it further.

**Comment by quacksire** [comment]
You can join us [here](https://discord.gg/applemusic) where we can open a ticket and discuss open positions and skills needs.

**Comment by iprasandeep** [comment]
> You can join us [here](https://discord.gg/applemusic) where we can open a ticket and discuss open positions and skills needs.

Thanks, Excited! to be part of the Cider-2 dev team.
