### ISSUE TITLE
[Bug]: Library not Appearing

### ISSUE THREAD

**Issue by Sheffdrum** [ciderapp/Cider#1545]
### Describe the Bug

A bug happened!

I’m using the ‘Cider’ app designed for people who have an Apple Music account but who do not have an Apple device. 

When I sign in to cider on my laptop everything seems to be functioning but the songs and albums that i’ve saved [by using the apple music app on my android phone] are not present and if i try to search for something nothing happens, the app seems to be dead.

i’m using linux mint os and i downloaded the app from the mint repository.

i can use apple music in a browser but it seems to be bug prone.

any suggestions? 

### Steps to Reproduce

1. present from the start

### Environment Information

- OS:
- Desktop Environment: 
- App Version:
- Commit ID:

### How did you download the software?

Flathub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by quacksire** [comment]
Please provide desktop environment, and app version (or commit ID) found on the About page. This helps use to narrow down issues that you are facing.

**Comment by Sheffdrum** [comment]
Thanks for your swift reply.


I’m using Mint with the MATE desktop environment and the cider app is version 1.5.1-3631


I also have a laptop using Linux Mint with the Cinnamon environment and cider doesn’t work on that either.

**Comment by coredev-uk** [comment]
You are on an extremely outdated version of Cider. Update it and in future please fill out the bug report correctly, providing all the relevant information in the environment information section and a appropriate title.

**Comment by Sheffdrum** [comment]
I downloaded the 1.5.9-amd64 version and it works.

The version that I was previously using  - 1.5.1-3631 - is the one available for download in the Linux Mint Software Manager. 

Many Thanks.
