### ISSUE TITLE
[Bug]:  Remote QR not working

### ISSUE THREAD

**Issue by thedogmaniac** [ciderapp/Cider#1546]
### Describe the Bug

When I try to scan the remote QR code, I get sent to the webbrowser with my IP and the Port, but nothing happens.
I am not using a VPN and my port forwarding is enabled.

### Steps to Reproduce

1. Clicked on Web Remote
2. Scanned QR Code
3. Get sent to an empty webpage which loads forever and then throws an error about not being able to connect

### Environment Information

- OS: Windows 11
- Desktop Environment: 
- App Version: 1.5.9 (I do not know about a beta, it just says 1.5.9
- Commit ID:

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
When you click on Remote in Cider, there should be a copy to clipboard option, click that and paste it in the url bar in your browser. It should take you to the remote. (The copy to clipboard function may only give you a port in which case you would need to do localhost:PORTNUMBER as url)

**Comment by thedogmaniac** [comment]
Hey there, thanks for the quick response, it works on my pc, but not on my
phone if I do it the way you told me.
Is that a common issue?

Regards

**Comment by thedogmaniac** [comment]
Btw, I am going to donate soon, but I don’t have a lot of money at the
moment. I love cider and everything you’re doing for it, and want to thank
you for your amazing work. I wish there were more TestFlight openings.

Regards

**Comment by coredev-uk** [comment]
Is your phone on the same network as your PC?

**Comment by thedogmaniac** [comment]
Yes it is.

**Comment by thedogmaniac** [comment]
I’ll try to add an outbound firewall rule for the program, maybe that’ll
work.

**Comment by thedogmaniac** [comment]
It still doesnt work, did you find out something on your end?

**Comment by maikirakiwi** [comment]
This is a LAN issue and we cannot do anything on our end.
What I can say is check if communication between devices connected to your router is allowed and make sure to disable private relay if you use it.
