### ISSUE TITLE
[Bug]: App resetting itself

### ISSUE THREAD

**Issue by Big-Guns** [ciderapp/Cider#1547]
### Describe the Bug

On reboot of the computer the program essentially resets, you need to login and select a theme and language again, I have not investigated to see if this extends to all settings. (Such as Cider Audio Lab)

### Steps to Reproduce

Open Cider, set a language, theme, login, etc.
Shut down your computer (With Cider still open)
Power on your computer
Login
Open Cider
Cider will have reset

### Environment Information

- OS: Windows 11 Home
Version: 22H2
Installed on	: 2022-‎10-‎01
OS build: 22621.755
Experience: Windows Feature Experience Pack 1000.22636.1000.0

- Desktop Environment: N/A
- App Version: 1.5.9-beta.52
- Commit ID: Unknown 

### How did you download the software?

GitHub

### Anything else?

I have tried Re-Installing.
I have checked to ensure its not ransomware protection interfering somehow.

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Try uninstalling and deleting %appdata%/Cider then reinstalling and logging in.

**Comment by Big-Guns** [comment]
That fixed the reset bug, however, I found a different bug in the process. Should I report it here or open another issue?
