### ISSUE TITLE
[Bug]: Login Window does not close

### ISSUE THREAD

**Issue by Big-Guns** [ciderapp/Cider#1548]
### Describe the Bug

When you log in to Apple, the Sign in With Apple window doesn't close after you finish logging in.

### Steps to Reproduce

Remove Cider from the machine
Install [Cider](https://github.com/ciderapp/cider-releases/releases/tag/v1.6.0) (v1.6.0) (I have it installed for all users, not sure if it makes a difference)
Setup and login as usual (In windowed mode, not full screen)
Login with Apple windows will not close when you finish logging it

### Environment Information

- OS: Windows 11 Home
Version: 22H2
Installed on: 2022-‎10-‎01
OS build: 22621.755
Experience: Windows Feature Experience Pack 1000.22636.1000.0

- App Version: [https://github.com/ciderapp/cider-releases/releases/tag/v1.6.0](https://github.com/ciderapp/cider-releases/releases/tag/v1.6.0)

- Device Specifications:
Processor: 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
Installed RAM: 16.0 GB (15.7 GB usable)
System type: 64-bit operating system, x64-based processor
Graphics: Intel Iris XE

### How did you download the software?

GitHub

### Anything else?

  -

### Code of Conduct

- [x] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

EDIT: Screenshot Addition:

![The next cider bug](https://user-images.githubusercontent.com/92866410/199290622-ee0e1954-d5cc-4f14-9095-35cc3f701cc0.jpg)

**Comment by quacksire** [comment]
Just press the X at the top right of the login window. Shouldn't be that difficult.

Sometimes Apple is buggy with the Continue button, we cannot control its behavior.

**Comment by Big-Guns** [comment]
It's not that is can't be closed, however it's a bug none the less.

**Comment by quacksire** [comment]
we cannot control the window's behavior.
