### ISSUE TITLE
[Bug]: Cider does not respect Window Snapping on Windows 10

### ISSUE THREAD

**Issue by meechgalhuquot** [ciderapp/Cider#1549]
### Describe the Bug

One of the features of PowerToys is to be able to snap windows to custom sizes, on Windows 10 it does not seem to respect this behavior, nor does it seem to respect snapping to window edges.

https://user-images.githubusercontent.com/52185596/199418265-9e3c262c-6e9f-44a2-872d-e74fa0bda9bc.mp4

### Steps to Reproduce

Attempted to use the built in Windows 10 snap to edge of screen as well as a third party tool named Microsoft PowerToys to snap the program to a custom window size, Cider completely ignores the resizing of the program

### Environment Information

- OS: Windows 10 build 22H2

- App Version: 1.6.0 Nightly, issue also present on older stable builds

### How did you download the software?

Winget (Nightly)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
update
