### ISSUE TITLE
[Bug]: Cider doesn't work after wake from sleep

### ISSUE THREAD

**Issue by Ilovemyhous** [ciderapp/Cider#1552]
### Describe the Bug

Basically, playback doesn't work anymore after waking the computer up from sleep.

https://user-images.githubusercontent.com/50217071/199823951-4b9f3989-7db5-44a4-88cd-af69c5fef1ce.mp4

### Steps to Reproduce

1. Play some media.
2. Put your computer to sleep.
3. Wake it up.

### Environment Information

- OS: EndeavourOS (Kernel 6.0.6-zen1-1-zen)
- Desktop Environment: Plasma 5.26.2
- App Version: 1.5.7

### How did you download the software?

AUR

### Anything else?

/

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by maikirakiwi** [comment]
This is a musickit issue where an inactive session of more than 15 minutes require a client reload.
A fix for this will be implemented in Cider 2.x as we are gradually phasing out support for 1.x.
