### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by seanhfyz** [ciderapp/Cider#1556]
### Describe the Bug

A bug happened!
If the computer sleeps, then after the laptop resumes after sleep, the cider cannot play music properly.

### Steps to Reproduce

1. Start - Power - Sleep
2. Restart windows
3. click any music in cider
4. and you find the music wouldn't play
5. you have to restart cider to resume music playing

### Environment Information

- OS: Windows 10
- Desktop Environment: 
- App Version:  1.5.9
- Commit ID:

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by Swiftzerr** [comment]
Duplicate of #1552
