### ISSUE TITLE
[Bug]: Ping spike when playing a new song

### ISSUE THREAD

**Issue by obito** [ciderapp/Cider#1560]
### Describe the Bug

A bug happened! I was playing League of Legends while having Cider opened. It seems to have a spike of ping (from 15ms to 48-70ms) when I select a new playlist, or playing a playlist in random mode (the cache doesn't work on random mode?).

It does that in every game, and doesn't happens with Spotify desktop client for example or even official Apple Music app.

### Steps to Reproduce

1. Clicked on a Playlist
2. Set it in random mode
3. Skip the song, you will see a huge spike in ping, making the game unplayable for a few seconds (and very annoying in a competitive game like League)

### Environment Information

- OS: Windows 10 Entreprise LSTC (fresh install) - 
- Desktop Environment: 
- App Version: 1.5.9 stable
- Commit ID: 

### How did you download the software?

Chocolatey

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by UnbreakCode** [comment]
there isn't a "full cache" of every song, so it loads the song every time again. It could also be the artwork quality btw
