### ISSUE TITLE
[Bug]: Cider's Stereo audio is unintentionally (?) altered by Windows spatial sound processing

### ISSUE THREAD

**Issue by tox1c90** [ciderapp/Cider#1566]
### Describe the Bug

Even though it's outputting Stereo audio only, the output of Cider is processed by the Windows spatial sound system when either "Windows Sonic for headphones" or "Dolby Atmos for headphones" is enabled, which noticeably degrades the audio quality.

This is an unexpected/unusual behavior, because typically pure Stereo sound is passed through Windows spatial sound system without being processed. This is the case for any other music streaming app I am aware of (e.g., Spotify, Amazon Music, Apple Music in browser...) as well as games or video players when they are set to "2.0" configuration instead of multichannel audio (5.1, 7.1...).
(I was almost ditching Cider shortly after trying it out because I noticed that for some elusive reason the audio quality seemed to be degraded compared to streaming Apple Music in browser.)

While disabling the spatial sound format everytime when streaming music instead of playing games or 5.1/7.1 movies via headphones would be a workaround, it is not really convenient.
As neither Windows Sonic nor Dolby Atmos for Headphones is really meant for adding fake-surround to Stereo sound, but primarily for creating a HRTF-like transformation when fed with *multichannel audio*, I would consider this a bug, although I do not know what the other apps do or dont do in order to get around their Stereo stream to be processed by Windows spatial sound.

### Steps to Reproduce

1. Play some music via Cider
2. Go to Windows sound settings and switch the spatial sound format between none and either Windows Sonic or Dolby Atmos
3. When doing this with other music or video players outputting Stereo sound, the audio is not affected at all, but the Cider audio is strongly altered.

### Environment Information

- OS: Windows 11 22H2 (Build 22623.891)
- App Version: 1.5.9

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by lilmothe** [comment]
Just tried it. Same here. although I haven't updated Cider in a while, Going to comment my experience after an update.

**Comment by maikirakiwi** [comment]
This seems like a Chromium issue rather than a Cider one.
Since we don’t handle audio routing in any shape or form because chromium does.
They have most likely fixed this in a later chromium build—incorporated by a newer beta from us—thus this should no longer be an issue. 
In any case I highly suggest you try out our in house spatialization found under audio lab that’s more tuned for modern compressed music.
