### ISSUE TITLE
[Bug]: Having Cider idling interrupts Music playing on other devices

### ISSUE THREAD

**Issue by 0xricksanchez** [ciderapp/Cider#1569]
### Describe the Bug

The following scenario: I have my laptop idling to e.g. hit the gym or similar, where I still have Cider open (or in the background) with the emphasis on the music being paused.
Now when playing music from a genuine Apple Music client on e.g. a phone/watch or whatever it happens every so often that the music stops playing.

![image](https://user-images.githubusercontent.com/17012133/202456871-91aeafe1-69b0-4a11-bb82-9ecea73ce9f9.png)

I assume that Cider is making some requests to the Apple Music API that causes this.
What's frustrating is that I did not yet figure out when this happens as it seems to happen "randomly". Not every time, sometimes once in like 2 hours, sometimes every couple of minutes..

### Steps to Reproduce

1. Have a device with cider open but music paused
2. Take another device and play music from the Apple Music client
3. Pray to RNGesus to have the above described scenario happen

### Environment Information

- OS: Arch Linux
- Desktop Environment: i3
- App Version: 1.5.9
- Commit ID: 

### How did you download the software?

AUR

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
We don't make idle requests, it must just be that the app is still using MusicKit.

**Comment by 0xricksanchez** [comment]
I can see how that would decrease usability by a lot when having to log in every *X* minutes not playing music in Cider. I don't know the API you're using here at all, so I have no idea what a solution could look like from the technical side. 
I am uncertain if there's something like a `is_playing_on_device()` functionality that could prevent Cider from further usage of MusicKit (if that's the culprit)

**Comment by coredev-uk** [comment]
Yeah the API docs aren't the most helpful, especially when it comes to things like this. I'll take a look to see if we can fix this.

**Comment by rschmukler** [comment]
Just confirming that I also see this behavior on Linux.
