### ISSUE TITLE
[Bug]: Issue with creating playlists and adding songs into them

### ISSUE THREAD

**Issue by sp33dv1** [ciderapp/Cider#1572]
### Describe the Bug

I can create playlists successfully but after creating them, when I try to put some songs into them nothing happens. I tried different songs but they don't appear in playlist. I tried restarting the program but still not working.

### Steps to Reproduce

1. Left panel "create new" under playlist section
2. Named it and it's a brand new empty playlist
3. Searched for a song
4. Then right click to that song "add to playlist" and choose the playlist I just created
5. Nothing happens, playlist is still empty

### Environment Information

- OS: Windows 10 21H2
- Desktop Environment: --
- App Version: 1.5.9
- Commit ID: --

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by JCerro01** [comment]
I have reproduced the steps and it seems like an error 404 is encountered when a song is added to the new playlist
![image](https://user-images.githubusercontent.com/60748895/207171621-3d789b8c-6a33-48ce-8769-6d1a47aad4be.png)

**Comment by ClipLee** [comment]
I have reproduced the steps, and I am having this issue as well. Plus whilst trying to delete playlist it disappears, then when double-clicking existing one it says "syncing" and it brings me back my deleted playlists just empty, no name, image, nothing.
