### ISSUE TITLE
[Bug]: The "Home" view does not load when the app is initially launched. Relaunching fixes it. 

### ISSUE THREAD

**Issue by rob-watts** [ciderapp/Cider#1573]
### Describe the Bug

If Cider has been off for a period of time (not between OS reboots) and I open it, the home screen's content area's loading icons spin forever. If I click a different menu item on the side bar, then return to Home, it does not fix it. 

Closing and reopening the app causes the home screen to load correctly.  This happens every time for me and has been happening for a long time.

![112256](https://user-images.githubusercontent.com/10930683/203351642-de9be1de-d888-4a69-890d-5832afefe81d.png)

### Steps to Reproduce

1. Open Cider to Home view

### Environment Information

- Windows 11
- Cider v1.5.9
- Installed from Microsoft store.

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by AtomicMegaNerd** [comment]
I am having the same issue. Also on Windows 11 and running Cider v1.5.9. I have to restart the app to get it to load the metadata on the home screen correctly. This happens every time I stop using the app for a little while.
