### ISSUE TITLE
[Bug]: Low priority - Windows: Discord RPC does not function with admin privileges 

### ISSUE THREAD

**Issue by AaronLeanage** [ciderapp/Cider#1574]
### Describe the Bug

Cider Discord RPC does not function when Discord is launched with admin privileges but Cider is not.

If both Cider and Discord are launched with user privileges, no issue occurs.
If both Cider and Discord are launched with admin privileges, no issue occurs.
Only if Cider is launched with no admin privileges but Discord is does it not update.

Usually I would put this down to the difference in user profile running the process, however, other games that also do not run as admin have no issue with displaying a rich presence in Discord. This is the reason for the bug report.

### Steps to Reproduce

1. Launch Discord with admin rights and open Cider
2. Turn on Discord RPC
3. No update in Discord

### Environment Information

- OS: Windows 10 Build 21H2
- Desktop Environment: N/A
- App Version: 1.5.7
- Commit ID: N/A

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by down-bad** [comment]
This is how Discord works. Not Cider's fault

**Comment by afland** [comment]
Why would you launch discord with admin privileges?
