### ISSUE TITLE
[Bug]: RAM/Memory Leak v1.5.9 (Microsoft Store)

### ISSUE THREAD

**Issue by tosunkaya** [ciderapp/Cider#1581]
### Describe the Bug

When i play Apple Music Radios on Cider 1.5.9 (Microsoft Store) for some hours, RAM usage is nonstop increasing like 3-5GB. There was no problem on 1.5.8 or earlier. RAM usage was normally ~250MB.
<img width="324" alt="image" src="https://user-images.githubusercontent.com/12996767/204247784-ff5db3c5-e48e-4e3c-b728-c9a32881aa86.png">

### Steps to Reproduce

1. Play any Apple Music Radio on Cider
2. Close it (background play is on/"Close button should hide the application" setting is on from "Visual)
3. Play in background for 1-2 hours

### Environment Information

- OS: Windows 11 Pro 22H2
- Desktop Environment: 22623.891
- App Version: 1.5.9 Microsoft Store

### How did you download the software?

Microsoft Store

### Anything else?

after i write this bug here is the increased RAM usage:

<img width="323" alt="image" src="https://user-images.githubusercontent.com/12996767/204249252-0c33ebb7-cef7-49c1-bc3e-9ef3827e78a6.png">

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/12996767/204249521-430ca551-8e72-4de0-a670-72510953d1d8.png">

### Code of Conduct

- [x] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by kp-hub** [comment]
I definitely see this issue as well.  Just running the app.
![image](https://user-images.githubusercontent.com/3271031/206580405-f0f27201-fbb1-47a6-9fe0-08bb2a64e64d.png)

Once memory get high enough I notice audio pops as well.

**Comment by kp-hub** [comment]
Testing the app a few times for an hour with music playing, I observed memory use increasing ~ 50-60 MB per min.  Or ~ 3 GB / hour.

**Comment by JarJarBeatyourattitude** [comment]
Hopefully this gets fixed soon
