### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Vyshak1510** [ciderapp/Cider#1585]
### Describe the Bug

![image](https://user-images.githubusercontent.com/75685443/205037036-00b0cf74-81e1-4b0b-8cab-304c7d2d315b.png)
is the search supposed to be transparent? 

### Steps to Reproduce

1. Clicked on search
2. searched for a song/artist
3. found the drop box with the song but was transparent

### Environment Information

- OS: windows
- Desktop Environment: 
- App Version:
- Commit ID:

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Bug should be resolved as of latest beta release. Update using the GitHub release if you wish to have this resolved.
