### ISSUE TITLE
[Bug]: Light Mode Not Working

### ISSUE THREAD

**Issue by Deathbyteacup** [ciderapp/Cider#1590]
### Describe the Bug

When setting the theme mode to System or Light mode, the app remains in dark mode.

### Steps to Reproduce

1. Clicked on... settings > visual > Display Style set to "Light" or "System" when the system theme was in light mode.

### Environment Information

- OS: Windows 11 22H2 22621.819
- Desktop Environment: 
- App Version: 1.6.0
- Commit ID:

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by KillerParticles** [comment]
Not technically a bug, Cider by default does not support light mode, you need to use a theme that supports it, such as iTheme for example.

That toggle in Cider is to force a theme, like iTheme, to use either light, dark or system theme.

**Comment by ryanpcmcquen** [comment]
Are there any plans to add a light theme in Cider 2.x?
