### ISSUE TITLE
[Bug]: Space bar

### ISSUE THREAD

**Issue by hannelock** [ciderapp/Cider#1591]
### Describe the Bug

when using the space bar for pause/play, it does not function as expected. Sometimes it redoes my last action (start playing the last song I manually started playing instead of pausing the now playing song), and sometimes it does 'nothing'.

### Steps to Reproduce

1. Start playing a song (1)
2. the next song (2) in queue starts playing (while I am working in other softwares)
3. I go back to Cider and press space bar (expecting it to pause song (2)
4. Song (1) starts playing from the beginning

### Environment Information

- OS: Ventura 13.0.1
- Desktop Environment: 
- App Version: 1.5.9
- Commit ID: 

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by ricci2511** [comment]
I was able to reproduce this. Quick checking the code I think I found the source of this issue, so when I have time later today or tomorrow and everything works fine I'll do a pr.

**Comment by cryptofyre** [comment]
oof email client ate that one up.

**Comment by Swiftzerr** [comment]
skill issue

**Comment by hannelock** [comment]
This issue still seems unresolved to me.
