### ISSUE TITLE
[Bug]: Cannot login / Network Error / Problem Connecting

### ISSUE THREAD

**Issue by tearfulDalvik** [ciderapp/Cider#1594]
### Describe the Bug

After entering apple id and password from the welcome wizard, the app shows that there is a network error. There is actually no network problem. 

### Steps to Reproduce

1. Open the app for the first time
2. Sign in using apple id
3. Fail
5. ![pic](https://i.ibb.co/hDHNqgd/20221207-223420.png)

### Environment Information

- OS: Windows 11
- Desktop Environment: 
- App Version: 1.6.0
- Commit ID:

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by KateTop** [comment]
same for me

**Comment by iwenbin** [comment]
yes,i‘m also meet this problem

**Comment by electricccat** [comment]
same for me

**Comment by Fluqzy** [comment]
same here

**Comment by markoelprototipo** [comment]
Same for me :(

**Comment by coredev-uk** [comment]
We're aware of this issue and are trying to resolve it. Keep and eye on our Twitter or Disord for updates.

**Comment by coredev-uk** [comment]
Restart your clients, and login should work.
