### ISSUE TITLE
[Bug]: Cannot access the login page 

### ISSUE THREAD

**Issue by yaoshiu** [ciderapp/Cider#1595]
### Describe the Bug

I have tried installing Cider on flatpak and aur, but neither of them work properly on my system. The same problem is that when I first open Cider and follow the prompts to the 'Sign in with Apple Music' page, no login page pops up, it's completely blank.

### Steps to Reproduce

1. Install Cider by `yay -S`
2. Open Cider

### Environment Information

- OS: Manjaro
- Desktop Environment: KDE Plasma 5.26.4
- App Version: 1.5.9-4

### How did you download the software?

AUR

### Anything else?

![Screenshot_20221208_144314](https://user-images.githubusercontent.com/56054933/206376901-bc572642-2d78-4abc-a271-3dbd799c28fb.png)

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by KateTop** [comment]
same to me

**Comment by PlaneTraveller** [comment]
Same here. If I proxychain it, it throws the following error:
```
[15:25:42.300] [info]  From here can you check for real changes, the initial scan has been completed.
[15:25:42.300] [info]  Cider client port: 9000
[15:25:42.301] [info]  Cider remote port: 6942
[15:25:42.302] [info]  remote broadcasted
[15:25:42.384] [error] (node:68670) electron: Failed to load URL: http://localhost:9000/ with error: ERR_CONNECTION_RESET
(Use `cider --trace-warnings ...` to show where the warning was created)

```

**Comment by Lamb666** [comment]
Same for me! I use the flatpak version on Pop_OS.

**Comment by maikirakiwi** [comment]
Something is taking up said ports used by Cider

**Comment by PlaneTraveller** [comment]
This is not solved. I checked port 9000 and 6942, and found that only cider is listening at 6942, and nothing is occupying 9000. Please give a few pointers for why it shows a blank page at login.

Any help would be appreciated!

**Comment by mikob** [comment]
Getting this too. Linux Mint 21.1 deb install.

**Comment by Palm1ye** [comment]
Getting this too. MacOS Ventura 13.3, DMG install via website.

**Comment by hopolapopola** [comment]
Also getting this issue, on Endeavour OS. Installed via the pkgbuild on the AUR, checked with `ss` that nothing else is using 6942 or 9000 - only cider was listening on 6942 and nothing was using port 9000 at all (not even cider itself)
