### ISSUE TITLE
[Bug]: MusicKit MEDIAPLAYBACKERROR

### ISSUE THREAD

**Issue by LuciousLisa** [ciderapp/Cider#1599]
### Describe the Bug

Can't play anything, error is shown in the bottom right of the application:
`MusicKit Encountered an Error: MEDIAPLAYBACKERROR`

### Steps to Reproduce

1. Opened Cider
2. Click music
3. Error

### Environment Information

- OS: Ubuntu 22.04.1 LTS
- Desktop Environment: Gnome 42.5
- App Version: 1.5.9
- Commit ID: N/A

### How did you download the software?

Flathub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by willcl-ark** [comment]
I am having this same error now too on 1.5.9

**Comment by mattnotmitt** [comment]
I was also seeing this but it seems to have gone back to normal now. You both might want to try again?

**Comment by LuciousLisa** [comment]
Confirmed, it seems to be working like normal again. Apologies for prematurely reporting it as a bug! Closing the issue.

**Comment by mattmilano** [comment]
Still an issue on KDE Neon with everything up-to-date. Happening on two computers.

**Comment by eproxus** [comment]
I had this problem on Windows 11 with version 1.5.9 from the Windows Store. A workaround is to go to _Settings_ → _Advanced_ and press _Reinstall WidevineCDM_.

**Comment by Naia-love** [comment]
> I had this problem on Windows 11 with version 1.5.9 from the Windows Store. A workaround is to go to _Settings_ → _Advanced_ and press _Reinstall WidevineCDM_.

It worked, thanks a lot ^^
