### ISSUE TITLE
[Bug]: Failed to start Cider in Windows11

### ISSUE THREAD

**Issue by kindyear** [ciderapp/Cider#1602]
### Describe the Bug

When I installed some plug-ins, I could not restart Cider successfully. I had tried to restart the operating system. I started it in the command window and the following log appeared

![image](https://user-images.githubusercontent.com/34499987/207062532-3e74ff41-a892-4bc0-ab54-30472bc759a6.png)

### Steps to Reproduce

1. Open WebGL
2. Install some plugins(Desktop Lyrics，Change App Icon)

### Environment Information

- OS: Windows 11 22H2 (22621.900)
- Desktop Environment: Windows
- App Version:1.5.9.7498

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by kindyear** [comment]
The problem has been solved by installing "Modify Application icon"

**Comment by coredev-uk** [comment]
If plugins cause issues, you can delete them by going to %appdata%/Cider/plugins and deleting the folder in there.
