### ISSUE TITLE
[Bug]: Wayland Support

### ISSUE THREAD

**Issue by m4gr4th34** [ciderapp/Cider#1603]
### Describe the Bug

No wayland version.  In transitioning to Wayland I found most apps have stable wayland versions (including brave browser etc).  

### Steps to Reproduce

Will not work with nvidia drivers on debian testing, since xwayland does not yet work with nvidia on debian testing.  window shows up as black or garbled.

### Environment Information

- OS: debian testing
- Desktop Environment: plasma kde
- App Version: 1.5.9
- Commit ID: ?

### How did you download the software?

Flathub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Try launching cider with the `--enable-features=UseOzonePlatform --ozone-platform=Wayland` flags.

**Comment by coredev-uk** [comment]
Other than the flags I stated above, support for this will not be worked on in Cider 1.0.
