### ISSUE TITLE
[Bug]: Wrong search width on macOS

### ISSUE THREAD

**Issue by kubai087** [ciderapp/Cider#1608]
### Describe the Bug

Due the difference of the window control button between windows and macOS, the the recommendation window of search container will be covered by about 1/3

Like this:
<img width="1625" alt="iShot_2022-12-14_21 12 51" src="https://user-images.githubusercontent.com/68949228/207604910-43104156-13bf-4a7e-b9bc-96b9981029c1.png">

### Steps to Reproduce

1. Clicked Search at the top right corner
2. Type anything
3. The recommendation window will appears with 1/3 covered

### Environment Information

- OS: macOS 13.1
- Desktop Environment: 
- App Version: 1.6.0
- Commit ID:

### How did you download the software?

GitHub

### Anything else?

I try to solve it with Devtools, and find it can be fixed. But it seems not a appropriate solution for all platforms.

Just give the search container a fixed width, with the value of 260px

<img width="2165" alt="iShot_2022-12-14_21 07 54" src="https://user-images.githubusercontent.com/68949228/207605422-f7349cd1-1201-4867-bd5f-cfa56a48e2dc.png">

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by kubai087** [comment]
Btw, it would be good if the absence of blur / acrylic effects of the recommendation of context menu (sorry for the inaccurate vocabulary expressions) will be fixed.

**Comment by maikirakiwi** [comment]
wont fix as Cider 1 is reaching EOL
