### ISSUE TITLE
[Enhancement] “show complete album” button when browsing library

### ISSUE THREAD

**Issue by Nosh118** [ciderapp/Cider#161]
**Is your feature request related to a problem? Please describe.**
Frustrating when browsing my library and want to listen to the whole album I’m looking at, not just the songs in the album I’ve added to my library 

**Describe the solution you'd like**
A “show complete album” button, like the Apple Music iOS app.

**Describe alternatives you've considered**
Go to artist page, select album, play from there

**Additional context**
![24535E3C-C770-4E7D-B9D1-47E71584B847](https://user-images.githubusercontent.com/67752804/150369574-2ad01e56-8bda-4ce3-b9df-1effc8cffc8b.jpeg)

**Comment by vapormusic** [comment]
kinda redundant to me cus you can just click on the album on the mediaitem and it will show you the full complete album

**Comment by Nosh118** [comment]
What do you mean the media item?

**Comment by vapormusic** [comment]
> What do you mean the media item?
> […](#)
> On 20 Jan 2022, 3:56 PM +0000, vapormusic ***@***.***>, wrote: kinda redundant to me cus you can just click on the album on the mediaitem and it will show you the full complete album — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

On a second thought, why not?

**Comment by vapormusic** [comment]
committed in upcomming branch. https://github.com/ciderapp/Cider/commit/a1b23e4a4a3f5a2205a2a9a94d96268598613ef5
