### ISSUE TITLE
[Bug]: Installing a new version of Cider removes the pinned icon on the Windows Taskbar

### ISSUE THREAD

**Issue by trparky** [ciderapp/Cider#1611]
### Describe the Bug

Installing a new version of Cider removes the pinned icon on the Windows Taskbar.

### Steps to Reproduce

1. Install Cider.
2. Pin Cider to the Windows Taskbar.
3. Download new version of Cider.
4. Note how your pinned icon is gone on the Windows Taskbar.

### Environment Information

- OS: Windows 11 22H2
- Desktop Environment: Windows
- App Version: 1.6.0
- Commit ID: 23f7f56e

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
This is not something we directly control, this would probably be down to either how Windows handles electron applications, o how electron-builder packages the app. For such a small issue, we will not be working on this.
