### ISSUE TITLE
[Bug]: Audio Output Channel Resetting

### ISSUE THREAD

**Issue by jacobmoberly** [ciderapp/Cider#1616]
### Describe the Bug

Okay so I have a GoXLR Mixer, and I like to set my music applications to send audio to the "Music" Output channel through Windows. I do this by going to Windows 10 Settings > System > Sound > App volume and device preferences (at the bottom).

Every other app I do this for remembers this setting and will playback through this Music channel and Cider does as well, but it seems to forget and default back to System after I sleep or reset my computer.

The setting in Windows Settings still says the Music output though, so I have to go back into settings, switch it to default, and then switch it back to Music every time it "forgets". I'd love to have it remember my preference, or better yet, add a Output channel directly in the Cider app. Thanks!

### Steps to Reproduce

1. Going to Windows 10 Settings > System > Sound > App volume and device preferences (at the bottom).
2. Set Output to my Music channel.
3. Works great...then put PC to sleep, or exit the app for a couple hours.
4. Cider reverts to default audio output, but the setting in Windows Settings is still Music.
5. Have to reclick another output, and then Music again.

### Environment Information

- OS: Windows 10
- Desktop Environment: AMD 5600X??
- App Version: 1.5.9
- Commit ID: N/A

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by maikirakiwi** [comment]
This isn't something we can control as Cider is driven by chromium at its core.
