### ISSUE TITLE
[Bug]: Cannot start Radio

### ISSUE THREAD

**Issue by astronaako** [ciderapp/Cider#1617]
### Describe the Bug

The start radio option from any track causes playback to stop and doesn't do anything else

### Steps to Reproduce

1. Right click any track
2. Click Start Radio

### Environment Information

- OS: Windows 
- App Version: 1.5.9

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Please screenshot the console from devtools when you try and play the radio.

**Comment by halturin** [comment]
![image](https://user-images.githubusercontent.com/118860/211777445-ab9acc3d-a452-4e3b-8643-1c9113b9c11d.png)
two POST errors happened on press play, but the song is playing.
the next two lines - were attempts to start the radio 

Cider 1.5.7 (linux, NixOS)

**Comment by coredev-uk** [comment]
@halturin Please update your Cider client. 1.5.7 was EOL and is no longer supported by our API.

**Comment by astronaako** [comment]
![image](https://user-images.githubusercontent.com/18577543/214213490-d4844baa-bbb4-4b96-b79e-3fb68a411658.png)
 Same issue on windows with Cider 1.5.9

**Comment by livkx** [comment]
Still an issue

**Comment by n0ahjs** [comment]
This issue does not affect me? I can start radios just fine from Cider 1.5.9.

Win11
Cider 1 (MS Store)

**Comment by Steven11q** [comment]
Still an issue
Manjaro Linux 1.5.9

**Comment by BoltR6** [comment]
Still an issue, although it works randomly

Windows 11 Pro and NixOS

**Comment by Jhines091** [comment]
Still an issue. This has never worked for me. I switched to the newly released Apple Music client and it is much better.
