### ISSUE TITLE
[Bug]crashes on startup at GetVSyncParametersIfAvailable() in gl_surface_presentation_helper.cc(260)

### ISSUE THREAD

**Issue by Bednar87** [ciderapp/Cider#1620]
### Describe the Bug

I installed the app from flathub and run it with flatpak run sh.cider.Cider.

Full log below:

`[20:58:24.335] [info]  [AppEvents] App started
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
[20:58:24.484] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'playbackNotifications.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[20:58:24.530] [info]  [AppEvents] App ready
[20:58:24.531] [info]  [Cider] Application is Ready. Creating Window.
[20:58:24.538] [info]  Setting up handlers for local files
[20:58:24.541] [info]  [Connect] Auth URL: https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[20:58:24.558] [info]  WebSocketServer started on port: 26369
[20:58:24.563] [info]  [Cider][Widevine] Status: {
  oimompecagnajdejgnnjijobebaeigek: {
    name: 'Widevine Content Decryption Module',
    status: 'new',
    version: '4.10.2557.0'
  }
}
[20:58:24.583] [info]  {
  auxAttributes: {
    amdSwitchable: false,
    canSupportThreadedTextureMailbox: false,
    glResetNotificationStrategy: 0,
    inProcessGpu: true,
    initializationTime: 0,
    isAsan: false,
    jpegDecodeAcceleratorSupported: false,
    optimus: false,
    passthroughCmdDecoder: false,
    sandboxed: false,
    softwareRendering: false,
    subpixelFontRendering: true,
    visibilityCallbackCallCount: 0
  },
  gpuDevice: [
    {
      active: true,
      cudaComputeCapabilityMajor: 0,
      deviceId: 29631,
      gpuPreference: 0,
      vendorId: 4098
    }
  ]
}
[20:58:24.584] [info]  From here can you check for real changes, the initial scan has been completed.
[20:58:24.584] [info]  Cider client port: 9000
[20:58:24.585] [info]  Cider remote port: 6942
[20:58:24.586] [info]  remote broadcasted
[73:1228/205828.651108:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
`

### Steps to Reproduce

I installed the app from flathub and run it with flatpak run sh.cider.Cider. It crashes immediately after - always, 100% reproducible

### Environment Information

Operating System: Arch Linux
KDE Plasma Version: 5.26.4
KDE Frameworks Version: 5.101.0
Qt Version: 5.15.7
Kernel Version: 6.1.1-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 24 × AMD Ryzen 9 5900X 12-Core Processor
Memory: 31.3 GiB of RAM
Graphics Processor: AMD Radeon RX 6800 XT

Cider 1.5.9 - https://flathub.org/apps/details/sh.cider.Cider

### How did you download the software?

Flathub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Appears to be an issue with Electron. Follow the upstream issue here Electron/Electron#32760
