### ISSUE TITLE
[Bug]: Error starting Cider with wayland flags

### ISSUE THREAD

**Issue by pratyush-1327** [ciderapp/Cider#1624]
### Describe the Bug

A bug happened!
Starting Cider with `flatpak run sh.cider.Cider --enable-features=UseOzonePlatform --ozone-platform=wayland` gives the below mentioned error:
`[17:07:31.669] [info]  [AppEvents] App started
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
LaunchProcess: failed to execvp:
xdg-settings
[17:07:32.222] [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'playbackNotifications.js',
  'raop.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[13:0102/170732.227682:ERROR:wayland_connection.cc(218)] Failed to connect to Wayland display: No such file or directory (2)
[13:0102/170732.227890:ERROR:ozone_platform_wayland.cc(220)] Failed to initialize Wayland platform
[13:0102/170732.227897:ERROR:env.cc(255)] The platform failed to initialize.  Exiting.
[0102/170732.228402:ERROR:scoped_ptrace_attach.cc(27)] ptrace: Operation not permitted (1)
/app/bin/cider-wrapper: line 7:    13 Segmentation fault      (core dumped) cider "$@"`

### Steps to Reproduce

1. open terminal
2. run code `flatpak run sh.cider.Cider --enable-features=UseOzonePlatform --ozone-platform=wayland`

### Environment Information

- OS: Fedora Workstation Linux 37
- Desktop Environment: Gnome [wayland]
- App Version: 1.5.9
- Commit ID:  -

### How did you download the software?

Flathub

### Anything else?

There was a recent issue too where the dev had mentioned flags to use , which could open cider via wayland session.
Using the same flags , I am unable to run it..

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by coredev-uk** [comment]
Please post the output of printenv. (Remove $user and any ssh stuff if you like)

**Comment by lunalicca** [comment]
I'm experiencing the same issue with Fedora 37 and Sway WM. Output of `printenv` (lightly edited):

```
SHELL=/bin/bash
COLORTERM=truecolor
HISTCONTROL=ignoredups
GTK_IM_MODULE=fcitx
HISTSIZE=1000
HOSTNAME=hostname
I3SOCK=/run/user/1000/sway-ipc.1000.1660.sock
XMODIFIERS=@im=fcitx
XCURSOR_SIZE=24
EDITOR=nvim
XDG_SEAT=seat0
PWD=/home/user
XDG_SESSION_DESKTOP=sway
LOGNAME=user
XDG_SESSION_TYPE=wayland
GRIM_DEFAULT_DIR=/home/user/Pictures
HOME=/home/user
LANG=en_US.UTF-8
XDG_CURRENT_DESKTOP=sway
SWAYSOCK=/run/user/1000/sway-ipc.1000.1660.sock
WAYLAND_DISPLAY=wayland-1
QT_QPA_PLATFORM=wayland
MOZ_GMP_PATH=/usr/lib64/mozilla/plugins/gmp-gmpopenh264/system-installed
XDG_SESSION_CLASS=user
TERM=foot
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=user
SDL_VIDEODRIVER=wayland
VISUAL=nvim
DISPLAY=:0
SHLVL=1
MOZ_ENABLE_WAYLAND=1
QT_IM_MODULE=fcitx
XDG_VTNR=1
XDG_SESSION_ID=2
XDG_RUNTIME_DIR=/run/user/1000
DEBUGINFOD_URLS=https://debuginfod.fedoraproject.org/ 
GREETD_SOCK=/run/greetd-1420.sock
XDG_DATA_DIRS=/home/user/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
PATH=/home/user/.cargo/bin:/home/user/.local/bin:/home/user/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
MAIL=/var/spool/mail/user
OLDPWD=/home/user/Downloads
_=/usr/bin/printenv
```

Launching the Flatpak from the terminal with `--socket=wayland` gets me a little further--the tray icon appears, and I can see Waybar picking up an audio player--but it fails to display a window:

```
[78:0108/011028.777894:ERROR:gl_surface_egl.cc(479)] eglCreateWindowSurface failed with error EGL_BAD_NATIVE_WINDOW
[130:0108/011028.782482:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
[78:0108/011028.783699:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 1
```

This recent issue looks very similar: https://github.com/ciderapp/Cider/issues/1514

**Comment by coredev-uk** [comment]
Is this your first time launching the app? If so then this may be an issue with config if the tray icon is not loading. Try deleting the application data for Cider (usually found in .config/Cider, not sure if flatpak isolates it somewhere else) and relaunching it with and without the socket flag.

**Comment by lunalicca** [comment]
> Is this your first time launching the app? If so then this may be an issue with config if the tray icon is not loading. Try deleting the application data for Cider (usually found in .config/Cider, not sure if flatpak isolates it somewhere else) and relaunching it with and without the socket flag.

Ah, sorry for the confusion--I'm experiencing the same problem as OP, where Cider just core dumps and never launches (hence the tray icon never appearing). Adding `--socket=wayland` manages to prevent the application from crashing, so the tray icon *does* appear, but because a window is never drawn, the application never finishes launching in this scenario, either. The terminal outputs the above listed errors and will sit there forever until either the process is killed or the application is quit from the tray icon.

Application data for Flatpak users appears to be stored at `~/.var/app/sh.cider.Cider/config/Cider`, but deleting this folder doesn't make any difference. The behavior is the same with or without the `--socket` flag (core dump without; never draws a window with).

Thanks for looking into this! 🐱

**Comment by coredev-uk** [comment]
Okay, have you tried using an alternative to flatpack for Cider (Either using the AUR package or running the AppImage/Deb/Snap from the release files)? I am using Wayland with the Cider AUR package, and it works fine, so it could be an issue with the flatpack.

**Comment by pratyush-1327** [comment]
> Okay, have you tried using an alternative to flatpack for Cider (Either using the AUR package or running the AppImage/Deb/Snap from the release files)? I am using Wayland with the Cider AUR package, and it works fine, so it could be an issue with the flatpack.

Okay so the AUR  package worked great with wayland but after I shifted to Fedora there is no RPM package for it . So we have to use flatpak only . Someone can try snap and mention if it works..
But a RPM package would be great , it will most probably solve all these issues too.

**Comment by lunalicca** [comment]
> Okay, have you tried using an alternative to flatpack for Cider (Either using the AUR package or running the AppImage/Deb/Snap from the release files)? I am using Wayland with the Cider AUR package, and it works fine, so it could be an issue with the flatpack.

The problem persists with the AppImage, similar to other users on #1514--same behavior, same error messages.

```
[317917:0112/114402.684931:ERROR:gl_surface_egl.cc(479)] eglCreateWindowSurface failed with error EGL_BAD_NATIVE_WINDOW
[317917:0112/114402.696265:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 1
```

It seems that most (or all) of us who are seeing these errors are using wlroots-based compositors (Sway, Hyprland), so perhaps it's a different issue from the one OP is seeing. Would it possible to reopen #1514 and continue investigating there?

**Comment by pratyush-1327** [comment]
> > Okay, have you tried using an alternative to flatpack for Cider (Either using the AUR package or running the AppImage/Deb/Snap from the release files)? I am using Wayland with the Cider AUR package, and it works fine, so it could be an issue with the flatpack.
> 
> The problem persists with the AppImage, similar to other users on #1514--same behavior, same error messages.
> 
> ```
> [317917:0112/114402.684931:ERROR:gl_surface_egl.cc(479)] eglCreateWindowSurface failed with error EGL_BAD_NATIVE_WINDOW
> [317917:0112/114402.696265:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 1
> ```
> 
> It seems that most (or all) of us who are seeing these errors are using wlroots-based compositors (Sway, Hyprland), so perhaps it's a different issue from the one OP is seeing. Would it possible to reopen #1514 and continue investigating there?

FYI , I have installed both sway and Gnome on Fedora 37. The issue persists on both of these desktop environments operating with wayland.
This used to happen on Arch Linux too if i tend to use Flatpak . It worked flawlessly with the AUR package.

**Comment by coredev-uk** [comment]
I suggest sticking the AUR package. As for the AppImage this may be an issue with Electron. With our current version, you should need to have the flags anymore so I'm not sure why these issues keep persisting.

**Comment by pratyush-1327** [comment]
> I suggest sticking the AUR package. As for the AppImage this may be an issue with Electron. With our current version, you should need to have the flags anymore so I'm not sure why these issues keep persisting.

Most of us cannot use AUR package as we are using Fedora. There is no RPM package for Cider to run it natively.
The flatpak has its own seperate libs and runtime so it cant be configured properly to be used with wayland on Fedora.
This is the reason this issue persists on Fedora only and not on Arch Linux

**Comment by lunalicca** [comment]
I can confirm that the issue persists when building from the AUR package using Distrobox. The application runs without issue in XWayland, but when Wayland flags are passed, the application fails to paint a window with basically the same errors as before:

```
[2150999:0202/155342.159555:ERROR:gl_surface_egl.cc(479)] eglCreateWindowSurface failed with error EGL_BAD_NATIVE_WINDOW
[2150999:0202/155342.164224:ERROR:x11_software_bitmap_presenter.cc(142)] XGetWindowAttributes failed for window 1
[2151029:0202/155342.164716:ERROR:command_buffer_proxy_impl.cc(128)] ContextResult::kTransientFailure: Failed to send GpuControl.CreateCommandBuffer.
```
