### ISSUE TITLE
[Bug]: Auth Window Not Loading

### ISSUE THREAD

**Issue by xhc942** [ciderapp/Cider#1625]
### Describe the Bug

A bug happened!
![image](https://user-images.githubusercontent.com/71172289/210318834-c59b7561-0aa1-4737-857b-088045366a88.png)
The software cannot be used after installation. It seems that there is no network！
![image](https://user-images.githubusercontent.com/71172289/210318996-ab93620f-a2f4-4e28-bac1-42da02295449.png)

### Steps to Reproduce

1.After the first installation, there was a problem

### Environment Information

- OS:
- Desktop Environment: 
- App Version:
- Commit ID:

### How did you download the software?

GitHub

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by Swiftzerr** [comment]
Try reloading the app. Check the console for any errors.

**Comment by Jeffrey-deng** [comment]
same problem

**Comment by Lamb666** [comment]
Same for quite a while

**Comment by BLdada** [comment]
Maybe you need VPN or a network proxy to connect apple.com for github channel in China.
Don't know why it doesn't work in github channel because the Microsoft Store version can login well.

**Comment by xhc942** [comment]
Thank you very much, the Microsoft Store version is available, and it's great to have such great software. Thank you for your team.

在 2023年1月8日，18:28，BLdada ***@***.***> 写道：

﻿

Maybe you need VPN or a network proxy to connect apple.com for github channel in China.
Don't know why it doesn't work in github channel because the Microsoft Store version can login well.

**Comment by BLdada** [comment]
But I thought that's weird. Why Cider cannot connect the Auth server on apple?
