### ISSUE TITLE
[Bug]: I lost half my playlist! (2000 songs)

### ISSUE THREAD

**Issue by UbaidA05** [ciderapp/Cider#1626]
### Describe the Bug

A bug happened!

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS:
- Desktop Environment: 
- App Version:
- Commit ID:

### How did you download the software?

Microsoft Store

### Code of Conduct

- [X] I agree to follow this Cider's [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md)

### Disclaimer

- [X] I acknowledge the [Support Disclaimer](https://docs.cider.sh/support/disclaimer)

**Comment by Swiftzerr** [comment]
Could you please explain in better what you did for this to happen? Is it only in cider of is it also in the official apple music app?

**Comment by coredev-uk** [comment]
Please create a new issue and fill out all fields, following the format.
