### ISSUE TITLE
Blurry text and pictures when scaling in Wayland

### ISSUE THREAD

**Issue by mmowchenko** [ciderapp/Cider#163]
Is there a way to correct the blurriness from scaling in Wayland when above 100%?

As an example, one can have "Exec=env MOZ_ENABLE_WAYLAND=1 thunderbird %u" in Thunderbird's desktop file to resolve this.

**Comment by ConnectedR** [comment]
It’s an issue with fractional scaling on all software that only supports Xorg. It’s unsolvable for the user unless there’s a flag in app to make it run in Wayland.

**Comment by vapormusic** [comment]
pretty sure you can just add --enable-features=UseOzonePlatform --ozone-platform=wayland
