### ISSUE TITLE
[Bug]: Unable to install. Unable to use in China. Error when login. Request https://api.cider.sh/v1/ report 403 and Access denied.

### ISSUE THREAD

**Issue by Lvmoy** [ciderapp/Cider#1630]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.

### Cider Version

1.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21H2

### Where did you download Cider from?

GitHub

### Describe the Bug

No apple music login page when set up install.exe. 
When I open dev mode, I find get request 'api.cider.sh/v1/' report 403 error.

And when I get 'api.cider.sh/v1/'  through Chrome, I got an error when visiting api.cider.sh/v1/.

`Errorcode: 1020
Ray ID: 7871caa19d4f7ac3
Country: CN
Data center: lax06
IP: 222.190.xxx.x
Timestamp: 2023-01-10 01:55:37 UTC` 

### Steps to Reproduce

Install cider through exe download from github. Setup apple music account. No login page shows.

### Anything else?

Do you guys set an access address restriction from CN?

**Comment by coredev-uk** [comment]
Due to the mass traffic we get from China, it has unfortunately been limited to paid users only as we cannot financially maintain a free Chinese user base. 

The only other suggestion I can give is to purchase Cider from the Microsoft Store or to join the Cider2 Beta.

**Comment by maikirakiwi** [comment]
加Q群531185058
有最新的消息
