### ISSUE TITLE
[Bug]: Unable to start the app

### ISSUE THREAD

**Issue by SirSharanChakradhar** [ciderapp/Cider#1633]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.

### Cider Version

1.5.9-5

### What operating system are you using?

Other (specify below)

### Operating System Version

Exodia OS - Archlinux

### Where did you download Cider from?

AUR

### Describe the Bug

First start after installation, everything was alright. Once closes the app and reopens, it never starts the app.  Opened the app from terminal yet same problem.   

[22:29:09.847] [info]  [AppEvents] App started
[41697:0111/222912.585949:ERROR:service_worker_storage.cc(1904)] Failed to delete the database: Database IO error

### Steps to Reproduce

Close/quit and reopen the app.

### Anything else?

NA

**Comment by coredev-uk** [comment]
Try a [clean install](https://cider.gitbook.io/welcome-to-gitbook/support/troubleshooting#1-clean-installation).
