### ISSUE TITLE
[Bug]: Cider is not showing Shairport-sync from the piCorePlayer

### ISSUE THREAD

**Issue by godzinilla** [ciderapp/Cider#1634]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.

### Cider Version

1.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 22621.963

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

I am using the piCorePlayer with newest available version of pCP and the Shairport-sync add-on. The device is Raspberry Pi 3B+. The Cider app is not showing my RPi under the Cast menu.

I have also the Shairport-sync instance in Docker on my another device (OpenMediaVault system server). This instance is showing in the Cider but when connected there is a electronic distorted sound and no music is playing.

Both Shairport-sync instances are visible and playable from iTunes on my Windows machine.

### Steps to Reproduce

As described in "Describe the Bug" section.

**Comment by coredev-uk** [comment]
Cider already has functionality for AirPlay built in. You can access this from the cast menu next to the volume slider in the player bar. Support for third party options will not be implemented in Cider 1 when we have a solution built in. A plugin can be built by the community or dev if this is really needed (if this did happen this most likely would not happen on Cider1).
