### ISSUE TITLE
Audio Lab Is Blank[Bug]: 

### ISSUE THREAD

**Issue by balls69** [ciderapp/Cider#1637]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.0 

### What operating system are you using?

Windows

### Operating System Version

Windows 10 21h2

### Where did you download Cider from?

Winget (Nightly)

### Describe the Bug

I just downloaded the last version went to go open the Audio Lab and it's completely blank. I've tried resetting the app, deleting it downloading it again and install the new download but  no luck.

### Steps to Reproduce

1. Open the latest nightly version
2. Click on Audio Lab

**Comment by coredev-uk** [comment]
I believe this was intentional at audio lab was not fully operational and was removed until Maikiwi is happy with it.
