### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by fi-sandervermeer** [ciderapp/Cider#1656]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.0.4.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

*THIS IS ABOUT THE PREVIEW RELEASE*

The app is completely blank after the initial "Starting Cider" load screen. No file menu, no buttons, absolutely nothing. Nothing happens, there is no CPU activity in Task Manager.

### Steps to Reproduce

Opened the app...

**Comment by coredev-uk** [comment]
Support for Cider 2 is not given here. Please make a visit the Discord for more information on bugs for Cider 2.
