### ISSUE TITLE
[Bug]: Unable to log into Apple account using security keys

### ISSUE THREAD

**Issue by qnm** [ciderapp/Cider#1666]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.5.9

### What operating system are you using?

Other (specify below)

### Operating System Version

PopOS

### Where did you download Cider from?

Flathub

### Describe the Bug

I'm using security keys (Yubikey) with my Apple account, and I'm unable to authenticate as the browser used by Cider doesn't support keys.

![image](https://user-images.githubusercontent.com/5343/222053169-a26f8849-9caa-442d-8485-9f134ce9a4aa.png)

### Steps to Reproduce

1. Opened Cider
2. Attempted to log into Apple
3. Prompted to use my security key, I'm unable to use it

**Comment by jacksonwelsh** [comment]
I was able to successfully sign in on the latest Windows Store v1 version, however was not able to sign in on macOS Cider 2.0.0-a001: 

![jacksonwelsh - Cider-2 2023-03-06 at 14 22 54](https://user-images.githubusercontent.com/20214768/223222633-d308d74c-5e39-4cb6-8ad4-6e8eb6cbdff1.png)

Will run a build tn and see if I can get it working on latest. May need to use a traditional browser to sign in though.
