### ISSUE TITLE
[Bug]: Invalid CORS Request when trying to sign in on Windows 10

### ISSUE THREAD

**Issue by sillywilly1970** [ciderapp/Cider#1667]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.5.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

When i go to sign in with my Apple ID and my password and it sends me the request to my Iphone i put in the code than Invalid CORS request pops up every time

### Steps to Reproduce

tried signing in on my Apple Account

### Anything else?

Invalid CORS request

**Comment by Akkowicz** [comment]
This version works:
https://apps.microsoft.com/store/detail/cider-ea/9PL8WPH0QK9M?hl=en-us&gl=us&rtc=1
