### ISSUE TITLE
[Bug]: Settings - popover overlaps with window control icons

### ISSUE THREAD

**Issue by jacksonwelsh** [ciderapp/Cider#1671]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.0.0 - FujisanCore

### What operating system are you using?

Windows

### Operating System Version

Win11 Edu 22H2 (22621.1265)

### Where did you download Cider from?

GitHub

### Describe the Bug

(downloaded cider from alpha discord channel)

When mousing near the top-right of the settings popover, the window control icons are also highlighted.

![image](https://user-images.githubusercontent.com/20214768/223301673-6306ecd7-c333-453f-a10e-5d0b2c860b05.png)

### Steps to Reproduce

1. Open Cider, and make the window relatively small (1/4 of my 32" display)
1. Open settings
1. Hover mouse near top-right of settings page

### Anything else?

This is a very minor issue, but because the close button for the settings page is in this region, it is very likely for users to notice this (or potentially miss and accidentally close the application).

**Comment by quacksire** [comment]
Make the issue in here: https://github.com/ciderapp/Fujisan-BugTracker

**Comment by quacksire** [comment]
https://github.com/ciderapp/Fujisan-BugTracker
