### ISSUE TITLE
[Bug]: Will not log in, "Problem Connecting, There may be a network issue."

### ISSUE THREAD

**Issue by ethmac007** [ciderapp/Cider#1702]
### Preflight Checklist

- [x] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 7 Build 7601: Service Pack 1

### Where did you download Cider from?

GitHub

### Describe the Bug

Just today, I Cider had seemed to stop connecting to (I assume) Apple login servers properly, as it was encountering errors (forgot to write it down unfortunately) and only allowed 1 minute 30 second previews of each song. I decided to re-login as this had happened once before, and that had fixed it. This time when going through the initial setup though, once I'd gone through all of the Apple login process, when it would normally finish and let me into the app, it showed this screen:
![Cider Problem Connecting](https://user-images.githubusercontent.com/79879329/236978754-8a48dfa9-ce04-4dc3-9a50-a0fa254a7a79.png)
I've now tried restarting, deleting the appdata folder, doing a normal reinstall, and doing a complete reinstall, but all yield the same result. I'd like to know if this is something that could possibly be resolved, or if this is something on Apple's end.

### Steps to Reproduce

1. Opened App
2. Went Through First-Time Setup
3. Did Apple Music Sign-In

**Comment by gibbyb** [comment]
this seems to be an issue on the appimage, flatpak, rpm, etc. and doesn't seem to be an issue with just one version as I tried older versions as well. Seems like Apple may have changed something that broke logins.

**Comment by yazninja** [comment]
Please update to the [Latest Release](https://github.com/ciderapp/cider/releases)

**Comment by jessebassett** [comment]
Same error here-Windows 10 version 22h2.

**Comment by yazninja** [comment]
FOR LOGIN ISSUES: update to the [Latest Release](https://github.com/ciderapp/cider/releases)

**Comment by JamieVangeysel** [comment]
The latest release does not include a dmg file? I have the same issue on Mac
