### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 1HARAKIRI1** [ciderapp/Cider#1703]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.5.9

### What operating system are you using?

Windows

### Operating System Version

Windows 10 version 22h2

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

No me deja iniciar sesion, luego de poner mis credenciales y poner mi codigo de verificacion de apple ID me dice que perdio la conexion, descargue el programa atravez de microsoft store y pague para usarla y no me deja iniciar sesion.

### Steps to Reproduce

Descargue el programa, lo abri e inicie sesion 

### Anything else?

![Cider (Beta) 08_05_2023 10_00_51 p  m](https://user-images.githubusercontent.com/132973868/236991357-7cc62fa7-180b-447a-a932-23a8695eec87.png)

**Comment by yazninja** [comment]
#1704 Please download the latest release
