### ISSUE TITLE
[Bug]: Will not log in, "Problem Connecting, There may be a network issue."

### ISSUE THREAD

**Issue by HeroMihneaO** [ciderapp/Cider#1704]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.0

### What operating system are you using?

Other Linux

### Operating System Version

Pop!_OS 22.04 LTS

### Where did you download Cider from?

GitHub

### Describe the Bug

I decided to install cider on my beautiful main machine and after logging in with my apple id boom it would fail. It will probably have to do more with the apple servers.  And I'm not the only one to encounter this issue like #1702  exactly same issue.

### Steps to Reproduce

    Opened App
    Went Through First-Time Setup
    Did Apple Music Sign-In

**Comment by AlphaRishi1229** [comment]
Facing the same issue with the same setup.

**Comment by jnfinitym** [comment]
Same on ElementaryOS, with 1.5.9 via Flathub. I can't login, even though I previously was logged in. Seems like Apple made a breaking change.

**Comment by SpinnySpiwal** [comment]
Same here, MacOS

**Comment by hrqmonteiro** [comment]
Same thing here, macOS ventura and on Gnome 44

![Screenshot 2023-05-11 at 19 13 22](https://github.com/ciderapp/Cider/assets/17055027/3275e932-f771-4e61-b20a-1f7543a5789b)

**Comment by adschem** [comment]
Same here with deb package on ubuntu

**Comment by PanJason** [comment]
Same problem, ubuntu 22.04 LTS

**Comment by hrqmonteiro** [comment]
Will someone look into this? Or the project is really abandoned?

The app is unusable (?)

**Comment by yazninja** [comment]
@adschem @hrqmonteiro @PanJason @AlphaRishi1229 @C0Nd3Mnd @Schmensch @HeroMihneaO @jnfinitym @SpinnySpiwal @ducky8239 
Download the [Latest Release](https://github.com/ciderapp/cider/releases

**Comment by AlphaRishi1229** [comment]
@yazninja yes login works now, but seems cider audio labs is not loading with the new update

**Comment by jardel20** [comment]
Same problem with AppImage on Fedora 38.

**Comment by hrqmonteiro** [comment]
Still happening on macOS through homebrew download

**Comment by sveby** [comment]
Same with Fedora 38, latest from Flathub.

**Comment by Schmensch** [comment]
The FLATPAK is 7 months out of date, which seems to be the cause of the issue. I opened an issue over there: https://github.com/flathub/sh.cider.Cider/issues/495

**Comment by rowbawts** [comment]
I'm the maintaner of the Flatpak it was 7 months out of date because that was the last "stable" release. I use it everyday and was not aware of the login issue until recently. I've just now pushed an update to the Flatpak to bring it up to 1.6.1 this should resolve all issues.

**Comment by rafabra988** [comment]
@yazninja will this update ever hit microsoft store? cider 1 still on 1.5.9 there
