### ISSUE TITLE
[Bug]: Not able to sign in

### ISSUE THREAD

**Issue by SherrySingh03** [ciderapp/Cider#1705]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### Where did you download Cider from?

GitHub

### Describe the Bug

Whenever I try to login using my Apple ID on Cider, it just says this. And I would like to add that I do have a working Apple Music Subscription and that Cider was working fine, and I've started to face this issue recently, when the application resetted itself by its own. And I would like to mention that this is not a network issue, can **confirm**.

![image](https://github.com/ciderapp/Cider/assets/83728289/9485ee29-b4cf-445e-ab75-fd37ebd112a7)

### Steps to Reproduce

1. Start Cider from scratch
2. Click on Next until you reach the Sign in to Apple Music step.
3. Login and enter the verification code as well.
4. After that, you'll see the mentioned screen.

**Comment by LiamDawe** [comment]
Can confirm the issue happens here on Linux too, refuses to sign in with the same error.

**Comment by ninjadrknss** [comment]
Can confirm the same issue happening on Window 11 too. I used to be able to sign in, but I would be logged out a few days later.

**Comment by ChiefGyk3D** [comment]
Confirming the issue for Windows 10. I used to be able to sign in but now I can't

**Comment by etx2** [comment]
Confirm the issue in debian os,

**Comment by dogo** [comment]
Confirm the issue in Fedora 38

**Comment by yazninja** [comment]
@LiamDawe @dogo @ChiefGyk3D @SherrySingh03 @etx2 Download the [Latest Release](https://github.com/ciderapp/cider/releases)

**Comment by SherrySingh03** [comment]
@yazninja how do I know if this is the official release or not?

**Comment by dogo** [comment]
@yazninja Where is the Flatpak update?

**Comment by yazninja** [comment]
> @yazninja how do I know if this is the official release or not?
> 

You can check the public pipelines, it has the build artifacts also posted there, the link to the pipeline is in the release page

**Comment by yazninja** [comment]
> @yazninja Where is the Flatpak update?

We are coordinating with our flatpak maintainer,  pls expect the update within the week

**Comment by jefaokpta** [comment]
> Confirm the issue in Fedora 38

Same issue via flatpak

**Comment by deathgrape** [comment]
Same issue with Cider (Legacy) off the Windows store.

**Comment by SherrySingh03** [comment]
Yea @deathgrape that’s why I had to buy Cider Preview. Can confirm there’s no issue in the Cider 2.x version
