### ISSUE TITLE
[Bug]: Unable to get Cider 2 free upgrade

### ISSUE THREAD

**Issue by mathdebater** [ciderapp/Cider#1707]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.1

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro version 22H2

### Where did you download Cider from?

GitHub

### Describe the Bug

I was trying to get the Cider 2 Free upgrade, but after clicking "Open in Microsoft Store" I dont see the option to get the free upgrade. It says it is $3.99.  I purchased Cider 1.x in like April 2022 so I should be eligible. 

![image](https://github.com/ciderapp/Cider/assets/36281248/e8499738-e163-4c0d-93a5-21c73a4de23f)

### Steps to Reproduce

I downloaded Cider 1.6.1 from github because the version 1.5.9 is broken, was unable to login to Cider. After installing 1.6.1, opened Cider and got the pop-up message saying I could get a free upgrade

**Comment by yazninja** [comment]
Please submit a ticket in discord and attach needed details
