### ISSUE TITLE
[Bug]: Unable to launch Cider 1.6.1.

### ISSUE THREAD

**Issue by Vishvamitra** [ciderapp/Cider#1708]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.1

### What operating system are you using?

Other Linux

### Operating System Version

Linux Mint 20.3

### Where did you download Cider from?

GitHub

### Describe the Bug

I've downloaded Cider 1.6.1 both in AppImage and in deb package format but it simply doesn't start. 

### Steps to Reproduce

Case 1: AppImage
After setting the correct permissions to turn the AppImage into an executable file, I just click on the icon of the AppImage but the program doesn't launch, although it's running according to GNOME System Monitor.

Case 2: Deb packaging
Installation process runs smoothly, but once I type the `cider` command in the CLI, the following error output is shown:
`[18:07:01.407] [info]  [AppEvents] App started
[94079:0514/180701.773687:ERROR:gpu_memory_buffer_support_x11.cc(49)] dri3 extension not supported.`

### Anything else?

![Screenshot from 2023-05-14 18-06-12](https://github.com/ciderapp/Cider/assets/40338178/97d2309d-86d2-4c11-9905-df3de4e51894)

**Comment by ChiefGyk3D** [comment]
Can confirm similar behavior in Windows 10 as well

**Comment by adschem** [comment]
Can confirm same issues on Ubuntu for deb and package and snap
