### ISSUE TITLE
[Bug]: Problema de conexión

### ISSUE THREAD

**Issue by diegobarri00** [ciderapp/Cider#1713]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.5.9

### What operating system are you using?

Windows

### Operating System Version

22621.1702

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

Al iniciar sesión con mi id de apple me da problema de conexión, da igual cuantas veces lo intente, si cierro o abro la app o incluso he probado a reiniciar el ordenador y el problema sigue ahí.

### Steps to Reproduce

1. Introduje mi id apple
2. introduje la contraseña de mi id.
3. al pasar al siguiente paso me salía "Problema de conexión. Puede que haya un problema con la red" pero no puede haber un problema puesto que estoy escribiendo esto desde el buscador Edge del mismo pc.

**Comment by NightMare646** [comment]
so there is no more cider for linux
