### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Paetrig** [ciderapp/Cider#1719]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.0.3 - Sabiiro

### What operating system are you using?

Windows

### Operating System Version

Version 21H2 (OS Build 22000.1936)

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

When searching for artists in succession in the **Artists** tab of my **Library**, clicking the **X** to clear the search field does nothing. To continue searching, I must highlight the field's existing text and overwrite it.

In my testing, I have found this is specific and unique to the search field of the **Artists** tab and does not occur in other search fields (e.g. global search fields or search fields in other tabs and/or sections).

### Steps to Reproduce

1. In the **Library** section, click **Artists**.
2. In the **Search** field, enter an artist's name.
3. ![image](https://github.com/ciderapp/Cider/assets/104074436/659ef606-fbc7-45b9-bef4-60c12cb64daf)
4. Click the **X** to clear the search field.
5. The contents of the **Search** field are not cleared.
6. To clear the contents of the Search field, highlight the text and replace.

**Comment by Paetrig** [comment]
I see the previous comment is a bot response but I wanted to be sure it was noted this issue is for Cider 2.0.3, not 1.0.x.

**Comment by Amaru8** [comment]
Hi there,

Thank you for submitting your issue. However, it appears that you have created the issue in the wrong repository. The repository you used, [Cider](https://github.com/ciderapp/Cider) has reached its end-of-life status and is no longer actively maintained.

To ensure that your issue receives the necessary attention and is addressed in the updated version, I kindly request you to repost your issue in the correct repository, **Cider 2**. [This repository](https://github.com/ciderapp/Cider-2) is specifically dedicated to issue reporting and is actively reviewed regarding the updates of **Cider 2**.

Thank you for your understanding. If you have any further questions or need assistance, please don't hesitate to reach out to us.

Best regards,
Amaru
