### ISSUE TITLE
[Bug]: ERROR: A failure occured in build() 

### ISSUE THREAD

**Issue by XoloitzcuintiI** [ciderapp/Cider#1725]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.1-6

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### Where did you download Cider from?

AUR

### Describe the Bug

Whenever I try to build and install cider from the AUR, I get an error that reads:

```
Checking versions... 

✘ node version is incorrect! Expected ^19 || ^18 || ^16 || ^14.19 but was v20.2.0.
✔ npm was validated with >= 6.13.4.
✔ yarn was validated with >= 1.21.1.

 Environment is invalid!
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: cider-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
cider - exit status 4
```

### Steps to Reproduce

1. Go to AUR
2. Find Cider
3. Attempt to install Cider with yay
4. Error occurs in terminal

Error occurs even when attempting to build and install the package manually with makepkg.

**Comment by quacksire** [comment]
Check your node version. Use NVM or something along those lines to install a compatible version. Read the error message.
