### ISSUE TITLE
[Bug]: Problem Connecting, There may be a network issue.

### ISSUE THREAD

**Issue by rafabra988** [ciderapp/Cider#1727]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.5.9

### What operating system are you using?

Windows

### Operating System Version

windows 11

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

i've seen that this is fixed on 1.6.1, so could y'all please update the microsoft store version that's still on 1.5.9 pls?

### Steps to Reproduce

try to login
gets a error message

**Comment by 9xN** [comment]
having this same issue

**Comment by julien-blanchon** [comment]
I'm also having this issue :(
