### ISSUE TITLE
[Bug]: "problem Connecting There may be a network issue."

### ISSUE THREAD

**Issue by feat119h** [ciderapp/Cider#1731]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.0

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro /22H2 /19045.2965

### Where did you download Cider from?

GitHub

### Describe the Bug

After installing cider, the phrase "Problem connectiong" appears in the process of linking Apple ID.
![why](https://github.com/ciderapp/Cider/assets/135157340/acb65fd0-acff-4ff2-8b26-b4566fb31bac)

When I click OK, it doesn't sync with my Apple Music at all.
![why2](https://github.com/ciderapp/Cider/assets/135157340/e956ab49-9e93-4c36-b871-9d6ba98b66d2)

### Steps to Reproduce

After installing cider, the phrase "Problem connectiong" appears in the process of linking Apple ID.
![why](https://github.com/ciderapp/Cider/assets/135157340/acb65fd0-acff-4ff2-8b26-b4566fb31bac)

### Anything else?

When I click Account Settings, it appears that I am logged in to Apple Music, but in the sider window, I cannot connect to Apple Music.
![why3](https://github.com/ciderapp/Cider/assets/135157340/e5382660-79b9-4ccc-a7a8-a4e1375fd8a9)

**Comment by Amaru8** [comment]
Hey! 👋 Please update to the final Cider Classic _(aka. Cider 1.x.x)_ version (1.6.1) on [GitHub Releases](https://github.com/ciderapp/Cider/releases/tag/v1.6.1). 

However, I need to note that Cider Classic has approached its **End-of-life** status, and support for it is limited. You can get the **future of Cider, Cider 2** in the [Microsoft Store](https://apps.microsoft.com/store/detail/cider-preview/9PL8WPH0QK9M) or on Steam (available soon…). 🚀
