### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Sarojidipity** [ciderapp/Cider#1737]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 22H2

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

I use Eartrumpet to send sound from different programs to different outputs - for Cider I send it to my speakers.  Cider shows up in Eartrumpet as a generic (program?) "msedgewebview2", so I have to reassign it to the correct device every time I open Cider.  In version 1.x it showed up as the actual Cider icon and name, so Eartrumpet always remembered my preference.
All other program outputs are recognised and remember by Eartrumpet, it appears to be due to the fact it is recognised as something generic rather than a distinct program.

### Steps to Reproduce

Start Cider, click play.  Sound comes from default device.
Open the Eartrumpet quickmenu from the task bar - Cider shows as "msedgewebview2".
Assign to the correct output device in Eartrumpet.
Close Cider and re-open.  Sound output resets to default and needs to be re-assigned.

**Comment by Amaru8** [comment]
Hi there,

Thank you for submitting your issue. However, it appears that you have created the issue in the wrong repository. The repository you used, [Cider](https://github.com/ciderapp/Cider) has reached its end-of-life status and is no longer actively maintained.

To ensure that your issue receives the necessary attention and is addressed in the updated version, I kindly request you to repost your issue in the correct repository, **Cider 2**. [This repository](https://github.com/ciderapp/Cider-2) is specifically dedicated to issue reporting and is actively reviewed regarding the updates of **Cider 2**.

Thank you for your understanding. If you have any further questions or need assistance, please don't hesitate to reach out to us.

Best regards,
Amaru
