### ISSUE TITLE
[Bug]: Window goes from dark to light and text is hard to read on wallpaper change or Windows notification message

### ISSUE THREAD

**Issue by Swammii** [ciderapp/Cider#1745]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.0.3

### What operating system are you using?

Windows

### Operating System Version

Windows 11 22H2 22621.1848

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

When I launch Cider it starts normally, but if I get a 'toast' message from the OS, or if my wallpaper changes, the window goes mostly white and is unreadable. If I close Cider and start it again, all is good until the next time I get a toast message or my wallpaper changes.
![2023-06-16_19h52_06](https://github.com/ciderapp/Cider/assets/136863892/cc62c72d-0799-421c-be16-3bee3be5132d)
![2023-06-16_19h53_17](https://github.com/ciderapp/Cider/assets/136863892/2a447cc1-19f4-4488-89e8-f239a8eec09e)

### Steps to Reproduce

Open Cider
Wait for a windows toast message, or change wallpaper.

### Anything else?

I did not have this issue with previous versions of Cider, before I purchased from the MS Store.

**Comment by Jensenator360** [comment]
+1

**Comment by jboeshart** [comment]
Also seeing this as well. Have to close it and reopen to get it to come back black...

**Comment by Swammii** [comment]
> Also seeing this as well. Have to close it and reopen to get it to come back black...
> 
> I'm running Cider 2.1.0 on Windows 11 22H2 OS build 22621.2134

I found a fix for this. In the Cider client, go to **Settings**, and then **Visual** on the left. There is an option for **Window Vibrancy Type** - if you set that to **None** the issue goes away. I am not 100% sure what this setting does, but I see no difference in the client with it disabled. Hope it works for you as well!  
![2023-08-14_14h53_43](https://github.com/ciderapp/Cider/assets/136863892/25cdd4f1-073d-4d79-a759-d8bcaedf184a)

**Comment by jboeshart** [comment]
Whatever that setting does, that seems to have done the trick. Good find @Swammii!

Still seems that there's a bug somewhere that needs to be addressed though. Maybe something the dev's can pick up at some point?
