### ISSUE TITLE
[Bug]: Discord Rich Presence not working on Linux

### ISSUE THREAD

**Issue by rthwldn** [ciderapp/Cider#1756]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.1.1

### What operating system are you using?

Other Linux

### Operating System Version

Pop!_OS 22.04 LTS x86_64 

### Where did you download Cider from?

GitHub

### Describe the Bug

Nothing will display in my Discord profile. In Cider I tried everything I even tried different installators and versions of Discord (PBT, Canary, Pop Store, .deb) and it still didn't work. Already tried logging out, restart Cider, Discord and computer.

![Screenshot from 2023-08-07 23-49-51](https://github.com/ciderapp/Cider/assets/141244942/7da72b6c-8f36-490b-af69-a83186d6b1da)
![Screenshot from 2023-08-07 23-50-02](https://github.com/ciderapp/Cider/assets/141244942/6904cdd0-024f-4f79-861e-c1fc8fcee8f2)

### Steps to Reproduce

It just doesn't work.

**Comment by quacksire** [comment]
please press home on the sidebar and press the bug icon in the top right corner of the page

**Comment by quacksire** [comment]
^
