### ISSUE TITLE
[Enhancement] Desktop Widget

### ISSUE THREAD

**Issue by EricZhang456** [ciderapp/Cider#176]
It would be nice to add a desktop widget to the application, like the mini player in iTunes.
<img width="419" alt="itunes_11_0_3_miniplayer" src="https://user-images.githubusercontent.com/32814750/150683948-0c3deea4-8c75-42fa-8271-248a47bf4113.png">

**Comment by vapormusic** [comment]
in the upcoming branch , there is plugin support and a simple miniplayer as well
