### ISSUE TITLE
[BUG] Artwork not showing in DiscordRPC for iCloud uploaded items

### ISSUE THREAD

**Issue by PZeide** [ciderapp/Cider#177]
**Describe the bug**
Artwork not showing in DiscordRPC for iCloud uploaded items

**To Reproduce**
1. Play an iCloud uploaded item
2. The Cider icon is showing instead of the artwork

**Expected behavior**
The music artwork instead

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows
 - Application Version *(e.g. 2.5.0)*: Latest commit (4a1ebed)

**Comment by vapormusic** [comment]
yeah i know

**Comment by vapormusic** [comment]
ok this is discord's limit: they only allows url that is shorter than 256 chars, which Apple Music artwork for itunes uploaded songs isnt
