### ISSUE TITLE
[Bug]: Cannot sign in with hardware keys as 2FA

### ISSUE THREAD

**Issue by agurenko** [ciderapp/Cider#1773]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.2.0

### What operating system are you using?

Other Linux

### Operating System Version

Fedora Linux 38 KDE Spin

### Where did you download Cider from?

GitHub

### Describe the Bug

I have 2FA enabled with hardware keys (Yubikey) and now login with Apple does not work as it does not show key prompt during authentication. Chrome and Firefox auth works fine.

### Steps to Reproduce

- Enable 2FA with hardware keys
- Logout
- Try to login with Apple

**Comment by GregTheHun** [comment]
I am also experiencing this issue with version 1.6.2 (Debian Sid)

**Comment by Flagstick8483** [comment]
Had the same issue with flatpack version of Cider. 
Installed Flatseal and gave Cider access to all devices in the device setting and was able to authenticate using Yubikey.
Hope this helps
