### ISSUE TITLE
[Bug]: In README.md shield badge of Twitter is old change it to it's new name and logo 𝕏

### ISSUE THREAD

**Issue by BandhiyaHardik** [ciderapp/Cider#1788]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

Twitter badge is old.

Old Badge:
![image](https://github.com/ciderapp/Cider/assets/110784317/7311ca35-5216-4804-a37c-7a7a63a97077)

New Badge:
![image](https://github.com/ciderapp/Cider/assets/110784317/b4525e57-3a7e-48a7-8e13-789f3d9a5df7)

### Steps to Reproduce

1. Go to <a href='https://github.com/ciderapp/Cider'>Cider Repo</a>
2.  Look into Twitter badge it is not updated to it's new logo badge

**Comment by quacksire** [comment]
no. bird stays

**Comment by Amaru8** [comment]
the thing is, we really like bird... bird... bird.

**Comment by BandhiyaHardik** [comment]
okay i got it @quacksire  @Amaru8 I will close the PR.
