### ISSUE TITLE
[Bug]: Can't log in to Apple Account secured with Security Key

### ISSUE THREAD

**Issue by haysidney** [ciderapp/Cider#1798]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.2

### What operating system are you using?

Other Linux

### Operating System Version

NixOS Unstable

### Where did you download Cider from?

Flathub

### Describe the Bug

I have my Apple account secured with Security Keys (Yubikeys). While logging in, when I'm prompted to touch my security key nothing happens.

![image](https://github.com/ciderapp/Cider/assets/36320477/4639b7a6-d822-4542-a733-e49858a2d778)

### Steps to Reproduce

1. Launch Cider
2. At the log in prompt, attempt to log in.
3. Be sad when it doesn't respond to my Yubikey being touched.

**Comment by haysidney** [comment]
I'm still having this issue. I'd prefer this not be closed.

**Comment by sefidel** [comment]
I'm running Cider 1.6.2 on NixOS unstable, and I was unable to reproduce this issue.
(YubiKey starts blinking, and touching the key works w/o issues)

OS: NixOS 24.05.20231224.5f64a12 (Uakari)
DE/WM: Sway (Wayland)

The program seems to run under XWayland.

**Comment by Sergong** [comment]
I'm running Cider 1.6.2 on Fedora 39 and I can reproduce this issue. The YubiKey blinks but nothing happens when I touch it.

Kernel: Linux 6.6.11-200.fc39.x86_64

It works just fine on the Apple Music website using Firefox 121.0.1
