### ISSUE TITLE
[Bug]: Cider is not responding. Reload the app?

### ISSUE THREAD

**Issue by S0DABLACK** [ciderapp/Cider#1829]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.2

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro OS build: 19045.4046

### Where did you download Cider from?

GitHub

### Describe the Bug

I went to open cider upon turning on my pc as I usually do and It gave me the following message,
"Cider is not responding. Reload the app?" I've ran it as admin, I've restarted my pc, deleted cider and all its folders and reinstalled cider and to no avail.

### Steps to Reproduce

I literally did nothing to cider for this to happen, it was working fine yesterday ;w;

**Comment by bearfm** [comment]
same issue

**Comment by S0DABLACK** [comment]
i bought the new version of cider, we good :3 
_or well I'm good-_

**Comment by BrycensRanch** [comment]
> i bought the new version of cider, we good :3 _or well I'm good-_

you sure did have quite the confidence to buy their app after it literally is so buggy 

> ### Preflight Checklist
> * [x]  I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
> * [x]  I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
> * [x]  I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
> * [x]  I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.
> 
> ### Cider Version
> 1.6.2
> 
> ### What operating system are you using?
> Windows
> 
> ### Operating System Version
> Windows 10 Pro OS build: 19045.4046
> 
> ### Where did you download Cider from?
> GitHub
> 
> ### Describe the Bug
> I went to open cider upon turning on my pc as I usually do and It gave me the following message, "Cider is not responding. Reload the app?" I've ran it as admin, I've restarted my pc, deleted cider and all its folders and reinstalled cider and to no avail.
> 
> ### Steps to Reproduce
> I literally did nothing to cider for this to happen, it was working fine yesterday ;w;
> 
> ### Anything else?
> _No response_

this happens on linux too, very disappointing.
