### ISSUE TITLE
[Bug]: new iphone cannot sign in

### ISSUE THREAD

**Issue by xnjzewdo** [ciderapp/Cider#1834]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

1.6.0

### What operating system are you using?

Other (specify below)

### Operating System Version

Pop!_OS

### Where did you download Cider from?

Flathub

### Describe the Bug

I changed my old iPhone to my new one. Despite requests to sign in, it always failed. Just got stuck in a looped there. Pardon me for any breach of etiquette, I did read the rules. Discord's support sent me on a Discord-server where I have no writing rights and nobody (admins, mods, anyone) answers me - so I came here and made a bug report.

### Steps to Reproduce

1. Cider was already on
2. I made my purchase during the day and did various apple support stuff with it
3. Cider no longer signed in using Apple credentials

### Anything else?

I paid for my version but had to remove it, I guess I thought my browser had kept the payment details. Now I really wanna install again, and I'm not even sure which version is the best for me.

How do I proceed to get a link from which download is possible? My online banking is also temporarily down due to failed change of app from one phone to another. In an e-mail, I could provide details that only I remember...

**Comment by xnjzewdo** [comment]
> Cider 1.x is no longer actively maintained. We highly suggest moving to the newer version versions of the app available at https://cider.sh through official storefronts ex. Itch.io, or the Microsoft Store.

And because of that I paid for the new one! Maybe I got the release number wrong? I couldn't find it on the site. It might've been 2.6.0 for all I care.

**Comment by xnjzewdo** [comment]
I had to come here because all "support" Cider team had was a link to a discord-server, but you don't have writing rights. I tried reading the rules etc. I DM'd many people and none replied.

I'm sure there are flaws in my post, I'm not the best writer on pages like these, on Stack Exchange I get slaughtered.

Right now all I wanna is that page right after payment where you can download debs and appimages and whatnot, because I liked Cider 2 a lot.

**Comment by xnjzewdo** [comment]
Since it's near impossible to reach anybody from Cider - there are no e-mails and nobody on discord answers me - I'm just going to switch to Tidal.

**Comment by BrycensRanch** [comment]
> Since it's near impossible to reach anybody from Cider - there are no e-mails and nobody on discord answers me - I'm just going to switch to Tidal.

bro's bug report never got handled and he's down money 🤣
