### ISSUE TITLE
[Bug]: Clear playlist button not working

### ISSUE THREAD

**Issue by peddy22** [ciderapp/Cider#1840]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.3.2_3

### What operating system are you using?

Ubuntu

### Operating System Version

Kubuntu 23.10

### Where did you download Cider from?

GitHub

### Describe the Bug

The clear playlist button doesn't clear the songs

### Steps to Reproduce

Clicked on clear, playlist is not cleared (clearing songs one by one still works)

**Comment by peddy22** [comment]
to be clear this is the button i'm referring to
![image](https://github.com/ciderapp/Cider/assets/58948206/ab879a0e-dfb7-4f79-9a36-82598fa13161)

**Comment by peddy22** [comment]
The issue has been reported confirmed and addressed on the new cider bug
tracker, it should not have been posted here

Arno

**Comment by coredev-uk** [comment]
Please report cider 2.x bugs at https://github.com/ciderapp/Cider-2/
