### ISSUE TITLE
[Bug]: Cider cannot connect to Discord via RPC

### ISSUE THREAD

**Issue by lkxoayh** [ciderapp/Cider#1843]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.3.2_3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 lastest

### Where did you download Cider from?

Microsoft Store

### Describe the Bug

cannot connect to Discord via RPC, I've been having this problem for a few days now, and I can't find any solution...

### Steps to Reproduce

Just try and see

**Comment by coredev-uk** [comment]
Please report cider 2.x bugs at https://github.com/ciderapp/Cider-2/
