### ISSUE TITLE
[Bug]: 2.4.0.0 will not sign in

### ISSUE THREAD

**Issue by daosein** [ciderapp/Cider#1850]
### Preflight Checklist

- [X] I have read the [Support Disclaimer](https://docs.cider.sh/support/disclaimer) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/ciderapp/Cider/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/ciderapp/Cider/issues) for a bug report that matches the one I want to file, without success.
- [X] I have read the [troublshooting FAQs](https://cider.gitbook.io/welcome-to-gitbook/support/faqs#why-is-my-discordrpc-status-not-appearing) and none solved my issue.

### Cider Version

2.4.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux 6.5.0-28-generic #29-Ubuntu x86_64 x86_64 x86_64 GNU/Linux

### Where did you download Cider from?

GitHub

### Describe the Bug

Cider 2.4.0.0 will not successfully access Apple Music after successful sign in with Apple account that has current Apple music subscription. 

### Steps to Reproduce

I removed old Cider version with Apt, deleted ~/.config/Cider. Downloaded Cider 2.4.0.0 from itch.io and installed with apt.
When opening Cider app, app is refreshing, no images shown. I click sign in option. Apple music sign in widow appears, sign in fine with Apple ID, type in sign in code sent to phone by Apple, select 'Trust device'. Window closes and Cider is still not signed in and is not refreshing page, no music or anything visible. Reboot rinse & repeat.

### Anything else?

![Screenshot_20240513_125817](https://github.com/ciderapp/Cider/assets/12023758/0104a409-6d9e-44b1-a0cf-9d0c8aeff50e)

**Comment by coredev-uk** [comment]
This is a Cider-2 issue, please place issues as such in the [Cider-2 repo](https://github.com/ciderapp/cider-2).
