### ISSUE TITLE
Release in Flatpak format for Linux

### ISSUE THREAD

**Issue by mtomczynski** [ciderapp/Cider#195]
Currently, the app is available on AUR for Arch Linux users. By releasing it as a Flatpak, it'd cover all Linux distributions and would be the easiest option to install the app for Linux users.

Flatpak's can be hosted on Flathub servers: [https://flathub.org/](https://flathub.org/)

**Comment by coredev-uk** [comment]
I will take a look into this, I have been thinking that a Flatpak release would be ideal for a while. However, Electron Flatpak releases seem to require much more than a simple compilation using electron-builder. I'll post updates here if any developments occur.

**Comment by VelocityDesign** [comment]
Is it not possible to just compile the app into a binary and have the flatpak install that?

**Comment by VelocityDesign** [comment]
Awesome! Can't wait for it to be ready!

**Comment by coredev-uk** [comment]
> Awesome! Can't wait for it to be ready!
Since updating the status, we've managed to create a manifest file with all the necessary files. However, we are encountering a few issues with getting it working. 

For anyone who has any knowledge in flatpaks, any help would be appreciated. You can find the relevant files [here](https://github.com/ciderapp/Cider/blob/main/flatpak/).

**Comment by Thesola10** [comment]
I'm currently trying to build the flatpak for Cider, and it looks like it is failing due to a missing `yarn.lock` in the cider repo. Below is the error message:

```
error Couldn't find any versions for "@sentry/electron" that matches "^2.5.4" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by Syhlx** [comment]
You need to install Node JS dependecies before building the flatpak. For this you will need Yarn.

To do this: in the root folder of the repo, type "yarn" or "yarn install" and Yarn will automatically install the dependencies in the "node_modules" folder and add the "yarn.lock" file.

**Comment by Thesola10** [comment]
I did install the dependencies locally, but also had to specify the `yarn.lock` file as a source in the flatpak manifest. Will keep posted once the builder stops going `EAGAIN` at every DNS query

**Comment by lilianmoraru** [comment]
Microsoft Teams: https://github.com/flathub/com.microsoft.Teams/blob/master/com.microsoft.Teams.json
and
Skype: https://github.com/flathub/com.skype.Client/blob/master/com.skype.Client.json

could be a good source of inspiration for Electron-based apps.

More Flathub Electron apps: https://github.com/search?l=JSON&q=org%3Aflathub+org.electronjs.Electron2.BaseApp&type=Code

**Comment by jannuary** [comment]
I think most Electron apps on Flathub just repack the binary instead of building, since it doesn't have access to network

**Comment by EricZhang456** [comment]
https://docs.flatpak.org/en/latest/electron.html
Could this help?

**Comment by coredev-uk** [comment]
When creating the flatpak I utilized that guide and the quickstart.
