### ISSUE TITLE
Subscribe to artist

### ISSUE THREAD

**Issue by booploops** [ciderapp/Cider#21]
Ability to subscribe to artist to get latest release on startup
- Get the subscribed artists view info
- Compare the views.latest-release to the last known latest release stored locally
- Show new releases in a tab

**Comment by inalone** [comment]
Have been wanting this out of any Apple Music client I've ever used, would love to see it. MusicHarbor is a separate client for this, but is refusing to launch on my work laptop so I have to manually keep up with artists on social media to know about releases.

**Comment by gms10ur** [comment]
resolved

**Comment by grolschie** [comment]
Hi. This a great feature. Thank you!

Would it be possible to save this info/ these settings to a file somewhere in the user's home directory, so that when reinstalling or running multiple versions of Cider, users don't have to re-subscribe to their favourite artists each time please?
