### ISSUE TITLE
[Enhancement] Requesting permission to publish on Flathub as a Flatpak

### ISSUE THREAD

**Issue by rowbawts** [ciderapp/Cider#224]
**Is your feature request related to a problem? Please describe.**
I use a distro that doesn't support anything other then Flatpaks (for the most part) so I'd like to see a Flatpak release for this project.

**Describe the solution you'd like**
I can either request someone build this for you or I can do it myself, just looking for permission.

**Describe alternatives you've considered**
Not really any alternatives I can think of.

**Additional context**
It's already requested by someone else on Flathub's [Discourse](https://discourse.flathub.org/t/cider-apple-music-flatpak-request/2116/2)

**Comment by quacksire** [comment]
commented on post.

I don't think we're ready yet

**Comment by quacksire** [comment]
clone of #195
