### ISSUE TITLE
[Enhancement] Add '1' on one song repeat button icon

### ISSUE THREAD

**Issue by OctopusET** [ciderapp/Cider#226]
**Is your feature request related to a problem? Please describe.**
One song repeat button only changes to gray, so it's hard to see difference. 

**Describe the solution you'd like**
I think it would be much better if it has '1' on icon. Like original apple music app does.

**Describe alternatives you've considered**
It would be better if it has color like whole song repeat button does

**Comment by gms10ur** [comment]
I Might be able to do this, nice suggestion imo. I will let you know if I do. (It will be on upcoming if I make it tho fyi)

**Comment by maikirakiwi** [comment]
Resolved
