### ISSUE TITLE
[BUG] Can't connect to LastFM

### ISSUE THREAD

**Issue by OctopusET** [ciderapp/Cider#227]
**Describe the bug**
LastFM connect button works, and it brings me to account connection page, but It doesn't bring me back to cider app. Even I can get token.
I think cider::// is not recognized on my system. 

**To Reproduce**
1. Go to Connectivity section on  'Settings'
2. Click on 'connect'
3. Click on 'YES, ALLOW ACCESS'
4. Not thing happens only reload website page.

**Expected behavior**
Able to connect to LastFM.

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: ArchLinux 
 - Application Version *(e.g. 2.5.0)*: Build with Latest commit

**Comment by CalebJohnathen** [comment]
Try restarting the app after you connect to last.fm

**Comment by OctopusET** [comment]
@CalebJohnathen It's still not working, I think cider:// URL brings me to Firefox not to cider.

**Comment by quacksire** [comment]
> @CalebJohnathen It's still not working, I think cider:// URL brings me to Firefox not to cider.

wat? where are you opening the cider:// link?

**Comment by quacksire** [comment]
> **Describe the bug** LastFM connect button works, and it brings me to account connection page, but It doesn't bring me back to cider app. Even I can get token. I think cider::// is not recognized on my system.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to Connectivity section on  'Settings'
> 
>     2. Click on 'connect'
> 
>     3. Click on 'YES, ALLOW ACCESS'
> 
>     4. Not thing happens only reload website page.
> 
> 
> **Expected behavior** Able to connect to LastFM.
> 
> **Environment Information**
> 
>     * OS _(e.g. Linux/Mac/Windows)_: ArchLinux
> 
>     * Application Version _(e.g. 2.5.0)_: Build with Latest commit

try doing ``cider:auth/lastfm``, see what happens

**Comment by kiosion** [comment]
Same issue; xdg-open doesn't recognize `cider://` as a url that should be opened by the cider program.

**Comment by coredev-uk** [comment]
> Same issue; xdg-open doesn't recognize `cider://` as a url that should be opened by the cider program. Edit: also applies to the Discord integration, the 'Listen on Cider' button in rich presence isn't handled right

Is this with the AUR package?

**Comment by coredev-uk** [comment]
Should be resolved.
