### ISSUE TITLE
[Enhancement] Cantonese Translations

### ISSUE THREAD

**Issue by tszngaiyip** [ciderapp/Cider#238]
I would like to have a Cantonese version in this apps.

**Comment by maikirakiwi** [comment]
Both Traditional and Simplified Chinese are available.

**Comment by tszngaiyip** [comment]
Cantonese is different from tradition Chinese. Cantonese is not as formal as Chinese, it’s more like to use in conversation

**Comment by maikirakiwi** [comment]
That's a huge ask because considering a lot of apps only have Traditional/Simplified Chinese, and Cantonese written in apps as an i18n language are generally not seen. Native Cantonese speakers can read either Simplified or Traditional Chinese anyway.

**Comment by tszngaiyip** [comment]
If Hong Kong people find it has Cantonese version. It will attract more people to use this app.

**Comment by vapormusic** [comment]
hmm, is there already traditional (hk) in the app?

**Comment by maikirakiwi** [comment]
![DPuZgEfltHrYGRBk](https://user-images.githubusercontent.com/74925636/151499578-9841ee91-d0ae-4c5a-9c02-dce9afdacb79.png)

**Comment by maikirakiwi** [comment]
I allowed trad. HK to be added because there are minute differences even though its not outlined in ISO standards.
However, iOS itself does not even have Cantonese as a UI language.
only Trad. Chinese (Hong Kong) which we already have.

**Comment by vapormusic** [comment]
Like what is the difference in writing between Trad. Chinese (Hong Kong) and Cantonese? I think one is written and one is spoken, am I wrong here?

**Comment by tszngaiyip** [comment]
> Like what is the difference in writing between Trad. Chinese (Hong Kong) and Cantonese? I think one is written and one is spoken, am I wrong here?

Yes, you are right.

**Comment by tszngaiyip** [comment]
> I allowed trad. HK to be added because there are minute differences even though its not outlined in ISO standards. However, iOS itself does not even have Cantonese as a UI language. only Trad. Chinese (Hong Kong) which we already have.

I know that most UI interface translations for applications in the Hong Kong market are typically written using a modernized literary grammar based on Mandarin grammar. If we can make a Cantonese version like Telegram and Signal, which are the communication app, it is a big step for protecting this language. Also, making a Cantonese version is shown that you are really care about Hong Kong market. 
If you accept my opinion, I would like to be the volunteer to translate the language to Cantonese.

**Comment by quacksire** [comment]
If you want, do you mind helping us translate?

**Comment by tszngaiyip** [comment]
> If you want, do you mind helping us translate?

Sure

**Comment by quacksire** [comment]
https://github.com/ciderapp/Cider/tree/upcoming/src/i18n

If you look at some of the files, you see how we're doing it.
