### ISSUE TITLE
[BUG] Library Loading Stuck

### ISSUE THREAD

**Issue by Joonas12334** [ciderapp/Cider#247]
**Describe the bug**
When going to any of the library tabs it just gets stuck on a random number and never loads my songs/albums/artists or recently added list.

**To Reproduce**
1. Go to any of the library tabs

**Expected behavior**
I expected to see all my songs.

**Screenshots**
<img width="1020" alt="bug" src="https://user-images.githubusercontent.com/62062088/151655533-42d8f89f-ecc1-4348-a854-5d5e407dcde4.png">

**Environment Information**
 - OS Windows 11 Pro 64Bit
 - Application Version 1.0.4.0 Windows Store

Log or troubleshooting guides don't seem to apply here.

**Comment by coredev-uk** [comment]
Please do CTRL + Shift + I and click console and show the output messages

**Comment by Joonas12334** [comment]
Sure, here you go. Hope it's any help :) 
<img width="1020" alt="image" src="https://user-images.githubusercontent.com/62062088/151655846-c4881c4a-991b-4cb6-b26d-f84e976e740f.png">

Thank you for such fast reply!

**Comment by yazninja** [comment]
Im pretty sure its because the songs are still loading in... Check bottom left

**Comment by coredev-uk** [comment]
That's the issue, it's stuck.

**Comment by Joonas12334** [comment]
They've been loading for about 30min now :(

**Comment by coredev-uk** [comment]
Have you attempted to remove the %APPDATA%/Cider folder?

**Comment by Joonas12334** [comment]
Will try that now.

**Comment by coredev-uk** [comment]
Another thing that you might be able to do is click on Songs and pressed the retry button

**Comment by Joonas12334** [comment]
I'm not seeing the Cider folder in appdata, not in any of the 3 (Local, LocalLow, Roaming)

**Comment by coredev-uk** [comment]
is there a cider low lowercase c?

**Comment by Joonas12334** [comment]
There isn't unfortunately. I'm using windows store version as well if that's any help

**Comment by coredev-uk** [comment]
Yeah just saw that, not sure where Windows store appdata is stored

**Comment by Joonas12334** [comment]
When trying the retry button.

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/62062088/151656019-7187cfc8-08d4-4d41-8004-30295d2983af.png">

**Comment by coredev-uk** [comment]
Try %APPDATA%/local/packages?

**Comment by Joonas12334** [comment]
Yeah, found a folder named 27554FireDevElijahKlauman.CiderAlpha_270bejk4xgzqp

**Comment by coredev-uk** [comment]
Is that what is inside it?

**Comment by Joonas12334** [comment]
Correct

**Comment by coredev-uk** [comment]
delete AppData presuming it has the Cider folder and only that inside.

**Comment by Joonas12334** [comment]
AppData folder is empty with no hidden files as well. Will delete it anyways

**Comment by coredev-uk** [comment]
Try and find a folder that has the following inside: 
![image](https://user-images.githubusercontent.com/64542347/151656198-d15d3908-c641-4816-b0dd-99917a1ccade.png)

**Comment by coredev-uk** [comment]
Doesn't need to be exact, but along the same lines, and delete all of it

**Comment by Joonas12334** [comment]
Huh, found a folder in 27554FireDevElijahKlauman.CiderAlpha_270bejk4xgzqp\LocalCache\Roaming\Cider that looks what we are looking for 
<img width="603" alt="image" src="https://user-images.githubusercontent.com/62062088/151656213-865324ce-f85d-497c-bb90-fabfe16be9b7.png">

**Comment by Joonas12334** [comment]
Deleted, will restart the application

**Comment by coredev-uk** [comment]
You will need to sign in and config the app again.

**Comment by yazninja** [comment]
also followed artists will be reset too

**Comment by coredev-uk** [comment]
Yeah sorry, forgot about that

**Comment by Joonas12334** [comment]
No hard done. Logged back in and it seems to get stuck in the same place again 
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/62062088/151656310-98a76db1-e52a-405f-8ac0-243f19612018.png">

**Comment by coredev-uk** [comment]
Must be an issue with the API call then, I'll have to forward this to the rest of the dev team as I don't know what else you can do. Sorry I couldn't be more help.

**Comment by vapormusic** [comment]
hmm could be that there is some unique/invalid songs in the library that cause all of this to be stopped

**Comment by Joonas12334** [comment]
The update fixed it. No idea when it updated but after relaunching the app I noticed my library loading and some new items in the library tab. Windows Store version went from 1.0.4.0 to 1.1.0.0 Whatever you guys/girls did it worked! Thank you!

**Comment by Joonas12334** [comment]
I guess I was celebrating a bit too early. The songs tab now loads however the albums, recently added and artists get stuck.
Heres a view of the network activity as well 
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/62062088/151679378-aafac985-6385-404a-877f-252e0a96c473.png">

**Comment by Joonas12334** [comment]
Extreme audio quality setting has disappeared as well :(

**Comment by maikirakiwi** [comment]
> Extreme audio quality setting has disappeared as well :(

They never were really implemented in the first place.
We just took that placeholder out because it did nothing.

**Comment by vapormusic** [comment]
> I guess I was celebrating a bit too early. The songs tab now loads however the albums, recently added and artists get stuck. Heres a view of the network activity as well <img alt="image" width="1244" src="https://user-images.githubusercontent.com/62062088/151679378-aafac985-6385-404a-877f-252e0a96c473.png">

thanks for showing this, can you click on the red (failed) connection in the network tab and share it please. Looks like apple sometimes does not like our query parameters.

**Comment by Joonas12334** [comment]
> > I guess I was celebrating a bit too early. The songs tab now loads however the albums, recently added and artists get stuck. Heres a view of the network activity as well <img alt="image" width="1244" src="https://user-images.githubusercontent.com/62062088/151679378-aafac985-6385-404a-877f-252e0a96c473.png">
> 
> thanks for showing this, can you click on the red (failed) connection in the network tab and share it please. Looks like apple sometimes does not like our query parameters.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/62062088/151760330-a1cba756-8e92-4185-82e9-9ff23f26e390.png">
Here you go! I hope it's any help
