### ISSUE TITLE
[Enhancement] Compatability with MPRIS

### ISSUE THREAD

**Issue by JustAnotherStrange** [ciderapp/Cider#260]
**Is your feature request related to a problem? Please describe.**
I'm on Linux. My keyboard has a pause button on it, which I've bound to run the command `playerctl play-pause`, which uses the MPRIS Dbus protocol to play/pause whatever is currently playing. It doesn't work with Cider.

**Describe the solution you'd like**
There seems to be a [node library](https://www.npmjs.com/package/mpris-service). It looks pretty good. It could be used for all the metadata stuff too, but the only part of it I'm interested in is the playing and pausing feature.

**Describe alternatives you've considered**
Maybe writing a small command line program that imitates the web requests of the web remote controller, and then binding that to my play/pause key. If the MPRIS implementation proves impossible, this is what I will probably do.  

**Additional context**
The `playerctl` program on Linux is a very clear way to access MPRIS data. 
[Info on MPRIS](https://wiki.archlinux.org/title/MPRIS)

P.S. I'm loving this piece of software!! It's a lifesaver; the web app for Apple Music is so terrible.

**Comment by quacksire** [comment]
MPRIS has already been i[mplemented](https://github.com/ciderapp/Cider/blob/main/src/main/plugins/mpris.ts
). Are you using an old version of Cider?

**Comment by coredev-uk** [comment]
What version are you using @JustAnotherStrange

**Comment by JustAnotherStrange** [comment]
Interesting. I can't seem to find what version I'm using, but I will switch to `cider-git` AUR package, and see if that fixes it.
It didn't; 
![image](https://user-images.githubusercontent.com/64844168/151685552-9a53b260-ecc9-40be-8fa3-e6103636d592.png)
This is while I am hearing music play. I wondered if it's a playerctl issue; But playerctl works fine controlling music playing in my browser. This is on the `cider-git` package from the AUR.

**Comment by coredev-uk** [comment]
I mean the package version from the AUR, that's using the commit id

**Comment by coredev-uk** [comment]
I used playerctl to test this when developing the MPRIS plugin so should be an issue with that.

**Comment by JustAnotherStrange** [comment]
It says version `cider-git 1.1.0.1500.d68807b-1` (latest commit, I just updated)
It still doesn't seem to be working. I even tried to use the `dbus-send` command without any abstractions:
![image](https://user-images.githubusercontent.com/64844168/151701532-a9e78926-2dc2-49c6-9e17-c04de12fda45.png)
That's a weird bug. 
![image](https://user-images.githubusercontent.com/64844168/151701708-2d86fd0d-9327-41a4-a3b6-e82590be31fa.png)
A possible culprit could be it thinking I'm not running Linux and preventing the entire plugin from running?
![image](https://user-images.githubusercontent.com/64844168/151701945-252e2174-682a-433d-8ae9-14f2cdc816f9.png)
Yet, in the console, it shows I am using Linux as my user agent.
The other plugins (last.fm, discord rpc) are there and are working fine. 
I wonder if I could turn on the console debug messages to see if the plugins are all starting up correctly, but I don't know how to do that, as I'm a bit of an amateur when it comes to JS/TS.

I hope this was helpful.

**Comment by devyntk** [comment]
I'm getting similarly confusing functionality with no MPRIS support. I'm running `1.1.0.1648.ac38a4e-1` - just updated from the AUR. Discord Rich Presence also seems to be broken for me. When launching with verbose, no plugins seem to be loading at all:
```
[AppEvents] App started
[Cider] User has launched the application with --verbose
[PluginHandler] Loaded plugins: []
```

**Comment by coredev-uk** [comment]
> 

We are aware of what was causing this issue and it should be resolved now.

**Comment by coredev-uk** [comment]
> It says version `cider-git 1.1.0.1500.d68807b-1` (latest commit, I just updated) It still doesn't seem to be working. I even tried to use the `dbus-send` command without any abstractions: ![image](https://user-images.githubusercontent.com/64844168/151701532-a9e78926-2dc2-49c6-9e17-c04de12fda45.png) That's a weird bug. ![image](https://user-images.githubusercontent.com/64844168/151701708-2d86fd0d-9327-41a4-a3b6-e82590be31fa.png) A possible culprit could be it thinking I'm not running Linux and preventing the entire plugin from running? ![image](https://user-images.githubusercontent.com/64844168/151701945-252e2174-682a-433d-8ae9-14f2cdc816f9.png) Yet, in the console, it shows I am using Linux as my user agent. The other plugins (last.fm, discord rpc) are there and are working fine. I wonder if I could turn on the console debug messages to see if the plugins are all starting up correctly, but I don't know how to do that, as I'm a bit of an amateur when it comes to JS/TS.
> 
> I hope this was helpful.

Try using playerctl to get the metadata of that dbus. Check if it is Cider, as sometimes the mpris instance does fail and it will fallback to the chromium media handling.

**Comment by JustAnotherStrange** [comment]
I just updated to the latest commit and the plugin seems to be working.
![image](https://user-images.githubusercontent.com/64844168/152172614-6ec35cfe-76a3-4f90-8012-8afe177c0242.png)
Thank you! I will close this now because I think it is solved.
