### ISSUE TITLE
Unban

### ISSUE THREAD

**Issue by DoctorAnon** [ciderapp/Cider#27]
Unban Arctic Anon

List of grievances:

Suicide Threats - Not s, it's singular and not even a threat it was a joke in response to someone obsessing over beiber.

Weird 4chan stuff - how is this even a bannable offense it violated no rules I literally just mentioned it 

Harassment of users - k I'll stop, and the intention was banter not harassment

Taking over the member list - ??? I was not involved in that in any way whatsoever. I only became aware of it when I was pinged 

@cryptofyre

**Comment by child-duckling** [comment]
You violated the main rule of our Discord Server.

> 1. Treat everyone with respect. Absolutely **no** harassment, witch hunting, sexism, racism, or hate speech will be tolerated.


Your unban request will not be fulfilled.

**Comment by cryptofyre** [comment]
You’re actions were against Discord TOS and threatened people on the server. Ban is still instated.
