### ISSUE TITLE
[BUG] Renaming a folder causes it to disappear (Windows10)

### ISSUE THREAD

**Issue by TravisC1** [ciderapp/Cider#271]
**Describe the bug**
I can create a new playlist folder, but when I rename it from the default "New Folder" the folder disappears from the sidebar (I scrolled down and it hasn't just moved position).

**To Reproduce**
1. Right click Playlists in sidebar and select New Playlist Folder
2. Right click folder called "New Folder" that is created and type a new name. Press enter when complete.
3. Folder disappears and is not in the list at all.

**Expected behavior**
Folder should have a new name and show in the list of playlists

**Environment Information**
 - OS *Windows 10*: 
 - Application Version *Latest from Windows Store. An aside- checked  the 'About' screen in-app and there's no version number written there. Might be useful to add that in future?*: 
 
**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
No open issues for folder creation found when I search 'folder'. Can not find "verboseLogging" in prefs to turn it on to generate a log file.

**Log File**
See above. Can not turn on verbose logging.

**Comment by damian-kociszewski** [comment]
Same thing happens on macOS Monterey 12.2.1
The playlist just disappears, even when you reload the app it's not there.

**Comment by quacksire** [comment]
> Might be useful to add that in future?
Added
