### ISSUE TITLE
[BUG] Performance Issues on Windows 10

### ISSUE THREAD

**Issue by np22-jpg** [ciderapp/Cider#272]
**Describe the bug**
Not really any lag, but I am experiencing high CPU and GPU usage on this [commit](https://github.com/ciderapp/Cider/commit/8476e6d70d0546360317ab26f68129c21afbf672). I'm running an i5-7300U with integrated graphics, if that helps. Sorry if this is to be expected on this hardware.
Edit: This only happens when the app is in the foreground. When minimized/hidden, there is no performance issue and CPU/GPU usage drops greatly.

**To Reproduce**
1. Compile the linked commit on windows 10
2. Run the software
3. Bring Cider into the foreground and observe the performance hit

**Expected behavior**
Mildly lower CPU/GPU usage.

**Screenshots**
<img width="728" alt="Capture" src="https://user-images.githubusercontent.com/41604897/151750664-ff04485f-9c24-43fa-a1f8-d7288fb2dd9a.PNG">

**Environment Information**
 - OS Windows 10
 - This [commit](https://github.com/ciderapp/Cider/commit/8476e6d70d0546360317ab26f68129c21afbf672)
 
**Additional context**
Nodejs 17

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
No
I did try setting "hw_acceleration" to "true" under "visual" in cider-config.json. Didn't really do anything.

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Can't figure out how to enable logging

Edit: Figured out this only happens when the app is in the foreground

**Comment by TanKot** [comment]
Also experiencing the same thing on windows 11

**Comment by gms10ur** [comment]
try disabling the hardware acceleration and background artwork from the app settings,

**Comment by booploops** [comment]
Are animated window background enabled or is animated artwork set to always?

**Comment by TanKot** [comment]
Yep it was.
I turned them off and now its good, Thanks!

**Comment by np22-jpg** [comment]
Worked for me! Thanks!

**Comment by JensMertelmeyer** [comment]
I would like to chime on here - I had a about 2 frames per second with Corei5 and integrated graphics. After disabling Hardware acceleration, it runs butter smooth.

Is there anything info I can provide to find the cause why it was so *extremely slow*?
