### ISSUE TITLE
[BUG] Updating to new version uninstalls Cider

### ISSUE THREAD

**Issue by TanKot** [ciderapp/Cider#274]
**Describe the bug**
Updating to new version uninstalls Cider

**To Reproduce**
1. Go to the Cider discord server.
2.  Send a message "/nightly"
3. Download The File for windows
4. Run the file
5. Go through the installer(it will stop halfway, and uninstall cider)
6. This is the bug. Running the installer once more will fix it.

**Expected behavior**

**Environment Information**
 - OS: Windows
 - Application Version: 1.1.0

**Comment by quacksire** [comment]
what? Hilarious! we can't do anything about this unfortunately.
