### ISSUE TITLE
[BUG] Clicking the artist on a Recently Played album on the home screen doesn't always go to the correct artist

### ISSUE THREAD

**Issue by madriemx** [ciderapp/Cider#282]
**Describe the bug**
I have recently played songs from the albums Commute and Ctrl-Alt-Del by The Diggs, but clicking on the artist link under those albums on Recently Played goes to the artist page for Daveed Diggs

**To Reproduce**
1. Play a song by The Diggs
2. Go to the Home screen
3. Click on the artist link for The Diggs under Recently Played
4. End up on Daveed Diggs page

**Expected behavior**
I expected the artist page for The Diggs to open.

**Screenshots**
![image](https://user-images.githubusercontent.com/74277456/151875845-6acf732e-9972-43c9-897e-5f2c6c5483aa.png)
![image](https://user-images.githubusercontent.com/74277456/151875867-46d06c8c-8cfd-490f-bca7-7afc6783ce7d.png)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Ubuntu 21.10 amd64
 - Application Version *(e.g. 2.5.0)*: tested on both 1.0.0 and commit 36a5521 (latest at time) built from source, installed with .deb
 
**Additional context**

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.
I can't find the log file for Cider, it's not in the same location as linked for AME

**Comment by cryptofyre** [comment]
We are currently manually searching the artist by the name but this should be resolved soon.

**Comment by TreeHouseFalcon** [comment]
Currently trying to get a pull request to help resolve it. It seems like it's a relatively easy issue to fix although I don't know if my solution has any side effects.
