### ISSUE TITLE
[Bug]: App does not remember position on 2nd monitor

### ISSUE THREAD

**Issue by TheMasterDingo** [ciderapp/Cider#294]
### Describe the Bug

App does not remember position on 2nd monitor, if i set it maxed on my 2nd monitor, close it, reopen it still opens on the main one , it remembers dimensions though

### Steps to Reproduce

open app
position it full screen on other monitor
close app
open app
it opens on the main monitor again

### Environment Information

- OS: Windows 11
- App Version: 1.1.0 ( got it from /nightly discord)
- Commit ID:

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Known issue for the module used for window state handling. Ref. [#27](https://github.com/mawie81/electron-window-state/issues/27).

**Comment by TheMasterDingo** [comment]
I tested the build here on github, it works fine for me
