### ISSUE TITLE
mpris not reporting 'Cider' as name of instance

### ISSUE THREAD

**Issue by inalone** [ciderapp/Cider#30]
Pretty simple issue probably - I'm currently making a Python script which hooks into Cider's mpris instance and scrobbles to last.fm, but while making this I found that Cider's mpris instance reports itself as a generic chromium instance so dbus-python can't hook itself to it due to having a . in the name.

While playing in Apple Music Electron:
![image](https://user-images.githubusercontent.com/60921914/146683058-31801dcb-bf41-48ce-86a7-d1fc8301cc6c.png)

While playing in Cider:
![image](https://user-images.githubusercontent.com/60921914/146683082-8367f072-f890-4570-9991-cee8acaa0815.png)

get_dbus.sh is just a simple echo statement which is handy for debugging this kinda thing:
`echo "$(dbus-send --session --dest=org.freedesktop.DBus \
        --type=method_call --print-reply /org/freedesktop/DBus \
        org.freedesktop.DBus.ListNames | grep org.mpris.MediaPlayer2 |
        awk -F\" '{print $2}' | cut -d '.' -f4- | sort )"
`

**Comment by cryptofyre** [comment]
MPRIS has not been globally configured yet. We have no efficient way to pull any information for songs yet (coming soon).

**Comment by inalone** [comment]
That makes sense - it always reports perfectly fine in the GNOME media controls so I thought it would be fine to hook into, but if it's a WIP I'll abandon the script and keep manually scrobbling for now.

**Comment by coredev-uk** [comment]
I have added the initial code to the backend, I just need to format it all and as I think we are going to use a plug-in system for a lot of this, the mpris service needs to be cleaned figured in that way

**Comment by coredev-uk** [comment]
Currently implemented and will not be an additional plugin, but base functionality, just as it will be with Discord Rich Presence.
