### ISSUE TITLE
[Enhancement]: Playback controls from the command line

### ISSUE THREAD

**Issue by Lerbiq** [ciderapp/Cider#313]
### The feature you would like

When you'd do `cider --next/prev/play` with cider open it would skip to the next/previous song in queue and pause or resume, depending if the song is playing or is paused.

This feature would be mainly useful for people using Cider with minimal window manager setups where media playback control using the keyboard is problematic. Simple script using this feature would allow people to use them with Cider.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Are you on Windows or Linux?

**Comment by booploops** [comment]
I just added a simple API into the develop branch with these endpoints if you want to give that a try
```
http://localhost:9000/api/playback/playpause
http://localhost:9000/api/playback/play
http://localhost:9000/api/playback/pause
http://localhost:9000/api/playback/next
http://localhost:9000/api/playback/previous
```

**Comment by Lerbiq** [comment]
> Are you on Windows or Linux?

I'm on Linux

**Comment by Lerbiq** [comment]
> > > Are you on Windows or Linux?
> > 
> > 
> > I'm on Linux
> 
> Try using playerctl

Thank you, it works. Didn't know something like this existed.
