### ISSUE TITLE
[Bug]: Discord Rich Presence not working on v1.1.0.74

### ISSUE THREAD

**Issue by yslupdates** [ciderapp/Cider#315]
### Describe the Bug

Hey I downloaded [Cider Nightly v1.1.0.74 from winstall.](https://winstall.app/apps/CiderCollective.Cider.Nightly) I currently do not have Discord Rich Presence working. I installed the .exe file and the app runs fine with the setting for discord rich presence turned on. I have windows 11 on latest updates, please let me know what I need to do to fix.

### Steps to Reproduce

1. Install Cider Nightly from winstall page (which is linked in this github repo)
2. Play a song
3. don't see discord rich presense

### Environment Information

- OS: Windows 11
- App Version: v1.1.0.74
- Commit ID: Unsure how to tell, I just downloaded exe from winstall page

### Anything else?

App is awesome besides this one issue! Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Resolved in the develop branch. Main push will be done soon to make fixes accessible to all users.
