### ISSUE TITLE
[Bug]: Persistent "Sign In" button after signing in.

### ISSUE THREAD

**Issue by grolschie** [ciderapp/Cider#317]
### Describe the Bug

After signing in to Apple Music, the "Sign In" button remains at the bottom left of the window.

I can use the app as I should, except I cannot find the Preferences option.

### Steps to Reproduce

1. Download Cider (Alpha) from Microsoft Store
2. Sign In with Apple ID

It doesn't matter if I reboot the PC, the "Sign In" button still remains. 

### Environment Information

- OS: Windows 11
- App Version: 1.1.0.0 (Microsoft Store version)
- Commit ID: n/a

### Anything else?

I am currently 3 month trialing an Apple Music "Family" subscription, and am not the main account holder. 

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by grolschie** [comment]
![cider](https://user-images.githubusercontent.com/625810/152437558-66289b2a-976d-42ab-a351-292c95d22072.png)

**Comment by quacksire** [comment]
1. Try doing `Control + R` when this happens again
2. Do `Control + Shift + I` and give us a screenshot (It'll help us help you)

**Comment by grolschie** [comment]
It happens permanently. Is this what you are after?
![screenshot](https://user-images.githubusercontent.com/625810/152446352-5da7047c-ddcb-419a-9f05-01cd4ca05970.png)

**Comment by grolschie** [comment]
The log from that window:
[localhost-1643931160056.log](https://github.com/ciderapp/Cider/files/7998964/localhost-1643931160056.log)

**Comment by grolschie** [comment]
After installing CiderCollective.Cider.Nightly Version 1.1.0.74 the "Sign In" button is replaced with "Cider User CiderUser
![cider](https://user-images.githubusercontent.com/625810/152448537-5b82540b-ddaf-4585-8bda-41e841289e92.jpg)
[localhost-1643932314764.log](https://github.com/ciderapp/Cider/files/7999015/localhost-1643932314764.log)
"

**Comment by quacksire** [comment]
Can you take a screenshot of the console tab of the dev tool. Should've been more specific, sorry :/

**Comment by grolschie** [comment]
Hi. Thanks. I have already uploaded .log files from the console. But here you go:

![Untitled](https://user-images.githubusercontent.com/625810/152461921-54f92ae7-fe1f-48f7-9697-5e36d69cc892.png)

The attached .log file and the screenshot are from the console tab of the Microsoft Store version of Cider.

**Comment by grolschie** [comment]
Hi. What more info do you need?

**Comment by gordallott** [comment]
also have this issue, console log looks functionally identical here. Only thing to note is that I'm also on the three month trial, and I am the main account holder.

**Comment by vapormusic** [comment]
@grolschie @gordallott fixed in develop branch, you guys can join the discord server and type /nightly to get those latest builds
