### ISSUE TITLE
[Enhancement]: Fast Forward and Rewind Buttons not Working 

### ISSUE THREAD

**Issue by dmuraco3** [ciderapp/Cider#318]
### The feature you would like

I use Fast Forward and rewind button a lot. This would be nice feature if possible 

![image](https://user-images.githubusercontent.com/70153277/152443868-1d5dd06b-9fc8-459d-88e9-8a9b3b2eab0f.png)

### Alternatives and Other Information

Willing to work on this

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
I think these are considered media keys, I'm not sure, I'll look into it.

**Comment by dmuraco3** [comment]
Thanks @quacksire . It works now for some reason after re installing.
