### ISSUE TITLE
[Bug]: Freeze when opening queue for large song library

### ISSUE THREAD

**Issue by devyntk** [ciderapp/Cider#319]
### Describe the Bug

I have a very large song library (close to 2.5k songs) and often will just throw this on shuffle. This freezes the app almost entirely if i ever open the queue requiring the app to quit. The song will keep playing during this but no new songs will play after.

### Steps to Reproduce

1. Get a very large song library
2. Open the queue for the library

### Environment Information

- OS: Arch Linux
- App Version: 1.1.0
- Commit ID: 1651.fdcffc1 (from arch package name)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SkyRexHUN** [comment]
Having the same problem with over 5000 songs.
