### ISSUE TITLE
[Bug]: "More to explore" section is not populated

### ISSUE THREAD

**Issue by tebowy** [ciderapp/Cider#323]
### Describe the Bug

The "More to explore" section is not populated in Cider, as visible on screenshot. It is visible in AM web, and AM electron (the background app on this screenshot)

![image](https://user-images.githubusercontent.com/3144357/152522401-5ac03887-4f76-46dc-bdcf-87986ff1e40b.png)

### Steps to Reproduce

1. Clicked on Browse
2. Scrolled down
3. Noticed "More to explore isn't there"

### Environment Information

- OS: Windows 11
- App Version: 1.1.0.0
- Commit ID: can't see from within the app

### Anything else?

This is the Windows Store build

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tebowy** [comment]
well duh, it's still like that

**Comment by cryptofyre** [comment]
been fixed in 1.5.0
![image](https://user-images.githubusercontent.com/33162551/171752240-b4b7eefe-26c5-45cf-9420-3825556c7f81.png)

**Comment by tebowy** [comment]
> been fixed in 1.5.0 

Uhm, is there any ETA for 1.5.0 rlease on MS Store?

**Comment by cryptofyre** [comment]
June 9th.
