### ISSUE TITLE
[Bug]: Never-ending loading in artist feed

### ISSUE THREAD

**Issue by Monochromish** [ciderapp/Cider#324]
### Describe the Bug

The artist feed will have a never-ending loading animation if not following any artists.
It should instead show a message such as "Follow some artists first and their latest releases will be here" or something similar.

Refer to the GIF image provided below

### Steps to Reproduce

1. Have no artists followed on Cider
2. Go to Home Tab
3. Click on the 'See All' button on 'Your Artists feed'

### Environment Information

- OS: Windows 11 Home x64
- App Version: 1.1.0.184 (Nightly)
- Commit ID: -

### Anything else?

![Cider_ZLFsHdVtm8](https://user-images.githubusercontent.com/79590499/152535327-32adb2f2-0184-43c5-a192-5eafa48ad342.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
> The feed is always infinite. It simply doesn't work, at least on my system (Arch Linux)

hmm works on my case, can you see in the devtools ( by ctrl+f11) whether that request is rejected by apple or not>

**Comment by kgarner7** [comment]
I'm another user affected by this bug, also running Arch Linux. 
Examining the devtools shows that I get the following error (at the time, the request had 162 artists)

```json
{"errors":[{"id":"...","title":"Too Many Ids","detail":"Too many ids specified on the request for resource type 'artists' (limit: 50)","status":"400","code":"40010","source":{"parameter":"ids"}}]}
```
