### ISSUE TITLE
[Bug]: Last.fm Scrobbling is Very Janky

### ISSUE THREAD

**Issue by JustAnotherStrange** [ciderapp/Cider#328]
### Describe the Bug

When I play a song, even if for a couple seconds, and then skip to a different song, Cider chooses to scrobble the song. This is especially a problem when I skip 5 or 6 songs in a playlist, looking for the one song I want, and it scrobbles all of them. Instead, it shouldn't scrobble the songs that were only played for a few seconds, and (possibly as a setting) wait until a significant amount of the song has been played to scrobble it.

Thanks for the hard work on this software! If this and the other feature request I made were both implemented, then I would be 100% daily driving this. If I was fluent in JS/TS I would have made a PR instead. See the "Anything else" section for proposed solutions I came up with.

Thanks!!

### Steps to Reproduce

1. Make the last.fm connection
2. Play a bunch of songs for only a few seconds each, skip around
3. See that all of the songs were scrobbled, despite barely being listened to

### Environment Information

- OS: Arch Linux
- App Version: Latest Commit
- Commit ID: Latest (just updated before typing this Issue)

### Anything else?

This is probably related to this code.
![image](https://user-images.githubusercontent.com/64844168/152613606-43f2f1ed-9150-4c86-af0e-ce8abde583d2.png)
In the `lastfm.ts` file.
It scrobbles no matter what on playback state change. 
In fact, these are the only two times `scrobbleSong` is called. 
https://github.com/ciderapp/Cider/blob/71bdb0160842130b375bf7e270e7f550d6d172c8/src/main/plugins/lastfm.ts#L81
The "% Delay" doesn't seem to make it so it'll only scrobble after 99% of the song is played; it'll just delay after the song has been called to be scrobbled, and do it anyway, despite the amount of song that has been played.

Some possible solutions:
1. making it, within the `scrobbleSong` function, only scrobble if X amount (adjustable in settings) of the song's duration has been played. Another possible solution would be to change the functions that call `scrobbleSong` to only call it if the song has been played X amount.
2. If the percent of runtime of the song isn't possible, it could also just be an amount of time, e.g. only scrobble if the song has been played for 30 seconds. That might be easier to implement, but it's less optimal than the previous one I said.
3. Or, even simpler, you could make it so it doesn't scrobble if the song was skipped, no matter what. It only does it if the song was finished.

Either one of these would work great for my use case. If you think of something else that would work, then that's fine too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Ref. #106

**Comment by inalone** [comment]
Fixed in https://github.com/ciderapp/Cider/pull/502
