### ISSUE TITLE
[BUG] Apple Music Social Account Information Fetch

### ISSUE THREAD

**Issue by FluffyCuteOwO** [ciderapp/Cider#34]
**Describe the bug**
the profile is not displayed

**To Reproduce**
1. Go to 'cider'
2. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/17436886/146996336-8c4be3be-8d1d-43e7-a367-3858db5c804d.png)

**Environment Information**
 - OS *Windows*: 
 - Application Version *latest*: 
 
![image](https://user-images.githubusercontent.com/17436886/146996564-b9218af3-1057-4a96-899b-b9bb57d7bdfc.png)

**Comment by inalone** [comment]
Do you have an Apple Music social profile? I had the same issue and I had to create an Apple Music social profile.

Also please name issues better than pure spam.

**Comment by FluffyCuteOwO** [comment]
> Do you have an Apple Music social profile? I had the same issue and I had to create an Apple Music social profile.
> 
> Also please name issues better than pure spam.

How i can create Apple Music social profile? I tried to search instructions, but it only for ios 11 0_0

**Comment by coredev-uk** [comment]
Do the above, [this guide](https://www.macrumors.com/how-to/apple-music-profile-ios-11/) can be useful. I will be pinning this for the time being as this is common with a lot of people it seems.
