### ISSUE TITLE
[Bug]: App doesn't reopen after closing windows 10

### ISSUE THREAD

**Issue by dmuraco3** [ciderapp/Cider#340]
### Describe the Bug

After exiting out of app it won't reopen. Have to go to task manager and end cider task then reopen.

### Steps to Reproduce

open cider then click exit. then click on cider.exe

### Environment Information

- OS: Windows 10 Pro 19042.1466
- App Version: latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Try going to settings and disabling 'Close button hides application'.

**Comment by lance-374** [comment]
> Try going to settings and disabling 'Close button hides application'.

Also after doing that you will have to go to the task manager, go to more details, then close all cider processes. Or just sign out and sign in again.

**Comment by dmuraco3** [comment]
thank you!

**Comment by coredev-uk** [comment]
> > Try going to settings and disabling 'Close button hides application'.
> 
> Also after doing that you will have to go to the task manager, go to more details, then close all cider processes. Or just sign out and sign in again.

Or you can right click the tray icon and select quit.
