### ISSUE TITLE
[Enhancement]: Include station queue

### ISSUE THREAD

**Issue by ChaseIngebritson** [ciderapp/Cider#348]
### The feature you would like

Currently, when listening to an artist or song's station, the only song in the queue is the one currently playing. Ideally it would have a list of upcoming songs in the station.

### Alternatives and Other Information

This would probably work in the same way as playlists would in terms of what's displayed in the queue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
I dont think this is possible due to Apple's API
