### ISSUE TITLE
[Translation]: The following is the Trad. Chinese(Taiwan) language I can't find the corresponding value in zh_TW.jsonc on Github.

### ISSUE THREAD

**Issue by jay900604** [ciderapp/Cider#352]
### Relevant Language

zh_TW

### Change or Addition or Both

Change a Language, Add a Language

### Change Requested / Any Additional Information

The following is the Trad. Chinese(Taiwan) language I can't find the corresponding value in zh_TW.jsonc on Github.

**English(US) corresponds to Trad. Chinese(Taiwan)**
Theme = 主題
PlaybackNotifications = 播放通知
lnline Playlists and Albums = 線上播放列表和專輯
Copy logs to clipboard = 複製執行紀錄檔剪貼簿

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GamingLiamStudios** [comment]
When new values are added to Cider, they aren't automatically added to the other files and need to be added manually.
So you'll need to find those values in `en_US.jsonc` and copy them over to `zh_TW.jsonc`.

**Comment by quacksire** [comment]
^^^^^^^^^^^^^

**Comment by jay900604** [comment]
> 將新的 i18n 值添加到 Cider 時，它們不會自動添加到其他文件中，需要手動添加。 因此，您需要在其中找到這些值`en_US.jsonc`並將它們複製到`zh_TW.jsonc`.

I didn't find the corresponding value even in en_US.jsonc, so I came to feedback.

**Comment by jay900604** [comment]
> ^^^^^^^^^^^^^
No corresponding value was found.
https://github.com/ciderapp/Cider/blob/main/src/i18n/en_US.jsonc

**Comment by GamingLiamStudios** [comment]
Well that's because the `main` branch seems to have the values hardcoded instead of in i18n. I'd recommend switching to the `develop` branch for translating, as that is the most up-to-date.
