### ISSUE TITLE
[Enhancement]: - dB marker tooltip on volume slider while hovering/dragging

### ISSUE THREAD

**Issue by xeizo** [ciderapp/Cider#354]
### The feature you would like

As Apples various music player apps always defaults to 50% volume it's confusing what is 0dB level when streaming Apple Music, a dB tooltip would avoid any confusion and max should be 0dB as we don't want clipping of any kind

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grolschie** [comment]
Actually, tooltips in general would be a handy enhancement.

**Comment by coredev-uk** [comment]
A tooltip for the volume percentage can be added, but dB I don't think can be done.

**Comment by xeizo** [comment]
0dB is the exact same as 100% so it really doesn't matter which

**Comment by grolschie** [comment]
0 to 100% would be more intuitive for most users I would imagine.

**Comment by xeizo** [comment]
Yes, probably as most don't know about dB

**Comment by maikirakiwi** [comment]
I'll take on this but only after audio module refactoring.

**Comment by maikirakiwi** [comment]
Resolved in commit [311fdc4](https://github.com/ciderapp/Cider/commit/311fdc402036d90c04c332f74247fda419ce97b3)
