### ISSUE TITLE
[Enhancement]: Use App Language For Apple Music Tabs

### ISSUE THREAD

**Issue by djohannes** [ciderapp/Cider#363]
### The feature you would like

Even though I've set Cider to English, all the Apple Music tabs (Listen Now, Browse and Radio) are in German, probably because that's the "main language" here in Austria. The Apple Music web player uses my browser language (English) and iTunes uses my system language (English). Is it possible to implement this for Cider as well? It's especially annoying for people who live in a country like Austria and so have their billing address set to it, but don't speak it's language.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
@vapormusic close if this is finished

**Comment by maikirakiwi** [comment]
Implemented in develop
