### ISSUE TITLE
[Bug]: NaN playback time in upcoming Albums

### ISSUE THREAD

**Issue by tebowy** [ciderapp/Cider#365]
### Describe the Bug

When viewing an album not released yet, with some unavailable songs (eg. https://music.apple.com/pl/album/black-summer/1608013512) the running time is viewed as NaN even though one track is already available.
Compare Cider:
![image](https://user-images.githubusercontent.com/3144357/152774610-ad97177c-bece-405e-add8-1a160eba1a2b.png)
To AM web
![image](https://user-images.githubusercontent.com/3144357/152774709-5dcff12a-3ee4-4f08-9626-d56564d40c23.png)

### Steps to Reproduce

1. Clicked on an upcoming album
2. Checked the album length

### Environment Information

- OS: Windows 11
- App Version: 1.1.0.0
- Commit ID: unknown (Microsoft Store build)

### Anything else?

One tidbit is that the unavailable yet songs are shown on AM web but not on Cider. Should this be a new bug?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Seems to be resolved from my testing. Feel free to reopen the issue if it should continue.
