### ISSUE TITLE
[Enhancement]: MiniPlayer Close Button

### ISSUE THREAD

**Issue by ollimenzel** [ciderapp/Cider#367]
### The feature you would like

I found out that you can go back by pressing esc-Key, but I guess a dedicated button to switch back to the full application would be good.
![image](https://user-images.githubusercontent.com/11551755/152804478-116c6c7c-63aa-49a1-855d-b18fff470f78.png)
Maybe the upper right corner would be a good place

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kyw504100** [comment]
isn't it already on the upper right corner?
![152804478-116c6c7c-63aa-49a1-855d-b18fff470f78](https://user-images.githubusercontent.com/79555466/152987675-bc33c378-be16-4667-99b2-fc15dd4dbfab.png)

**Comment by ollimenzel** [comment]
I feel ashamed that I didn't saw this yesterday...
Maybe the Icon could be shown a little stronger (less opacity)

**Comment by kyw504100** [comment]
Should looks better now
![image](https://user-images.githubusercontent.com/79555466/153047873-1ff59417-b704-4544-b906-62b337dd5e64.png)
