### ISSUE TITLE
[Bug]: Seamless transition has a large gap in playlists and a small gap in albums 

### ISSUE THREAD

**Issue by TreeHouseFalcon** [ciderapp/Cider#370]
### Describe the Bug

When playing songs back-to-back from an album, the seamless transition setting *seems* to work as intended, albeit with a small but noticeable gap. However, when playing the same songs back-to-back in a playlist the gap lengthens to nearly 1 second between the songs even with a multi-hundred MB download speed.

### Steps to Reproduce

1. Find two songs from an album that were designed to seamlessly transition into each other.
2. Play the two songs in order from their album's page. You'll notice the gap between the songs is short but still noticeable.
3. Create a playlist with those two songs in the same order.
4. Play those songs from the playlist. You'll notice the gap is considerably longer.

### Environment Information

- OS: Windows 10 Home

### Anything else?

This issue is the only reservation I have with Cider. The app works great, but this is a very prominent issue for me.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by snarkDADMin** [comment]
Confirming the above behavior occurs for me as well on develop branch built this morning (2022-02-07, ~8:45AM Central Time)

**Comment by VincentJoshuaET** [comment]
Getting this also, went back to the official Apple Music web app for now.

**Comment by Viktini** [comment]
Same here, hearing a small gap in-between tracks when listening to albums like what snarkDADMin specified. Happened on `cider-git` from the AUR (version `1.4.5.3373.40544237-1` to be specific)

**Comment by snarkDADMin** [comment]
Commenting to remove the stale tag. This issue is still present.

**Comment by coredev-uk** [comment]
Seamless transitioning is a feature apple created, unfortunately, there is not much we can do for this.

**Comment by yellowsink** [comment]
gapless playback still does not work correctly.

**Comment by coredev-uk** [comment]
As I said before, this is an apple feature. We cannot do anything to resolve this.

**Comment by yellowsink** [comment]
Really? Huh. I don't quite see how *not having a gap between tracks* is an unachievable thing - its worked fine with a couple of local file players I've used before. But if it's actually really impossible (which i still highly doubt) then fair enough. Though i will also say, there is a setting for "seamless playback" in the ui that appears to do very literally nothing, so, uh, idk. 
    	
    
  

 From: Core ***@***.***>Sent: Monday, August 22, 2022 2:20 pmTo: ciderapp/Cider ***@***.***>Cc: Cain Atkinson ***@***.***>; Comment ***@***.***>Subject: Re: [ciderapp/Cider] [Bug]: Seamless transition has a large gap in playlists and a small gap in albums (Issue #370) 
As I said before, this is an apple feature. We cannot do anything to resolve this.

**Comment by cryptofyre** [comment]
Apple won't let us fix it. Therefore we can do nothing about it.

**Comment by snarkDADMin** [comment]
Then remove the toggle from the settings UI if it's still there. Easy fix.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cryptofyre** [comment]
Thats not a fix nor a solution at all. Gapless works for albums as thats how Apple designed it, we're not going to remove it because it doesn't work for playlists.

**Comment by maikirakiwi** [comment]
I'm going to reiterate everything once and for all.
Cider is at its core, a heavily bootstrapped frontend for Apple's API, therefore, playback is completely coded by Apple and we just provide UI buttons for you to pause/resume. It is for this exact reason that we do not have complete control over how audio is played back unlike something like foobar because foobar's playback is system level but Cider is server sided and acts as a bridge to decrypt audio with drm THEN plays it back to your sound output.

**Comment by maikirakiwi** [comment]
It WOULD have been a very easy thing to implement IF we didn't use MusicKit to play audio, but then you would lose access to the entirety of Apple Music, which is not the point of the app.

**Comment by yellowsink** [comment]
Makes sense. Kinda a bummer tho but fair.
