### ISSUE TITLE
[Bug]: Removing mutliple items from queue does not work

### ISSUE THREAD

**Issue by glawler** [ciderapp/Cider#371]
### Describe the Bug

Highlighting more than one item (but holding shift and clicking) in the Queue and right clicking to remove the items appears to work, but does not. The items are removed from the list, but are actually still there - the song is still played. 

edit: note - this bug is in the currently playing Queue list, not a playlist.

Also the string displayed is `Remove ${self.selectiedItems.lengthj} tracks from queue". See attached screenshot. 

### Steps to Reproduce

1. Click on open queue button.
2. Click first entry
3. Hold shift and click second entry
4. Right click andd choose remove items
5. Push `>>` to skip current track
6. See that the "removed" song still plays.

### Environment Information

- OS: Fedora 34
- App Version: 
- Commit ID: commit 424b22f98ff491ea143983e02cccfe28fc9bb32b (HEAD -> main, origin/main, origin/HEAD)

### Anything else?

![image](https://user-images.githubusercontent.com/1774652/152825747-9ee8401b-7ca3-4292-98ea-eed2a45e650b.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by glawler** [comment]
Looks like a missing line. This fixes the item removal, but not the display issue.

```
diff --git a/src/renderer/views/components/queue.ejs b/src/renderer/views/components/queue.ejs
index 6e8d657..f60a13f 100644
--- a/src/renderer/views/components/queue.ejs
+++ b/src/renderer/views/components/queue.ejs
@@ -107,6 +107,7 @@
                                 self.queueItems = self.queueItems.filter(function (item) {
                                     return !item.remove
                                 })
+                                app.mk.queue._queueItems = self.queueItems;
                                 app.mk.queue._reindex()
                                 self.selectedItems = []
                             }
@@ -135,4 +136,4 @@
             }
         }
     });
-</script>
\ No newline at end of file
+</script>
```

**Comment by glawler** [comment]
I don't know JS well enough to know how to fix the string interpolation problem.

**Comment by glawler** [comment]
Although an obvious solution is to just use strings like "Remove selected tracks from queue". I'd submit a PR for this, but I don't speak all the languages you all support. :)

This looks like a problem for "play tracks next" and "play tracks later" as well.

**Comment by undeadbydawn** [comment]
You can use ctrl-click and choose each track manually, then right-click & remove all from playlist

**Comment by glawler** [comment]
> You can use ctrl-click and choose each track manually, then right-click & remove all from playlist

This is in the Queue, not a playlist.
