### ISSUE TITLE
[Enhancement]: don't show album art on album view 

### ISSUE THREAD

**Issue by lucasgroothuis** [ciderapp/Cider#372]
### The feature you would like

Not showing album art for each individual song when viewing an album would make sense, I think. It's something most streaming services seem to do and it makes things look a lot cleaner.
current cider: 
![image](https://user-images.githubusercontent.com/95186159/152828509-18373836-3587-40d7-85cb-8c262c287aea.png)
spotify: 
![image](https://user-images.githubusercontent.com/95186159/152828574-add314ce-9502-46ad-96ef-51a8bd3538e7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Unfortunately this is not how the official Apple Music app behaves. We intend to follow their style guide for a cohesive experience whenever possible.

![image](https://user-images.githubusercontent.com/74925636/152897470-cbfcb29a-0aff-4aef-a0f4-94766611e698.png)

**Comment by maikirakiwi** [comment]
Wait hold up

**Comment by maikirakiwi** [comment]
![image](https://user-images.githubusercontent.com/74925636/152897700-b18e5362-c9fe-490e-aaf2-e4141e7759f3.png)

What this should look like
