### ISSUE TITLE
[Bug]: Scrobbling wrong artist.

### ISSUE THREAD

**Issue by lachlanelijah** [ciderapp/Cider#377]
### Describe the Bug

The band 'Between the Buried and Me' scrobbles as 'Between The Buried.' Doesn't happen on other Apple Music clients that also have scrobbling.

![image](https://user-images.githubusercontent.com/42135069/152916806-10602091-ad9f-4264-8584-2b62d9525df2.png)

### Steps to Reproduce

1. Play any track from the band

### Environment Information

- OS: Windows 10 Home 19044.1466
- App Version: Latest 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tebowy** [comment]
This heuristic seems to be the culprit https://github.com/ciderapp/Cider/blob/424b22f98ff491ea143983e02cccfe28fc9bb32b/src/main/plugins/lastfm.ts#L126-L128
