### ISSUE TITLE
[BUG] Cider stops playing music on stations when app is in background.

### ISSUE THREAD

**Issue by calumcl** [ciderapp/Cider#38]
**Describe the bug**
Essentially the title. If the app is in the foreground, stations play absolutely fine and without any issues. When in the background, whenever the current track stops the station will stop playing completely. If you press play again, it starts again from the last track playing before it stopped, however shows the next up track in the station. Playlists are fine and don't exhibit this behaviour, it only happens with the auto-generated stations.

**To Reproduce**
1. Play station for artist/song/etc
2. Wait til end of track and don't have app in focus
3. See error.

**Expected behavior**
For the app to play the next track regardless of being in the foreground or background.

**Screenshots**
[Here are some videos of me running through the process for foreground and background if that helps seeing my issue.
](https://imgur.com/a/pXvjShJ)

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Fedora 35
 - Application Version *(e.g. 2.5.0)*: latest commit : 2fca495

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Can't see any logs in my directory at the moment, assuming they're not in yet or if there a toggle I'm missing. Happy to recapture them  if needed and I missed the toggle.

**Comment by lucasduartesobreira** [comment]
Hi, I think this bug got fixed by #35.
