### ISSUE TITLE
[Bug]: Unable to see Lossless Audio Quality

### ISSUE THREAD

**Issue by TanKot** [ciderapp/Cider#383]
### Describe the Bug

A bug happened!

I'm Now unable to see Lossless As an option in audio quality.
Was able to see it before this update.

### Steps to Reproduce

1. Clicked on... Settings
2. Audio

### Environment Information

- OS: Windows 11
- App Version: 1.1.0(i think)

### Anything else?

Nope.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GamingLiamStudios** [comment]
Yeah, this ain't a bug. No lossless as of right now. Lossless before wasn't lossless, but EQ. It's now called `Cider Adrenaline Processor™`
