### ISSUE TITLE
[Enhancement]: Autoplay

### ISSUE THREAD

**Issue by joaquimo-oramos** [ciderapp/Cider#386]
### The feature you would like

I would really like the autoplay feature from mobile.

https://www.macobserver.com/tips/quick-tip/auto-play-similar-music/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
This is already in the app and can be found in the queue popout, as shown here by a user in our Discord.
![image](https://user-images.githubusercontent.com/64542347/153169961-ab9c339d-a929-427b-b919-2b7a5123ea72.png)
