### ISSUE TITLE
[BUG] 'Cider is not responding. Reload the app?'

### ISSUE THREAD

**Issue by debanikray** [ciderapp/Cider#39]
The app on launching after successful installation says 'Cider is not responding. Reload the app?'

<img width="762" alt="image" src="https://user-images.githubusercontent.com/39643559/147387801-95919b01-fdb1-4266-818d-1a7dedb78760.png">

**Comment by vapormusic** [comment]
Should be fixed . It seems that you had a connection problem with our API server

**Comment by coredev-uk** [comment]
Assuming this is fixed due to the lack of a response.
