### ISSUE TITLE
[Bug]: UTF-8 support for song titles not working correctly

### ISSUE THREAD

**Issue by cptn-cosmo** [ciderapp/Cider#392]
### Describe the Bug

My song titles that are in Japanese are not being displayed correctly, both in the main window as well as the mini-player

### Steps to Reproduce

try to play any song where the title is in Japanese

### Environment Information

- OS: Archlinux
- App Version: 1.1.0
- Commit ID: master branch built a few minutes ago

### Anything else?

![Screenshot from 2022-02-08 20-59-49](https://user-images.githubusercontent.com/7382310/153074754-77e86835-e592-495f-a9fe-48416ef2df5b.png)

![Screenshot from 2022-02-08 20-57-24](https://user-images.githubusercontent.com/7382310/153074651-a7ed6c1d-35c0-4ee7-8079-f302025c9fe2.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
After testing this, seems to be fine for me. Make sure you install the relative fonts from the AUR.
<img width="727" alt="image" src="https://user-images.githubusercontent.com/64542347/158781369-944d14a7-4a49-4fdd-beb3-2be809a70cba.png">
