### ISSUE TITLE
[Enhancement]: Add warning if adding a duplicate song to a playlist

### ISSUE THREAD

**Issue by TreeHouseFalcon** [ciderapp/Cider#398]
### The feature you would like

A warning stating that the song you're adding to a playlist is already in it would be nice. I'm currently migrating from Spotify and I find myself adding a lot of duplicates to my main playlist.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by booploops** [comment]
Added a week ago
