### ISSUE TITLE
[Bug]: Cider doesn't close when clicking "Close" on the Tray icon (Windows 11)

### ISSUE THREAD

**Issue by GT2000byte** [ciderapp/Cider#399]
### Describe the Bug

This bug doesn't let me close the app when using the menu from the tray icon, which leads me to kill the task through the "Process" tab in Task Manager.

### Steps to Reproduce

1. Right-click the Cider icon from the up arrow menu (near the volume, network, etc. icons)
2. Click "Quit"

### Environment Information

- OS: Windows 11 (Latest version)
- App Version: 1.1.0.74
- Commit ID: 424b22f

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Is this issue still occurring?

**Comment by booploops** [comment]
Resolved in newer builds, MPRIS was active on Windows when it shouldn't have been.
