### ISSUE TITLE
[Enhancement]: Play iTunes Smart Playlists In Cider

### ISSUE THREAD

**Issue by TanKot** [ciderapp/Cider#402]
### The feature you would like

A great addition to this project would be the ability to play iTunes' Generated smart playlists in Cider.
Currently I can only see them in my Recently played, not in my library nor can i view them.
This feature would be amazing it use 😁.

### Code of Conduct

- [ ] I agree to follow this project's Code of Conduct

**Comment by booploops** [comment]
Unfortunately there are no known API endpoints or support for smart playlists in MusicKit at the moment

**Comment by vapormusic** [comment]
> Unfortunately there are no known API endpoints or support for smart playlists in MusicKit at the moment

oh no not webobjects daap again

**Comment by TanKot** [comment]
Oh Ok,
Thanks For The Reply!
