### ISSUE TITLE
[Bug]: Wrong sized icon showing up in Taskbar and Start

### ISSUE THREAD

**Issue by chrs-it** [ciderapp/Cider#408]
### Describe the Bug

No transparency either. This applies to both the Taskbar and Start, but not the System Tray.

### Steps to Reproduce

1. Install Cider from Microsoft Store.
2. Pin Cider to Taskbar and Start.
3. Enjoy!

### Environment Information

- OS: Windows 11 Dev (OS Build 22543.1000)
- App Version: Cider 1.1.0.0

### Anything else?

![Taskbar](https://user-images.githubusercontent.com/81048329/153206380-ab317dd3-5c8b-4478-9e2d-2837186a68ac.png)
![Start](https://user-images.githubusercontent.com/81048329/153206394-f7db0e3d-6ae5-4faa-a050-7b1a86f8a930.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
already fixed. wait for next update please
