### ISSUE TITLE
[Bug]: Queue is replaced after restarting Cider

### ISSUE THREAD

**Issue by pavidal** [ciderapp/Cider#414]
### Describe the Bug

When playing through an album or playlist and progressing through the queue, restarting Cider will replace all songs within the queue. The tracks that replaced the queue are also out of order, includes previously played tracks and a duplicate of the current track. 

Expected behaviour is to resume last playback position within the queue, in the same order. 

### Steps to Reproduce

1. Populate the queue by playing an album or playlist
2. Play through the queue
3. Restart Cider
4. Open queue 

### Environment Information

- OS: Windows 10 20H2
- App Version: 1.1.0
- Commit ID: 506e7ba4bb991d61a984fc23889fee828f3fe5cf

### For example: a queue playing Dawn FM, stopping at the 5<sup>th</sup> track "Sacrifice".

![image](https://user-images.githubusercontent.com/26520527/153270366-28ef6771-1779-4089-9c25-1f5a08bd8341.png)

![image](https://user-images.githubusercontent.com/26520527/153268978-48866505-9860-4c75-af0b-4319e7536de2.png)

### Queue once Cider is restarted:

Cider has added a duplicate entry for "Sacrifice" even though it's already playing, and the rest of the queue is replaced with tracks from the album (including tracks that were already played). These are also in the wrong order. The queue should look like the previous screenshot.

![image](https://user-images.githubusercontent.com/26520527/153269503-ba84534e-d07c-4d50-8958-9f739598f287.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
This is now fixed as of this commit [a536e54](https://github.com/ciderapp/Cider/commit/a536e544a50418ef48c62de22a3c43ba9979f55c)
