### ISSUE TITLE
[Bug]: App doesn't close at all

### ISSUE THREAD

**Issue by SakethKanchi** [ciderapp/Cider#417]
### Describe the Bug

App doesn't close  until you end the task using task manager. The right click and closing doesn't respond at all.

### Steps to Reproduce

1. Close the app.
2. Open task manager.
3. Cider is still running.
4. Try closing cider from the overflow menu on the taskbar. Nothing happens and Cider still running.

### Environment Information

- OS: Windows 11 Pro

### Anything else?

https://user-images.githubusercontent.com/70198692/153350745-677cd316-d540-479e-9d92-02fe6cde86f8.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
try use the develop branch

**Comment by SakethKanchi** [comment]
> try use the develop branch

How do i download it?

**Comment by vapormusic** [comment]
> > try use the develop branch
> 
> How do i download it?

Go to the discord server , type /branchbuilds develop
