### ISSUE TITLE
[Enhancement]: Enable other languages than default for Apple Music Storefront

### ISSUE THREAD

**Issue by CollimatedCalamity** [ciderapp/Cider#419]
### The feature you would like

Currently, Cider uses the default language for the user's storefront, which could potentially be annoying for people whose primary language is different from the default language in a region, especially when using Last.fm or Discord Rich Presence.

According to the [Apple Music API Documentation](https://developer.apple.com/documentation/applemusicapi/storefronts_and_localization), you can choose a different language by adding it in the request.

For example. this would give the artist name as "ビリー・アイリッシュ"
`https://api.music.apple.com/v1/catalog/jp/albums/310730204`

While this would give the artist name as "Billie Eilish" and would scrobble under the correct artist and emulate the behavior of Spotify integration to Discord by displaying the artist name in English, no matter the user's region.
`https://api.music.apple.com/v1/catalog/jp/albums/310730204?l=en-US`

### Alternatives and Other Information

Adding this should also close #363, I think.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
Wait , already in develop branch

**Comment by CollimatedCalamity** [comment]
I uninstalled the old version and reinstalled the latest build from develop branch and it seems to work except for the artist name in Cider's currently playing and Discord rich presence.
<img width="256" alt="Cider_yy9oi36Ae2" src="https://user-images.githubusercontent.com/99399112/153403976-627ca0df-3e9e-418b-a1b6-b1a29e42a6b5.png">

<img width="327" alt="Cider_da8dYgznFj" src="https://user-images.githubusercontent.com/99399112/153403694-110a4a27-294a-4d5d-b213-443f0831b4b2.png">

<img width="152" alt="Discord_MMxLfY6N4U" src="https://user-images.githubusercontent.com/99399112/153403708-2abb1b54-c240-4bc3-be35-8ea2ff9b6dc6.png">

**Comment by vapormusic** [comment]
This is because its from the same data object , will find a way to fix it

**Comment by Bingsooo** [comment]
Alright, thank you.

**Comment by vapormusic** [comment]
fixed on https://github.com/ciderapp/Cider/commit/636aeb450e21c767a485c04df2cf29aca9748b95
