### ISSUE TITLE
Local Playback of iTunes Files

### ISSUE THREAD

**Issue by quacksire** [ciderapp/Cider#422]
### The feature you would like

title

### Alternatives and Other Information

https://stackoverflow.com/questions/57518133/play-local-audio-files-in-my-app-without-using-the-input-type-file

https://www.npmjs.com/package/@sequencemedia/itunes-library-stream

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
#49
