### ISSUE TITLE
[Bug]: Title bar mini player shows artist name in wrong locale

### ISSUE THREAD

**Issue by cavealex** [ciderapp/Cider#425]
### Describe the Bug

The Band "ChthoniC" has a Traditional Chinese (zh-tw) name called "閃靈", and the same name in Simplified Chinese (zh-cn) called "闪灵".

However, when playing any of their songs, the artist name always shows the zh-cn name, regardless of whether Cider is set to display English (US) or Traditional Chinese (zh-tw).

Everywhere else, the zh-tw name is shown, as is expected on a zh-tw localized version of Windows 10.

This problem exists for all artists that have zh-tw names. The zh-cn name is always shown.

### Steps to Reproduce

1. Play any song from any artist that has zh-tw names.
2. The artist name will show using zh-cn locale regardless of system and app locale.

### Environment Information

- OS: Windows 10 Professional 21H1 build 19043.1466
- App Version: Windows Store version downloaded on 2022/02/11
- Commit ID:

### Anything else?

![CiderBug](https://user-images.githubusercontent.com/6653593/153496397-0fcc3d6e-e922-423f-a8cc-3bb2a1f7e705.jpg)

As an aside, this seems like a very common problem with software in recent years where developers default to the zh locale and don't specify the sub-region. However, zh-cn and zh-tw uses different character sets, so it is wrong to consider the two to be the same language. For a lot of people using the zh-tw locale, seeing their favorite artist name in zh-cn all the time is possibly enough to avoid using the software altogether. It would be much appreciated if the issue is not dismissed as unimportant and never fixed.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
This is because we have recently tried to implement MusicKit storefront locale thus resulting in the behavior you have screenshoted. (Present in the build since about 3 days ago)

Wait for @vapormusic to fix this.

**Comment by maikirakiwi** [comment]
Attributed to #419

**Comment by vapormusic** [comment]
fixed https://github.com/ciderapp/Cider/commit/636aeb450e21c767a485c04df2cf29aca9748b95
