### ISSUE TITLE
[Enhancement]: Round icon

### ISSUE THREAD

**Issue by dangswing** [ciderapp/Cider#426]
### The feature you would like

A round icon will be better:
![image](https://user-images.githubusercontent.com/48401234/153518625-30512e9b-a2ab-4cad-9d5c-144b0a877ba1.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Resolved in develop branch. The next Windows store release should have it.
