### ISSUE TITLE
[Bug]: Attempting to connect and authorize last.fm application opens up a new cider window where you're prompted to login to apple account again.

### ISSUE THREAD

**Issue by Monochromish** [ciderapp/Cider#428]
### Describe the Bug

Clicking on the `Yes, allow access` button on the Last.fm Application Connect link opens another Cider window where you are prompted to log in to your Apple Account again.
Even if you log in to the new Cider window, the Last.fm still fails to connect.

Refer to the Attached GIF for more information

### Steps to Reproduce

1. Clicked on the `Connect` button on Cider Settings
2. Clicked on the `Yes, allow access` button on the Last.fm Application Connect link

### Environment Information

- OS: Windows 11 x64 Home
- App Version: v1.1.383.383 (Develop Branch)
- Commit ID: ~

### Anything else?

![Cider](https://user-images.githubusercontent.com/79590499/153593634-dd2be2dd-0abb-4c4e-8861-63141721507a.gif)

I've also tried restarting Cider completely, does not fix anything.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
hmm second instance blocking stop working

**Comment by vapormusic** [comment]
fixed https://github.com/ciderapp/Cider/commit/391a9f42f419d12a47ce27b176922e53309dd247
