### ISSUE TITLE
where are the releases?

### ISSUE THREAD

**Issue by gamerseye123** [ciderapp/Cider#43]
where did the releases go? the aur doesnt work, and the github releases are empty. its obvious there are releases, there are linux peoples writing issues about the program. are they using windows? am i insane?

**Comment by vapormusic** [comment]
there are "releases" : there are artifacts built in the Actions tab of GitHub. No GitHub releases yet because it's still in alpha

**Comment by coredev-uk** [comment]
> where did the releases go? the aur doesnt work, and the github releases are empty. its obvious there are releases, there are linux peoples writing issues about the program. are they using windows? am i insane?

What’s error for the aur package?

**Comment by coredev-uk** [comment]
Please open another issue or make a comment on the AUR package if the issue you are/were having persists.
