### ISSUE TITLE
[Bug]: FileError cannot find the font

### ISSUE THREAD

**Issue by KochCow** [ciderapp/Cider#431]
### Describe the Bug

A bug happened!
![捕获](https://user-images.githubusercontent.com/83562660/153689366-d9a5bc58-f118-4cee-9977-60e0fa69e48d.PNG)

### Steps to Reproduce

Everytime when I open the app

### Environment Information

- OS:Windows 10 21H2
- App Version:1.1.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
are you living in mainland china ? maybe they are blocking google's font links

**Comment by KochCow** [comment]
> are you living in mainland china ? maybe they are blocking google's font links

Thank you for the response.
Yes,I live in China.And next I will try proxy server

**Comment by KochCow** [comment]
When I turn on the global proxy for cider, it works fine!
