### ISSUE TITLE
[Enhancemensong queue]: song queue

### ISSUE THREAD

**Issue by MavisTok** [ciderapp/Cider#433]
### The feature you would like

For example, I clicked on jay chou's homepage and chose to view all his popular songs. At this time, I selected one of them to play. I hope that I can enter all the remaining popular songs into the queue, so that only one song will be played. The song stopped.
![image](https://user-images.githubusercontent.com/52002734/153705676-47fc66d9-1c08-451f-a12a-7e6a36128d7d.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
fixed in develop
