### ISSUE TITLE
[BUG] Playlist Cover Art Won't Show Up Correctly (4-artwork playlist image)

### ISSUE THREAD

**Issue by TanKot** [ciderapp/Cider#44]
Normally we can see 4 images in a collage but its only the first song's image now....
Like this
![image](https://user-images.githubusercontent.com/77598655/147532258-5088560b-6c7e-40a2-946e-8a75d87d6b30.png)

**Comment by vapormusic** [comment]
Apple is doing this by perform a detailed list of the playlists and load the first 4 images.

**Comment by coredev-uk** [comment]
Closed due to inactivity and lack of response from the issue author.
