### ISSUE TITLE
[Bug]: GPU is higher and higher when loading!! 

### ISSUE THREAD

**Issue by nanoTiO2** [ciderapp/Cider#440]
### Describe the Bug

A bug happened!
when i was in the following page and states（when some divs are loading）, GPU in my computer will exert all his's strength. with time passing.

![截图jietujptu_2022-02-13_06-39-51](https://user-images.githubusercontent.com/58650184/153731438-bf1efa55-1bc8-4e9a-bb10-b0d6f9d9edc4.png)
n
![截图jietujptu_2022-02-13_06-58-24](https://user-images.githubusercontent.com/58650184/153731492-3950cbed-8880-499e-b212-0f5ea8f73ccc.png)

### Steps to Reproduce

1. open this main window when setup
2. have a low connection internet environment
3. when something is cycling (loading)
4. the GPU occupancy will be high

### Environment Information

- OS: win10
- App Version:0.01
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
请使用CI里最新的版本。

https://app.circleci.com/pipelines/github/ciderapp/Cider?branch=develop&filter=all

0.0.1已经很老了，新版已经解决了这个问题。
