### ISSUE TITLE
[Bug]: MS Store Bug: BrowserWindow not Showing

### ISSUE THREAD

**Issue by Mintkarla** [ciderapp/Cider#444]
### Describe the Bug

A bug happened!
![image](https://user-images.githubusercontent.com/68771240/153752855-4be8966c-698f-41fb-a91e-c4bb4d8db0be.png)
Whether it is the Microsoft Store version or the direct-installed version, the program cannot be opened. But open task manager to see background processes.

### Steps to Reproduce

Download from Microsoft Store, no response when opened. Check that there are processes in the background. Uninstall the store version, download the direct version, still can't open but there is a process in the background

### Environment Information

- OS:Windows 11.493
- App Version:new

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KKirara1227** [comment]
![image](https://user-images.githubusercontent.com/68771240/153753100-7472173b-6bee-43c6-a84e-44f6bf3ee106.png)

**Comment by ollimenzel** [comment]
The Windows Store App needs to be paid (99cent)
Could this be your problem? Happend to me after the second day I installed it from MS-Store.
The App wasn't opening.

**Comment by coredev-uk** [comment]
Closing due to lack of response.
