### ISSUE TITLE
[Bug]: Not displaying account picture correctly

### ISSUE THREAD

**Issue by PIndividual** [ciderapp/Cider#447]
### Describe the Bug

The account picture can't load correctly.

### Steps to Reproduce

1. Signed into your Apple Music account, and that's it.

### Environment Information

- OS: Windows 10 21H2
- App Version: 1.1.0.74
- Commit ID:

### Anything else?

<img width="1080" alt="image" src="https://user-images.githubusercontent.com/62368342/153797290-044164fa-6f17-4a75-9232-d281ffcff27b.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by a1eaiactaest** [comment]
Tried changing it?

**Comment by PIndividual** [comment]
Yes, still not working, reinstalling the app also won't help

**Comment by coredev-uk** [comment]
Probably due to API issues. I'm going to close this issue, if it continues perform a [clean installation](https://github.com/ciderapp/Cider/wiki/Troubleshooting#clean-installation), and reopen the issue if it continue after that.
