### ISSUE TITLE
[Enhancement]: the songs in the library are sorted by the time i have added/lyrics translation

### ISSUE THREAD

**Issue by crisshane** [ciderapp/Cider#456]
### The feature you would like

nice substitution of itunes
it would be much better if it can added some functions,such as the songs in the library are sorted by the time i have added and support lyrics translation.

### Alternatives and Other Information

Some apps has realized the function of lyrics translation https://github.com/WXRIW/Lyricify-App

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by booploops** [comment]
Lyric translation can be enabled under the app settings with Musixmatch
![image](https://user-images.githubusercontent.com/49113086/156459356-91a9b526-0405-4f2d-aee6-00b89e391429.png)

As for date added on library songs, this is a big headache for us as Apple's MusicKit API does not provide the date added for songs, but does for albums (this is how recently added works).  This same limitation is also present on the Apple Music web player for the same reason.
