### ISSUE TITLE
[BUG] iTunes Uploaded SkipToPrevious Song Issue

### ISSUE THREAD

**Issue by Itsredsect** [ciderapp/Cider#46]
I have songs in my library that I uploaded myself and songs from Apple Music. When I play my own song, skipping back usually works very well. Only with the song BassMarck there are problems, because when I play this song and then want to return to a previous song, I use the buttons for it. The previous song is only displayed briefly and then another song is played randomly. This problem also exists when I play a song from Apple Music and the previous one is a song of its own, also here the same happens and mostly the next song is played, in this case, so when I play Cry out for Hero and want to listen to the previous song, instead of Be my lover, Die by the Blade is played. 

![grafik](https://user-images.githubusercontent.com/95378207/147605704-28e93c78-7206-475c-82dc-3beb75f483c3.png)

**Comment by puyoxyz** [comment]
same as #100 ?

**Comment by vapormusic** [comment]
should be mitigated in latest develop https://github.com/ciderapp/Cider/commit/942aa1b1b4676098437763fb8c7113084c7ce1c1 ,
also disable seamless transition would minimize the chance of it happen

**Comment by coredev-uk** [comment]
The mitigated changes have caused issues with calls to media keys in the MPRIS module.

**Comment by quacksire** [comment]
fixed
