### ISSUE TITLE
[Bug]:Dowloded from Microsft Store but can not open the software. My system is Win 11 

### ISSUE THREAD

**Issue by NEXTOPzlz** [ciderapp/Cider#463]
### Describe the Bug

Dowloded from Microsft Store but can not open the software. My system is Win 11 

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS:Win11
- App Version:
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ollimenzel** [comment]
I had to pay the 99 Cent first then it worked on the second day after installing.
Now it's working fine ever since.
