### ISSUE TITLE
[Bug]: Windows 10 pinned Start menu icon is chonky

### ISSUE THREAD

**Issue by coneslayer** [ciderapp/Cider#469]
### Describe the Bug

When Cider is pinned to the Start menu in Windows 10, the app icon is oversized compared to all the other pinned applications.

### Steps to Reproduce

1. Find Cider in the Start menu
2. Right-click Pin to Start
3. Observe size of icon

### Environment Information

- OS: Windows 10 Pro 21H2 (19044.1526)
- App Version: 1.2.0 (Microsoft Store)
- Commit ID: not displayed in About??

### Anything else?

![image](https://user-images.githubusercontent.com/4835005/154492441-51182216-0fd0-42c5-8a6b-52f09b5e4f2e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Ref: #444

**Comment by coredev-uk** [comment]
Resolved.
