### ISSUE TITLE
[Enhancement] Play Symbol netxt to a Song 

### ISSUE THREAD

**Issue by Itsredsect** [ciderapp/Cider#47]
It would be nice if next to the currently playing song is an icon indicating that this song is playing. Especially with large playlists, you look stupid until you find the song that is currently playing, so a conspicuous icon like Spotify would help.
![grafik](https://user-images.githubusercontent.com/95378207/147605929-4782af71-0766-4f5a-9805-a816134791e1.png)

**Comment by gms10ur** [comment]
resolved
