### ISSUE TITLE
[Enhancement]: Save album covers

### ISSUE THREAD

**Issue by Moresteck** [ciderapp/Cider#473]
### The feature you would like

What I've been missing from TIDAL is the ability to save best quality album covers with ease. It was a simple right mouse click -> Save as, but that's not as easy on Apple Music.

I'd love to see an option to save the album cover in the best possible quality, or also in a few lower quality options (maybe 500x500, something like this).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by booploops** [comment]
Added in latest develop commit for playlist/album pages
