### ISSUE TITLE
[Bug]: Like / Dislike not working from search menu

### ISSUE THREAD

**Issue by ollimenzel** [ciderapp/Cider#474]
### Describe the Bug

When I try to like / dislike a song that I found through search the buttons aren't clickable

### Steps to Reproduce

1. Search for a song
2. Right click on the song to bring up the menu
3. Try to like / dislike the song

### Environment Information

- OS: Windows 11
- App Version:  1.2.1
- Commit ID:

### Anything else?

![image](https://user-images.githubusercontent.com/11551755/154699597-ec530e86-9ad3-4519-9fda-77d8f65dc159.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
Will be fixed in the next update, tks for notifying!
