### ISSUE TITLE
[BUG] Closing Cider window ends the program instead of minimizing to tray

### ISSUE THREAD

**Issue by PancakeSparkle** [ciderapp/Cider#48]
OS: Arch Linux
Desktop Environment: KDE
Closing the Cider window actually closes the whole thing, even though minimize to tray is selected.
![Screenshot_20211231_015448](https://user-images.githubusercontent.com/13101558/147795104-73808c02-681a-49b4-8132-31e657378101.png)

**Comment by Sillyvan** [comment]
Can confirm. this happens on windows too
