### ISSUE TITLE
[Bug]: Window Animations missing on W10/11

### ISSUE THREAD

**Issue by cryptofyre** [ciderapp/Cider#490]
### Describe the Bug

Title explains it all, but this should be fixed pretty easily.

### Steps to Reproduce

just minimize the app lool

### Environment Information

- OS: Windows 11 x64
- App Version: 1.2.1
- Commit ID: latest dev

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Movisivi** [comment]
Animations work on Windows 11 Dev 22557.1
