### ISSUE TITLE
[Enhancement]: Allow follow artist from album screen

### ISSUE THREAD

**Issue by blowdart** [ciderapp/Cider#498]
### The feature you would like

In order to follow an artist whose music I am currently listening to I have to click through to the artist screen, Adding the Follow Artist menu item to the album ellipse menu would remove a click.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by booploops** [comment]
Added in the newest develop commit with the new artist chip component

![image](https://user-images.githubusercontent.com/49113086/155524651-2fdf2375-a07d-478b-b89b-e9a5df90671f.png)
