### ISSUE TITLE
[Bug]: corrupted empty playlists

### ISSUE THREAD

**Issue by pb29** [ciderapp/Cider#506]
### Describe the Bug

It seems there are some corrupted empty playlists between normal playlists. they got no songs, no name, and just like this picture.
and these can't be deleted, I tried so many times but it didn't work. they don't appear on Mac/iOS/Web Apple Music.
![image](https://user-images.githubusercontent.com/26969207/155082086-e70abd8a-ddfb-4ba4-8801-278e4239b723.png)

### Steps to Reproduce

1. Its just there, everytime, everywhere.

### Environment Information

- OS: Windows 10
- App Version: 1.2.1
- Commit ID: what is this?

### Anything else?

nope

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohammadrafigh** [comment]
I have some more info on this. I found that this happens when you change your origin. That's because Apple won't allow you to use the playlists made from another origin. So the API returns empty playlists in new origin.

**Comment by mohammadrafigh** [comment]
@coredev-uk any progress on this?

**Comment by pb29** [comment]
> I have some more info on this. I found that this happens when you change your origin. That's because Apple won't allow you to use the playlists made from another origin. So the API returns empty playlists in new origin.

Yep, I changed my origin from US to my country like... about 11 months ago. to be exact- july 21, 2021
and I was away from this program a while, but I checked it and somehow these corrupted playlists are gone!
maybe these dummy data gets deleted from Apple side?

**Comment by mohammadrafigh** [comment]
Nope this issue still exists for me. Maybe after a few months they delete
old region playlists I'm not sure but I just changed my region 2 months ago.

**Comment by mohammadrafigh** [comment]
Ok I found more info. In fact Apple returns undefined for those playlists. It would be as easy as filtering playlist results to not include undefined items. I may be able to send a PR.
