### ISSUE TITLE
[Bug]: Close Button Should Hide Application fails to reopen window in MacOS

### ISSUE THREAD

**Issue by jtl001** [ciderapp/Cider#508]
### Describe the Bug

After enabling the experimental feature 'Close Button Should Hide Application' on MacOS (Monterey 12.2.1), once the close button is pressed on the window Cider will not reopen that window. The only way to get a window to open is to force close and reopen the app. 

Upon further checking, the issue also occurs when the feature is disabled, failing to close the application.

### Steps to Reproduce

1. Enable 'Close Button Should Hide Application' option in Settings (Also seems to occur when disabled)
2. Close application window by clicking red x
3. Attempt to reopen app by clicking icon in dock
4. See that Cider appears as active app in Menu Bar, but no window will show
5. Force close app using CMD ALT ESC
6. Restart app. New window

### Environment Information

- OS: MacOS Monterey 12.2.1
- App Version: 1.2.1
- Commit ID: ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Enable close button hide

**Comment by coredev-uk** [comment]
Should be resolved as of commit b71a7b2
