### ISSUE TITLE
[Bug]: Cider starts in fullscreen

### ISSUE THREAD

**Issue by JustAnotherStrange** [ciderapp/Cider#509]
### Describe the Bug

When I start Cider, it goes into fullscreen. I don't want it to do that

### Steps to Reproduce

1. Open Cider
2. It is in fullscreen (this should not happen)

### Environment Information

- OS: Arch Linux
- App Version: Latest commit (AUR)
- Commit ID: Just updated from AUR before testing.

- WM: i3-gaps

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Try the build of the commit mentioned above, it should be resolved in that. Reopen the ticket if the issue persists.
