### ISSUE TITLE
[BUG] Track length

### ISSUE THREAD

**Issue by Itsredsect** [ciderapp/Cider#51]
![grafik](https://user-images.githubusercontent.com/95378207/147972135-f284ffd9-e728-4b64-a8df-a00cae1df0a7.png)

**Comment by inalone** [comment]
Can you please explain what you have to do to reproduce this bug? This isn't a helpful report

**Comment by coredev-uk** [comment]
I understand the issue, of the timestamp not being calculated correctly. However, we still need you to follow the bug report template so we can reproduce the issue to find a way to resolve it.

**Comment by Itsredsect** [comment]
no idea how this happened. I played my songs from the library and then skipped to the end of the song, like 10 sec before. But when the song ended, the display would not stop.

**Comment by coredev-uk** [comment]
If you can reproduce the issue, reopen this issue.
