### ISSUE TITLE
[Bug]: all the song in my playlist are with explicit icon

### ISSUE THREAD

**Issue by ltt2077** [ciderapp/Cider#511]
### Describe the Bug

>
![屏幕截图 2022-02-24 190256](https://user-images.githubusercontent.com/85069795/155512488-226585af-7513-4efc-911f-c235deeab41e.jpg)
 Besides I can't play any song with e icon in cider, I can't play any song in my playlist now.

### Steps to Reproduce

I install cider prerelease from GitHub first，then uninstall this version and get cider alpha from Microsoft store.Then open cider ,all the song are with e icon in my playlist.

### Environment Information

- OS:win11
- App Version:1.2.779
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
There was a recent outage of Apple Music servers , this is currently affecting in their API. You can see the same behaviour on the Apple Music web app.
