### ISSUE TITLE
[Bug]: Next/previous track shortcuts don't work

### ISSUE THREAD

**Issue by Stratoco** [ciderapp/Cider#517]
### Describe the Bug

When using fn key on keyboard or assigned function on mouse to skip track, nothing happens. Works with other audio players. Play/pause works however. Tested both with keyboard and with mouse using logitech gaming software to set button function. 

### Steps to Reproduce

FN+Skip track

### Environment Information

- OS: Win7
- App Version: v1.1.0.74
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
please use the develop branch
