### ISSUE TITLE
[Bug]: Attempting to start a new instance when the app is hidden doesn't focus the existing instance

### ISSUE THREAD

**Issue by adryd325** [ciderapp/Cider#523]
### Describe the Bug

Closing app without a system tray with "Close Button Should Hide the Application" makes it impossible to show the window

### Steps to Reproduce

1. Open Cider
2. Make sure "Close Button Should Hide the Application" is enabled
3. Use the close button to hide the application
4. Open the application from the app launcher

EXPECTED RESULT:
The hidden Cider instance should show itself

ACTUAL RESULT:
Nothing happens

### Environment Information

- OS: Arch Linux (Rolling), GNOME, Xorg
- App Version: 1.1.0
- Commit ID: 2a9622fa

### Anything else?

A solution to fix this would be to show any existing windows when launching a new instance, similar to how discord does things. This seems to work when the app is unfocused but not when it's hidden.

Launching from a terminal shows that Cider tries to focus the existing instance, but it doesn't seem to work

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Try the latest build.

**Comment by adryd325** [comment]
It's fixed! Ty!!
