### ISSUE TITLE
[Bug]: Web Remote QR Code Uses Wrong Network Interface

### ISSUE THREAD

**Issue by djohannes** [ciderapp/Cider#525]
### Describe the Bug

When I click on Web Remote, the QR code uses the IP address for the Hyper-V network interface instead of my real network card. In the Cider folder I've found a file called "Network Persistent State", which even mentions the correct local IP for "supports_quic". Other similar programs all use the correct local IP, so I have no idea why Cider uses my Hyper-V network interface.

### Steps to Reproduce

I installed the Android subsystem for Windows 11, which requires Hyper-V

### Environment Information

- OS: Windows 11
- App Version: 1.2.858

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by djohannes** [comment]
@quacksire I am not using Cider via Hyper-V, that’s the issue. It’s running on my system like normal but for some reason the QR code uses the wrong network card, the Hyper V card.
 I only have Hyper-V for the Android app support.

**Comment by cryptofyre** [comment]
This is a Windows related issue. Forward it to them as the network is controlled by the host operating system.

**Comment by djohannes** [comment]
@cryptofyre Thank you for your reply! Other similar programs use my correct network card so far, that's why I'm so confused. 
But, would it be possible to implement an "advanced option" to allow people to select the network card Cider uses for the QR code or change the IP manually? I saw on Discord that a few other people also experienced this (Cider using the wrong network card for the QR code, not just the Hyper-V one). This also makes the new Remote app useless for me, because there is only the QR code scanner and no manual option.

**Comment by quacksire** [comment]
> would it be possible to implement an "advanced option" to allow people to select the network card Cider uses for the QR code or change the IP manually?

A very very narrow niche. 

As other apps like Spotify or iTunes (which both broadcast remote protocols like Cider) don't do this, it doesn't seem practical in time or energy to implement it.

Though it might be plugin worthy.

**Comment by djohannes** [comment]
" @quacksire As other apps like Spotify or iTunes (which both broadcast remote protocols like Cider) don't do this, it doesn't seem practical in time or energy to implement it."
I'm still confused why it's not an issue with either of those, the iTunes Remote works just fine and Spotify local file sync works fine as well. Also with other software. Only Cider decided to use the wrong network card so far. 
I reported this as Feedback in Windows but I highly doubt that there will be a "fix" anytime soon if it seams to work with all the other software but let's hope, after all the Android Support is still in beta.

"Though it might be plugin worthy."
Thank you for the advice with the plugin, I might look into it and see if I can write something for it! 👍
