### ISSUE TITLE
[Bug]: Missing Styles or dependencies on fresh Windows Account on the MS Store version.

### ISSUE THREAD

**Issue by cm45** [ciderapp/Cider#527]
### Describe the Bug

![Bug](https://user-images.githubusercontent.com/16745583/155951611-1751be56-5f32-4edc-990b-110522d47d68.png)

Seems like I'm just missing some dependencies or the application fails to load some assets.

### Steps to Reproduce

1. Fresh Windows 11 Account (It works for the other account)
2. Installed it from the Microsoft Store
3. Started the application

Already reinstalled it.

### Environment Information

- OS: Windows 11
- App Version: Current MS Store Version
- Commit ID: 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
remove everything in the [Cider Folder](https://cider.sh/link?debug/appdata) then reinstall again
