### ISSUE TITLE
[Bug]: Can't cycle through song lyrics when playing and more... - Cider Remote App on iOS

### ISSUE THREAD

**Issue by Monochromish** [ciderapp/Cider#528]
### Describe the Bug

I've noticed this bug where you just can't scroll up/down when a song is playing in the Cider Remote App I got from the test flight app. Refer to the video given below for more information on this.

The remote itself also seems very buggy and the fluid animations most of the time don't work which makes it look worse.

### Steps to Reproduce

1. Open Cider Remote App
2. Play a song
3. Click on the lyrics button on the Remote App
4. Try to scroll up/down

### Environment Information

- OS: iOS 15.3.1
- App Version: 1.0.1 (3)
- Commit ID: ∼

### Anything else?

https://user-images.githubusercontent.com/79590499/155971577-8242e62d-59a1-49c1-8c75-db57becdf5e5.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
Please open an issue on this repository
https://github.com/ciderapp/Cider-Companion
