### ISSUE TITLE
[BUG]  Application Scaling Issue

### ISSUE THREAD

**Issue by Itsredsect** [ciderapp/Cider#53]
![grafik](https://user-images.githubusercontent.com/95378207/147973769-63f51831-e50f-4092-95dd-50b21ab41b10.png)

**Comment by coredev-uk** [comment]
Please follow the template provided.

**Comment by Itsredsect** [comment]
I have different sized monitors and when I drag the program from the large to the small, cider does not always adjust accurately. You can see this here. Also, the heart that is next to the title is sometimes outside.

**Comment by maikirakiwi** [comment]
Resolved by adding a clear scale option in settings
