### ISSUE TITLE
[Bug]: The app cannot be closed correctly

### ISSUE THREAD

**Issue by RogerPanBUAAedu** [ciderapp/Cider#532]
### Describe the Bug

A bug happened! When I pressed the close bottom, the app is still working and staying in the tray. I must open the task management and close the Cider threads one by one. 

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS: windows 10 
- App Version: 
- Commit ID: 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Nosh118** [comment]
Have you tried installing the latest build? [Version 1.2.944](https://944-429851205-gh.circle-artifacts.com/0/~/Cider/dist/artifacts/Cider-Setup-1.2.944.exe)

**Comment by coredev-uk** [comment]
Lack of response and information provided. Closed.
