### ISSUE TITLE
[Bug]: Non colored emojis for headings

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Cider#536]
### Describe the Bug

Emojis are non-colored inside text or headings with `font-weight` set to ≥600.

![The Cider search screen, showing the New Nordic playlist. A rectangle surrounds the snowflake emoji.](https://user-images.githubusercontent.com/32032824/156202173-d3853904-b970-47e5-8d68-7c54de09c860.png)
<figcaption><em>The search screen, <code>font-weight</code> is unset.</em></figcaption>

![The New Nordic playlist page, with a rectangle surrounding the snowflake emoji.](https://user-images.githubusercontent.com/32032824/156202179-09dbfe22-b021-4956-9080-01a5bef728ec.png)
<figcaption><em>The playlist page, <code>font-weight</code> is set to 700.</span></em></figcaption>

### Steps to Reproduce

- Go to the [New Nordic ❄](https://music.apple.com/us/playlist/pl.7a069eaae621439a885abd59148938e9) playlist within the search field and compare with the text inside the playlist page

### Environment Information

- OS: Windows 10 21H2 - 19044.1526
- App Version: N/A
- Commit ID: 8e846e0dc6baec044d30c21022607ecde4a8ec69

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1266022 chromium bug
