### ISSUE TITLE
[Bug]: Max audio quality is High (256 kbps)

### ISSUE THREAD

**Issue by Mikolaj-Walkowiak** [ciderapp/Cider#544]
### Describe the Bug

I've built the app from the develop branch and the max audio quality I can select is 256 kbps.

### Steps to Reproduce

1. Build the app from the develop branch
2. Log-in
3. Go to settings

### Environment Information

- OS: Windows 10
- App Version: 1.2.1-develop
- Commit ID: 2a9622fa9873c2f7e2ea0fd8175da12a1defe834

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
lossless does not exist on musickit (the api we are using to interact with Apple's servers)

**Comment by Mikolaj-Walkowiak** [comment]
I'm not talking about lossless here? Is really 256 the max quality? Not even 320KBps?

**Comment by maikirakiwi** [comment]
Apple uses AAC encoder, which results the audio being 256kbps AAC. An objectively good balance between quality and size. AAC is also one of the most efficient fullband codec available.

You are comparing Apples to Bananas if you are referring to 320kbps some other codec such as Ogg Vorbis/MP3/Opus.  

Please take a second a google the difference of 256kbps AAC and whatever 320 (? unit) codec you are referring to.

Best, 
Maikiwi

**Comment by Mikolaj-Walkowiak** [comment]
Ok, sorry, did not know that. Maybe it's worth adding 256 kbps AAC to the description to avoid confusion with mp3.

**Comment by maikirakiwi** [comment]
> Ok, sorry, did not know that. Maybe it's worth adding 256 kbps AAC to the description to avoid confusion with mp3.

Apple only uses AAC and it's outlined in the Apple Music's Preferences, quite redundant imo.
