### ISSUE TITLE
[Bug]: Unable to update Cider on Windows

### ISSUE THREAD

**Issue by chakkkkwan** [ciderapp/Cider#552]
### Describe the Bug

I check the logfile, which said there is an error which cannot find the file directory

### Steps to Reproduce

1. Click on the "Check Update" button
2. Popped the notification "Error Updating Cider"
![image](https://user-images.githubusercontent.com/96745821/157405874-82e57cd4-f3df-4d50-a661-583f30744671.png)

### Environment Information

- OS: Windows 10 21H2
- App Version: 1.3.0.0
- Commit ID: 

### Anything else?

[Ciderlog_20220309163846.txt](https://github.com/ciderapp/Cider/files/8213071/Ciderlog_20220309163846.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ssanch** [comment]
+1

**Comment by quacksire** [comment]
The MS Store release has to be updated via the MS Store.
