### ISSUE TITLE
[Enhancement] Update macOS icon

### ISSUE THREAD

**Issue by jthobbs** [ciderapp/Cider#555]
Can we get the macOS icon updated to match the design standards? Currently, the icon is a different shape and is much bigger than all other app icons

**Comment by Amaru8** [comment]
Already fixed with [macOS Icon Update](https://github.com/ciderapp/Cider/commit/3c3b60cee9d2a9add01be831ddbab58593de5c69)

**Comment by quacksire** [comment]
Done.

following the Big Sur icon guidelines.
