### ISSUE TITLE
[Bug]: Artist names not separated

### ISSUE THREAD

**Issue by brotherelric** [ciderapp/Cider#556]
### Describe the Bug

![imagen](https://user-images.githubusercontent.com/66126306/157517697-644fafbe-0303-465f-adce-0d1fad102d9f.png)
Artist names not separated with the "&" in this case.

### Steps to Reproduce

1. https://music.apple.com/album/bo-jackson/1579768175

### Environment Information

- OS: Windows 10 (21H1)
- App Version: 1.3.1180
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Seems to be resolved from my testing. Feel free to reopen the issue if it should continue.
