### ISSUE TITLE
[Bug]: UI not working

### ISSUE THREAD

**Issue by QuickXand** [ciderapp/Cider#559]
### Describe the Bug

A bug happened
![屏幕截图 2022-03-10 223351](https://user-images.githubusercontent.com/96399652/157685031-5d7acb69-6d70-4f62-83b8-bc1d94a4ef33.png)
!

### Steps to Reproduce

1. Problem happen when it started.

### Environment Information

- OS:Windows 11 22000.556
- App Version:1.3.1084
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
Reinstall and delete everything in %appdata%/Cider
