### ISSUE TITLE
[Bug]: Can't use media buttons to control playback

### ISSUE THREAD

**Issue by aitbw** [ciderapp/Cider#560]
### Describe the Bug

Last night, I updated Cider to its latest version (v1.1.0.1841.2a9622fa-1) via AUR — unfortunately, I've been experiencing the following error every time I try to control it with my keyboard media buttons (same with GNOME's media buttons):

![image](https://user-images.githubusercontent.com/9470839/157721964-e97dd6be-3a04-42de-9887-90a207499dd4.png)

I tried a clean install with no avail, and the `develop` branch is encountered with the same errors. "Next/Previous track" buttons are also facing similar errors.

### Steps to Reproduce

1. Start playing any song with your mouse/touchpad
2. Try to pause it with your keyboard media buttons (or with GNOME's media buttons)
3. See error on Cider

### Environment Information

- OS: Manjaro Linux
- App Version: 1.1.0.1841.2a9622fa-1 (`develop` build is also facing the same issue)
- Commit ID: [d941fb3](https://github.com/ciderapp/Cider/commit/d941fb3ef193987b3e7356c5dbae69f78b00e0b1)

### Anything else?

Error when hitting the "Next track" button:

![image](https://user-images.githubusercontent.com/9470839/157723863-962a694c-ae29-4230-90d1-fccdf0548f9a.png)

Error when hitting the "Previous track" button:

![image](https://user-images.githubusercontent.com/9470839/157723930-d39451b2-7b6f-4901-bcbd-8bbb08a5cae7.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Try the latest cider-git build

**Comment by coredev-uk** [comment]
I did attempt to debug it, for some reason certain calls are not being made to the MPRIS plugin. Hopefully I can get a fix done for this by the end of the week.

**Comment by aitbw** [comment]
@coredev-uk, oh, wonderful! Thanks a lot :blush:

If you anything else from my end, just let me know :) I'd be more than glad to help

**Comment by coredev-uk** [comment]
Try the latest develop build, from my usage it is resolved.

**Comment by aitbw** [comment]
@coredev-uk, that did the trick, thank you so much!
