### ISSUE TITLE
[Bug]: The "Now Playing" icon on the left side of the playlist is displayed incorrectly.

### ISSUE THREAD

**Issue by zhanbao2000** [ciderapp/Cider#565]
### Describe the Bug

When a song finishes playing and start the next song in the playlist, the "Now Playing" icon on the left side of the playlist does not move to the next song, but remains on the previous song.

Expected
![图片](https://user-images.githubusercontent.com/29254102/158049163-58c0dcde-d3a4-4562-9996-d0398744e0ad.png)

Actual
![图片](https://user-images.githubusercontent.com/29254102/158049242-6c3cd9b0-5df6-4ef6-9b19-fbba4573a015.png)

### Steps to Reproduce

1. Select a playlist.
2. Double click a song to play it.
3. Drag the song's progress bar near the end so that it ends playing as soon as possible.
4. Wait for the song to finish playing.
5. Look at the playlist below and you will see the "Now Playing" icon is still in its previous position.

### Environment Information

- OS: Windows 10 21H1
- App Version: 1.3.1302
- Commit ID: 

### Anything else?

 - When the mouse is moved over this song in the playlist, the icon will return to normal display.
 - If you click the Next button or the Pause button, the "Now Playing" icon will also return to normal.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ClipLee** [comment]
Experiencing this issue 1.6.0, I'd suggest reopening it.

I had to hover over it with my mouse for it to update the current song being played.
