### ISSUE TITLE
[Bug]: Infinite pop ups when trying to play a song

### ISSUE THREAD

**Issue by GT2000byte** [ciderapp/Cider#574]
### Describe the Bug

This bug is present in the newest Cider release from winget.
When trying to play a song, a bunch of pop up dialogues appear saying the following:

> Error occurred: Uncaught Type error: Cannot read properties of undefined (reading '0')

I tried to log out from my Apple ID to no avail and the pop up keeps, well, popping up infinitely until Cider is closed.

### Steps to Reproduce

1. Clicked on any song after opening Cider

### Environment Information

- OS: Windows 11
- App Version: 1.3.1302

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Hey to better assist you, please DM me your logs from Settings -> Copy to clipboard on Discord. (Maikiwi#0001)

Most likely something wrong on my part.

**Comment by yazninja** [comment]
Hi OP @GT2000byte,
winget package has been updated. Please try and update to check if problem persists.

**Comment by maikirakiwi** [comment]
Closed for now. Suspected to be an ancient audio.js related issue. (Now fixed)
