### ISSUE TITLE
[Bug]: Media keys not working in Snap version

### ISSUE THREAD

**Issue by Carlgo11** [ciderapp/Cider#575]
### Describe the Bug

Cider won't cooperate with media keys on the snap version. Installed the deb version and it worked fine there. Also worked in the snap version of the old apple-music-electron program.

### Steps to Reproduce

1. Download Cider through snap `snap install cider`
2. Try to use any media key on your keyboard

### Environment Information

- OS: Ubuntu 21.10
- App Version: latest/edge 1.3.0 (2022-03-15) snap-id: 2PJi9WNcrpxB9Bh79Ov3E2V7Hc7PIMV8
- Commit ID:

### Anything else?

[Cider log](https://gist.github.com/Carlgo11/664dc84c03ce37b0e2e8d28655011cdc)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Could you post your log please. You can find the option to copy the logs in Settings.

**Comment by Carlgo11** [comment]
I added it as a [gist](https://gist.github.com/Carlgo11/664dc84c03ce37b0e2e8d28655011cdc).
Thinking the problem might be due to this line:
```
[error] DBusError: Connection ":1.165" is not allowed to own the service "org.mpris.MediaPlayer2.Cider" due to AppArmor policy
```

**Comment by coredev-uk** [comment]
Yeah, probably is that. I cant seem to find any documentation from electron on this AppArmor issue.

**Comment by coredev-uk** [comment]
You might be able to create your own apparmor profile by following [this](https://ubuntu.com/server/docs/security-apparmor).

**Comment by Carlgo11** [comment]
Potentially similar issue: https://forum.snapcraft.io/t/error-trying-to-comunicate-with-spotify-via-dbus/15501

**Comment by Carlgo11** [comment]
Bug not present anymore
