### ISSUE TITLE
[Bug]: Can't update due to CircleCI

### ISSUE THREAD

**Issue by chuck00000** [ciderapp/Cider#577]
### Describe the Bug

Cider can't updated latest development verison on Windows, always show error updating cider;
even  install older version of cider, click check updates button, still didn't get latest dev version, only stable version available. The Devlopmentment appimage isn't available on your cider.sh website.

Cider check update button always frustrating, About one month it's always say error updating cider, so I always go to older version of cider, click check updates button, in order to get latest dev version. How sucks of this!

### Steps to Reproduce

Cider can't updated latest development verison on Windows, always show error updating cider;
even  install older version of cider, click check updates button, still didn't get latest dev version, only stable version available. The Devlopmentment appimage isn't available on your cider.sh website.

Cider check update button always frustrating, About one month it's always say error updating cider, so I always go to older version of cider, click check updates button, in order to get latest dev version. How sucks of this!

### Environment Information

- OS:Windows 11
- App Version:
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
I believe this issue is caused as a result of the Winget builds being made in CI.

**Comment by quacksire** [comment]
CircleCi has made changes to their artifact handling, which makes no longer publicly available. I am frustrated with you on this. We are in the process of at least getting a redundancy plan into place, so the auto updating works as intended.

**Comment by chuck00000** [comment]
> CircleCi has made changes to their artifact handling, which makes no longer publicly available. I am frustrated with you on this. We are in the process of at least getting a redundancy plan into place, so the auto updating works as intended.

Ah! I uninstall the development version cider, can't get it back😭

**Comment by chuck00000** [comment]
> CircleCi has made changes to their artifact handling, which makes no longer publicly available. I am frustrated with you on this. We are in the process of at least getting a redundancy plan into place, so the auto updating works as intended.

cider stable verison check update today it's always says error updating cider

**Comment by quacksire** [comment]
> cider stable verison check update today it's always says error updating cider

it will say that as 

>  We are in the process of at least getting a redundancy plan into place, so the auto updating works as intended.

**Comment by chuck00000** [comment]
> > cider stable verison check update today it's always says error updating cider
> 
> it will say that as
> 
> > We are in the process of at least getting a redundancy plan into place, so the auto updating works as intended.

I'm not using the Microsoft Store verison.

**Comment by quacksire** [comment]
[To Continue Updating, You Need To Grab A Fresh Build](https://download.cider.sh/?exe)
