### ISSUE TITLE
[Bug]: app.relaunch() not working in linux

### ISSUE THREAD

**Issue by lehades** [ciderapp/Cider#582]
### Describe the Bug

I'm working on a plugin and i've found that trying to restart the app under linux does not work (in windows everything works as intended).

electron's standard procedure to restart the app is:
```
app.relaunch();
app.quit();
```

### Steps to Reproduce

1- Call these functions in a plugin
```
app.relaunch();
app.quit();
```
2- App closes (Linux & Windows)
3- App reopens (Windows), App stays closed (Linux)

### Environment Information

- OS: Ubuntu 21.10, Mint 20.3, Win10 21H2
- App Version: cider_1.3.1434 (both .deb and flatpak)
- Commit ID:

### Anything else?

https://www.electronjs.org/es/docs/latest/api/app#apprelaunchoptions

According to the docs there is an optional execPath which i've tried passing as process.execPath, process.argv0 or hardcoding the app path without any success

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
Hey can you try on cider's devtools console with 
```ipcRenderer.send('relaunchApp','');``` ?

**Comment by coredev-uk** [comment]
This never worked correctly, electron's relaunch function doesn't seem to operate correctly on Linux.

**Comment by quacksire** [comment]
```
By default, the new instance will use the same working directory and command line arguments with current instance. When args is specified, the args will be passed as command line arguments instead. When execPath is specified, the execPath will be executed for relaunch instead of current app.

Note that this method does not quit the app when executed, you have to call app.quit or app.exit after calling app.relaunch to make the app restart.

When app.relaunch is called for multiple times, multiple instances will be started after current instance exited.
```

**Comment by coredev-uk** [comment]
I've attempted to fix this with the recommended patch found [here](https://github.com/electron-userland/electron-builder/issues/4650), however from personal testing, this doesn't fix this. Feel free to test it yourself, but not much more can be done to resolve this.
