### ISSUE TITLE
[Bug]: New songs added appear at the bottom of the library in 'date added' sort mode

### ISSUE THREAD

**Issue by andreastheodor** [ciderapp/Cider#587]
### Describe the Bug

Songs added to my library in Apple Music or directly in Cider often don't show up in my library at the top, but at the very bottom of the list. This is in 'date added' sort mode. 

In general, though, adding new songs to the library in Cider isn't seamless, and while they do show up immediately in the Apple Music app, it takes a while for them to appear in my Cider library (and even if they do, at the bottom of the list as described above).

### Steps to Reproduce

I added a couple of new songs to my library in the Apple Music app and couldn't see them in my Cider library. I then scrolled down my list to find they had been added to the very bottom of my library. I'm using the 'date added, ascending' sort mode. 

Then when I added a new song to my library directly on Cider, the songs I had previously added on Apple Music (which appeared at the bottom of the list previously) now showed up at the top as normal. The new song I had just added however appeared at the very bottom again.

### Environment Information

- OS: Windows 11 Pro: 21H2
- App Version: 1.3.0 (via Microsoft Store)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
> In general, though, adding new songs to the library in Cider isn't seamless, and while they do show up immediately in the Apple Music app, it takes a while for them to appear in my Cider library (and even if they do, at the bottom of the list as described above).

Apple-provided API is pretty limited, for example, we have to manually load the albums list then sort the songs via date added info from the albums.
I may try to improve this but it's up to Apple to improve the API.
