### ISSUE TITLE
[Bug]: Can't install with winget

### ISSUE THREAD

**Issue by kglundgren** [ciderapp/Cider#590]
### Describe the Bug

I cannot install Cider with the winget command listed.
This is the command used:
winget install --id=CiderCollective.Cider.Nightly  -e

This is the error I get:
An unexpected error occurred while executing the command:
Download request status is not success.
0x80190194 : Not found (404).

### Steps to Reproduce

Run the command mentioned above.

### Environment Information

- OS: Windows 10.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
Hi, 
winget maintainer for Cider here. 

As the Devs are transitioning from using CircleCI to using Github Releases, there are a lot of bugs and as of now we cannot pass winget scans as the release archive repo is not yet setup. 
Do not worry though as @quacksire is working on a repo that has archivable releases.

**Comment by dxnnie** [comment]
> Hi, winget maintainer for Cider here.
> Do not worry though as @quacksire is working on a repo that has archivable releases.

Same issue here, but on Windows 11 Pro.

Thanks for clarifying for us.

**Comment by yazninja** [comment]
Update: Cider has now made a PR to winget, just waiting for a review from the moderators, then we are all set!
![image](https://user-images.githubusercontent.com/71800112/159391422-45d51242-bab0-4673-8392-623b8635bc95.png)

**Comment by yazninja** [comment]
Hi OP @kglundgren  and @dxnnie,
winget package has been updated. Thank you for your patience and sorry for the inconvenience.

**Comment by kglundgren** [comment]
@yazninja I can confirm that it works now. Thanks!

**Comment by yazninja** [comment]
Nice, you may close the issue now if you don't have any further queries ig

**Comment by dxnnie** [comment]
> Hi OP @kglundgren and @dxnnie, winget package has been updated. Thank you for your patience and sorry for the inconvenience.

Nohing to be sorry about! Thanks for the amazing software and the amazing work that you do.
