### ISSUE TITLE
[Bug]: Cannot use buttion in the desktop taskbar icon

### ISSUE THREAD

**Issue by flex-enjoy** [ciderapp/Cider#592]
### Describe the Bug

When clicking previous / pause / next button in the desktop taskbar, cider will throw an error like:

Error occurred: Uncaught TypeError: MusicKitInterop.nextTrack is not a function

### Steps to Reproduce
1.
![ksnip_20220321-223957](https://user-images.githubusercontent.com/99305234/159285154-447c06eb-f5c3-4db0-80cd-aebb987240d1.png)
2.
![ksnip_20220321-223936](https://user-images.githubusercontent.com/99305234/159285197-16a0f515-d3a4-4150-ace4-edb2936f79dc.png)

### Environment Information

- OS: Gentoo Linux / KDE Plasma 21.03
- App Version: 1.3.1483

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
What build are you on?

**Comment by flex-enjoy** [comment]
> What build are you on?

Using deb from https://dl.circleci.com/private/output/job/32e8c020-c09f-4415-ae32-aedd6013f1e4/artifacts/0/~/Cider/dist/artifacts/cider_1.3.1483_amd64.deb

**Comment by flex-enjoy** [comment]
Seems fixed in version 1.4.0.1631
