### ISSUE TITLE
[Bug]: Unable to login

### ISSUE THREAD

**Issue by PKizzle** [ciderapp/Cider#593]
### Describe the Bug

When trying to login using my Apple credentials, I receive a connection error. Trying to login again does not solve it. I have 2FA enabled, so the login requires me to enter a code sent to one of my Apple devices. Strangely it takes quite a long time until I receive a code on my devices. I have additionally tried to reinstall the app, but that also has not solved the issue for me.

This is an image of the error:
![image](https://user-images.githubusercontent.com/39984529/159328077-a801b46a-e88e-4c00-b90c-67d8bf85b069.png)
The text is in German. Rough translation: Connection error. Possibly there is a network connection issue. Try again.

### Steps to Reproduce

1. Start Cider
2. Try to login using the popup window

### Environment Information

- OS: Windows 11 21H2 (Build 22000.588)
- App Version: 1.3.0.0
- Commit ID: unknown - Microsoft Store version

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PKizzle** [comment]
I don't know how or why, but I was able to successfully login again. Is this issue on Apple's side?

![image](https://user-images.githubusercontent.com/39984529/159330658-06b49ff1-bfb7-4e4e-86b5-a74a1be4f87a.png)
Translation: You're logged in. You can now use the Apple Music player on this and other websites to listen to tracks and add them to your library.

**Comment by biutas** [comment]
Yep, was an issue on Apple SSO. iCloud, Music, App Store, Maps.. all were off for a few minutes.

**Comment by maikirakiwi** [comment]
Apple had an outage and is now fixed.

**Comment by PKizzle** [comment]
Ah, I see. That's a relief. By the way, I just found out that you have to mark the browser as "secure" during the 2FA authentication otherwise the login window opens again and again. Is that unavoidable?
