### ISSUE TITLE
[BUG] Album art sometimes doesn't load on Now Playing Bar 

### ISSUE THREAD

**Issue by Nosh118** [ciderapp/Cider#60]
**Describe the bug**
Album art doesn't display on now playing bar

**To Reproduce**
1. Play a song

**Expected behavior**
Album art should display instead of just an outline of a square

**Screenshots**
Don't have any atm, it's inconsistent

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows
 - Application Version *(e.g. 2.5.0)*: Build Windows #457 Action
 
**Additional context**
Happens on and off - yet album art-based gradients still display for full screen lyrics

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
N/A

**Log File**
Follow [this](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/FAQs#2-how-to-find-the-log-file) to find your log file.
Attach your log file to the post but make sure to remove any LastFM keys that are in the file.
I assume this is redundant

**Comment by gms10ur** [comment]
I can confirm I have this issue too. here is a screenshot.
![image](https://user-images.githubusercontent.com/17664911/148268503-a025c8a4-7390-466a-982f-44442fd4e930.png)
