### ISSUE TITLE
[Bug]: Web Remote Button

### ISSUE THREAD

**Issue by trevorraney** [ciderapp/Cider#603]
### Describe the Bug

The Web Remote button in the Cider drop down leads to the Cider.sh homepage. Not sure why it's linked there, seems like information that should be on the About page in the app. 

Second, the "Remote" button on the page clicking on "Web Remote" in the drop down just leads to Cider.sh/remote. The QR code is gone.

### Steps to Reproduce

1. Clicked Cider dropdown menu
2. Clicked "Web Remote" -> Taken to Cider.sh about page
3. Clicked "Remote" -> Taken to Cider.sh/Remote
4. No QR code to scan with the Cider Remote app

### Environment Information

- OS: Windows 10
- App Version: 1.3.1516
- Commit ID: b5f7635

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
Hi @trevorraney ,
Canyou try if your problem persists in the [latest develop](https://github.com/ciderapp/cider-releases/releases/download/v1.3.0.1562/Cider-Setup-1.3.0-alpha.1562.exe) release.

**Comment by trevorraney** [comment]
Hey, thanks for the response, 

Just updated and yes, still persists. Possibly I'm not looking in the right place for the QR code to scan, or it actually isn't implemented yet. Thought I saw it on a release a few weeks ago. Video below showing the issue I described above.

<video src="https://user-images.githubusercontent.com/64988493/160245463-673864c9-831a-4d0f-9eda-6520170af283.mp4"></video>

**Comment by quacksire** [comment]
Are you behind a school or a business firewall that prevents the app from querying your local IP?

**Comment by trevorraney** [comment]
I am not.

**Comment by trevorraney** [comment]
So I just used one of those online QR code generators with the local address that Cider is using for the remote, scanned it with the app, and it worked.

However, Cider is still not displaying a QR code anywhere within the app as far as I can tell.

**Comment by aryamanpurkait** [comment]
> So I just used one of those online QR code generators with the local address that Cider is using for the remote, scanned it with the app, and it worked.
> 
> However, Cider is still not displaying a QR code anywhere within the app as far as I can tell.

Umm...how did you do that?

**Comment by trevorraney** [comment]
> > So I just used one of those online QR code generators with the local address that Cider is using for the remote, scanned it with the app, and it worked.
> > However, Cider is still not displaying a QR code anywhere within the app as far as I can tell.
> 
> Umm...how did you do that?

I know what the local address and port number were for the remote interface. Using that address I plugged it into a QR code generator, scanned it with the Cider Android app, and it worked.

**Comment by aryamanpurkait** [comment]
So where did you get the local address and port address?

**Comment by trevorraney** [comment]
I had previously bookmarked the address when the QR code was generated in the app — likely a nightly from late February/early March.

I just assumed that the address/port converted to a QR code when scanned in the Cider Remote android app would open the remote controls.

**Comment by aryamanpurkait** [comment]
So where were you able to generate the QR from the app initially?

**Comment by trevorraney** [comment]
Yes...as was said in my original issue post:

> _Second, the "Remote" button on the page clicking on "Web Remote" in the drop down just leads to Cider.sh/remote. **The QR code is gone.**_

The QR code previously appeared for me within the app when I clicked on the "Remote" button in the Cider settings. Now it doesn't. Assumed it was an error, but perhaps it was intentional.

It's all moot now in my particular case, but for other people who do want to use the Remote companion app, they may be confused.

**Comment by aryamanpurkait** [comment]
So I guess I'll have to wait for further notice.

**Comment by yazninja** [comment]
> So I guess I'll have to wait for further notice.

I can help you personally on discord. just send a ping/dm
