### ISSUE TITLE
[Bug]: Track play/pause, next & previous does not work with function keys.

### ISSUE THREAD

**Issue by EA-Wardie** [ciderapp/Cider#604]
### Describe the Bug

When using keyboard function keys to play/pause, next and previous a track the app throws an error message.

![next_track](https://user-images.githubusercontent.com/56725833/159517518-94c8b050-fc7b-46af-81e8-53d6d8ab070b.png)
![play_pause](https://user-images.githubusercontent.com/56725833/159517527-04fcc7e2-5257-423a-a55c-20d3b9683f52.png)
![prev_track](https://user-images.githubusercontent.com/56725833/159517534-4413b3df-4165-41f0-ad10-10904a073254.png)

### Steps to Reproduce

1. Have a track playing (in playlist).
2. Use keyboard function/multimedia keys to play/pause, next or previous the track.

### Environment Information

- OS: popOS 21.10
- App Version: 1.3.1308
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
.

**Comment by Shane-Park** [comment]
### Environment
- OS: Ubuntu 20.04 
- Version: 1.3.1483

has same issue

**Comment by coredev-uk** [comment]
This is a bug with main, use any nightly release if you want a quick fix. Once the branch is merged, it should be fixed.
