### ISSUE TITLE
[Enhancement] Replace "play" and "shuffle" buttons with icons

### ISSUE THREAD

**Issue by ar33ny** [ciderapp/Cider#66]

**Comment by ConnectedR** [comment]
I think the icons should appear before the text like iOS rather than replace it. 
![1C9B5361-0C5F-4155-BF21-2CFA1724BDB1](https://user-images.githubusercontent.com/44319023/148277249-d36801a2-69f3-43b1-b085-75c88282d4a8.jpeg)

**Comment by gms10ur** [comment]
### done in #158 
![img](https://cdn.discordapp.com/attachments/912876442117894154/933543722598170634/unknown.png)
