### ISSUE TITLE
[Enhancement] Add play/pause, next and previous buttons to the miniwindow of app (Thumbar Buttons)

### ISSUE THREAD

**Issue by ar33ny** [ciderapp/Cider#68]
![image](https://user-images.githubusercontent.com/88456605/148224800-f696d8e7-a644-42c3-8885-8fa180a335b7.png)
here! Spotify has it and I use it very much so it might be cool

**Comment by gms10ur** [comment]
added with the pull request of #138 <3

**Comment by quacksire** [comment]
merged, added

**Comment by gms10ur** [comment]
Not available on upcoming tho..
