### ISSUE TITLE
[Enhancement]: Wayland Support

### ISSUE THREAD

**Issue by Loberrino** [ciderapp/Cider#684]
### The feature you would like

Wayland Support is probably one of the lower priority requests to be made thus far, but being able to run Cider on native Wayland would really just complete it for me, as it seems that currently trying to start the game without XWayland just crashes it.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
I believe passing `--enable-features=UseOzonePlatform --ozone-platform=wayland` will resolve the crashing. Electron does have native support on Wayland, just need to tweak it a bit.

**Comment by lrazovic** [comment]
> > I believe passing `--enable-features=UseOzonePlatform --ozone-platform=wayland` will resolve the crashing.
> 
> Well I just tried enabling support for Wayland windowing in Flatseal for Cider and then running `flatpak run sh.cider.Cider --enable-features=UseOzonePlatform --ozone-platform=wayland` and I got:
> 
> ```
> [08:31:57.642] [info]  [AppEvents] App started
> [08:31:57.649] [info]  WebGPU is enabled.
> LaunchProcess: failed to execvp:
> xdg-settings
> LaunchProcess: failed to execvp:
> xdg-settings
> LaunchProcess: failed to execvp:
> xdg-settings
> LaunchProcess: failed to execvp:
> xdg-settings
> LaunchProcess: failed to execvp:
> xdg-settings
> LaunchProcess: failed to execvp:
> xdg-settings
> [08:31:57.991] [info]  [PluginHandler] Loaded plugins: [
>   'chromecast.js',
>   'discordrpc.js',
>   'lastfm.js',
>   'menubar.js',
>   'mpris.js',
>   'thumbar.js',
>   'webNowPlaying.js'
> ]
> interface 'wl_output' has no event 4
> ```

This is unfortunately a known bug fixed in Electron 17.3 and later. Cider is currently using Electron 16.0.7.
