### ISSUE TITLE
[Bug]: Playing music on another device (iPhone, iPad, etc) causes error when Cider is open

### ISSUE THREAD

**Issue by xx88xx** [ciderapp/Cider#692]
### Describe the Bug

an error comes up on iphone apple music saying "more than one device is trying to be used at once - please become a family member" or something along those lines, even though cider is not playing anything actively.

### Steps to Reproduce

1. open cider 
2. leave it open on your dekstop
3. play something in AM on iphone

### Environment Information

- OS: win 11 - ios 15.4
- App Version: cider 1.3.1254
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xx88xx** [comment]
![image](https://user-images.githubusercontent.com/60696375/160093904-1864eec2-53ec-4b8f-98e6-1e78eac58a46.png)

**Comment by coredev-uk** [comment]
With this, there isn't much we can do. A timeout could be added that closes Cider after a certain amount of time of inactivity, but due to the limited functionality of MusicKit, we cant keep the app connected and open without logging you out.

**Comment by cryptofyre** [comment]
Adding some RnD on this by saying that after the timeout value (set by the user) has been reached without user playback we could probably just restart musickit and keep the user logged in as normal but it would clear the current song loaded.

**Comment by xx88xx** [comment]
@cryptofyre would there be a way to program it so it refreshes musickit and then takes it back to that song, but doesn't start playing? or does interacting with musickit at all, like populating the player (without playing the song) cause the same issue?

**Comment by xx88xx** [comment]
this is still an ongoing issue in latest build

**Comment by Arch-Storm** [comment]
Yes, pls try to find a workaround for this. I've been going insane because of this.

**Comment by vapormusic** [comment]
ok should we just add pause timer to stop this lmao
