### ISSUE TITLE
[Bug]: Cider randomly stops playing music

### ISSUE THREAD

**Issue by xx88xx** [ciderapp/Cider#693]
### Describe the Bug

after an hr or so of use, cider stops playing music.
the only thing that solves this is fully closing cider and reopening it or pressing ctrl + f10

### Steps to Reproduce

1. use cider for an hr or so
2. at one point it will stop playing a song midway, or will not go on to play the next song
3. restart of cider or ctrl + f10 is required to continue using cider

### Environment Information

- OS: win 11
- App Version: 1.3.1254
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
try disabling this 
[!](https://images-ext-1.discordapp.net/external/dav_SGIhB5rpGHGk_y6MDwv6EFjJ_SNhCaB0AonrN8Y/https/cdn.upload.systems/uploads/PpqgifkH.png?width=1439&height=235)

**Comment by xx88xx** [comment]
@yazninja ok I'll try next few days!

**Comment by xx88xx** [comment]
Didn’t fix it, but may have improved and extended the amount of time between refreshes

**Comment by xx88xx** [comment]
is anything being done to fix this?

**Comment by cryptofyre** [comment]
Can’t reproduce this issue.

**Comment by eproxus** [comment]
Still an issue.

**Comment by theironraiden** [comment]
Had this same issue. After disabling seamless audio transition, I stopped having no audio at all, but now insteal some times I get choppy audio (1 sec audio 1 sec pause) until y restart the app or CTRL+F10

**Comment by jordanspringer** [comment]
I had this issue on the Windows Store app versions prior to 1.5.2. I haven't had music randomly stop playing so far in 1.5.2 or 1.5.3.

**Comment by eproxus** [comment]
Yeah, this seems fixed to me

**Comment by theironraiden** [comment]
In the latest version it appears to be fixed.

**Comment by cryptofyre** [comment]
Appears to be fixed, closing.
