### ISSUE TITLE
[Bug]: Recently Added not moving to next or previous song

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Cider#695]
### Describe the Bug

In Library > Recently Added tab, it is not possible to skip to next or previous song. I have to select songs manually to play them.

### Steps to Reproduce

1. Go to Library > Recently Played
2. Double click / Click on Play on a song
3. Try to skip to next song or previous song
4. Nothing happens, current song continues to play and when it ends, nothing happens.

### Environment Information

- OS: Windows 11
- App Version: 1.3.1550
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
Tbh this happens across all of AM because you are technically playing just that album/single on its own and not in a list.. Happens in iOS, Android, iTunes and Mac. Can you even consider this a bug?

**Comment by Naxterra** [comment]
> Tbh this happens across all of AM because you are technically playing just that album/single on its own and not in a list.. Happens in iOS, Android, iTunes and Mac. Can you even consider this a bug?
> 
> Selecting songs and sorting by date added achieves the same thing you want to do.

Then maybe menu style could be different, because it looks like same as Library > Songs > Sort by Date added instead of showing Recently Added songs / albums in their own separate space.

**Comment by KillerParticles** [comment]
The songs section only displays songs and music videos whereas the recently added is meant to include everything, songs and music videos plus albums and other things. 

Maybe an enhancement can be made at best, but I don't see it as a bug unless you call it a bug with AM in general, but its not a Cider bug per say.

**Comment by Naxterra** [comment]
Then I will open a new ticket for feature request.
