### ISSUE TITLE
[Bug]: Manually uploaded songs cannot be removed from Library

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Cider#696]
### Describe the Bug

Manually uploaded songs, like via iTunes previously, cannot be removed from library. When I right click on the song, I see Add to Library option, and adding then removing has no effect.

### Steps to Reproduce

1. Right Click on uploaded song
2. Select Remove or Add to library
3. Song stays
![24-03-2022_21-21-12](https://user-images.githubusercontent.com/41871948/160003381-d93f236f-56df-4b45-8cf2-18cca97d0008.png)

### Environment Information

- OS: Windows 11
- App Version: 1.3.1550
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by xx88xx** [comment]
Have noticed this too
