### ISSUE TITLE
[Bug]: Manually uploaded ringtones has no menu and cannot be played

### ISSUE THREAD

**Issue by Naxterra** [ciderapp/Cider#697]
### Describe the Bug

Manually uploaded ringtones via iTunes to the Library cannot be played. Right click has no effect and clicking on Play has no effect either.

### Steps to Reproduce

1. Clicked on uploaded ringtone
2. Nothing happens when selecting Play or right clicking on it.

### Environment Information

- OS: Windows 11
- App Version: 1.3.1550
- Commit ID:

![24-03-2022_21-24-56](https://user-images.githubusercontent.com/41871948/160003887-e56b2a47-c006-4f54-9d91-7f7c07b2384f.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
does this play in [Apple Music Web](https://music.apple.com) ?

**Comment by Naxterra** [comment]
> does this play in [Apple Music Web](https://music.apple.com) ?

Interesting, it doesn't play in AM Web but it plays in iTunes
