### ISSUE TITLE
[Bug]: "Show Complete Album" appears at bottom of every album in user's library

### ISSUE THREAD

**Issue by 8times9** [ciderapp/Cider#700]
### Describe the Bug

The default behavior in Music.app iOS is to only show "Show Complete Album" at the bottom of an album if that user does not have the full album saved to their personal library.

As it is now in Cider, it shows underneath every tracklist for every single library album regardless of whether the complete album is saved or not.

Why does it matter? Because this makes it take one more step to show the post-tracklisting "More by", "Featured on", and "You Might Also Like" sections, which are hidden by this Show Complete Album text and require clicking on it and scrolling back down to view them.

### Steps to Reproduce

1. Ensure an album is on your library
2. Click on album in the Recently Added, Albums, Artists, etc pages. On the Listen Now page, only the albums shown in the Recently Played section will exhibit the incorrect behavior described.
3. Scoll to the bottom and observe the text link to Show Complete Album.

### Environment Information

- OS: Windows 10
- App Version: 1.3.0 MSFT version
- Commit ID: Unsure how to view this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
![image](https://user-images.githubusercontent.com/71800112/160074528-10916b70-aaff-4651-8bf2-86ff8aa00268.png)
this is already fixed in development versions, wait for it to be updated to the MSFT store version
