### ISSUE TITLE
[Bug]: LastFM not connecting.

### ISSUE THREAD

**Issue by Tuanboard** [ciderapp/Cider#701]
### Describe the Bug

Cannot track to LastFM while it said connected.

### Steps to Reproduce

1. Link to LastFM as it leads.
2. Check the information when it's connected.
3. Music cannot be tracked correctly.

### Environment Information

- OS: Windows 10
- App Version: the latest
- Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
![image](https://user-images.githubusercontent.com/71800112/160074103-0ad93626-7c9b-42d4-b012-1b4a4f7e7167.png)
Debug -> Open Cider folder.
Delete the whole folder.
Then log back in to apple music and reconnect to Last.fm

**Comment by lucianoratamero** [comment]
After debugging it a bit, I found out what the error was. No idea how to fix it, though 😓 

```js
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them
    at Function.s (<anonymous>:1:83)
    at Cn.LastFMAuthenticate (http://localhost:9000/main/vueapp.js:4059:13)
    at HTMLButtonElement.onclick (http://localhost:9000/#settings:1:5)
```

This error is thrown when the authentication callback is triggered here: https://github.com/ciderapp/Cider/blob/39802835d56ad40ffaf8f14a06f15db0052ab407/src/renderer/main/vueapp.js#L4059

**Comment by lucianoratamero** [comment]
bumping to prevent the bot from auto closing the issue

**Comment by coredev-uk** [comment]
Lastfm was reworked, should be good now.
