### ISSUE TITLE
[Enhancement] Heart(Favorites) Button Changes

### ISSUE THREAD

**Issue by KBB8942** [ciderapp/Cider#71]
I feel like it would be better if the heart( favorite ) button for individual songs is the same as the one on the playbar
![image](https://user-images.githubusercontent.com/97172684/148225586-54f0a1ea-eb3e-4b5a-8e6e-453e5e2f2dc4.png)

**Comment by mahendrsa** [comment]
How did you get the button working? mine always shows up not liked

Like this:
![image](https://user-images.githubusercontent.com/71089682/149604467-c01ecc0a-b961-4f4a-aabd-1bd99d955ded.png)
