### ISSUE TITLE
Android app/Discord integration questions

### ISSUE THREAD

**Issue by dnestico** [ciderapp/Cider#713]
### The feature you would like

Just wondering if there are any plans for an Android app?

The apple music app is fine but this would be a nice replacement.

Also just wondering if it's possible to use the Apple Music API to tell discord what music I'm listening to for my status on any device. It works great on cider but I would love it to work when I listen on my phone. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
> Just wondering if there are any plans for an Android app?

There is a Cider Remote App in Google Play

**Comment by dnestico** [comment]
I mean a replacement for the apple music android app, that I can use anywhere as my music player on the go.

**Comment by dnestico** [comment]
> There is a Cider Remote App in Google Play
> 
> 
I mean a replacement for the apple music android app, that I can use anywhere as my music player on the go.

**Comment by KillerParticles** [comment]
The AM app on android is already one of the best experiences you can have listening to AM in general, not trying to bash the Cider team or anything but I don't see what would be better about Cider over the official app in this case. Why do you want Cider on Android?

**Comment by dnestico** [comment]
Not really that I want it was just asking if its available tbh.

But if it was it would be nice for the customization abilities like themes and also just a new UI. But not a big thing I need, just asking.

**Comment by yazninja** [comment]
I guess it would be possible, you will still need the Apple Music app for authenticatipns, and as far as i know, still no downloads support with the current implementation of Musickit for Android.

**Comment by KillerParticles** [comment]
Apps like Marvis Pro exist on IOS and is really good, since you have android I know you can't get it but if you've seen people use Marvis Pro, is that basically what you want?

There does seem to be a need for it I guess as people really like Marvis.

**Comment by dnestico** [comment]
Pretty much yea, just a different apple music client, ideally open source. I know there's a couple on IOS. Would be cool even though yes AM app is already good.
