### ISSUE TITLE
[Bug]: ⌘Q does not quit the Cider on MacOS

### ISSUE THREAD

**Issue by gravo-lan** [ciderapp/Cider#721]
### Describe the Bug

After using the quit keyboard shortcut, ⌘Q, Cider goes black and does not quit, the music continues playing but there's no GUI.
To quit Cider you need to either force-quit or use the menu bar icon

<img width="1280" alt="Screenshot 2022-03-27 at 7 29 20 PM" src="https://user-images.githubusercontent.com/66149576/160279369-f07a189b-9b1d-49ff-9574-3ff7a3f16118.png">

### Steps to Reproduce

1. ⌘Q or click the close button on the Cider window
2. Screen goes black but nothing closes
3. Menubar icon > Quit is required to quit or resume using since GUI is blacked out

### Environment Information

- OS: MacOS Monterey 12.2.1
- App Version: 1.1.0
- Commit ID: 862dbc5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MakufonSkifto** [comment]
It's not fixed. I downloaded the app today and the error still remains. I'm on `macOS Monterey 12.3.1`.

**Comment by quacksire** [comment]
This should be resolved now with https://github.com/ciderapp/Cider/commit/5f07c8309fa5047bdb9853435819796aee063090

I fixed the default keybinds, so you might need to delete your cider-config file for it to take into effect
