### ISSUE TITLE
[Enhancement] Remove single/ep/album thing from the song

### ISSUE THREAD

**Issue by ar33ny** [ciderapp/Cider#73]
![image](https://user-images.githubusercontent.com/88456605/148226712-14e64894-3d45-4980-b1e8-6dcde48a8a47.png)

I want to listen a song, I don't really care whether it's EP or single, that's information noise.

**Comment by lance-374** [comment]
You could edit the metadata using iTunes. the " - Single" is just part of the name of the album on Apple Music.

**Comment by Swiftzerr** [comment]
Dog thats the album name

**Comment by inalone** [comment]
https://github.com/ciderapp/Cider/pull/504
