### ISSUE TITLE
[Bug]: Windows app seems to be stuck while opening

### ISSUE THREAD

**Issue by vmax77** [ciderapp/Cider#730]
### Describe the Bug

I just installed the app and opened it, and it seems to be stuck at startup splash screen with the Cider Logo, and nothing seems to happen after. I have uninstalled and reinstalled the app multiple times. 

My config: 
Windows 11 (insider - Beta)
Intel i5-10600K
64GB RAM

### Steps to Reproduce

1. Opened the app 
2. Stuck in startup splash

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID: Unable to find out. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Are you on the microsoft store version or develop/main?

**Comment by vmax77** [comment]
Store Version

**Comment by maikirakiwi** [comment]
I'm semi sure that it's because microsoft store is outdated on patches. Microsoft is currently reviewing an update that we just submitted few days ago and for the meantime, please go to https://github.com/ciderapp/cider-releases/releases and download any build that says (develop).

**Comment by vmax77** [comment]
Yes, that seems to work!
