### ISSUE TITLE
[Bug]: Error occured: Script error.

### ISSUE THREAD

**Issue by RC-14** [ciderapp/Cider#731]
### Describe the Bug

When I start Cider I get this popup:
![image](https://user-images.githubusercontent.com/61058098/160557026-b951aa16-822c-4d5e-8e1c-dae427c44708.png)

It doesn't seem to break anything and is just annoying.

### Steps to Reproduce

1. Start Cider
2. Wait for the UI to appear
3. UI and error message appear

### Environment Information

- OS: 5.15.28-1-MANJARO x86_64 GNU/Linux (uname -rmo)
- App Version and/or Commit ID: cider-git 1.4.0.2845.023843c3-1

### Anything else?

The [provided steps for a clean install](https://github.com/ciderapp/Cider/wiki/Troubleshooting) did not fix the problem. (a reboot did fix it once but not anymore)

Log when starting Cider in console: [tmp.log](https://github.com/ciderapp/Cider/files/8368920/tmp.log)

I found this while searching for solutions: https://git.dorkbox.com/dorkbox/SystemTray/commit/18aa47ae5b8f4ebdc24e30182ebcd49bf25b3499

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by golebara** [comment]
I just bought the app. Same error. First and every launch results in the same error.

OS: Windows 11 Pro (OS Build: 22000.556)
Cider app version: 1.4.0

**Comment by yazninja** [comment]
Hi, this is a problem with our API and will be fixed shortly.

**Comment by golebara** [comment]
@yazninja Thanks!

**Comment by yazninja** [comment]
It should be good, you can close the Issue if you have no other questions :>>

**Comment by golebara** [comment]
Thanks @yazninja 
Looks like the error has gone away
