### ISSUE TITLE
[Feature Request]: Connect everything through proxy

### ISSUE THREAD

**Issue by s-kk** [ciderapp/Cider#732]
### The feature you would like

The ability to configure Cider to connect through a proxy (HTTP, HTTPS or Socks proxy).

### Alternatives and Other Information

Add an option to enable proxy in settings or add a commandline option. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
You should be able to do this through an OS-level setting.
