### ISSUE TITLE
[Bug]: Wont open after install on Mac

### ISSUE THREAD

**Issue by Josech18** [ciderapp/Cider#738]
### Describe the Bug

I just installed Cider MacOs Build for the first time and it wont even open. It says "Cider is not responding. Reload the app" over and over again. 

### Steps to Reproduce

Dead on Arrival, I cant even open it after the first install 

### Environment Information

- OS: MacOS Monterey 12.3
- App Version and/or Commit ID:

### Anything else?

<img width="1013" alt="Screen Shot 2022-03-29 at 10 19 31 AM" src="https://user-images.githubusercontent.com/99493108/160646233-c0b8db00-71c5-4438-8e5f-a9e5978baf72.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by joelghill** [comment]
This also appears to be an issue on Windows 11. New to the app, is there an error log we can submit to help diagnose?

Windows 11, version 22H2 Insider Preview (10.0.22581.100) 
Cider v1.4.0

**Comment by Josech18** [comment]
I’ve tried that, still getting the same error message.

**Comment by quacksire** [comment]
Try reinstalling, it should work now
