### ISSUE TITLE
Mac App won’t start. 

### ISSUE THREAD

**Issue by Jeanmarchp** [ciderapp/Cider#741]
### Describe the Bug

The app doesn’t seem to launch a window when opening the app. If I restart the MacBook then it works and launches the full app. 

### Steps to Reproduce

1. Close The app and open it again.

 

### Environment Information

- OS: Mac OS Latest build 
- App Version and/or Commit ID: latest version 

### Anything else?

Issue seems to fix it self after a restart of the MacBook 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PapiPeppers** [comment]
Same thing for me. I can get the sign in dialog, but after entering my apple ID details and getting to the next screen with the "Continue" button, clicking "Continue" does nothing nor does hitting enter or any other method of pressing the button. No other windows are opened and none are accessible in the menu.

**Comment by dborod** [comment]
I'm having the same issue. Rebooting my Mac hasn't resolved the issue.

I'm in Canada, in case that's a useful data point.
