### ISSUE TITLE
[Bug]: [Microsoft Store] Open Themes Folder and Open Cider Folder buttons point to an unavailable location 

### ISSUE THREAD

**Issue by Thunderz2016** [ciderapp/Cider#742]
### Describe the Bug

In the Microsoft Store version, the "Open Themes Folder" and "Open Cider Folder" buttons point to non-existent folders in %appdata%, and the paths to the actual themes and Cider folders are unclear. 

### Steps to Reproduce

When clicking on the "Open Themes Folder" button on the "Themes from GitHub" page, an error message saying that location "%appdata%\Cider\Themes" is unavailable appears. A similar error message also appears after clicking on the "Open Cider Folder" button under the Advanced setting.

### Environment Information

- OS: Windows 10 Home 21H2 build 19044.1586
- App Version and/or Commit ID: 1.4.0 (Microsoft Store)

### Anything else?

A screenshot of the error message that appears after clicking on the "Open Themes Folder" button:
![image](https://user-images.githubusercontent.com/24950670/160682241-659e0c81-215e-4bc1-a4a2-0d8181620acc.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amaru8** [comment]
**Hi @Thunderz2016, I have some great news!** This bug is now fixed in the latest development version of **Cider**, and the fix will be included in the next Microsoft Store update.
