### ISSUE TITLE
[Bug]: Cannot install via npm

### ISSUE THREAD

**Issue by spencerkraisler** [ciderapp/Cider#745]
### Describe the Bug

I tried following the configuration instructions and got to the point where I type "npm install". I do have git and npm installed and working correct. I got this following error:

```
Cider % npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cider@1.4.0
npm ERR! Found: webpack@5.69.1
npm ERR! node_modules/webpack
npm ERR!   dev webpack@"~5.69.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer webpack@"^4.42.1" from electron-webpack@2.8.2
npm ERR! node_modules/electron-webpack
npm ERR!   dev electron-webpack@"^2.8.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/spencerkraisler/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/spencerkraisler/.npm/_logs/2022-03-30T06_22_44_276Z-debug-0.log

```

### Steps to Reproduce

1. cd Cirder
2. npm install

### Environment Information

- OS: macOS 12.3
- App Version and/or Commit ID: Current app version

### Anything else?

I am running on a Mac studio, which using the ARM M1 max chip. Very possible that this won't work since it runs on x86 maybe?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
do not use npm to install
read the docs

**Comment by spencerkraisler** [comment]
> do not use npm to install (if u really want to use npm, do `npm install --force`)
> read the docs:
> https://github.com/ciderapp/Cider/wiki/Compiling
> Its better to use yarn

Tried the force thing already but didn’t work. I’ll try yarn. As a side note, the configuration tutorial says yarn is option. Someone should
update it with this information.

**Comment by yazninja** [comment]
> the configuration tutorial says yarn is option. Someone should update it with this information.
Ill ask the person maintaining the wiki about this, thanks for notifying!

**Comment by coredev-uk** [comment]
It is optional as npm usually does work as an alternative.

**Comment by quacksire** [comment]
```
npm i --force
```

**Comment by coredev-uk** [comment]
> npm i --force

They already did this, -f is short for —force.

**Comment by adolphnov** [comment]
> do not use npm to install (if u really want to use npm, do `npm install --force`)
> read the docs:
> https://github.com/ciderapp/Cider/wiki/Compiling
> Its better to use yarn

I'm sad, I'm using yarn but it compiles with errors.

`Found 2 errors in the same file, starting at: node_modules/@types/verror/index.d.ts:31`

**Comment by vapormusic** [comment]
Building in MacOS is really tricky, I don't really recommend anyone to build it themselves. If you wanna see how I did it, look at this file: 

https://github.com/ciderapp/Cider/blob/main/.github/workflows/build-macos.yml

**Comment by adolphnov** [comment]
Thank you bro.

**Comment by rursache** [comment]
thanks @vapormusic, this should be in the wiki

>  yarn install
>  cp resources/verror-types node_modules/@types/verror/index.d.ts
>  cp resources/macPackager.js node_modules/app-builder-lib/out/macPackager.js 
>  yarn dist:universalNotWorking -p never
