### ISSUE TITLE
[Bug]: macOS icon is larger than others

### ISSUE THREAD

**Issue by squintgit** [ciderapp/Cider#753]
### Describe the Bug

This isn't really a bug, but it's not a feature request either, so I'm classifying as a bug.

It's also minor, but the Cider icon on macOS is larger than the default icons. It kind of sticks out in the dock.

Would like to see the icon more closely match the size of Apple's default icons.

### Steps to Reproduce

n/a

### Environment Information

- OS: macOS Monterey
- App Version and/or Commit ID: 1.4.0

### Anything else?

No

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by raphaklr** [comment]
FYI, here is a screenshot of the issue:

<img width="212" alt="Bildschirmfoto 2022-05-03 um 13 11 25" src="https://user-images.githubusercontent.com/6332580/166443315-a67a1ac9-5b20-4c0f-8fe6-08c6397f2a2b.png">

Also: This duplicated issue https://github.com/ciderapp/Cider/issues/753.

**Comment by raphaklr** [comment]
Still an issue ¯\_(ツ)_/¯

**Comment by cryptofyre** [comment]
Fixed a while ago.
