### ISSUE TITLE
[Bug]: Cider never loads songs

### ISSUE THREAD

**Issue by LaramieJoe** [ciderapp/Cider#760]
### Describe the Bug

A bug happened! Not sure what's happening, but Cider will not ever load my songs library. 

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS:
- App Version and/or Commit ID:
windows 11

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
please fill in each answer to the best of your ability in order for us to help you
