### ISSUE TITLE
[Feature Request]: Upload my files with music for icloud library music

### ISSUE THREAD

**Issue by hackintosh1984pl** [ciderapp/Cider#761]
### The feature you would like

I have upload my files with music to iCloud music libray - Apple Music/Match subscryption . iTunes or new aplication Music.app this doing. Cider also ?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
File uploading is not supported in Cider, let alone MusicKit. Your best chance is to import them into iTunes/Music.app and turn "Sync Library" on
