### ISSUE TITLE
[Bug]: Vertical Monitor Lyrics/Queue Formatting Issues

### ISSUE THREAD

**Issue by RohanB2** [ciderapp/Cider#764]
### Describe the Bug

Vertical 16:9 Monitor Formatting Issue when looking at full cover + current playing info + lyrics/queue.

### Steps to Reproduce

1. Clicked on the album cover of the current playing song
2. Pulls up the song with current playing info as well as current lyrics or queue.

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID: Cider for Microsoft Store

### Anything else?

![formatting cider issue](https://user-images.githubusercontent.com/102451995/160970022-f0257f0d-bd82-49c1-8fc8-0a6d991d21b1.png)
![image](https://user-images.githubusercontent.com/102451995/160970100-81e3ce15-465d-4ed1-b267-0ad238b416f8.png)
Lyrics are getting cut off as well as queue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Ref. #549
