### ISSUE TITLE
[Bug]: snap package .desktop filename error

### ISSUE THREAD

**Issue by 5uy4n9** [ciderapp/Cider#766]
### Describe the Bug

when running cider in the terminal, I found that desktop missing error output:
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/**cider_Cider.desktop**"

but actually the .desktop filename in "/var/lib/snapd/desktop/applications/" is **cider_cider.desktop**, but the program required filename is capitalized C in second cider

### Steps to Reproduce

run cider in terminal

### Environment Information

- OS: Pop!_OS 21.10
- App Version and/or Commit ID: Snap installed cider (edge) 1.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
From my knowledge, the snap package is not maintained by any of the development team. We cannot help further, I suggest reaching out to the publisher, Innatical.
