### ISSUE TITLE
[Feature Request]: 

### ISSUE THREAD

**Issue by TomRoskam** [ciderapp/Cider#767]
### The feature you would like

Lossless audio would be awesome, that would make this a real replacement of Tidal.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
Lossless audio is currently impossible for us to add due to limitations from Apple. In the meantime we have a Audio setting called CAP which aims to clean up vocals and offer a similar experience to lossless.
