### ISSUE TITLE
[Bug]: Cast does not connect

### ISSUE THREAD

**Issue by bfrostieone** [ciderapp/Cider#773]
### Describe the Bug

Cast does not connect to Google Mini pair. 

### Steps to Reproduce

1. Open Cast menu
2. Click Google Mini pair (assuming based on IP address), nothing happens. 
3. Song appears to keep playing but without music playing on computer or speakers. 

### Environment Information

- OS: Windows 11 Home, Version 21H2, OS Build 22000.556
- App Version and/or Commit ID: Version 1.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
I actually had this bug earlier on and I managed to fix it by doing this: 

> Open Control Panel
> Click Network and Internet
> Click Network and Sharing centre
> Click Change Advanced Sharing Settings on the left hand side
> Expand the Guest or Public list and turn on both the options. 
> Restart your pc

Doing this for me fixed this same issue you are having. Give it a try and see if it works. 

Also if you are using the GitHub develop branch, a new build has been published a couple hours ago to fix the name bug on the cast menu, now you should see the correct name for your devices and not a bunch of gibberish!

**Comment by bfrostieone** [comment]
Thanks! I have tried this several times now and it does not work. I am not sure if it is because I have the speakers paired or not. I switched over to the development branch, and now I see the Cast device names, which helps a lot. It actually shows my office speakers three times, each speaker individually and as a pair. I have tried connecting to each one and nothing happens. No music, no sound of the speaker connecting, just nothing.

**Comment by Amaru8** [comment]
I tried Cast with an Android TV, and it worked flawlessly.
I allowed the Cider.exe and port 6942 through Windows Defender Firewall with Advanced Security.

OS: Windows 11 Home, Latest Public Release
App Version and/or Commit ID: Version 1.4.1-alpha.1688

**Comment by KillerParticles** [comment]
> Thanks! I have tried this several times now and it does not work. I am not sure if it is because I have the speakers connected as a pair or not. I switched over to the development branch, and now I see the Cast device names, which helps a lot. It actually shows my office speakers three times, each speaker individually and as a pair. I have tried connecting to each one and nothing happens. No music, no sound of the speaker connecting, just nothing.

its something to do with firewalls and all that that is causing this, unfortunately theres no way to tell which problem you are facing, neither did i until i tired many fixes and the one i posted is the one that fixed it to me. try searching 'windows 11 cast not outputting music' or something like that and see what it says.

**Comment by bfrostieone** [comment]
I do not believe the issue is firewalls. Cider will cast without issue to other speakers in my house. I have two google/nest mini's on my office desk that are "paired", and Cider will not cast to the paired speakers. I can cast to them from the Chrome/Brave/Edge browsers, but not Cider.  

![Cider Cast_4-5-22](https://user-images.githubusercontent.com/102767677/161780250-bdba233b-916c-432e-bfee-39301750bcd3.jpg)

I am not sure if it has to do with the "paired" speakers sharing an IP address? I know basically nothing about how to add cast support into an app.

**Comment by bfrostieone** [comment]
Also, thanks for your help!

**Comment by KillerParticles** [comment]
When you cast to the ones you say you can cast to, can you play any audio?

**Comment by bfrostieone** [comment]
Yes, when casting to the other speakers it makes the connecting sound and then starts playing music. On the office speakers it makes no connecting sound and plays no music. 

I cast to my office speakers all the time from a browser (mostly with PocketCasts web app), so I know they do work.

**Comment by bfrostieone** [comment]
I unpaired the speakers and I can play music to the speakers individually. Definitely a "paired" speaker issue.
