### ISSUE TITLE
[Bug]: apple log in problem

### ISSUE THREAD

**Issue by jkpoll96** [ciderapp/Cider#774]
### Describe the Bug

can't log into apple, it was fine at first but after i turned my pc on after a day its logged out but i cant log back in, i put in everything right and it says it was accepted but it still doesn't work 

### Steps to Reproduce

logged back on pc after a day

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID:

### Anything else?

n/a

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
API is fixed try logging in now.

**Comment by money5240** [comment]
> ### Describe the Bug
> 
> can't log into apple, it was fine at first but after i turned my pc on after a day its logged out but i cant log back in, i put in everything right and it says it was accepted but it still doesn't work 
> 
> ### Steps to Reproduce
> 
> logged back on pc after a day
> 
> ### Environment Information
> 
> - OS: Windows 11
> 
> - App Version and/or Commit ID:
> 
> 
> 
> ### Anything else?
> 
> n/a
> 
> ### Code of Conduct
> 
> - [X] I agree to follow this project's Code of Conduct

**Comment by money5240** [comment]
Update CMake version to match Make's

**Comment by coredev-uk** [comment]
Closing this as I assume it's resolved. If you experience further issues, perform a [clean install](https://github.com/ciderapp/Cider/wiki/Troubleshooting#clean-installation), if the issue persists, open another issue.
