### ISSUE TITLE
[Bug]: Can't play explicit songs

### ISSUE THREAD

**Issue by SkyRexHUN** [ciderapp/Cider#775]
### Describe the Bug

Can't start playing explicit songs, or when the playlist comes to an explicit songs, the player stops and I can't resume playing.

### Steps to Reproduce

Just try to play any explicit song.

### Environment Information

- OS: Windows 11 Pro 64bit
- App Version and/or Commit ID: latest Microsoft Store version (1.4.0.0)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
Have you tried going to https://tv.apple.com/gb , going to settings and setting the music filter to explicit?

**Comment by SkyRexHUN** [comment]
I had content restrictions turned off alltogether, thought that it meant that I don't have to do anything like this.
Yes, I have tried this directly from Cider, but it didn't work at the time, for some reason it did work from the Apple TV website. Strange...

**Comment by KillerParticles** [comment]
Its a common problem that's been popping up, but yes, from my understanding changing the content filter on the tv website changes it for the MusicKit API, which effects both AM Web and Cider. So changing it there will change it in Cider.
