### ISSUE TITLE
[Feature Request]: WASAPI Support

### ISSUE THREAD

**Issue by tharos96** [ciderapp/Cider#778]
### The feature you would like

To continue this feature request: https://github.com/ciderapp/Apple-Music-Electron/issues/92
What's the state of this?

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
Cider already uses WASAPI.

**Comment by vapormusic** [comment]
> Does Cider support WASAPI exclusive mode?

No
