### ISSUE TITLE
[Bug]:  Buggy touchscreen experience

### ISSUE THREAD

**Issue by devKaili** [ciderapp/Cider#781]
### Describe the Bug

Using the app with a touch screen on Surface Pro is buggy. 

### Steps to Reproduce

I tried to scroll through my library with my finger and instead of scrolling, I started moving songs around...

### Environment Information

- OS: Windows 11
- Device: Surface Pro 7
- App Version:  1.4.0-alpha.1644 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Cider hasn't been designed for the touch experience yet. This could be a future addition further on.

**Comment by booploops** [comment]
Resolved the scrolling issue

**Comment by devKaili** [comment]
Thanks for fixing it although the fix is only working for the "Songs" tab, but when I scroll in an album on my touch screen, I get the same bug as before.
