### ISSUE TITLE
[Bug]: cider fails to launch

### ISSUE THREAD

**Issue by asdfghjkl403622** [ciderapp/Cider#789]
### Describe the Bug

Failed to load module "appmenu-gtk-module"
when using the cider release in the aur,
[12:19:24.079] [info] [AppEvents] App started [12:19:26.001] [info] [PluginHandler] Loaded plugins: [ 'chromecast.js', 'discordrpc.js', 'lastfm.js', 'menubar.js', 'mpris.js', 'thumbar.js', 'webNowPlaying.js' ] Authorization required, but no authorization protocol specified Trace/breakpoint trap (core dumped) 
when using the git version in the aur, 

### Steps to Reproduce

launch inn terminal on wayland on kde plasma

watch as the segmentation fault comes in

### Environment Information

- OS: arch linux
- App Version and/or Commit ID: cider-git-1.4.0.2872.78bd4594-1, cider-1.4.0.2846.60ea677c-1 both tested and had different issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
@coredev-uk mind looking into this?

**Comment by coredev-uk** [comment]
Run cider with the ` --enable-features=UseOzonePlatform --ozone-platform=wayland` args

**Comment by adryd325** [comment]
Can reproduce. 

> Run cider with the ` --enable-features=UseOzonePlatform --ozone-platform=wayland` args
This doesn't appear don't do anything on Xorg; even if I change `--ozone-platform=wayland` to `--ozone-platform=x11`

**Comment by Lampomaniac** [comment]
Reproduced on with the Flatpak version on Fedora 35.

![image](https://user-images.githubusercontent.com/95165010/161432695-1c61da2a-1e64-4ac7-8e55-bd27d74e2bbe.png)

**Comment by mefsaal** [comment]
Cider without args
❱❱❱ cider
 [info]  [AppEvents] App started
 [info]  WebGPU is enabled.
 [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'thumbar.js',
  'webNowPlaying.js'
]
Authorization required, but no authorization protocol specified
[1]    2674 trace trap (core dumped)  cider

Cider with args 
 ❱❱❱ cider --enable-features=UseOzonePlatform --ozone-platform=wayland
 [AppEvents] App started
 [info]  WebGPU is enabled.
 [info]  [PluginHandler] Loaded plugins: [
  'chromecast.js',
  'discordrpc.js',
  'lastfm.js',
  'menubar.js',
  'mpris.js',
  'thumbar.js',
  'webNowPlaying.js'
]
[3541:0403/140220.260828:ERROR:gpu_init.cc(457)] Passthrough is not supported, GL is egl, ANGLE is 
[3541:0403/140220.263103:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[14:02:20.296] [info]  [AppEvents] App ready
[14:02:20.296] [info]  [Cider] Application is Ready. Creating Window.
Authorization required, but no authorization protocol specified
[1]    3302 segmentation fault (core dumped)  cider --enable-features=UseOzonePlatform --ozone-platform=wayland


If i delete the config directory cider run again until i reboot the pc

**Comment by mefsaal** [comment]
I found the the bug in my case is the "XAUTHORITY" Variable in the cider-config.json. Dont know why but the variable need to change every-time i reboot. 

If i delete the variable, cider start and change the Arg in the variable
Example:

Reboot 1
"XAUTHORITY": "/run/user/1000/xauth_nglCWB"

Reboot 2
"XAUTHORITY": "/run/user/1000/xauth_EORCXj"



In Wayland and X11 is the same, always need to change.

**Comment by undeadbydawn** [comment]
Verified.
Deleting cider-config.json allows cider-git to launch without issues.
The launch options suggested do nothing at all

> I found the the bug in my case is the "XAUTHORITY" Variable in the cider-config.json. Dont know why but the variable need to change every-time i reboot.
> 
> If i delete the variable, cider start and change the Arg in the variable Example:
> 
> Reboot 1 "XAUTHORITY": "/run/user/1000/xauth_nglCWB"
> 
> Reboot 2 "XAUTHORITY": "/run/user/1000/xauth_EORCXj"
> 
> In Wayland and X11 is the same, always need to change.

Verified.
Deleting cider-config.json allows cider-git to launch without issues.
The launch options suggested do nothing at all

**Comment by rowbawts** [comment]
> The flatpak version seems to work fine thankfully, but it would be nice to have the git version with all the latest patches. Can someone fix this bug?

 This obviously still needs resolution but just to comment I maintain the Flatpak/Flathub release and it automatically builds off the latest builds from git the only delay to release is a Flathub mandated delay, When a new version get's built it doesn't get published until a scheduled activity runs putting all unpublished apps in the queue live it's usually every 3 hours. You can watch the status [here](https://flathub.org/builds/#/apps/sh.cider.Cider)

**Comment by Lampomaniac** [comment]
> The flatpak version seems to work fine thankfully, but it would be nice to have the git version with all the latest patches. Can someone fix this bug?
> 
> 

The flatpak version does not work for me.

**Comment by rowbawts** [comment]
> > The flatpak version seems to work fine thankfully, but it would be nice to have the git version with all the latest patches. Can someone fix this bug?
> 
> The flatpak version does not work for me.

To not clog up this issue page with _potentially_ unrelated info if you join the [Discord](https://discord.gg/applemusic) I can help you troubleshoot the Flatpak if you want to get that working. Just ping me in the support channel **seby#0101**

**Comment by mefsaal** [comment]
> Verified. Deleting cider-config.json allows cider-git to launch without issues. The launch options suggested do nothing at all
> 
> > I found the the bug in my case is the "XAUTHORITY" Variable in the cider-config.json. Dont know why but the variable need to change every-time i reboot.
> > If i delete the variable, cider start and change the Arg in the variable Example:
> > Reboot 1 "XAUTHORITY": "/run/user/1000/xauth_nglCWB"
> > Reboot 2 "XAUTHORITY": "/run/user/1000/xauth_EORCXj"
> > In Wayland and X11 is the same, always need to change.

hi, could just delete the  "XAUTHORITY" line plz and tell me if cider work, not delete the al cider-config.json file. tell me if you have the same bug as i.

i think its a electron bug, but dont know

**Comment by undeadbydawn** [comment]
Follow-up
Deleting just the XAUTHORITY line didn't work on reboot. It did, however, prompt a new Apple Music login window.
I'm now wondering if the bug is actually on Apple's side and a change in their own authorisation practices, since my "Artist Feed" has also vanished

> hi, could just delete the "XAUTHORITY" line plz and tell me if cider work, not delete the al cider-config.json file. tell me if you have the same bug as i.
> 
> i think its a electron bug, but dont know.
> 
> Edit 1 :
> 
> Well i see cider store the "XAUTHORITY" inside the cider-config.json when its a token-cache value and change every reboot/login.

**Comment by mefsaal** [comment]
> Follow-up [EDIT: important corrections] First I tried commenting XAUTH out. That did nothing. I then (without rebooting) deleted the line. That prompted a new Apple Music login window. I deleted the line again and rebooted. No dice.
> 
> The only thing that has consistently worked is deleting the file.
> 
> _However_, I'm suspecting this is a change on Apple's side as my Followed Artists feed has also vanished again
> 
> > hi, could just delete the "XAUTHORITY" line plz and tell me if cider work, not delete the al cider-config.json file. tell me if you have the same bug as i.
> > i think its a electron bug, but dont know.
> > Edit 1 :
> > Well i see cider store the "XAUTHORITY" inside the cider-config.json when its a token-cache value and change every reboot/login.

you need delete the XAUTH line everytime you reboot, before open cider. The XUATH token change everytime you reboot the pc. 


If this dont work for you; Can you upload the cider-config.json before and after delete plz?.

**Comment by undeadbydawn** [comment]
Deleting the XAUTH line after login and before launch does, indeed, work

> you need delete the XAUTH line everytime you reboot, before open cider. The XUATH token change everytime you reboot the pc.
> 
> If this dont work for you; Can you upload the cider-config.json before and after delete plz?.

**Comment by mefsaal** [comment]
Hi i see the commit https://github.com/ciderapp/Cider/commit/0eb59d1119f6fdab829e0a693b228ef5b82aca9b start the bug in linux platform. dont know why cider config needs store the "ENV" params

**Comment by mefsaal** [comment]
with the last merge patch, fixes the Cider bug on window. Plz Close it

**Comment by undeadbydawn** [comment]
Awesome.
Today Cider launched with no tinkering required.

**Comment by undeadbydawn** [comment]
...
And it's back to not launching unless I delete XAUTH.
That was fun for a good 12 hours

**Comment by mefsaal** [comment]
> ...
> And it's back to not launching unless I delete XAUTH.
> That was fun for a good 12 hours

Delete al cider folder config and try again. For my side the xauth bug not Happer anymore.

 Update cider from last commit and try

**Comment by coredev-uk** [comment]
Apologies for the lack of my assistance with this, glad it managed to get resolved.
