### ISSUE TITLE
[BUG] App needs a restart after sign-in

### ISSUE THREAD

**Issue by Nosh118** [ciderapp/Cider#80]
**Describe the bug**
Nothing loads until you restart the app after you sign in for the first time

**To Reproduce**
1. Install app for first time
2. Log in

**Expected behavior**
App should show you logged in (your username etc. in bottom left) and should start loading all your content

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows
 - Application Version *(e.g. 2.5.0)*: Latest commits as of 05/01/22

**Comment by quacksire** [comment]
For anyone looking for a solution, just do a Ctrl+R (or Command+R) after you sign in

We are looking into a solution.
