### ISSUE TITLE
[Bug]: High CPU and RAM usage in windows..

### ISSUE THREAD

**Issue by KanishTech** [ciderapp/Cider#803]
### Describe the Bug

CIder app uses 20% CPU and 1100mb of RAM at idle. My system specs are:
CPU: intel i7-8550U
RAM: 8gb
GPU: intel uhd 620. 

### Environment Information

- OS: Windows
- App Version and/or Commit ID: 1.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
Set Animated Artwork to only selected items and Animated Window Background to off. I have the same CPU.

**Comment by ryzetech** [comment]
Having the same issue, ~20% CPU usage with a Ryzen 2600. RAM usage isn't that dramatic (~270 MB).
Cider v1.5.7 Github @ Windows 10

I have disabled Animated Window Backgrounds and Animated Artworks entirely, without any effect.
