### ISSUE TITLE
[Bug]: Port 9000 in use by Cider cannot be changed

### ISSUE THREAD

**Issue by limzykenneth** [ciderapp/Cider#804]
### Describe the Bug

By default Cider seems to be binding to http://localhost:9000, I'm not sure what for (Chromecast? Discord integration?) but in any case I need to be able to use port 9000 for some other applications I use. I would prefer that Cider does not use port 9000 (or any ports) by default or at least provide an option to turn off this binding/bind to a different user defined port.

### Steps to Reproduce

1. Start Cider
2. Attempt to start a local web server on port 9000

### Environment Information

- OS: Pop OS 21.04
- App Version and/or Commit ID: 1.4.0-alpha.1642

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
We'll probably end up changing this to a randomized UDP to prevent overlapping. I suppose an option can be made for this however.

**Comment by quacksire** [comment]
could we technically do mdns for this?

**Comment by coredev-uk** [comment]
Are you running any program that could potentially be preventing cider from creating the web server ?

**Comment by limzykenneth** [comment]
I'm running a local web server on port 9000 from time to time as part of some other web development stuff I do. The thing is if I have Cider running, I cannot use port 9000 (I can get around it but it is inconvenient); on the other hand if I am already using port 9000 without Cider running, then start Cider, I'm prompted to sign into my Apple account again but other than that all functionality that I care about works just fine.

Based on that last point it seems to me (correct me if I'm wrong) that usage of port 9000 is not essential to the core functionality of Cider. As such it would be great if that reliance on port 9000 can be refactored out or be made optional depending on what feature is actually using it.

**Comment by digitalgopnik** [comment]
> We'll probably end up changing this to a randomized UDP to prevent overlapping. I suppose an option can be made for this however.

This would be nice!

**Comment by bozerkins** [comment]
I run into the same problem. Any update regarding this?

**Comment by zwx00** [comment]
I have the same issue. Port 9000 is very commonly used and there's a lot of conflicts. In particular, I can't run my docker stack at the same time I listen to music, which is ridiculous (it's precisely then that I want to listen to music the most!).
