### ISSUE TITLE
[Bug]: Mini-players closes on moving the window

### ISSUE THREAD

**Issue by sunnyjain** [ciderapp/Cider#805]
### Describe the Bug

When you move the mini-player window it changes to the default/normal view

https://user-images.githubusercontent.com/6739157/161444454-5aba1156-a80b-41b3-a0d9-410fa99a0b3c.mov

.

### Steps to Reproduce

1. Open the app.
2. play a song and click on the mini-player icon.
3. move/drag the mini-player window.
4. Notice how it changes back to the default/extended view.

### Environment Information

- OS: macOS 12.3
- App Version: 1.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
#784 duplicate
