### ISSUE TITLE
[BUG] Songs don't play until after multiple restarts

### ISSUE THREAD

**Issue by Nosh118** [ciderapp/Cider#81]
**Describe the bug**
Sometimes songs just don't play and the player stays stuck on a single song despite clicking play on other ones. That single song doesn't load/play and the app requires multiple restarts to fix. Happens on and off sometimes - most recently on a fresh install on a new device.

**To Reproduce**
1. Play a song on auto sound quality
2. It doesn't load
3. Try play another song

**Expected behavior**
The song should play as should subsequent ones

**Potential fix**
Switching quality back to Extreme and restarting the app a couple times

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*: Windows
 - Application Version *(e.g. 2.5.0)*: Latest commit as of 05/01/22

**Comment by mahendrsa** [comment]
Yes! I've encountered this same bug. Maybe auto is not implemented yet?
