### ISSUE TITLE
[Bug]: Cider Audio Issues

### ISSUE THREAD

**Issue by AllanBoden** [ciderapp/Cider#814]
### Describe the Bug

When playing a track around 10 seconds from the end the audio stutters for a second and then continues.  It seems to be intermittent as it doesn't do it every time.  I have attached a video showing the problem.

https://user-images.githubusercontent.com/103040462/161747339-bfb53123-4264-4364-b905-4a647afdd73f.MOV

### Steps to Reproduce

1. Select a track and start playing it.  Around 10 or so seconds from the end music stops for a second and then continues.

### Environment Information

- OS: Windows 11 Home (10.0.22000 Build 22000)
- App Version and/or Commit ID: v1.4.1 from the Microsoft Store

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AllanBoden** [comment]
This is still a issue in the latest version.

**Comment by polaraditia** [comment]
This is still a issue in the last stable version 1.5.3.
Windows 10

**Comment by yazninja** [comment]
> This is still a issue in the last stable version 1.5.3. Windows 10

You may try to Disable `Seamless Audio Transitions` in order to address this problems, although this may cause a little more gap between each song:
![image](https://user-images.githubusercontent.com/71800112/183893952-54a7de47-d597-4d0f-9c09-f0fd6243d08b.png)

**Comment by cryptofyre** [comment]
Closing due to wontfix.
