### ISSUE TITLE
[Bug]: Parse error on first launch of Cider

### ISSUE THREAD

**Issue by jaanus** [ciderapp/Cider#820]
### Describe the Bug

When I start Cider and log in, I get this error view.

<img width="1136" alt="Screenshot 2022-04-06 at 09 38 26" src="https://user-images.githubusercontent.com/184253/161911673-86e6c79a-ba65-4c87-99e2-40da0f32f9c6.png">

After I restart the app, there is no more error, and it works.

### Steps to Reproduce

1. Download Cider DMG release from releases page.
2. Sign in with the Apple Music popup that comes up.
3. Observe the error shown above.

### Environment Information

- OS: macOS Monterey 12.3.1 (21E258)
- App Version and/or Commit ID: Cider DMG release 1.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
This may have just been a fuckup on Google's end with the font. If it continues, reopen the issue.
