### ISSUE TITLE
[Bug]: Search result outside of search box/area

### ISSUE THREAD

**Issue by ilyshirai** [ciderapp/Cider#827]
### Describe the Bug

It's the same thing what the title says - one of search result go outside of search box/area
![Cider 06-04-2022 21-02-58 (AO4tp)](https://user-images.githubusercontent.com/69073674/162049395-0dbe68c2-1459-4810-bb83-210dc8c7f81f.gif)

### Steps to Reproduce

- Type "Yandere" in search bar

### Environment Information

- OS: Windows 11 Pro 22000.556 (stable release)
- App Version and/or Commit ID: 1.3.1302 (stable branch/winget)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
![image](https://user-images.githubusercontent.com/71800112/162118745-e0ce0801-265f-4c4e-b360-505fbb7b5fe8.png)
Thanks, will add this patch to the develop branch
