### ISSUE TITLE
[Bug]: fileError

### ISSUE THREAD

**Issue by hupoo** [ciderapp/Cider#830]
### Describe the Bug

A bug happened!
![image](https://user-images.githubusercontent.com/20273539/162116339-e1d2b689-d909-4e98-a743-56c84eacdaf6.png)

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS:
- App Version and/or Commit ID:

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
is this from microsoft store?
