### ISSUE TITLE
[Bug]: Using the Cider Remote once Cider is casted to a TV causes the screen to flicker

### ISSUE THREAD

**Issue by KillerParticles** [ciderapp/Cider#832]
### Describe the Bug

When I cast Cider to my Shield TV and then try to use the Cider Remote, when the app connects to Cider it causes my TV screen to flicker consistently. The app still seems to work but the flickering makes it very hard to read what's on the screen. Closing the Cider app stops the flickering.

### Steps to Reproduce

1. Open Cider and cast it to a TV
2. Open the remote app and connect to the Cider instance
3. Once connected the TV screen should be experiencing this bug of flickering.

### Environment Information

- OS: Windows 11 Home 21H2
- App Version and/or Commit ID: Develop branch version 1.4.1-alpha.1672

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
Are you able to attach a video of this happening and a log (Settings => Advanced => Copy Logs)?

**Comment by KillerParticles** [comment]
https://user-images.githubusercontent.com/93286201/162287503-00281793-77b9-4ef3-b812-53cd2b015e52.mp4
[Ciderbug832.txt](https://github.com/ciderapp/Cider/files/8446174/Ciderbug832.txt)

Best I could do as when I switch to the camera app, the remote app loses connection and the bug stops.
