### ISSUE TITLE
[Bug]: Pausing will rapidly pause then play again when pressing keyboard media key.

### ISSUE THREAD

**Issue by sc0ttr0berts0n** [ciderapp/Cider#833]
### Describe the Bug

Pausing will pause then play again when pressing keyboard media key. The same is occasionally also true when paused and pressing the button to unpause, but generally works correctly.

https://user-images.githubusercontent.com/320764/162196831-1edc7359-7303-4f74-bab7-22a0c017ed76.mp4

.

### Steps to Reproduce

1. Play song.
2. Press Keyboard Media Key (Play/Pause)
3. Observe Rapid Pause / Play

### Environment Information

- OS: Win10 Pro 21H1
- App Version and/or Commit ID: 1.4.1
- Keyboard: Corsair K70

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
This appears like a Windows bug or keyboard issue and not to be related to Cider itself.
