### ISSUE TITLE
[Bug]: Album Art and unexpected window hiding

### ISSUE THREAD

**Issue by Sxrrr** [ciderapp/Cider#835]
### Describe the Bug

There is a little issue in the top dock for MacOS. Seems like the album art keeps disappearing, and the duration of the song becomes very long. Sometimes the player just disappears and just shows the Cider app logo and unable to interact with that to change music

### Steps to Reproduce

1. Clicked on top bar (music icon)

### Environment Information

- OS: MacOS
- App Version and/or Commit ID: 1.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
Are you able to paste the log?

Settings => Advanced => Copy Logs
