### ISSUE TITLE
[Bug]: FileError: 'https://fonts.googleapis.com

### ISSUE THREAD

**Issue by ylcz2014** [ciderapp/Cider#839]
### Describe the Bug

when i open cider，it shows:
FileError: 'https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap' wasn't found (0)
in [style.less](http://localhost:9000/style.less) on line 6, column 1:

5@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@100;300;400;500;700;900&display=swap");
6@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@100;300;400;500;700;900&display=swap");
7@import url("less/bootstrap-vue.min.css");
![image](https://user-images.githubusercontent.com/13727499/162340712-df538b7c-7070-4768-b0c5-d0291bddfb0a.png)

### Steps to Reproduce

Everytime when I open the app

### Environment Information

- OS:Windows 10 pro 20h2
- App Version and/or Commit ID: 1.4.1-alpha.1707

### Anything else?

I have seen https://github.com/ciderapp/Cider/issues/431 ,I live in China too. but i can access fonts.googleapis.com when in browser. 
![image](https://user-images.githubusercontent.com/13727499/162341602-4edb4da6-d0a8-4d60-b183-b40328473026.png)
And microsoft store version cider(Alpha) don't have this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by rderensy** [comment]
I get that too on 1.4.3-alpha.1784 on Ubuntu, installed from the .deb. It would be nice to load those fonts locally, or at least have a fallback on local fonts.

**Comment by cryptofyre** [comment]
Closing due to a very specific edge case scenario, I used to have the same issue before upgrading my hardware.
