### ISSUE TITLE
[BUG] can't install from AUR due to node-lts-gallium conflict

### ISSUE THREAD

**Issue by vxsl** [ciderapp/Cider#84]
**Describe the bug**
Cannot install via AUR due to unresolvable package conflict between `nodejs` and `nodejs-lts-gallium`.

**To Reproduce**
```shell
yay -Sy cider

...

looking for conflicting packages...
:: nodejs-lts-gallium and nodejs are in conflict. Remove nodejs? [y/N] 
N
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: nodejs-lts-gallium and nodejs are in conflict
error installing repo packages
```

**Expected behavior**
Users should be able to install this package without having to remove their system version of Node.

**Environment Information**
 - OS *(e.g. Linux/Mac/Windows)*:  Linux 5.15.10-arch1-1 x86_64
 - Application Version *(e.g. 2.5.0)*: 1.0.0-1 (AUR)
 
**Additional context**
A comment on the AUR package says:
> _this package doesn't work if you use nvm to manage your nodejs versions since it depends on nodejs-lts-gallium_

I can't speak to whether the conflict is related to the use of nvm; however, I do use nvm.

**Comment by coredev-uk** [comment]
A bug that was related to the latest nodejs version was causing issues with compiling, so a requirement for nodejs-lts-galium was necessary. When installing type `y` when responding to the conflict. I will revisit the nodejs issues page to see if this has been resolved.

**Comment by vxsl** [comment]
was this resolved? Perhaps you could link to the node issue here. @coredev-uk

**Comment by coredev-uk** [comment]
I did take a look into this issue and found it was a fault with electron-acrylic-window. The issue can be found [here](https://github.com/Seo-Rii/electron-acrylic-window/issues/80)

**Comment by vxsl** [comment]
@coredev-uk Thank you for providing the reference :pray:
