### ISSUE TITLE
[Bug]: I click the button but the music never plays

### ISSUE THREAD

**Issue by GD-Slime** [ciderapp/Cider#842]
### Describe the Bug

All other pages: albums, artists pages can be opened. But when I click the play botton, it just can't start to play.
I can use apple music's webpage to play music, but not Cider. It should not be my network problem.
![2022-04-08 174315](https://user-images.githubusercontent.com/82302542/162410493-5ffa490c-86be-489d-9f33-1009266ad99f.png)

### Steps to Reproduce

1. open Cider
2. choose any singles or albums
3. click the play botton, then nothing happend.

### Environment Information

- OS: Windows 10 21H2 (19044.1586)
- App Version and/or Commit ID: 1.4.1 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GD-Slime** [comment]
this is the log : https://paste.ubuntu.com/p/ddpNyys8kB/

**Comment by FrozenBicycle** [comment]
The same thing happened on me. The issue remains unresolved as of now (version 1.4.5).

**Comment by Souna** [comment]
Exact same issue on my end

**Comment by coredev-uk** [comment]
Open the renderer console by doing CTRL + Shift + I and post any errors that appear.

**Comment by FrozenBicycle** [comment]
Erros in console:

1. `Failed to load resource: the server responded with a status of 404 ()`
  `locale err NOT_FOUND: 404`
  `    at Function.responseError (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:15:4139)`
  `    at https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:44:253212`
  `    at Generator.next (<anonymous>)`
  `    at fulfilled (https://js-cdn.music.apple.com/musickit/v2/amp/musickit.js:29:977)`

2. `Uncaught (in promise) DOMException: Failed to execute 'createMediaKeys' on 'MediaKeySystemAccess': CDM creation failed`

3. `Failed to load resource: net::ERR_TOO_MANY_REDIRECTS`

4. `Failed to load resource: the server responded with a status of 404 (Not Found)`

Clicking the < Play > button again after these errors does not cause any console output errors, but Cider does not play music properly either.
