### ISSUE TITLE
[Enhancement] Add Escape key exit

### ISSUE THREAD

**Issue by condense-fidelity-elope** [ciderapp/Cider#85]
**Is your feature request related to a problem? Please describe.**
When I click on the currently playing album, it puts me in a menu with the lyrics which is pretty cool. The issue is that I have to double click the album cover to get out of that menu. It's not very user-intuitive and annoying, and took me 2 minutes to figure out. 

**Describe the solution you'd like**
It would preferable if the escape key also made you exit the menu (it's the first thing I did and imagine also others would do to try to exit)

**Describe alternatives you've considered**
An X button would also be nice

**Additional context**
![image](https://user-images.githubusercontent.com/75458027/148440441-ceb70b94-29ba-498e-9d05-b211d04a3441.png)
talking about this menu

**Comment by Swiftzerr** [comment]
I will add this now

**Comment by coredev-uk** [comment]
Done in 905173f
