### ISSUE TITLE
[Bug]: Audio normalization turns itself on startup

### ISSUE THREAD

**Issue by IplaygamesIhate** [ciderapp/Cider#851]
### Describe the Bug

Audio normalization turns itself on startup. Make it so it doesn't turn on automatically.

### Steps to Reproduce

1. Clicked on...audio and turned off audio normalization. When I close and reopen the app, it turns on automatically.

### Environment Information

- OS: Win 10 Version 10.0.19044 Build 19044
- App Version and/or Commit ID: version 1.4.0-alpha 1644

### Anything else?

Thank you for the app. I love it

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by maikirakiwi** [comment]
Resolved

**Comment by IplaygamesIhate** [comment]
Thank you. I really enjoy the app
