### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ShinyPlasm** [ciderapp/Cider#856]
### Describe the Bug

When you play a song and put it in "full screen" mode, the lyrics just show "Loading... / Lyrics not found./ Instrumental.". This happens for all my songs in my library (most of which the lyrics do show on the mobile app).

### Steps to Reproduce

1. Play a song
2. Click on the song icon at the top of the app to enter full screen
3. Select lyrics at the bottom-right of the app
You will then see a lyrics not found error. 
![image](https://user-images.githubusercontent.com/46997381/162631016-fdcb90c9-8b17-461b-88fe-285d83b9adae.png)

### Environment Information

- OS: Windows 11 
- App Version and/or Commit ID: v1.4.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
Hi, this is a known issue, Apple has blocked access to their lyrics, and Cider is left to rely on musixmatch

**Comment by yazninja** [comment]
Merge to #859
