### ISSUE TITLE
[Bug]: Apple Music Lyrics does not work but the Musixmatch work (Sometimes)

### ISSUE THREAD

**Issue by Reiux** [ciderapp/Cider#859]
### Describe the Bug

When I try to play a song, There's no lyrics showing up on Apple Music lyric servers

But if I try to enable Musixmatch lyrics, Lyrics are working but for some songs only.

### Steps to Reproduce

1. Clicked on Lyrics, Doesn't show up anything
2. Try to enable Musixmatch lyrics, It worked but for some songs only.

### Environment Information

- OS: Windows 11 Build 22593
- App Version and/or Commit ID: 1.4.1-alpha.1688 and 1.4.1-alpha.1751

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by GamingLiamStudios** [comment]
This is a known issue. Apple has disabled Public Access to Lyrics through their API, so the only currently working stream is Musixmatch. As for the songs that don't work with Musixmatch, that is again not a problem with Cider, but Musixmatch most likely not having the lyrics for that song.

**Comment by Lainasan** [comment]
Okay, thanks I also check the lyric settings after updating and Musixmatch is enabled by default.

Btw, thanks for the info!
