### ISSUE TITLE
[Bug]: Animation doesn't move to next song if window is in background

### ISSUE THREAD

**Issue by enzo-js** [ciderapp/Cider#860]
### Describe the Bug

When playing from a playlist or album, the EQ animation over the number doesn't go to the next song if the window is in the background when the song changes.
I took a pic because I suck at explaining : - )
![image](https://user-images.githubusercontent.com/46859140/162663025-d6d53f7d-91d9-4a68-98e1-d8e71c203a88.png)

### Steps to Reproduce

1. Play a song
2. Let it naturally go to the next song with the window in the background (i had shuffle off and was on a playlist)
3. Bring Cider's window the foreground
4. There will either be the one EQ on the previous song, or it will be on both the previous and current song.
5. ez pz lemon squeezy?

### Environment Information

- OS: Windows 11 Pro Build 22000.co_release.210604-1628
- App Version and/or Commit ID: MS Store - Version 1.4.1 - Stable Branch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ATragicEnding** [comment]
I was gonna open a new bug report but this seems similar to my issue (Animation won't update but will also sometimes appear multiple time in the window).

For example :
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/32797161/164587512-93f25c8c-e3ac-492c-ab10-7fa47b2e28f9.png">

**Comment by enzo-js** [comment]
> I was gonna open a new bug report but this seems similar to my issue (Animation won't update but will also sometimes appear multiple time in the window).
> 
> For example : <img alt="image" width="1440" src="https://user-images.githubusercontent.com/32797161/164587512-93f25c8c-e3ac-492c-ab10-7fa47b2e28f9.png">
> 
> Edit : Just realized you are on Windows. I'm on OSX so issue might not be exactly the same but perhaps related.

I've had this instance of the issue as well, several songs go by before I bring Cider up again and it looks like your screenshot. Definitely related but idk beyond that 🤣
