### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by gunslingerfry** [ciderapp/Cider#872]
### Describe the Bug

Space bar is both mapped to Play/Pause and to the focused control. 

### Steps to Reproduce

If you click on the back button (for example) and press the space bar it will go back and pause. If you click on the pause/play button then space bar pauses then plays.

### Environment Information

- OS: Manjaro Qonos
- App Version and/or Commit ID: 1.4.1.2889.ac030ddd
- Oh... this is the develop branch.

### Anything else?

Built from the cider-git aur package.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
Duplicate #728
