### ISSUE TITLE
Share Artist does not work on the Artists page

### ISSUE THREAD

**Issue by Amaru8** [ciderapp/Cider#873]
https://github.com/ciderapp/Cider/blob/8616f4297863dd0c849c3f1ea4678dd8c3617a2b/src/renderer/views/pages/library-artists.ejs#L205-L216

**Comment by Amaru8** [comment]
When you right click an artist, on the Artists page, it just throws an error in the console.

**Comment by Amaru8** [comment]
https://user-images.githubusercontent.com/52407090/163354878-39cfbfd9-c91a-4753-97e5-22f5f8b0bfb0.mp4

**Comment by Amaru8** [comment]
used template in #874 , sorry

**Comment by vapormusic** [comment]
There is no sharing option for Library Artist for now.

Maybe we should add like a search query as fallback?
