### ISSUE TITLE
[Bug]: Share Artist doesn't work on the Artists page

### ISSUE THREAD

**Issue by Amaru8** [ciderapp/Cider#874]
### Describe the Bug

When you right click an artist, on the Artists page, it just throws an error in the console.

### Steps to Reproduce

1. Open Artists page
2. Open Console
3. Right click on an artist
4. Select Share
5. Check the console

### Environment Information

- OS: `Windows 11 Home`
- App Version and/or Commit ID: `Version 1.4.2-alpha.1779`

### Anything else?

https://user-images.githubusercontent.com/52407090/163354878-39cfbfd9-c91a-4753-97e5-22f5f8b0bfb0.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amaru8** [comment]
This is the code I think:

https://github.com/ciderapp/Cider/blob/8616f4297863dd0c849c3f1ea4678dd8c3617a2b/src/renderer/views/pages/library-artists.ejs#L205-L216

**Comment by Amaru8** [comment]
@vapormusic

this works:
![Cider_QDc3L4H8xg](https://user-images.githubusercontent.com/52407090/163356338-07c30cf9-3971-461f-893e-1a71526b1528.png)

but this doesn't:
![Cider_EFaEGfEeck](https://user-images.githubusercontent.com/52407090/163356552-9bb8b506-22d6-4aca-b082-1ea58b55f7ab.png)

isn't these two the same thing?

**Comment by vapormusic** [comment]
> @vapormusic
> 
> this works: ![Cider_QDc3L4H8xg](https://user-images.githubusercontent.com/52407090/163356338-07c30cf9-3971-461f-893e-1a71526b1528.png)
> 
> but this doesn't: ![Cider_EFaEGfEeck](https://user-images.githubusercontent.com/52407090/163356552-9bb8b506-22d6-4aca-b082-1ea58b55f7ab.png)
> 
> isn't these two the same thing?

Absolutely not. Apple treats library objects and normal AM objects differently. Library objects also include uploaded tracks with artist name( that may not exist in AM database) therefore sometimes we can only get the name of the artist, not the id to share them.

**Comment by KillerParticles** [comment]
Vapor is correct, its probably why you can upload and edit artists songs and albums on AM without it breaking the actual artists songs and albums. Your library is separate and unique to you and probably is why it cannot be shared.

**Comment by Amaru8** [comment]
Okay, can I make a PR to hide the share option?
