### ISSUE TITLE
[Bug]: Unlabeled Buttons (screen readers)

### ISSUE THREAD

**Issue by SoNothingMC** [ciderapp/Cider#876]
### Describe the Bug

Discord message:  
<https://discord.com/channels/843954443845238864/843954687794348072/964163240978432060>

I have formatted this into an issue report so this can be tracked.

Full text from the message follows:

> I am not sure were to put this request. I am a person with a visual impairment, I rely on the use of a screen reader. A screen reader reads what is on the screen, so that I can use the computerusing the keyboard. I am happy with Cider, thanks for developing this application. I bought this app last week, when I used it with my screen reader, I encountered unlabeled buttons, my screen reader kept on saying unlabeled button. I was wondering if the accessibility of Cider  with a screen reader could be improved. So that I can navigate through the different areas of the application. Hear is a link that might help. Please let me know if I need to include more details in this message.
Accessibility overview - Windows apps | Microsoft Docs

### Steps to Reproduce

N/A

### Environment Information

- OS: Windows
- App Version and/or Commit ID: Microsoft Store

### Anything else?

Please contact miguelorduno#0293 (698683068520726529) for more information.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
Added in #1016
