### ISSUE TITLE
[Bug]: Linux app won't launch

### ISSUE THREAD

**Issue by magdelenn** [ciderapp/Cider#877]
### Describe the Bug

It just won't launch

### Steps to Reproduce

1. Clicked on the icon

### Environment Information

- OS: Fedora 36
- App Version and/or Commit ID: Latest

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mefsaal** [comment]
Delete all cider folder config and try again.

**Comment by rowbawts** [comment]
> Delete all cider folder config and try again.

Yeah the config was changed and it kinda messed it up. This should fix it you only need to delete cider-config.json.
