### ISSUE TITLE
[Bug]: Back Button padding

### ISSUE THREAD

**Issue by calum523** [ciderapp/Cider#879]
### Describe the Bug

Back button not aligned correctly, more padding/ margins are needed
<img width="216" alt="Screenshot 2022-04-15 at 8 23 23 pm" src="https://user-images.githubusercontent.com/40227797/163623434-a917a858-e106-4b2b-b285-9b8b6b98bc26.png">
.

### Steps to Reproduce

Whole app interface

### Environment Information

- OS: macOS
- App Version and/or Commit ID: Current Development Branch

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
fixed is #985
