### ISSUE TITLE
[Bug]: Discord Rich Presence option keeps turning off

### ISSUE THREAD

**Issue by Reiux** [ciderapp/Cider#887]
### Describe the Bug

Tried enabling Discord Rich Presence on Cider Settings>Connectivity

But after relaunching the app it disables by itself and the Rich presence doesn't show up on discord.

I enabled it:
![image](https://user-images.githubusercontent.com/90865965/163709676-5df0a874-c542-4f1e-9ac7-a8db3e9cb12a.png)

After realunching:
![image](https://user-images.githubusercontent.com/90865965/163709745-8ec07705-f226-4957-b0ba-a106dae07c93.png)

And btw, what is this another 'Lyrics' tab
![image](https://user-images.githubusercontent.com/90865965/163709884-b9f55685-3618-4f2a-84d9-cc72fb1aa5e3.png)
There's a connect button on it and when I clicked on it, it says 'Account Is Connected'
and this is the link that appeared on my URL bar and it's related on discord.
https://connect.cidercollective.dev/callback/discord?app=cider&appPort=9000

### Steps to Reproduce

1. Open Cider Settings>Connectivity and enable Discord Rich Presence
2. Relaunch
3. Go to the settings again and It's going to disable itself

### Environment Information

- OS: Windows 11 Build 22593
- App Version and/or Commit ID: 1.4.3-alpha.1788 (Latest release)

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by rowbawts** [comment]
Go to the advanced tab click open cider folder and delete cider-config.json this will fix it.

**Comment by Reiux** [comment]
Thanks it works now.
![image](https://user-images.githubusercontent.com/90865965/163711081-681f5542-9cf2-4fce-a683-2390a2ab3ffa.png)

**Comment by rowbawts** [comment]
> Thanks it works now. ![image](https://user-images.githubusercontent.com/90865965/163711081-681f5542-9cf2-4fce-a683-2390a2ab3ffa.png)

No problem, this will have deleted all your settings so be sure to go over and re-set and you might have had modified previously.

**Comment by coredev-uk** [comment]
This was due to a migration bug that I did try to mitigate, however this did not work.

**Comment by cryptofyre** [comment]
Lyrics duplicate has been fixed as per 7dbed1d
