### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by hope-cpu** [ciderapp/Cider#888]
### Describe the Bug

A bug happened!  some wrong with the font and login when opening macOS。

### Steps to Reproduce

1. Clicked on...

### Environment Information

- OS: macOS M1 bigsur11.6 
- App Version and/or Commit ID: cider dmg
![SCR-20220417-st0](https://user-images.githubusercontent.com/52284632/163714823-25122bec-435f-484c-b6b1-cd49cc474c4b.png)

### Anything else?

this is a very nice app, but I am not a developer, and I do not know how to explain this bug. sorry to not help.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
This is due to Cider not being connected to Internet.
