### ISSUE TITLE
[Bug]: Version string in Windows Registry causes WinGet to keep telling you that you need to upgrade

### ISSUE THREAD

**Issue by trparky** [ciderapp/Cider#890]
### Describe the Bug

The DisplayVersion string that's contained uninstall section of the Windows Registry for Cider contains the string "1.4.2-alpha.1779" thus if you use WinGet to keep your softeware up to date, it will keep telling you that you have to upgrade Cider. Cider is in the WinGet database, however the version string it's looking for is "1.4.2.1779". Note how it doesn't have the word "alpha" in it.

### Steps to Reproduce

1. Install Cider.
2. Launch "winget upgrade" at the command prompt.
3. Note how it tells you that you have a new version of Cider to install even though you really do have the latest version already installed.

### Environment Information

- OS: Windows 11 Pro
- App Version and/or Commit ID: 1.4.2-alpha.1779

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by yazninja** [comment]
Hello, winget maintainer here, this is due to the new changes in nightly builds. Will be fixed soon

**Comment by yazninja** [comment]
Hello @trparky,
This should be solved in Nightly packages. `winget install CiderCollective.Cider.Nightly` for the stable releases i will release a fix when the main branch is updated

**Comment by trparky** [comment]
I installed 1.4.3-alpha.1810 and it's still an issue.

**Comment by Beamy68** [comment]
> I installed 1.4.3-alpha.1810 and it's still an issue.

They said it was fixed in the Nightly builds.

**Comment by cryptofyre** [comment]
Closing due to potential resolution.
