### ISSUE TITLE
[Bug]: Rich presence breaking if variable too long

### ISSUE THREAD

**Issue by pozm** [ciderapp/Cider#901]
### Describe the Bug

With rich presence if one of the fields are too long it just won't display it at all. so listening to a song or album which exceeds that limit will cause rich presence to not work.

### Steps to Reproduce

1. play a song which has a long name

### Environment Information

- OS: Windows 11
- App Version and/or Commit ID:
1.4.3-alpha.1790

### Anything else?

Here's a long album which you can use for testing.
https://music.apple.com/gb/album/music-to-listen-to-dance-to-blaze-to-pray-to-feed-to/1492724579

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pozm** [comment]
I would recommend trying to cap the field if too long? idk that is the first solution which comes to mind.

**Comment by coredev-uk** [comment]
There is a character limit set in the code
