### ISSUE TITLE
[Enhancement] open Apple Music links in Cider

### ISSUE THREAD

**Issue by Nosh118** [ciderapp/Cider#91]
**Is your feature request related to a problem? Please describe.**
It’s frustrating when you’re trying to open an Apple Music link (for eg. a private playlist) and it doesn’t open in Cider

**Describe the solution you'd like**
Allow Apple Music links to be opened in Cider (including linked playlists that aren’t public)

**Comment by quacksire** [comment]
we do have hooks for the itms/itmss (iTunes) and music/musics (macOS Music.app) URIs. I can add handlers to them, but I don't know what format they are in.

**Comment by quacksire** [comment]
found it, added
