### ISSUE TITLE
[BUG] Can't play music due to 'missing' libwidewinecdm.so

### ISSUE THREAD

**Issue by kuhaufleitung** [ciderapp/Cider#92]
**Describe the bug**

Can't play any music, presumably because of the following error message. The .so file was definitely installed and permissions are also set correctly.

`[26172:0109/145444.091751:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Cider client port: 9000
[26247:0109/145448.952117:ERROR:cdm_module.cc(138)] CDM at /home/kuhaufleitung/.config/Cider/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so could not be loaded.
[26247:0109/145448.952197:ERROR:cdm_module.cc(139)] Error: /home/kuhaufleitung/.config/Cider/WidevineCdm/4.10.2391.0/_platform_specific/linux_x64/libwidevinecdm.so: cannot open shared object file: No such file or directory`

**To Reproduce**
1. installed via yay `yay -S cider`
2. open and login
3. console throws error

**Environment Information**
 - OS: 5.15.13-arch1-1
 - Application Version *(e.g. 2.5.0)*: latest as of 09.01.22
 

**Have you followed the troubleshooting guide and checked for any outstanding/pinned issues that can help?**
*Troubleshooting guide can be found [here](https://github.com/Apple-Music-Electron/Apple-Music-Electron/wiki/Troubleshooting).*
Yes

**Log File**
No log file has been generated at `.cache/AppleMusic/logs/main.log` nor the .config equivalent

**Comment by coredev-uk** [comment]
Clear `.config/Cider` (`rm -Rf .config/Cider`).

**Comment by llight3** [comment]
Can confirm this issue i fixed it with --no-sandbox

**Comment by llight3** [comment]
> Clear `.config/Cider` (`rm -Rf .config/Cider`).

In my case this didn't help

**Comment by coredev-uk** [comment]
This is probably a result of having sandbox enabled for the BrowserWindow, but from my testing disabling it has broken the application.

**Comment by llight3** [comment]
Im also on arch and installed via yay if that helps

**Comment by coredev-uk** [comment]
Yeah, I maintain the AUR package, and test in arch so I'm not sure why I'm not having these issues.

**Comment by coredev-uk** [comment]
From testing it just now, the --no-sandbox launch arg does not have an affect on the process as sandbox is forced on in the BrowserWindow options. I believe that would just disable sandboxing for the main process. On the electron docs they state that the flag will disable sandboxing for all processes, however with the sandbox option in BrowserWindow options, it still disables the renderers nodejs environment.

**Comment by kuhaufleitung** [comment]
> Clear `.config/Cider` (`rm -Rf .config/Cider`).
```
node:internal/bootstrap/switches/does_own_process_state:126
    cachedCwd = rawMethods.cwd();
                           ^

Error: ENOENT: no such file or directory, uv_cwd
    at process.wrappedCwd [as cwd] (node:internal/bootstrap/switches/does_own_process_state:126:28)
    at node:path:1082:24
    at Object.resolve (node:path:1096:39)
    at resolveMainPath (node:internal/modules/run_main:15:40)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:75:24)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'uv_cwd'

```

**Comment by kuhaufleitung** [comment]
nevermind, that fixed itself with a restart.
Running cider with --no-sandbox actually works. So for now i'll use that. Thanks for helping.

**Comment by sergeant-savage** [comment]
I'm having this same issue on Manjaro. Installed from AUR thru pamac.` --no-sandbox` seems to work, but the application takes much longer to launch than before.

**Comment by cryptofyre** [comment]
I recently made a couple commits that should fix the sandboxing/missing .so issue. If you could recompile and verify that the issue persists that would be great!

**Comment by sergeant-savage** [comment]
Built successfully, and all seems to work again, thanks!
