### ISSUE TITLE
[Enhancement] Support ModernFlyouts

### ISSUE THREAD

**Issue by Greenoliv** [ciderapp/Cider#93]
Is there any way, to support the [ModernFlyouts](https://modernflyouts-community.github.io/) media control widget? 

![ryBwdCexyx](https://user-images.githubusercontent.com/52407090/148687550-cf2d9a88-833f-4937-a6b7-328ef1e70f9d.png)

**Comment by coredev-uk** [comment]
I believe the changes that would be made if #90 was implemented would also come with support for ModernFlyouts. Keep an eye on that issue for further updates on this.
