### ISSUE TITLE
[Bug]: Cider doesn't react after Cast menu open

### ISSUE THREAD

**Issue by Amaru8** [ciderapp/Cider#940]
### Describe the Bug

When you open the Cast menu, after 1-2 seconds the window freezes, and it won't react to anything. The music will continue playing.

### Steps to Reproduce

1. Click on Cast
2. Sometimes you need to interact with it (click search)
3. Now you can't click anything

### Environment Information

- OS: `Windows 11 Home`
- App Version and/or Commit ID: `Version 1.5.0-alpha.1882`

### Anything else?

The log of Cider, gathered with Debugtron:

[castError.log](https://github.com/ciderapp/Cider/files/8564520/castError.log)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
wait, i'll fix this real soon

**Comment by Amaru8** [comment]
Resolved.
