### ISSUE TITLE
[Bug]: Right-clicking on song image in Redmond mode doesn't show the full GUI (MINOR)

### ISSUE THREAD

**Issue by srbuttcheeks** [ciderapp/Cider#942]
### Describe the Bug

As the title states, right-clicking on the image of a song while in Redmond mode doesn't show the complete GUI, as it goes down and off-app. This can be fixed by making the GUI go up, as it does when right-clicking on a song area other than the image (or clicking the 3 dots).

![image](https://user-images.githubusercontent.com/70353312/165406738-3d1a4d6a-b77a-4a2e-b424-c18cac8e1419.png)

### Steps to Reproduce

1. Settings -> Visual -> Window Style: Redmond
2. Right-click the image of the song that's currently playing. 

### Environment Information

- OS: Windows 10
- App Version and/or Commit ID: Cider Version 1.4.4 - Build 1876 (main)

### Anything else?

These are images of how the GUI looks after right-clicking on another song area, clicking the three songs and in Cupertino.

![image](https://user-images.githubusercontent.com/70353312/165406877-250facd7-245d-42e6-9365-5d20d9c7943b.png)
![image](https://user-images.githubusercontent.com/70353312/165406890-a5c6d4ab-674b-4aad-8682-2405df7ea65b.png)
![image](https://user-images.githubusercontent.com/70353312/165406942-e10dcafd-3d78-44e8-bd7c-574908ce9819.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Amaru8** [comment]
Hi @srbuttcheeks, I have some great news! This bug is now fixed in the latest development version of Cider, and the fix will be included in the next Microsoft Store update.
