### ISSUE TITLE
[Bug]: Duplicated Tray Icons - Linux - Gnome 41

### ISSUE THREAD

**Issue by ryanNupp** [ciderapp/Cider#947]
### Describe the Bug

Duplicating icons in the menu bar tray while using the app. My settings are all mostly default. Only way I could make them go away was to close the app and reopen.
![Screenshot from 2022-04-27 00-28-29](https://user-images.githubusercontent.com/99926961/165594859-82f418e9-b0f1-4323-a434-e6f44da5aa23.png)
 

### Steps to Reproduce

There was only one thing I could get to reproduce so far, but I think there may be another thing or two causing this as well. When clicking on the Cider button top left then clicking 'Web Remote' it creates a duplicate tray icon each time.

### Environment Information

- OS: Fedora Linux 35 Workstation
- App Version: 1.4.5-alpha.1888
-----
Extra info (in case it might help):
- Kernel: 5.16.20-200.fc35.x86_64
- DE: GNOME 41.4
- WM: Mutter
- CPU: Intel i7-9700KF
- GPU: AMD Radeon RX 6600 XT
- Memory: 2x8gb @ 3200mhz
-----

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by ryanNupp** [comment]
Forgot to add I'm using the flatpak version from Flathub

**Comment by Amaru8** [comment]
This might be related to #858.

**Comment by coredev-uk** [comment]
Not sure how the app can generate multiple trays, check if multiple instances have of cider have been created

**Comment by ryanNupp** [comment]
From what I can see, there's still only the one instance of Cider running. On top of that, of all of the duplicates (no matter how many) only one seems to properly function with the Minimize to Tray and Show Cider buttons. It seems that all of them say 'Minimize to Tray' except only the one on the very left will show the 'Show Cider' prompt when it's already minimized. Here's a video to show what I mean:
https://user-images.githubusercontent.com/99926961/165637825-85c65d8b-cad9-4ae1-9055-d465a6836145.mp4

Also here's a video showing all of the Cider-related system processes in my System Monitor app while the tray icon duplicates are created:
https://user-images.githubusercontent.com/99926961/165638240-bf7269b7-d3d9-4c99-92f2-bd7228234c61.mp4

**Comment by mohammadrafigh** [comment]
It seems the app is initializing tray icon on an app start event since refreshing the app using "ctrl + r" or "ctrl + shift + r" creates a new tray icon too.

**Comment by afonsofrancof** [comment]
> It seems the app is initializing tray icon on an app start event since refreshing the app using "ctrl + r" or "ctrl + shift + r" creates a new tray icon too.

I also have this bug. Arch linux with XMonad

**Comment by coredev-uk** [comment]
Closing. Check #858 for progress updates.
