### ISSUE TITLE
[Bug]: Cast Menu not present

### ISSUE THREAD

**Issue by bfrostieone** [ciderapp/Cider#952]
### Describe the Bug

There is no Cast Menu 

### Steps to Reproduce

1. Clicked on Cider Icon (see attached image)
2. No Cast option

### Environment Information

- OS: Windows 11 Home Version 21H2
- App Version and/or Commit ID: Version 1.4.4

### Anything else?

![cider_bjf](https://user-images.githubusercontent.com/102767677/165838338-dec78cc1-847b-44c8-a937-458998b99c52.jpg)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by grolschie** [comment]
Same issue. There's a Cast button somewhere? Running Windows 11 Home and Cider 1.4.5 from the Microsoft Store.

**Comment by bfrostieone** [comment]
@grolschie if I am on the stable branch, mine is still gone. the cast menu shows up on the developmental branch

**Comment by vapormusic** [comment]
> @grolschie if I am on the stable branch, mine is still gone. the cast menu shows up on the developmental branch

Enable Advanced AudioContext in Settings -> Audio
