### ISSUE TITLE
[Enhancement] Track change notifications

### ISSUE THREAD

**Issue by 8times9** [ciderapp/Cider#96]
**Is your feature request related to a problem? Please describe.**
I wish to know what song has begun playing when I am in other programs on my computer.

**Describe the solution you'd like**
It would be helpful if there were a track change notification, similar to in iTunes/Music.app for Mac, where a notification appears with the album artwork, artist, album, and track name of the new song which is playing.

**Describe alternatives you've considered**
N/A

**Comment by coredev-uk** [comment]
Notifications are enabled for Linux/MacOS users but are disabled for Windows users due to the annoyance that it can be for some users. I change could be made in the future, but the majority of users prefer it this way.

**Comment by 8times9** [comment]
I mean...it could be an opt-in option?

**Comment by coredev-uk** [comment]
We didn't want to bloat up the settings menu of Cider, as AME did get very bloated with settings that were not necessary. I used the Spotify app as an example in this instance, as for why its set to MacOS/Linux only. I will revisit the option for this once I've completed the typescript backend.

**Comment by gms10ur** [comment]
I will +1 to this feature. the notifications can be easily disabled if wanted. but I will love to see the notifications. and even a skip button to the notification itself would be so useful like the macOs

**Comment by lutoma** [comment]
I'm on the opposite side of this. I'm on Linux and would like to disable the notifications since I find them quite annoying. So a settings option to configure this would be great :)

**Comment by coredev-uk** [comment]
4996594 Completed.
