### ISSUE TITLE
[Bug]: Chromium indiscriminately resamples audio to 48000kHz

### ISSUE THREAD

**Issue by LMFuture-Me** [ciderapp/Cider#963]
### Describe the Bug

![image](https://user-images.githubusercontent.com/36117602/166109657-dabda023-44c8-4fb0-ae8b-035178d01af0.png)
I initially felt that there was a problem with the sound quality. I thought it was my psychology, and it wasn't until I did the ABX test that I determined it was indeed Cider's problem.
I checked my PipeWire audio server. And found that every songs have been resampled to 48000kHz. To know whether it's Cider or Chromium's fault. I tried to use normal Chromium browser to play songs which are 44100kHz. Same condition appears. So I am sure that it's Chromium's fault. But is there any workarounds? Such as calling other audio libraries? After all, it's a music player.

### Steps to Reproduce

I just described it.

### Environment Information

- OS:OpenSUSE
- App Version and/or Commit ID:April30 Latest from flathub.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vapormusic** [comment]
This is Chromium's fault. You should be fine for now as Apple AACs are 48khz. It only matters once lossless arrive
