### ISSUE TITLE
[Bug]: XDG Base Directory Specification is ignored

### ISSUE THREAD

**Issue by hw0lff** [ciderapp/Cider#965]
### Describe the Bug

Cider stores configuration files, data, state and caches in $XDG_CONFIG_HOME. Separate directories should be used instead. For more information on what kind of data belongs in which directory, see the [XDG Base Directory Specification](https://specifications.freedesktop.org/basedir-spec/latest/ar01s02.html).

### Steps to Reproduce

1. Install Cider (via [AUR](https://aur.archlinux.org/packages/cider))
2. Start Cider

### Environment Information

- OS: Archlinux 
- App Version and/or Commit ID: 1.4.4.3221.8ef2ca6b-1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
We don't make any direct modifications to where application data is stored, we currently use the defaults that electron uses.
