### ISSUE TITLE
[Bug]: No Sound When Casting to Google Home Mini!

### ISSUE THREAD

**Issue by rhora10** [ciderapp/Cider#974]
### Describe the Bug

When Casting to my google home mini, I get the sound that a device has connected to it and is trying to cast something to it. The music appears to be playing(the timestamp keeps moving up) but no sound. Thought that It could be that my google home mini was on mute, so i turned the volume up, but that did not work.

### Steps to Reproduce

1. Clicked on the top left(Cider Logo)
2. Went to cast
3. Clicked on the Device I wanted to cast to
4. Cider connected to the device

### Environment Information

- OS: Ubuntu 20.04.4 LTS
- App Version and/or Commit ID:  1.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by KillerParticles** [comment]
Hi, can you check this link [here](https://github.com/ciderapp/Cider/wiki/Support-FAQs#cannot-cast-on-my-network-windows), go to cannot cast on my network and follow those steps.

**Comment by vapormusic** [comment]
Can you try it again?
