### ISSUE TITLE
[Bug]: macOS (latest release) prompts for login every launch

### ISSUE THREAD

**Issue by nexxai** [ciderapp/Cider#976]
### Describe the Bug

Every time I open the app, I have to re-login to my Apple Music account.  On top of that, once I've entered in my details and they're accepted, the screen that says "[You’re Signed In] - Apple Music players on this and other sites now have access to your account, so you can play full songs and add them to your Library." will not go away when I click the "Continue" button.  I have to use the red dot at the top left corner of the popup window.

### Steps to Reproduce

1. Open Cider

### Environment Information

- OS: macOS 12.3.1
- App Version and/or Commit ID: 1.4.0 (installed from releases)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by coredev-uk** [comment]
Have you tried a [clean installation](https://docs.cider.sh/support/troubleshooting#1-clean-installation)?

**Comment by quacksire** [comment]
Cannot reproduce

**Comment by nexxai** [comment]
@coredev-uk I can confirm that after a clean installation, and installing using the "Cider.pkg" release, I am still seeing both the lack of retaining login credentials (therefore, having to login on every full application open), and the "You're Signed In" window not going away when clicking the "Continue" button on it.

I'm happy to provide whatever logs you need, just let me know what and where.

**Comment by quacksire** [comment]
Try going to Application Support and deleting the entire Cider folder, the. trying again.


Also,the Continue button will never close the window due to how Apple handles their login flow system, the red stoplight button should be sufficient.

**Comment by afonsofrancof** [comment]
I also have this problem on linux, with my first install. Arch Linux.

**Comment by LukeVader-IV** [comment]
Same behavior happens on Fedora 36,Installed through Flathub.
Asks for login on every launch and "continue" button has no effect.
Although it should be noted that it only asks for 2fa on the first login, but that's probably just a browser cookie.

**Comment by Repartee41** [comment]
Same behavior on both Arch Linux with i3 (package from the AUR) and with Fedora 36 with Gnome (package from Flatpak).
Both the login on every launch as well as "continue" having no effect.

**Comment by codevski** [comment]
This is still a problem fresh arch install

**Comment by DeeeeLAN** [comment]
I am having the same issue on Arch.

**Comment by Ray-Eldath** [comment]
Same on Manjaro with Gnome 42.3, and Cider installed from AUR.
