### ISSUE TITLE
[BUG] Acrylic module HiDPI window lag

### ISSUE THREAD

**Issue by SubZeroNexii** [ciderapp/Cider#98]
**Describe the bug**
Enabling acrylic and resizing the window causes huge amounts of lag to the point the window continues to resize after you let go of the window.

**To Reproduce**
1. Enable any HiDPI scaling option in windows (anything over 100% basically)
2. Enable Acrlyic in Cider settings
3. Drag/Resize the window around

**Screenshots**
(I tried catching the bug in action but it seems that it also lags the screen capture)
![bOL0Qd6yqd](https://user-images.githubusercontent.com/11245286/148700017-8150d60f-96a6-4407-8bb0-c9f2031a37e3.gif)

**Environment Information**
 - OS *Windows 11 Insider Beta 22000.376*: 
 - Application Version *Cider commit d99b9d1eac7e8188dd8741ea2294f9040c9968db*:

**Comment by quacksire** [comment]
Acrylic has been dropped due the libraries' lack of cross platform compatibility
