### ISSUE TITLE
[Bug]: Cannot bring up taskbar when bringing cursor to bottom of screen if using 'automatically hide taskbar in desktop mode'

### ISSUE THREAD

**Issue by SmartWater2021** [ciderapp/Cider#981]
### Describe the Bug

When the Cider window is open, moving my cursor to the bottom of my desktop doesn't bring up the taskbar (taskbar is normally revealed when my cursor hovers around the bottom of the screen). Instead, the cursor is blocked from accessing the bottom of the screen and turns into the 'window resizing' cursor function. This all happens when the Cider window is maximised to fill the screen.
![issue pic_LI](https://user-images.githubusercontent.com/78865326/166294819-b0ac8f8c-4909-453d-9fcc-e5b3f3186ec7.jpg)

### Steps to Reproduce

1. Have the windows personlisation option in settings called "Automatically hide the taskbar in desktop mode" enabled.
2. Open Cider and maximise the window
3. Move your cursor to the bottom of the screen
4. Result = Taskbar won't pop up.

### Environment Information

- OS: Windows 10, version 21H2
- App Version and/or Commit ID: 1.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
This is not a Cider issue.

Please refer to your operating system's feedback or help site for more information.

**Comment by SmartWater2021** [comment]
So it doesn't matter that cider is the only application this happens with?

**Comment by cryptofyre** [comment]
Cider should not have any impact on operating system functions. I’d create a bug report to Microsoft to get that resolved as we can’t do anything to fix something Microsoft bugged out.

**Comment by SmartWater2021** [comment]
Ah ok, thanks.
