### ISSUE TITLE
[Bug]: Incorrect hierarchy used when sorting songs library by artist

### ISSUE THREAD

**Issue by stewartkyle** [ciderapp/Cider#982]
### Describe the Bug

When viewing your library by songs and sorting by artist, tracks within an album are then sorted alphabetically instead of by track number. This results in album tracks being out of order when using the Songs view. The current sort hierarchy for artist sort in Cider appears to be:

1. Artist name, alphabetically
2. Album name, alphabetically
3. Track name, alphabetically

The correct hierarchy should be:

1. Artist name, alphabetically
2. Album name, alphabetically
3. Track number

This is the hierarchy used in iTunes/Apple Music.

### Steps to Reproduce

1. Go to Library -> Songs.
2. Sort by Artist.

### Environment Information

- OS: Windows 11 64-bit
- App Version and/or Commit ID: Windows Store, v.1.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bcha** [comment]
Sad to see this gone stale, still an issue :(

**Comment by cryptofyre** [comment]
Should be fixed now, please leave a comment if this still occurs. Closing in the meantime.
