### ISSUE TITLE
[Bug]: Queue is broken in many areas

### ISSUE THREAD

**Issue by KillerParticles** [ciderapp/Cider#987]
### Describe the Bug

When you shuffle songs and go into the Queue, or play songs without shuffling, you run into a few bugs:
1. The currently playing song is shown as the next up song, which it shouldn't
![image](https://user-images.githubusercontent.com/93286201/166835851-1a24eedb-e7a0-495b-9132-3341270b63cc.png)

2. Any changes you make to the queue, such as moving songs up or down the list, are completely ignored. Cider will use the queue of the unshuffled songs instead. This means if you unclick the shuffle button, that is the queue that will be played. If you are not shuffling then this is fine as you see the queue as it is, but when shuffled it means this isn't the actual queue. Also if you don't shuffle whilst it is true you can see the correct order, you still cant rearrange the queue.

3. You cannot move songs up or down the queue, they will reset to their original state and even if they do move. trying to play them will instead play the original song there

### Steps to Reproduce

1. Play/shuffle a album/playlist and try to change the queue, or some of the other bugs i mentioned.

### Environment Information

- OS: Windows 11 Home
- App Version and/or Commit ID: Cider Version 1.4.5 - Build 2190 (develop)

### Anything else?

https://user-images.githubusercontent.com/93286201/166836973-5852c5a1-8155-4458-af7e-b0e8209d3dd6.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cryptofyre** [comment]
blame apple’s shitty musickit code. we have to rewrite the entire queue system.

**Comment by KillerParticles** [comment]
Just fyi i know a fix was pushed, but it fixed none of these bugs. I still have the same bugs on the most recent build.
