### ISSUE TITLE
[BUG] I can't see any albums or artists

### ISSUE THREAD

**Issue by dooorians** [ciderapp/Cider#99]
**Describe the bug**
On the left bar, when I clicked on these 2 sections, nothing appears. The only thing that appears is in the left down corner box with this message if I click on one of the categories is : " Updating library artists... 0/0 ", " Updating library albums 0/0 " or sometimes a number appears 430/570 and it never loads any further.

**To Reproduce**
1. Open Cider
2. Click on Albums or Artists

**Expected behavior**
I think it's because I have paid some albums via iTunes and also I have some songs in my iTunes that i load into Itunes.

**Screenshots**

![1](https://user-images.githubusercontent.com/97409898/148700721-bdbe6dea-72e8-4af7-bbbe-e2464c895a05.png)

**Environment Information**
 - Windows 11
 - Cider 1.0 (download from discord)

**Comment by coredev-uk** [comment]
If you could take a screenshot of the console (Do Ctrl+Shift+I and click console) when this error is occurring, then it will give us some insight into why its failing to fetch.

**Comment by vapormusic** [comment]
@coredev-uk , i think SW is the culprit here

**Comment by dooorians** [comment]
> If you could take a screenshot of the console (Do Ctrl+Shift+I and click console) when this error is occurring, then it will give us some insight into why its failing to fetch.
![2](https://user-images.githubusercontent.com/97409898/148757852-585cbd57-caa0-4969-8a92-08cf90bd0840.png)
![3](https://user-images.githubusercontent.com/97409898/148757854-8ca3eb98-643c-461f-a41b-174dc1fe3a83.png)

**Comment by vapormusic** [comment]
hmm, looks like we need some try-catchs for special cases

**Comment by dooorians** [comment]
> hmm, looks like we need some try-catchs for special cases

I did not notice but « Recently Added » does the same thing.

Do I have something to do to help you ?

**Comment by vapormusic** [comment]
> > hmm, looks like we need some try-catchs for special cases
> 
> I did not notice but « Recently Added » does the same thing.
> 
> Do I have something to do to help you ?

It would be better for us to help you if you join our discord server : https://discord.com/invite/applemusic
