### ISSUE TITLE
[Bug]: Connect login flow not working

### ISSUE THREAD

**Issue by zyjiang0601** [ciderapp/Cider#990]
### Describe the Bug

When I click the connect button, I will be guided to a discard authorization platform. After I click the Authorize button, the website reloaded again. I suspect that the apps did not make fully support on this connect function.

### Steps to Reproduce

1. Clicked on connect button;
2. It will reproduce anyway.

### Environment Information

- OS: macOS 12.4
- App Version and/or Commit ID: 1.4.5

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by quacksire** [comment]
The connect feature is currently under heavy development, this is known and is being handled.
